### ISSUE TITLE
Please, add more libs for angular bootstrap 

### ISSUE THREAD

**Issue by alexeenka** [jsdelivr/jsdelivr#10191]
On https://www.jsdelivr.com/projects/angular.bootstrap last version is **0.13.3**
But it's already **1.2.1** version on https://angular-ui.github.io/bootstrap/

Thanks

**Comment by jimaek** [comment]
Done https://github.com/jsdelivr/jsdelivr/commit/c29aadefb1b90eab3f27bd55e007fcc763f3771e
