### ISSUE TITLE
Adding missing versions

### ISSUE THREAD

**Issue by devinivy** [jsdelivr/jsdelivr#10366]
I recently updated the location of a repo that moved from a personal account to a github organization.  JsDelivr has pulled-in the most recent version from the new repo location, but several other versions have also been released since the repo was moved, and jsDelivr hasn't pulled them in.  Will jsDelivr eventually sync with past releases, or should I make a PR to manually add those versions to jsDelivr?

**Comment by jimaek** [comment]
jsDelivr wont pull old versions automatically. Also I dont see any reason to host old versions, people should be using the latest ones

**Comment by devinivy** [comment]
@jimaek I appreciate your point!  All the same, is it considered okay to make a PR manually adding those versions?

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
