### ISSUE TITLE
jquery slim listed in jquery 2.2.1

### ISSUE THREAD

**Issue by miyurusankalpa** [jsdelivr/jsdelivr#10488]
jquery slim which is 3.0.0-beta1 file is listed in 2.2.1

https://cdn.jsdelivr.net/jquery/2.2.1/jquery.slim.min.js
https://cdn.jsdelivr.net/jquery/2.2.1/jquery.slim.js

**Comment by jimaek** [comment]
Indeed, thats a mistake. Unfortunately I cant remove these files in case someone is using them.
Sorry
