### ISSUE TITLE
concat files is non-productive with http/2?

### ISSUE THREAD

**Issue by mjau-mjau** [jsdelivr/jsdelivr#10537]
Question: Would it be fair to say that loading multiple files in a single request becomes somewhat un-productive now with http/2 support? Of course, not all browsers support http/2 yet, but it seems caching is more effective with single file requests.

**Comment by mjau-mjau** [comment]
Besides the fact that multi-file requests are buggy. Sometimes it's served gzipped, sometimes not:
![](http://d.pr/i/baS7+)
![](http://d.pr/i/U06B+)

**Comment by jimaek** [comment]
Yes, with HTTP2 concat files are no longer effective. Maybe in the future we will hide this functionality from our website.
