### ISSUE TITLE
How to link source maps

### ISSUE THREAD

**Issue by DiegoRBaquero** [jsdelivr/jsdelivr#10635]
Hi,

I currently use the following packages: `https://cdn.jsdelivr.net/g/webtorrent@0.87,momentjs@2,angularjs@1.4(angular.min.js+angular-route.min.js+angular-sanitize.min.js),angular.ui-grid@3.1,angular.ng-notify@0.7,angular.file-upload@12`

But I get source maps errors such as: Failed to parse SourceMap: https://cdn.jsdelivr.net/g/ng-notify.min.js.map

I had similar things with some CSS files (moved independently) but now they are occurring in JS... previously not. Is there a way to manually specify the source maps url?

If every project I use must be separated into independent requests then it will suck.

Thank you

**Comment by jimaek** [comment]
Unfortunately there is no way to fix this issue. But you can safely ignore it. map files are needed only for debugging and are loaded only when you open developer tools.

**Comment by tomByrer** [comment]
^ & .map files are usually only used for debugging live sites, which is much more rare than debugging locally or the development machine.
