### ISSUE TITLE
vue-validator 2.0.0 not published to jsdelivr

### ISSUE THREAD

**Issue by kazupon** [jsdelivr/jsdelivr#10786]
The following version is pointing to the old version.
Why ?
https://cdn.jsdelivr.net/vue.validator/2.0.0/vue-validator.min.js

I hope that vue-validator is pointing correct version. :)

**Comment by jimaek** [comment]
Its taken from the official file. Its tagged as 2.0.0 but inside also says beta
https://github.com/vuejs/vue-validator/blob/v2.0.0/dist/vue-validator.min.js

**Comment by kazupon** [comment]
Ah, sorry ...
This is my mistake.
Thanks!!
