### ISSUE TITLE
When using automatic bundling, font-awesome does not work

### ISSUE THREAD

**Issue by sgoblin** [jsdelivr/jsdelivr#10965]
When I use [this](https://cdn.jsdelivr.net/g/fontawesome@4.5.0,normalize@3.0.3,ink@3.1.10(css/ink-flex.min.css)) bundled URL, the font-awesome font files do not load, due to the use of relative links: `src:url('../fonts/fontawesome-webfont.eot?v=4.5.0');`. Is there a way around this?

**Comment by jimaek** [comment]
Unfortunately no https://github.com/jsdelivr/jsdelivr/issues/4353
