### ISSUE TITLE
update foundation-APPS

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#11002]
Sorry @ work, g2g, but tested broken
http://foundation.zurb.com/forum/posts/38626-foundation-for-apps-cdn-not-working
Note: different than [Foundation for SITES](https://www.jsdelivr.com/projects/foundation), might need to change that entry.

**Comment by jimaek** [comment]
I dont understand, what exactly is the problem here? What do I need to do?

**Comment by soumak77** [comment]
ZURB has basically dropped support for foundation for apps which prompted moving the framework to an open source fork located at https://github.com/base-apps/angular-base-apps.  PR https://github.com/jsdelivr/jsdelivr/pull/12754 adds file hosting for the new fork.

**Comment by soumak77** [comment]
@tomByrer this project is now hosted as https://www.jsdelivr.com/projects/angular-base-apps

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
