### ISSUE TITLE
algolia/places.js 0.0.13 and 0.0.14 are not picked by bot

### ISSUE THREAD

**Issue by vvo** [jsdelivr/jsdelivr#11052]
Can you help?

**Comment by jimaek** [comment]
It was a bug introduced when moving servers. Tutum is shutting down so I had to move everything to Docker Cloud. 
`git config --global user.email` was not set on the new server so git was erroring on every commit the bot tried to do. Sorry about that.

**Comment by vvo** [comment]
Thanks!
