### ISSUE TITLE
Does it support http/2?

### ISSUE THREAD

**Issue by franciscop** [jsdelivr/jsdelivr#11087]
I am a long term fan of jsdelivr (ever since you integrated [Picnic CSS](http://picnicss.com/) there) and now someone is making a [pull request to add my library to CDNJS](https://github.com/umbrellajs/umbrellajs.github.io/pull/1).

While I have some reasons I prefer jsdelivr, they have a case in that they support http/2, so supposedly compressed headers. I just checked and in the CDN subdomain my standard headers are not even so small. So do you plan to add support to http/2 and, subsequently, compressed headers? Any roadmap/plans if so?

**Comment by jimaek** [comment]
We are using KeyCDN + CloudFlare + MaxCDN.
KeyCDN and CloudFlare support HTTP2. MaxCDN supports SPDY and is planning to support HTTP2 soon.

**Comment by franciscop** [comment]
Awesome, thanks
