### ISSUE TITLE
Can we host Google Fonts Here?

### ISSUE THREAD

**Issue by ricardopolo** [jsdelivr/jsdelivr#11185]
Because HTTP2 and sharing the same HTTP connection I would love to host all of our external dependencies in one CDN.

So would you think that may be possible host a resource that is available in Google Fonts CDN? I think they dont publish the fonts in NPM or Bower.

**Comment by jimaek** [comment]
I would love to host them but its impossible at the moment. Google compiles them and doesnt offer a changelog to know when to update a font. Its impossible to track them basically and offer the exact same files as Google offers without setting up a copy of their infrastructure.

**Comment by ricardopolo** [comment]
Thanks!

**Comment by ricardopolo** [comment]
@jimaek I just discover this Google repository https://github.com/google/fonts

**Comment by jimaek** [comment]
I know of that repo. Like I said they are compiling their fonts. I cant just upload the contents of that repo. I would need to setup all of their scripts and software to do what Google fonts does.
