### ISSUE TITLE
Whats the point of Load Multiple Files

### ISSUE THREAD

**Issue by ricardopolo** [jsdelivr/jsdelivr#11184]
I cannot understand the benefits of your feature of concatenate multiple projects in one Url.

In HTTP2 and SPDY all requests to the same domain shares the same HTTP connection, so its the same as concatenation. 
I also think that if you have all of your resources in the same URL when you update one, the URL will change, and force the user to re download everything again, losing all cache benefits. If you have multiple URLs per dependency, when one changes, you wont for to re download all dependencies again.

So, I cannot understand the point of using tha feature, but, am I missing something?

**Comment by jimaek** [comment]
That feature was created before HTTP2 was even discussed. We are not forcing anyone to combine multiple files, our CDN works just fine with loading all of them individually :)

**Comment by ricardopolo** [comment]
Thanks@jimaek! In you experience, would you recommend still use it today or would go for individually load?

**Comment by jimaek** [comment]
I would recommend loading them individually. In the future we might do a redesign and remove completely that functionality

**Comment by ricardopolo** [comment]
Awesome, thanks @jimaek!
