### ISSUE TITLE
Why are you slower than CDNJs?

### ISSUE THREAD

**Issue by ricardopolo** [jsdelivr/jsdelivr#11183]
According to http://www.cdnperf.com/ you are slowed than CDNJs, I dont understand why if you have multibalanced and eventually use the same newtork (Cloudflare)?

Thanks :)

**Comment by jimaek** [comment]
cdnperf uses Pingdom for monitoring the performance. Pingdom only uses 4-5 servers. You cant compare the performance of a CDN that has 100+ locations using only 5 servers.
So its not that reliable.
The correct way to test the CDN performance would be to use RUM data from millions of users.

**Comment by ricardopolo** [comment]
I think I will be moving multiple project from cdnjs to jsdelivr in the next few days. You bought me whit SRI in the web interface, and hosting all repos, they only host if the project has certain github stars :)

**Comment by jimaek** [comment]
:+1: Welcome aboard
