### ISSUE TITLE
Huge pings for South America

### ISSUE THREAD

**Issue by IanSzot** [jsdelivr/jsdelivr#11192]
Hi, recently users from South America (especially Brazil) have been getting abnormal ping results from jsdelivr. What used to be around 20~40 is now at 140~200.

Debug tool results: http://goo.gl/JM1LEB

You can also see on the Statistics page how big the load times are.

**Comment by jimaek** [comment]
Can you ping the following hostnames and tell me the latency?

1. cdn.jsdelivr.net
2. jsdelivr3.dak.netdna-cdn.com
3. testingcf.jsdelivr.net

**Comment by IanSzot** [comment]
@jimaek 
133ms for cdn.jsdelivr.net
135ms for jsdelivr3.dak.netdna-cdn.com
12ms for testingcf.jsdelivr.net

**Comment by jimaek** [comment]
Thanks. One more
jsdelivr-cb7.kxcdn.com

**Comment by IanSzot** [comment]
@jimaek 221ms

**Comment by jimaek** [comment]
Clear your cache and wait a few minutes. Then try again to ping cdn.jsdelivr.net

**Comment by jimaek** [comment]
If the problem persists please comment again
