### ISSUE TITLE
Should we include Cedexis RUM if we have the  Cedexis tag?

### ISSUE THREAD

**Issue by ricardopolo** [jsdelivr/jsdelivr#11201]
We want to contribute to routing decisions of JsDelivr, and I read that we do it using https://www.jsdelivr.com/projects/jsdelivr-rum 

If we already have the Cedexis Radar Tag, including the jsdeliver are we already improving JSDelivr, or we should include your RUM tag too?

**Comment by jimaek** [comment]
It depends on your Radar settings. Our is optimized to give priority to our providers.
In any case dont use 2 radar tags at the same time.
