### ISSUE TITLE
places.js 0.20.0 is not available on CDN

### ISSUE THREAD

**Issue by vvo** [jsdelivr/jsdelivr#11326]
was merged some time ago, thanks.

**Comment by jimaek** [comment]
There is your problem
![firefox_2016-04-27_20-12-00](https://cloud.githubusercontent.com/assets/1834071/14863130/c400ed5e-0cb4-11e6-825f-ce6975367626.png)

I did a manual sync and contacted their support. The new version is now online

**Comment by vvo** [comment]
Thank you
