### ISSUE TITLE
cdn.jsdelivr.net/sweetalert2/latest/sweetalert2.min.js is not actually latest

### ISSUE THREAD

**Issue by limonte** [jsdelivr/jsdelivr#11946]
https://www.jsdelivr.com/projects/sweetalert2

https://cdn.jsdelivr.net/sweetalert2/latest/sweetalert2.min.js

- expected: https://cdn.jsdelivr.net/sweetalert2/3.2.3/sweetalert2.min.js
- actual: https://cdn.jsdelivr.net/sweetalert2/3.2.1/sweetalert2.min.js

Project was bumped to `v3.2.3` 4 days ago.

**Comment by jimaek** [comment]
Latest is cached for 7 days for performance reasons, its not instant.
I purged the cache manually now

**Comment by limonte** [comment]
Seven days is a lot. Please consider decreasing the caching time for the latest alias. Also, it will be great to have the information about caching time here: https://github.com/jsdelivr/jsdelivr#version-aliasing

**Comment by jimaek** [comment]
At the time I created that function there was a technical limitation of minimal 7 days with a CDN provider. I will need to check if they allow lower values now.
