### ISSUE TITLE
Project not updated

### ISSUE THREAD

**Issue by franciscop** [jsdelivr/jsdelivr#12142]
Hi, I have recently changed the directory in the update.json from Picnic CSS and you accepted the PR. However the project [stays in version 6.0.0](http://www.jsdelivr.com/projects/picnicss) while the [latest git version is 6.1.1](https://github.com/picnicss/picnic/releases)

Following it, it seems that [jsdelivr is having a not very efficient conversation](https://github.com/jsdelivr/jsdelivr/pull/12027) with... itself:

```
It looks like you want to contribute to jsdelivr/jsdelivr, @jsdelivrbot, however [...]
```

How can I fix this? Can you fix it?

**Comment by jimaek** [comment]
Just comment in the PR if the change is valid and not a mistake.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
