### ISSUE TITLE
angular.chartjs not updated

### ISSUE THREAD

**Issue by jtblin** [jsdelivr/jsdelivr#12306]
Looking at https://github.com/jsdelivr/jsdelivr/tree/master/files/angular.chartjs, the latest version is 0.8.8, however the latest version of angular-chart.js is [0.10.2](https://github.com/jtblin/angular-chart.js/releases/tag/0.10.2).

Not sure why this is happening, there have been errors with the alpha/beta branch because of missing css file in the new version but it is not a problem with 0.10.2 (I'll need to open an issue for the css file later).

Thank you

**Comment by jimaek** [comment]
Im traveling and cant check. @MartinKolarik Can you help please?

**Comment by MartinKolarik** [comment]
@jimaek I think it's the same problem as #12037. There's a 1.0.0-alpha, so we don't download 0.x anymore. I can change the logic to always download 0.x versions if you'd like.

**Comment by jtblin** [comment]
Sorry for the lag, it would have been great before but not needed anymore as I'm moving out of alpha/beta. Thanks.
