### ISSUE TITLE
fontawesome-markers not being merged.

### ISSUE THREAD

**Issue by tankerkiller125** [jsdelivr/jsdelivr#12724]
It seems that the bot can't see the info.ini in the fontawesome-markers directory dispite it definitely existing. https://github.com/jsdelivr/jsdelivr/blob/master/files/fontawesome-markers/info.ini

**Comment by MartinKolarik** [comment]
@jimaek IIRC this is a known bug and the first PR always needs to be merged manually.

**Comment by jimaek** [comment]
sorry, I misunderstood what the bug was
