### ISSUE TITLE
JSDelivr still doesn't add font-SpoqaHanSans PR

### ISSUE THREAD

**Issue by the1900** [jsdelivr/jsdelivr#12880]
First I requested to merge and It merged see #12704. 

Now I wonder why JSDelivr's bot doesn't add files in the PR? even I added `info.ini` and `update.json` correctly,

The PR I want to add is a webfont [SpoqaHanSans ](https://github.com/spoqa/spoqa-han-sans). It has  tags can automatically management by bot.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
