### ISSUE TITLE
Ionic Icons Fonts 404

### ISSUE THREAD

**Issue by Chiru13** [jsdelivr/jsdelivr#12947]
The following font files cannot be found:

Failed to load resource: the server responded with a status of 404 (Not Found) http://cdn.jsdelivr.net/fonts/ionicons.woff?v=2.0.1 

Failed to load resource: the server responded with a status of 404 (Not Found)
http://cdn.jsdelivr.net/fonts/ionicons.ttf?v=2.0.1

**Comment by jimaek** [comment]
I dont understand, I need more info where you see those errors, here are the correct URLs http://www.jsdelivr.com/projects/ionicons

**Comment by Chiru13** [comment]
Okay so, go here: http://ionicons.com/ they already have a CDN there which just requires you to include a css file with no issues, however in JSDelivr the .CSS file is **PRESENT**, however not all font files are.

**Comment by jimaek** [comment]
Can you give me an example how you are include the css?
We have the fonts but for some reason your browser is loading the files from the wrong directory.

**Comment by Chiru13** [comment]
<link rel="stylesheet" href="https://cdn.jsdelivr.net/g/weather-icons@0.0.1,flag-icon-css@2.3.1,ionicons@2.0.1,embed.js@4.1.4(embed.min.css)">

**Comment by Chiru13** [comment]
I have gone through the CSS file and the url to the fonts are incorrect, which is why I get the 404 errors.

**Comment by jimaek** [comment]
Thats what I thought. You cant use /g/ with css files that include other files like fonts.
You need to load that css separately from the combined files

**Comment by Chiru13** [comment]
Okay, thanks it works now!
