### ISSUE TITLE
support of static brotli compression

### ISSUE THREAD

**Issue by OlegKi** [jsdelivr/jsdelivr#12943]
Do you plan to support brotli compression? Chrome, Firefox and Opera supports brotli (see http://caniuse.com/#feat=brotli). 

There are exist currently some CDNs (see https://www.keycdn.com/support/brotli-compression/ and https://www.cdn77.com/brotli for example), some other. One can read [here](https://samsaffron.com/archive/2016/06/15/the-current-state-of-brotli-compression) for example some additional information about the current state of brotli compression.

Thanks in advice.
P.S. I know 8 months late issue https://github.com/jsdelivr/jsdelivr/issues/7702. It's interesting to me some update on the subject.

**Comment by jimaek** [comment]
We are using KeyCDN, MaxCDN, CloudFlare and Quantil. We cant do anything on our side, its a CDN feature.

If KeyCDN supports it then when you hit KeyCDN on our load-balancing then you will get brotli.

**Comment by OlegKi** [comment]
Thanks for the answer. It sounds interesting! Could you send a reference which describes *how* one can "hit" KeyCDN on jsdelivr's load-balancing? Is it possible by adding some options to URLs, which points to any jsdelivr resource?

**Comment by jimaek** [comment]
Load balancing is done on a DNS level, so you cant influence it in any way via the URL.
You automatically hit the fastest CDN for your location. If you visit http://www.jsdelivr.com/ you can see which CDN is the fastest for you at that moment (the highlighted logo)

**Comment by OlegKi** [comment]
Thanks for the information. In other words it means that jsDelivr uses the *existing* CDN of KeyCDN, MaxCDN, CloudFlare and Quantil and thus one can't influence, which from there CDNs be chosen by the client. The brotli compression will be available on jsDelivr depend on the availability of it on the CDN chosen during load balancing.

I'm closing the issue. One can still post here any additional information to the subject (support of brotli compression on jsDelivr).

**Comment by jimaek** [comment]
You are correct. If you want brotli you need to ask for it from our CDN providers.

**Comment by styfle** [comment]
It looks like cloudflare supports brotli but a quick test shows that brotli is not enabled for jsdelivr https://tools.keycdn.com/brotli-test

**Comment by jimaek** [comment]
Are you sure you are hitting Cloudflare when doing the test? Because it's enabled but only there

**Comment by MartinKolarik** [comment]
Yes, CF always sends `cf-cache-status` and `cf-ray`

**Comment by styfle** [comment]
This must not have used CF then.

```
$ curl -H 'Accept-Encoding: br' -I https://cdn.jsdelivr.net/npm/marked/marked.min.js
HTTP/2 200 
date: Sun, 02 Sep 2018 11:58:32 GMT
content-type: application/javascript; charset=utf-8
content-length: 21525
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=604800, s-maxage=43200
x-content-type-options: nosniff
etag: W/"5415-SH7KHFjnA/pbOvSwe7nlkhd6pCw"
x-served-by: cache-ams4137-AMS, cache-yyz8322-YYZ
vary: Accept-Encoding
server: NetDNA-cache/2.2
x-cache: HIT
accept-ranges: bytes
```

**Comment by jimaek** [comment]
Yes, that's MaxCDN
