### ISSUE TITLE
Missing cache headers for png/svg

### ISSUE THREAD

**Issue by mjau-mjau** [jsdelivr/jsdelivr#13045]
Is there any logical reason why images delivered by jsdelivr are not assigned cache-headers?

For example:
https://cdn.jsdelivr.net/emojione/assets/png/1f1eb-1f1f7.png
https://cdn.jsdelivr.net/emojione/assets/svg/1f1eb-1f1f7.svg

![screenshot](https://d.pr/i/1hqa7+)

This of course creates performance score penalties to any websites using these resources:

![screenshot](http://d.pr/i/1gNEq+)

**Comment by mjau-mjau** [comment]
or does this vary per library implementation?

**Comment by jimaek** [comment]
This is now fixed. It will take a few days to appear for already cached files.
