### ISSUE TITLE
Raven also needs to also contain raven.js for sourcemap to work

### ISSUE THREAD

**Issue by mattrobenolt** [jsdelivr/jsdelivr#13078]
I'm not familiar with JSDeliver, but I'm a developer on Sentry/Raven, and it was brought to our attention that the raven.js being hosted here has an invalid sourcemap.

From what I can tell, the problem is that the corresponding unminified version isn't being uploaded to go with the minified version and sourcemap.

See https://github.com/getsentry/raven-js/issues/675 for a bit more context.

I'm not sure how to resolve the issue here or what the complete ramification of this issue is for uses of JSDeliver.

Thanks! :)

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
