### ISSUE TITLE
please update open-iconic and fullpage.js?

### ISSUE THREAD

**Issue by hocine** [jsdelivr/jsdelivr#13087]
[https://github.com/iconic/open-iconic](https://github.com/iconic/open-iconic) is now at 1.1.1 (jsdelivr is at 1.1.0)

[https://github.com/alvarotrigo/fullPage.js](https://github.com/alvarotrigo/fullPage.js) is now at 2.8,2 (jsdelivr is at 2.5.9)

thanks!

**Comment by lenovouser** [comment]
Both updated, can be closed.

- [jsdelivr.com/projects/jquery.fullpage](https://www.jsdelivr.com/projects/jquery.fullpage)
- [jsdelivr.com/projects/open-iconic](https://www.jsdelivr.com/projects/open-iconic)
