### ISSUE TITLE
deliver complement font files bug

### ISSUE THREAD

**Issue by bouks** [jsdelivr/jsdelivr#13172]
Hi.

Calling:

`//cdn.jsdelivr.net/g/angular.ui-grid@3.2.6(ui-grid.min.css),bootstrap@3.3.7(css/bootstrap.min.css),normalize@3.0.3`

The navigator makes two new dynamic calls (firefox example):

`http://cdn.jsdelivr.net/g/angular.ui-grid@3.2.6(ui-grid.min.css),bootstrap@3.3.7(css/ui-grid.woff`

and

`http://cdn.jsdelivr.net/g/angular.ui-grid@3.2.6(ui-grid.min.css),bootstrap@3.3.7(css/ui-grid.ttf`

that are not good.

- First, missing ")" at the end of the request
- Second, the complements are for the first projectname (angular.ui-grid) and the dynamic link allocated them to the second (bootstrap)

Interchanging the projectnames whatever the order does not change anything.

**Comment by jimaek** [comment]
You cant use the combination feature with files that include other files inside. Load those files separately.
Its not possible to fix this.
