### ISSUE TITLE
Too many libraries not updated

### ISSUE THREAD

**Issue by ddddgh** [jsdelivr/jsdelivr#13217]
It used to be a good source of libs. At least for the most commonly used jquery. Slowly when i started using more "uncommon" files it starts to show it's weakness.

It's really not that uncommon. Just a few example of what i'm using

Pace.js lots of version missing

Zepto.js latest is 1.2.0

Normalize.css latest is 4.2.0

Prefixfree

Etc...

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
