### ISSUE TITLE
highlight.js 9.6.0

### ISSUE THREAD

**Issue by isagalaev** [jsdelivr/jsdelivr#13280]
Hi! I noticed that highlight.js hasn't been automatically updated (like it used to) to version 9.6.0 from here: https://github.com/highlightjs/cdn-release. Did anything change on your side that we missed?

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by isagalaev** [comment]
Thanks! I noticed the last two releases have been picked up very quickly!
