### ISSUE TITLE
New versions not published after alpha has been released

### ISSUE THREAD

**Issue by FezVrasta** [jsdelivr/jsdelivr#13326]
I have released the version 1.0.0-alpha.1 and alpha.2 of my Popper.js library, now all the releases I do on the version v0.\* are not published to JSDelivr.

Any way to fix this?

**Comment by douglasdeodato** [comment]
👍

**Comment by FezVrasta** [comment]
Even worst, now that I reached `1.0.0` stable, it's not getting updated.

Your service is simply broken, I'm going to remove it from my README and simply point to unpkg.com that works a treat.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
