### ISSUE TITLE
Changes to update.json never merged.

### ISSUE THREAD

**Issue by bit101** [jsdelivr/jsdelivr#13331]
The mechanism for updating a library based on tagged releases in github works fine. The pull request goes through and the library is updated within 10 minutes generally, in my experience.

But recently I changed the structure of my project and added a couple of files. I updated the update.json to reflect the new files and submitted a pull request for that. Weeks went by and it was never touched. I finally cancelled the pull request.

In the mean time, I released a v2.0 version of my library. It actually didn't need some of the files that were originally included, so I deleted them and again put in a pull request for update.json.

But now my 2.0 changes pull request has failed because the files are not available. If I can't get update.json to update, then I need to add back in useless files to make jsdelivr update the package. 

Am I missing something on how to correctly change update.json?

**Comment by megawac** [comment]
Just an issue of noone being full time on the project right now/wanting to go through the back log. In the future just ping me, jimaek or another mod and we'll happily merge when the bot reports errors which you don't care aboiut

**Comment by bit101** [comment]
Excellent, thanks!
