### ISSUE TITLE
How is POP location determined from response headers?

### ISSUE THREAD

**Issue by mjau-mjau** [jsdelivr/jsdelivr#13549]
Hi. I tried searching around, but could not find any specific information about this. The **X-Via** tag seems to contain information about where the resource is served from, although it seems a bit vague.

When I request a file (for example [jQuery 2.2.4](https://cdn.jsdelivr.net/jquery/2.2.4/jquery.min.js)), it returns a response that insinuates the file was served from China somewhere:
```
X-Via:1.1 mgny23:8105 (Cdn Cache Server V2.0), 1.1 meizhou37:7 (Cdn Cache Server V2.0), 1.1 mangu9:4 (Cdn Cache Server V2.0)
```
I am based in Phuket, Thailand, approximately half way between Bangkok and Singapore. Normally, all CDN requests (from CDN providers) are routed to Singapore from here, although I would expect more requests being routed to Bangkok now that more POPs are showing up there. It's 1330km to singapore from here, but must be 4000km to meizhou China. Of course, it would generally not be performance-friendly to get files served from within China and outwards anyway.

When performing a **traceroute** of cdn.jsdelivr.net, it seems fast, and eventually ends on an IP that is located in Bangkok. Good ... but I wonder why this isn't reflected in requests to assets.

**traceroute cdn.jsdelivr.net**
traceroute: Warning: cdn.jsdelivr.net has multiple addresses; using 122.155.238.37
traceroute to 1stapacsniwebmw.dtwscache.speedcdns.com (122.155.238.37), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  4.016 ms  1.066 ms  0.993 ms
 2  10.87.163.1 (10.87.163.1)  14.113 ms  42.510 ms  8.023 ms
 3  10.87.246.233 (10.87.246.233)  11.440 ms  16.668 ms  13.359 ms
 4  10.185.105.236 (10.185.105.236)  21.837 ms  24.563 ms  25.024 ms
 5  10.185.105.101 (10.185.105.101)  20.785 ms  25.434 ms  22.889 ms
 6  58-97-82-126.static.asianet.co.th (58.97.82.126)  20.857 ms
    58-97-82-120.static.asianet.co.th (58.97.82.120)  24.179 ms  23.191 ms
 7  61-91-213-177.static.asianet.co.th (61.91.213.177)  23.904 ms  22.714 ms  20.833 ms
 8  61-91-213-35.static.asianet.co.th (61.91.213.35)  26.611 ms  25.798 ms  23.864 ms
 9  61-91-213-81.static.asianet.co.th (61.91.213.81)  30.738 ms  25.632 ms  30.749 ms
10  122.155.226.17 (122.155.226.17)  26.400 ms  22.141 ms
    122.155.226.105 (122.155.226.105)  23.911 ms
11  61.19.9.74 (61.19.9.74)  1128.982 ms
    61.19.9.190 (61.19.9.190)  61.625 ms  1034.804 ms
12  122.155.238.33 (122.155.238.33)  43.172 ms  22.684 ms  22.008 ms
13  122.155.238.37 (122.155.238.37)  24.050 ms  24.542 ms  21.870 ms

122.155.238.37 == CAT Telecom, Bangkok

**Results from jsdelivr debug-tool**
http://goo.gl/0HgRXn

Thu, 01 Sep 2016 14:26:31 GMT

http://ipinfo.io/json
ip: 119.76.127.226
hostname: ppp-119-76-127-226.revip17.asianet.co.th
city: Phuket
region: Phuket
country: TH
loc: 7.9500,98.3583
org: AS17552 True Internet Co.,Ltd.
postal: 83000

http://cdn.jsdelivr.net/information.txt
nginx/1.10.0

2-01-2cd3-000f.cdx-i-119-76-127-226.cedexis.net
cdn.jsdelivr.net.mwcloudcdn.com

https://cdn.jsdelivr.net/r15lgc.js
OK

http://cdn.jsdelivr.net/r15lgc.js
OK

http://testingcf.jsdelivr.net/r15lgc.js
OK

http://jsdelivr3.dak.netdna-cdn.com/r15lgc.js
OK

http://jsdelivr-cb7.kxcdn.com/r15lgc.js
OK

http://quantil.jsdelivr.net/r15lgc.js
OK

cloudflare.avail.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
availability: 90%
continent: AS
country: TH
asn: 17552

maxcdn.avail.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
availability: 96%
continent: AS
country: TH
asn: 17552

keycdn.avail.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
availability: 100%
continent: AS
country: TH
asn: 17552

quantil.avail.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
availability: 100%
continent: AS
country: TH
asn: 17552

cloudflare.http_rtt.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
116 ms

maxcdn.http_rtt.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
117 ms

keycdn.http_rtt.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
109 ms

quantil.http_rtt.2-01-2cd3-0010.cdx-i-119-76-127-226.cedexis.net
10 ms

Thanks.

**Comment by tony-quantil** [comment]
Hi mjau-mjau, 

The x-via header you are seeing in the response is the cached HTTP header from the original request to the origin for this content. The most left server named "mgny23" is located in NY close to the origin, the second is located in China, the third is the edge node close to you in Bangkok. The edge node in Bangkok is the one that served your request, including the cached HTTP header.
Hope that answers your question, and I will be glad to answer your future questions if there are any.

Tony
CDN Product Manager
QUANTIL
www.quantil.com

**Comment by mjau-mjau** [comment]
Ok thanks ... Good to know that things seem to be working nicely. I would have guessed NY and China, but I would never have guessed "Mangu" in Bangkok ... It would have been optimal with a reference chart or a better x-via location-description, but I guess this depends on many factors.
