### ISSUE TITLE
"latest" version tag not working as expected 

### ISSUE THREAD

**Issue by frncesc** [jsdelivr/jsdelivr#13595]
Project "jclic.js" was updated two days ago from __v0.1.33__ to __v0.1.34__ in GitHub.
Everything seems to be OK in JSDelivr:

- API and project page indicate that 0.1.34 is the latest version, as expected:
http://www.jsdelivr.com/projects/jclic.js
https://api.jsdelivr.com/v1/jsdelivr/libraries?name=jclic.js

- Direct calls with full version tag work properly, returning 0.1.34:
https://cdn.jsdelivr.net/jclic.js/0.1.34/jclic.min.js 

- Also calls with lower branch version digits are returning 0.1.34:
https://cdn.jsdelivr.net/jclic.js/0.1/jclic.min.js
https://cdn.jsdelivr.net/jclic.js/0/jclic.min.js

- And it also works fine using the "merge" mode:
https://cdn.jsdelivr.net/g/jclic.js

... but calling jsdelivr with `latest` (our favorite method!) erroneusly returns the previous version (0.1.33):
https://cdn.jsdelivr.net/jclic.js/latest/jclic.min.js

Please, can you check it?

Thanks!!

**Comment by jimaek** [comment]
/lastest/ is cached for 7 days for performance reasons. I just purged the cache for it to work but normally it would expire by itself.

**Comment by frncesc** [comment]
OK, 

Thank you very much!!
