### ISSUE TITLE
Make it scalable through reviews

### ISSUE THREAD

**Issue by franciscop** [jsdelivr/jsdelivr#13631]
Following on https://github.com/jsdelivr/jsdelivr/issues/13136, I'd like to propose something new. I was going to offer reviewing few PR when I saw my project still not merged to help with the load. But that would be only one-off, so maybe you could ask that for each PR or project someone wants to add, they have to review 5-10 other open PR and give a :+1: or :-1: for moderation and maybe point out some improvements. This way the more PR, the more reviews of other projects that are generated (thus making it scalable).

Also, there is a project called [Up For Grabs](https://github.com/jsdelivr/jsdelivr/issues/13136) where many people new to OSS get started contributing, so maybe you are interested on plugging it in so they can review projects. I've found [many people that contribute a bit each](https://github.com/umbrellajs/umbrella/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Aup-for-grabs%20) through there.

I don't know if the language would be better _requiring_ or _recommending_ to do this, but I think that would be up to you and how much load you are getting (I suggest strongly recommending it, in the end of the day most open source contributors just want to help, even more an amazing project like jsdelivr).

**Comment by jimaek** [comment]
Even with lots of contributors the current format cant work in the long term. It needs a complete overhaul and automation if the project is to survive. Already lots of people are leaving jsDelivr.

I am starting the work on the npm proxy soon.

**Comment by franciscop** [comment]
@jimaek I don't know the internals but I don't *just* mean a lot of contributors; I mean a number of contributors relative to the number of requests. So the bot could auto-accept a PR with 5 :+1: and 0 :-1: for example.

**Comment by jimaek** [comment]
It still wont work. Too much manual work is required. Plus the repo size will continue to grow

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
