### ISSUE TITLE
HPKP & HSTS Support

### ISSUE THREAD

**Issue by indolering** [jsdelivr/jsdelivr#13678]
Downgrading a request to HTTP or getting an HTTPS certificate for a website is fairly low bar to clear.  While I understand you have to support HTTP, what about a subdomain that enforces HTTPS (via HSTS) and pins the key for ~72 hours (~~HSTS~~ HPKP)?  Ideally, projects would be able to opt-out of the non-HTTPS CDN as well.

**Comment by jimaek** [comment]
I dont understand this part "Downgrading a request to HTTP or getting an HTTPS certificate for a website is fairly low bar to clear." What do you mean by that?

**Comment by indolering** [comment]
Downgrade attacks/TLS stripping is less of an issue when it comes to libraries, as the problem typically arises when people punch in the address to a website by hand.  But it would be nice if the libraries also refused to load.

There has been [research](https://github.com/konklone/cdns-to-https) on upgrading standard requests to HTTPS on CDNs and it looks like everything redirects fine save for some CORS issues.  [cdnjs](https://github.com/cdnjs/cdnjs/issues/4328) is switching to HSTS for the primary domain and have even added themselves to the browser preload list.

However, the HTTPS infrastructure is very insecure: there are about 2K entities that can issue an HTTPS certificate for **any** website and even Comodo was hacked by script kiddie.  The certificate authorities issue certificates based on the ability to receive an email, create a DNS record, or embed some HTML in a page ... so you basically have to trust every network and service provider between your servers and the 2K issuing entities out there.

HPKP mitigates the issue by binding trust in the browser to a specific key that it has seen before.  This key can even be put into the browser preload list, that way even users who haven't visited the website remain secure.  Not sure if that is feasible for you given your use of multiple CDNs.

**Comment by jimaek** [comment]
Ok, I will keep this issue open for now. We are actively working on the new version of jsDelivr right now and we might include this in there as well.
Thanks
