### ISSUE TITLE
Make Subresource Integrity attr visible by default

### ISSUE THREAD

**Issue by indolering** [jsdelivr/jsdelivr#13749]
I would like to advocate for switching to displaying the entire `<script src="https://..." integrity="sha256-SAex..." crossorigin="anonymous">` tag by default.

I took me a while to find the SRI tag in the UI and this would encourage people to use the SRI attribute.  People who only need the raw URL can easily select it from within the larger display.

**Comment by jimaek** [comment]
part of new website
