### ISSUE TITLE
how long does take to get to jsdelivr update a new release?

### ISSUE THREAD

**Issue by douglasdeodato** [jsdelivr/jsdelivr#14053]
Hi guys,

how long does take to get to jsdelivr update a new release?

I did a new release  36 minutes ago in my github project and still not publish.

I have info and update running. 

thanks

**Comment by douglasdeodato** [comment]
looks like it take 2 days after the release has been done?

**Comment by megawac** [comment]
It depends on a couple things. Usually 30 mins-1 day (the updating bot crashes from time to time ;))
