### ISSUE TITLE
jsDelivr is not keeping file structure

### ISSUE THREAD

**Issue by RoteMinecraftIL** [jsdelivr/jsdelivr#14253]
When I updated my project to `0.3.1`, the file structure kinda broke.
I expected it to be something like

```
0.3.1
  | rotem.min.css
  | rotem.css
  |-fonts
    | ionicons.eot
    | ionicons.ttf
    |...
```

But instead, I got this:

```
0.3.1
  | rotem.min.css
  | rotem.css
  | ionicons.eot
  | ionicons.ttf
  |...
```

How can I fix this, so the files will work correctly?

**Comment by megawac** [comment]
can you link the update.json in question?
