### ISSUE TITLE
Project not available in search

### ISSUE THREAD

**Issue by sslotsky** [jsdelivr/jsdelivr#14296]
The `violet` css framework was merged some time ago in #13582, but still does not show up when in the search on jsdelivr.com.

**Comment by megawac** [comment]
You need to create a git tag on your repo before your project will get pulled onto the CDN

https://github.com/kkestell/violet/releases

**Comment by sslotsky** [comment]
@megawac there is now a release but the search still does not pull up violet. Is there a minimum version number or something like that?
