### ISSUE TITLE
non-gzipped/non-deflated responses is trimming trailing newlines.

### ISSUE THREAD

**Issue by jdalton** [jsdelivr/jsdelivr#14459]
While adding [SRI integrity attributes](https://www.srihash.org/) I noticed that the response for 

> https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js)

 was incorrect.

It looks like jsdelivr is truncating the last `\n` for non-gzipped/non-deflated responses.
The trimming, different responses for non-gzipped and gzipped, will cause SRI checks to fail for non-gzipped client responses.

Related to https://github.com/request/request/issues/2434 and https://github.com/mozilla/srihash.org/issues/152.

**Comment by jdalton** [comment]
The trimming will cause SRI checks to fail for non-gzipped responses.

**Comment by jimaek** [comment]
I will take a look but using SRI with combined URLs is really not recommended as these links are highly dynamic

**Comment by jdalton** [comment]
The combined build is of libs at specific versions so shouldn't be dynamic.

**Comment by jimaek** [comment]
True, but it still wasn't meant to be used with SRI. Still, I will try to fix this issue as long as its not a CDN level bug.

Btw how important is the combination feature for you? We are building a new backend with new features and I would love your input.

**Comment by jdalton** [comment]
> Btw how important is the combination feature for you? We are building a new backend with new features and I would love your input.

I dig it. It's come in handy more than a few times.

**Comment by jdalton** [comment]
Any updates @jimaek?

**Comment by jimaek** [comment]
Hey, sorry it took so long. After reviewing everything the only solution I see right now is to avoid using SRI with /g/ URLs. Fixing it is a bit problematic and could break SRI for other websites that already use it.

We are working on jsDelivr v2 anyway right now. The problem will be fixed there and wont generate any negative effects like the current solution would

**Comment by jdalton** [comment]
Cool!
