### ISSUE TITLE
SweetAlert2 package is not updated to the latest

### ISSUE THREAD

**Issue by limonte** [jsdelivr/jsdelivr#14468]
You can see here https://cdn.jsdelivr.net/sweetalert2/latest/sweetalert2.js that current jsdelivr version of sweetalert2 is `v5.3.5`, but the actual latest is [v5.3.8](https://github.com/limonte/sweetalert2/releases/tag/v5.3.8), which was released 6 days ago.

Also, there's no https://cdn.jsdelivr.net/sweetalert2/5.3.8/sweetalert2.js which makes me think that something is happened to the indexing process of jsdelivr.

**Comment by MartinKolarik** [comment]
Fixed. Thanks for reporting.

**Comment by limonte** [comment]
Thank you @MartinKolarik :beers:
