### ISSUE TITLE
Merge id- cd52681 not yet shown in jsDelivr CDN links

### ISSUE THREAD

**Issue by Syncfusion-JavaScript** [jsdelivr/jsdelivr#14460]
We have added some new files in released version 14.3.49. It seems its moved to jsDelivr:master. But the CDN links are not shown for newly committed(Merge id- cd52681) files in the below link.

https://www.jsdelivr.com/projects/syncfusion-javascript 

We need to show the CDN links to this newly committed files too. Is it possible to show the CDN links for newly committed files in latest version 14.3.49 ?

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
