### ISSUE TITLE
dinamical-rcms library, not visited by jsdelivr bot

### ISSUE THREAD

**Issue by estebanrfp** [jsdelivr/jsdelivr#14474]
Hi, I have recently added my library. but i cant see any changes at the moment
How can I fix this?

**Comment by louisameline** [comment]
Same here, the bot has not updated jquery.tooltipster over the last month.

**Comment by louisameline** [comment]
In my case the bot actually refused the PR but I did not get a notification. I'll delete my comment in this issue.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
