### ISSUE TITLE
Files not found on "https://cdn.jsdelivr.net/"

### ISSUE THREAD

**Issue by pmeisen** [jsdelivr/jsdelivr#14819]
The version 1.0.6 of our library `breinify-api` was added to the GitHub repository, but if someone tries to use the version through https://cdn.jsdelivr.net/breinify-api/1.0.6/breinify-api.min.js or https://cdn.jsdelivr.net/breinify-api/1.0.6/breinify-api.js the system returns with "File not found".

The correct file is released in our GitHub and was correctly merged with the jsdelivr GitHub, see https://github.com/jsdelivr/jsdelivr/tree/master/files/breinify-api/1.0.6

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
