### ISSUE TITLE
Could not find file specified in mainfile for project

### ISSUE THREAD

**Issue by oblogic7** [jsdelivr/jsdelivr#15319]
Getting the following error on some connections.

![image](https://cloud.githubusercontent.com/assets/453840/21116951/5c892844-c07d-11e6-9210-dada6ddd9c12.png)

**Comment by Mottie** [comment]
It looks like the URL you used references tablesorter as `tablesorter@2.17.4`, but it needs to be changed to `tablesorter@2.17.4(js/jquery.tablesorter.js)`... try this link instead:

https://cdn.jsdelivr.net/g/toastr@2.0.1,bootstrap.daterangepicker@1.3.21,numeraljs,bootstrap.select@1.6.3,uniformjs@2.1.2,bootstrap.switch@3.3.2,jquery.blockui,amplifyjs,is.js,typeahead.js,tablesorter@2.17.4(js/jquery.tablesorter.js),backbonejs@1.3.2,keen.js

**Comment by abishekrsrikaanth** [comment]
Correcting mainfile to fix this issue https://github.com/jsdelivr/jsdelivr/pull/15358

**Comment by Mottie** [comment]
Thanks!

**Comment by Mottie** [comment]
Umm actually, that change breaks linking to the newer versions of tablesorter... versions 2.17.4 and older have a different directory structure - there is no `dist` folder.

**Comment by Mottie** [comment]
Interestingly, if you look at the API: https://api.jsdelivr.com/v1/jsdelivr/libraries?name=tablesorter

You'll see that all the available version `"mainfile"` entries are using the most current `info.ini` setting.

**Comment by Mottie** [comment]
@megawac would you please look at this again?

**Comment by megawac** [comment]
Its working for me, clear your cache

**Comment by Mottie** [comment]
I cleared my cache, and the main jsDelivr page is still not showing the most recent versions:

http://www.jsdelivr.com/?query=tablesorter

![2016-12-16 03_51_52-jsdelivr - a free super-fast cdn for developers and webmasters](https://cloud.githubusercontent.com/assets/136959/21258551/2ab93674-c343-11e6-93ea-3faaaaf7ff4f.png)

The JSON in the api has the incorrect `mainfile` values for the last two versions:

```js
[{
  "assets": [{
    "files" : [...],
    "version": "2.28.2",
    "mainfile": "js/jquery.tablesorter.min.js" // this should be "dist/js/..."
  },{
    "files" : [...],
    "version": "2.17.4",
    "mainfile": "js/jquery.tablesorter.min.js" // correct
  },{
    // ...
  }
}]
```

**Comment by Mottie** [comment]
Ok, now it's working... I guess pushing out a new version fixed it.

**Comment by Mottie** [comment]
Sorry to be a nuisance! But it appears that the main page is stuck on v2.17.4 for my repository again. I've refreshed my cache, cleared storage and tried different browsers....
