### ISSUE TITLE
d3.js project not picking up new versions

### ISSUE THREAD

**Issue by bradvogel** [jsdelivr/jsdelivr#15568]
Hi, this is a question that I asked in Gitter but didn't get a response. So I'm asking here hoping someone can help.

I'm confused why libgrabber stopped picking up D3.js updates at version v3.5.17, when the latest is v4.4.0 in D3's github repo: (https://github.com/jsdelivr/jsdelivr/tree/master/files/d3js). It has an auto-update file (https://github.com/jsdelivr/jsdelivr/blob/master/files/d3js/update.json) and the repo is properly tagged in git.

**Comment by MartinKolarik** [comment]
It's just a guess but try to send a PR to change `repo` in update.json from `mbostock/d3` to `d3/d3`

**Comment by bradvogel** [comment]
Thanks! Filed https://github.com/jsdelivr/jsdelivr/pull/15569. Will close this.
