### ISSUE TITLE
add jquery-sparkle

### ISSUE THREAD

**Issue by helantao** [jsdelivr/jsdelivr#15669]
Library name: jquery-sparkle
Git repository url: https://github.com/maxspeicher/jquery-sparkle
npm package url(optional): https://github.com/maxspeicher/jquery-sparkle
License(s): MIT
Official homepage: https://github.com/maxspeicher/jquery-sparkle
Wanna say something? Leave message here:

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
