### ISSUE TITLE
Add jPut

### ISSUE THREAD

**Issue by helantao** [jsdelivr/jsdelivr#15670]
Library name: jPut
Git repository url: https://github.com/shabeer-ali-m/jPut
npm package url(optional): https://github.com/shabeer-ali-m/jPut
License(s): MIT
Official homepage: https://github.com/shabeer-ali-m/jPut

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
