### ISSUE TITLE
Moving repo to organization repository breaks CDN?

### ISSUE THREAD

**Issue by ron666** [jsdelivr/jsdelivr#16149]
Currently, John Dyer's repositories (mediaelement ones) are under his name but he's considering moving them into an organization repo. Would that break anything on your side?

**Comment by megawac** [comment]
Nope, might require updating the github URLs eventually, but github automatically forwards the urls to the migrated URL by default AFAIK

**Comment by ron666** [comment]
@johndyer FYI
