### ISSUE TITLE
Problem with font-awesome 4.2.0 lib hosted on EXVM-SG

### ISSUE THREAD

**Issue by ping** [jsdelivr/jsdelivr#1624]
http://exvm-sg.jsdelivr.net/fontawesome/4.2.0/css/font-awesome.css (and the .min version too) is referring to font files on the domain **oss.maxcdn.com** (instead of a relative path on the same domain). 

In addition, .min version refers to the font file http://oss.maxcdn.com/fontawesome/4.2.0/sfonts/fontawesome-webfont.woff?v=4.2.0 which is missing (404) but the full version refers to http://oss.maxcdn.com/fontawesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0. It looks like the .min version has a typo in the path, **sfonts** instead of fonts.

**Comment by misterkumarsharma** [comment]
yes it fixed now
