### ISSUE TITLE
[advice request]: Publishing a parallel version of bootstrap.native

### ISSUE THREAD

**Issue by thednp** [jsdelivr/jsdelivr#16243]
A lot of users requested a V4 version of [bootstrap.native](https://github.com/thednp/bootstrap.native) and I delivered, but I need your advice on how to publish it to CDN/npm:

* should I make a new repository `bootstrap.native.v4` to make a PR for a new script
* should I rename files to `bootstrap-native-v4.js` and publish them in the same `/dist` folder?
* is there anything better to do in this case?

Thanks.

**Comment by megawac** [comment]
Both those options work for us on our end. We try not to enforce too many opinions on our users.

I think the `bootstrap-native-v4.js` may make more sense but feel free to take either approach.
