### ISSUE TITLE
Moved lib jquery-form

### ISSUE THREAD

**Issue by kevindb** [jsdelivr/jsdelivr#16461]
http://www.jsdelivr.com/projects/jquery.form
The [jquery-form/form](https://github.com/jquery-form/form) project has changed ownership from [malsup/form](https://github.com/malsup/form).

I'm not sure what the best practice is to update the library. The canonical URL should probably change to `http://www.jsdelivr.com/projects/jquery-form`, but I don't want to break existing links that are pointing to `jquery.form`. Is there anything cleaner than "list the library twice"? Maybe a redirect from the old URL to the new?

Thank you for your help. I'm trying to breathe new life into this project and make its transition as smooth as possible.

**Comment by megawac** [comment]
I would suggest continue using the `jquery.form` project name. Otherwise the only other option is to list the library twice.

**Comment by kevindb** [comment]
#16544 has been merged and the website has updated with 4.0.1. Thank you for your help!
