### ISSUE TITLE
Chart.js is not updated

### ISSUE THREAD

**Issue by whs** [jsdelivr/jsdelivr#16860]
Even though it have an [update.json](https://github.com/jsdelivr/jsdelivr/blob/master/files/chart.js/update.json) and latest release on [GitHub release](https://github.com/chartjs/Chart.js/releases). Chart.js in JSDelivr seems to be very outdated.

Is there anything wrong with the auto update process?

**Comment by masimao** [comment]
jQuery Migrate is still the version 1.4.1, while 3.0.0 is already available.

I found various other resources outdated too.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
