### ISSUE TITLE
Links Collections Issue : Web fonts failed to load 404

### ISSUE THREAD

**Issue by msivakr** [jsdelivr/jsdelivr#16997]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: https://cdn.jsdelivr.net/g/bootswatch@3.3.7(cyborg/fonts/glyphicons-halflings-regular.woff2  bootstrap-select.min.css),cookieconsent3@3.0.4(cookieconsent.min.css):12:3072

downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: https://cdn.jsdelivr.net/g/bootswatch@3.3.7(cyborg/fonts/glyphicons-halflings-regular.woff

**Comment by jimaek** [comment]
The URLs look broken. Please provide more info to reopen the task.
