### ISSUE TITLE
Zepto JS unminified 

### ISSUE THREAD

**Issue by Chiru13** [jsdelivr/jsdelivr#17010]
Hello,

Can you provide a minified version of the addons? https://cdn.jsdelivr.net/zepto/1.2.0/fx.js and others? as currently I use this: https://cdn.jsdelivr.net/g/zepto@1.2.0(zepto.min.js+fx.js) and Zepto is minified but the FX module isn't.

Thanks!

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
