### ISSUE TITLE
Taking built files from npm.

### ISSUE THREAD

**Issue by ritz078** [jsdelivr/jsdelivr#17248]
Hi,

I am the creator of [embed.js](https://github.com/ritz078/embed.js).

Earlier the `dist` folder was available on github and the cdn was working fine. Then I removed it from github and added the `build` script to `prepublish` hook of npm. So currently the folder is available on npm but not github. So due to jsdelivr isn't updating. I there anything I need to do ? Any help is appreciated.

**Comment by jimaek** [comment]
The new version of jsDelivr will automatically support npm projects without any config required. It will be released soon so please wait. 
If you are in a hurry you could send a manual PR with your files.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
