### ISSUE TITLE
Repos moved to organization repo not reflecting latest version

### ISSUE THREAD

**Issue by ron666** [jsdelivr/jsdelivr#17267]
My repos for MediaElement got moved to an organization repo (https://github.com/mediaelement/mediaelement-plugins and https://github.com/mediaelement/mediaelement) so right now they are not reflecting the latest versions.

I created PRs to update the info.ini for both projects (#17178 and #17179). Is that all I need to do?

**Comment by megawac** [comment]
Yep, should be good. Feel free to ping me if they aren't picked up after these updates.

**Comment by ron666** [comment]
Thanks. I had to do one more update to the info.ini files. If you can merge them I'd appreciate it. After that, how much time should it pass to see the changes?

**Comment by ron666** [comment]
BTW my PRs are #17283 and #17281
