### ISSUE TITLE
MediaElement latest version now showing up

### ISSUE THREAD

**Issue by ron666** [jsdelivr/jsdelivr#17294]
@megawac I adjusted my info.ini files to reflect a new URL for the MediaElement and MediaElement Plugins projects. But none of them are pointing to the right versions on the jsDelivr website. They must point now to 4.0.2 and 2.0.0, respectively

**Comment by megawac** [comment]
I think the `update.json` requires updating (https://github.com/jsdelivr/jsdelivr/blob/master/files/mediaelement/update.json)

**Comment by ron666** [comment]
The interesting thing is that it's pointing right now to the right repo `mediaelement/mediaelement`; other than that I don't know what else needs to be updated on it. Any hints?

**Comment by ron666** [comment]
Oh, I see. You already committed that change. Thanks. BTW I just updated the `update.json` for the other repo. If you can merge this it'd be awesome

**Comment by ron666** [comment]
@megawac I noticed that my PR (#17314) has an error but it's related to a change on the file structure. What can I do if that's a necessary change?

**Comment by megawac** [comment]
No worries, more of just a warning than an error

**Comment by ron666** [comment]
I see. Thanks for your quick response
