### ISSUE TITLE
jsdelivrbot seems to be ignoring new tags

### ISSUE THREAD

**Issue by floydpink** [jsdelivr/jsdelivr#17613]
There have been a few new tags added on the source repo that somehow are not being picked up by `libgrabber`

Can someone please guide me on the right direction to understand the issue and how it can be resolved?

Source repo: https://github.com/kollavarsham/smc-webfonts
Info.ini: https://github.com/jsdelivr/jsdelivr/blob/master/files/smc-webfonts/info.ini
Update.json: https://github.com/jsdelivr/jsdelivr/blob/master/files/smc-webfonts/update.json

Thanks

**Comment by mistic100** [comment]
Same for https://github.com/mistic100/jQuery-QueryBuilder/releases/tag/2.4.3

**Comment by floydpink** [comment]
Is there a log file that `libgrabber` generates somewhere that can be looked into to see why a specific repository is not being synced?

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
