### ISSUE TITLE
jsdelivr serves a broken file

### ISSUE THREAD

**Issue by akashta** [jsdelivr/jsdelivr#17808]
Hi,

Sometimes jsdelivr serves a broken file cdn.jsdelivr.net/hola_player/1.0.30/hola_player.js.
The file ends with `{if(!(a instanceof b))throw new TypeError("Cannot call a` that causes a syntax error.
It seems that broken file comes from Fastly CDN.

I have saved HAR files for a bad request and a good one:
- bad: https://drive.google.com/open?id=0B4dQYL-OgjGbRFkxNkQzV1dRRHc
- good: https://drive.google.com/open?id=0B4dQYL-OgjGbaXp4eXNXV0NRelE

You can open HAR files with https://toolbox.googleapps.com/apps/har_analyzer/ 
Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/11210348/25426212/14cd8d92-2a77-11e7-8e43-8576df21b91e.png)

Thanks!

**Comment by jimaek** [comment]
We dont modify the files. Please try using a newer versions from the author
