### ISSUE TITLE
SSL Certificate SHA1 issue on Chrome

### ISSUE THREAD

**Issue by msivakr** [jsdelivr/jsdelivr#17876]
> You attempted to reach cdn.jsdelivr.net, but the server presented a certificate signed using a weak signature algorithm (such as SHA-1). This means that the security credentials the server presented could have been forged, and the server may not be the server you expected (you may be communicating with an attacker).

I am getting this error message over 15 days, how to sort this?

**Comment by jimaek** [comment]
Please provide more information. What is your browser. What is the URL.
Full HTTP headers from the URL and IP when you try to ping the hostname.
