### ISSUE TITLE
Auto-generate minified files in WordPress proxy

### ISSUE THREAD

**Issue by as-com** [jsdelivr/jsdelivr#17994]
For example, https://cdn.jsdelivr.net/wp/contact-form-7/trunk/includes/js/scripts.js does not come with a minified version, and a minified version should be automatically generated with a `.min` request, similar to the npm proxy.

**Comment by jimaek** [comment]
The /wp/ endpoint does not have the same abilities as the ones above it. So no minification either. At least for now
