### ISSUE TITLE
Integrate jsDelivr

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr#17993]
Since our new backend automatically supports all projects hosted at npm/github/wordpress we can easily integrate it into all kinds of systems.

For example automated "CDN Links" on websites that show npm listing. All kinds of plugins that would generate CDN links. 
We can do the full integration ourselves and simply send a pull request adding this functionality if the relevant project is open source.

Share here your ideas what kind of integrations we could build.

**Comment by smartclash** [comment]
@jimaek Awesome idea

**Comment by jhabdas** [comment]
It would be cool if the jsDelivr WordPress plugin could be used to install WP plugins over the wire. This direction could help new WordPress developers hosting on GitHub the additional effort of trying to figure out how to deploy to SVN.

**Comment by JorgeAntrax** [comment]
HoHi, I'm having trouble viewing my website on a mobile device.
Trato de abrir este enlace en un celular moto G4 .

https://cdn.jsdelivr.net/gh/JorgeAntrax/kimera@0.2.6/css/kimera.min.css
En una computadora todo bien me muestra el archivo pero en mi celular no carga el css que estoy enlazando mediante cdn.

**Comment by JorgeAntrax** [comment]
Me podrías apoyar a revisar si configure todo bien o a saber porque pasa esto, gracias
