### ISSUE TITLE
New Version Syncfusion packages not updated

### ISSUE THREAD

**Issue by GanesanRengasamy** [jsdelivr/jsdelivr#17999]
We have released the new version (15.2.0.40) Syncfusion-ej-global (https://www.jsdelivr.com/projects/syncfusion-ej-global) and Syncfusion-JavaScript (https://www.jsdelivr.com/projects/syncfusion-javascript) packages. But these are still not yet updated in registry.

Please look into this and update the latest version (15.2.0.40) Syncfusion packages.

Regards,
Ganesan R.

**Comment by jimaek** [comment]
We switched to a new automated system. We can now pull your files directly from npm or github. Read more about it here https://github.com/jsdelivr/jsdelivr#usage

**Comment by GanesanRengasamy** [comment]
Okay. But still the registry is not updated to the latest version. Also, we are creating the new issue regarding this and send the mail to you for every release.  Is this the procedure to publish the packages in jsdelivr for every release?

**Comment by jimaek** [comment]
No pull requests are needed. We pull directly from npm. Everything is automated.
For example https://cdn.jsdelivr.net/npm/syncfusion-ej-global@15.2.40/

**Comment by GanesanRengasamy** [comment]
it's confusing..... 

Still the jsdelivr registry is not updated to the latest version. I just want publish the Syncfusion JavaScript and Syncfusion ej-global package in jsdelivr. Please refer to the below screenshot.

![image](https://cloud.githubusercontent.com/assets/16695209/25896201/cedc7ad4-35a0-11e7-9a70-13946ed5e5cc.png)

In the below links still the latest version packages are not updated.
https://www.jsdelivr.com/projects/syncfusion-ej-global
https://www.jsdelivr.com/projects/syncfusion-javascript

**Comment by jimaek** [comment]
The website is outdated. The new version of that project is on our CDN. You can see it here https://cdn.jsdelivr.net/npm/syncfusion-ej-global@15.2.40/

**Comment by MartinKolarik** [comment]
@GanesanRengasamy the website is completely separate from the CDN and doesn't support the new features yet. Everything you publish to npm is automatically available on jsDelivr in less than 1 minute after publishing, even when not listed on the website.

**Comment by GanesanRengasamy** [comment]
Thanks for the response. 

We can use the ej-global files from the link you mentioned till the website will be updated for the Syncfusion ej-global packages. What about the Syncfusion JavaScript packages? I tried the below link to use the Syncfusion Javascript files.

https://cdn.jsdelivr.net/npm/syncfusion-javascript@15.2.40/Scripts/ej/web/ej.web.all.min.js

But I have faced the problem like below,

![image](https://cloud.githubusercontent.com/assets/16695209/25897478/b23eb126-35a5-11e7-90c0-f428f8a041b0.png)

Could you please update the Syncfusion JavaScript packages published details like the Syncfusion ej-global?

**Comment by jimaek** [comment]
Your project is over our limit of 50MB. Normally this is not a problem and we could just increase this limit,
BUT your project is not open source. 
jsDelivr is only for projects using an open license. You dont, so we cant offer you any support.
You need to use a commercial CDN such as Fastly, MaxCDN or CloudFlare.

thanks
