### ISSUE TITLE
MediaElementJS not up-to-date

### ISSUE THREAD

**Issue by rafa8626** [jsdelivr/jsdelivr#18006]
The current version of MediaElementJS is 4.1.1; however, in your website is only listed until 4.1.0, can you assist with that, please?

**Comment by jimaek** [comment]
The website is outdated at the moment. Read here about how to use the new jsdelivr backend https://github.com/jsdelivr/jsdelivr#usage

**Comment by rafa8626** [comment]
So, is there an estimated time where the website will be updated soon? I rely on the CDN for several projects to maintain the latest version available

**Comment by jimaek** [comment]
You dont need the website for that. You can create your own CDN links by simple using the names of the projects you want to use. For example 

http://cdn.jsdelivr.net/npm/mediaelement/
http://cdn.jsdelivr.net/npm/mediaelement@4.1.1/build/mediaelement.min.js

**Comment by rafa8626** [comment]
Gotcha. Thanks for the quick response and clarification.
