### ISSUE TITLE
Regarding the 50mb limit

### ISSUE THREAD

**Issue by ping** [jsdelivr/jsdelivr#18002]
As an offshoot question from #18001, is the 50mb a hard limit or can devs request for exceptions?

This limit will effectively exclude emoji libs, which is a bigger problem then before now that emojione v3 (Ranks/emojione/issues/488) has adopted a new restrictive license.

For FOSS alternatives, there is still good old [twitter/twemoji](https://github.com/twitter/twemoji) and a fork of emojione v2 [EmojiTwo/emojitwo](https://github.com/EmojiTwo/emojitwo) but neither can currently be supported by jsdelivr.

If exceptions can be made, I think it will be good to clarify the kind of projects that can apply, and the procedure to request so.

**Comment by jimaek** [comment]
Right now its not possible to create exceptions per project, but I think we should allow that. Once we do that we can document the procedure.

Until then the best solution is "custom cdn" https://github.com/jsdelivr/jsdelivr#custom-cdn-hosting

**Comment by MartinKolarik** [comment]
Higher limits for whitelisted projects might actually work but we'll need to test how large the package can be to prevent upstream timeouts. For `/gh/`, we probably can't go much higher.

**Comment by ping** [comment]
It seems both simultaneously hopeful and unhopeful at the same time lol.

I suspect a better time to broach this, is probably after the new backend/website has stabilised. I'll wait for the dust to settle. :) Thanks again.
