### ISSUE TITLE
Readme section on WordPress doesn't indicate source

### ISSUE THREAD

**Issue by Shelob9** [jsdelivr/jsdelivr#18018]
I'm pretty sure that when you refer to WordPress in your docs, as a source for files, you mean, https://plugins.svn.wordpress.org/ specifically. That should be made clear, because not all WordPress plugins are available via WordPress.org which could be confusing.

I'll make a PR based on my assumption.

**Comment by jimaek** [comment]
You are correct, thanks for the PR.
