### ISSUE TITLE
We cannot load any Scripts/css cdn links which is hosted from jsDelivr npm / GitHub

### ISSUE THREAD

**Issue by Syncfusion-JavaScript** [jsdelivr/jsdelivr#18014]
**Issue 2:**
We have try to load any Scripts/css cdn links which is hosted from jsDelivr npm / GitHub we got below error message.
https://cdn.jsdelivr.net/npm/syncfusion-ej-global@15.1.41/i18n/ej.culture.en-US.js
"Package size exceeded the configured limit of 50 MB."
Can you update any workarounds regarding this package size exceeded validations ?

**Comment by jimaek** [comment]
@MartinKolarik I dont see this error. How is it possible to have the error appear and disappear later?

**Comment by MartinKolarik** [comment]
@Syncfusion-JavaScript I'm not sure how you could get that error message with `syncfusion-ej-global`, that package is less than 1 MB.

**Comment by Syncfusion-JavaScript** [comment]
@jimaek, @MartinKolarik  - Have any workaround regarding package size exceeded validation ?

**Comment by MartinKolarik** [comment]
@Syncfusion-JavaScript what packages are we talking about?

**Comment by Syncfusion-JavaScript** [comment]
@MartinKolarik - We got the package size exceed validation message from syncfusion-javascript package. Find the sample files from below packages which I have tested both npm and github. 

# **Syncfusion-JavaScript**

## Files try to load 

https://cdn.jsdelivr.net/gh/syncfusion/JavaScript-Widgets@15.2.43/Content/ej/web/bootstrap-theme/ej.web.all.min.css

https://cdn.jsdelivr.net/npm/syncfusion-javascript@15.2.43/Content/ej/web/bootstrap-theme/ej.web.all.min.css

## Error Message

Package size exceeded the configured limit of 50 MB.

# ej-global

## Files Try to load

https://cdn.jsdelivr.net/npm/syncfusion-ej-global@15.2.43/i18n/ej.culture.ar-AE.min.js

https://cdn.jsdelivr.net/gh/syncfusion/ej-global@15.2.43/i18n/ej.culture.af-ZA.js

## Result

Loaded successfully.

**Comment by MartinKolarik** [comment]
#17999
