### ISSUE TITLE
Hate to be that guy...

### ISSUE THREAD

**Issue by jhabdas** [jsdelivr/jsdelivr#18011]
http://cdn.jsdelivr.net/npm/hack@0.8.0/dist/hack.min.css

I noticed the dynamically generated minfied bundles don't include the current `LICENSE` file.

**Comment by jimaek** [comment]
The original doesnt include it either http://cdn.jsdelivr.net/npm/hack@0.8.0/dist/hack.css

**Comment by jhabdas** [comment]
It's not requisite for MIT/ISC so long as the license is included in the source. I gave an issue to add a license banner here: https://github.com/egoist/hack/issues/56

**Comment by jimaek** [comment]
Pulling an external LICENSE file would be too much I think. But its certainty possible to leave existing license information un-touched. I am also curious what the hack authors will say

**Comment by jhabdas** [comment]
Most projects tend to use a banner when bundling minified versions to save space. jQuery is a good example of this. Banners usually prefix with `/*!` and include a `@license` or `@copyright` doc block to help prevent stripping by compressors. I just had some OSS I worked very hard on copied without attribution today and learned how to apply AGPL for a WordPress plugin so this stuff is all very top of mind for me right now.

**Comment by jhabdas** [comment]
Well, I'm not just going leave this open. I did my part.
