### ISSUE TITLE
New version not updated 

### ISSUE THREAD

**Issue by Syncfusion-JavaScript** [jsdelivr/jsdelivr#18013]
**Issue 1:**
We have "update.json" file in our github repo and it was updated properly each new versions automatically till version 15.1.41. Please refer our Github repos below, 

1.https://github.com/Syncfusion-JavaScript/jsdelivr/tree/master/files/syncfusion-ej-global 
2.https://github.com/Syncfusion-JavaScript/jsdelivr/tree/master/files/syncfusion-javascript
After release v15.4.40, v15.4.41 and v15.4.43, Its not updated properly in below mention jsDeliver packages
http://www.jsdelivr.com/projects/syncfusion-javascript 
http://www.jsdelivr.com/projects/syncfusion-ej-global

Can you please check and update regarding this ?

**Comment by jimaek** [comment]
These URLs will not get updated anymore. You need to switch to the new /npm/ format and pull files directly from there.

**Comment by Syncfusion-JavaScript** [comment]
@jimaek - Thanks for the update. We have updated another issue regarding package manager publishing. 

https://github.com/jsdelivr/jsdelivr/issues/18014

Can you please look into this ?
