### ISSUE TITLE
Can't combine files from WordPress.org

### ISSUE THREAD

**Issue by Shelob9** [jsdelivr/jsdelivr#18020]
Sorry if this is the wrong channel for this type of issue.

I am trying to integrate jsdelivr with my WordPress plugin Caldera Forms, because I want to use your ability to combine files. See: https://github.com/CalderaWP/Caldera-Forms/issues/1735

But the /combine endpoint doesn't seem to work with /wp For example, these two links work:

- https://cdn.jsdelivr.net/wp/caldera-forms/tags/1.5.2/assets/build/js/ajax-core.min.js
- https://cdn.jsdelivr.net/wp/caldera-forms/tags/1.5.2/assets/build/js/admin.min.js

But I tried https://cdn.jsdelivr.net/combine/wp/caldera-forms/tags/1.5.2/assets/build/js/admin.min.js,wp/caldera-forms/tags/1.5.2/assets/build/js/ajax-core.min.js and got `Invalid URL. The URL structure is /combine/gh/user/repo@version/file.js,npm/package@version/file2.js` 

Am I missing something?

**Comment by jimaek** [comment]
The combination feature is limited to npm and github at the moment. 

You can load these files separately for now, with HTTP2 its actually better to avoid combination.

**Comment by Shelob9** [comment]
@jimaek Thanks for the fast response. I'll go back to trying to get Github to work then, I think that's not working (for example https://cdn.jsdelivr.net/CalderaWP/Caldera-Forms@1.5.2/assets/build/js/admin.min.js)  because we're not using semver properly. 

`You can load these files separately for now, with HTTP2 its actually better to avoid combination.`
I know, but a large number of our users are not using HTTPS and/or have crappy host that doesn't support HTTP2. Part of why I wanted to use jsdelivr is beacuse I want to combine our CSS and JS files further and hurt those using HTTP2, but provide a good option for those who are not.

**Comment by jimaek** [comment]
Fixing github would be the best solution. It should not be very hard to do.

**Comment by Shelob9** [comment]
@jimaek Do you think are problem is that we have tags like 1.5.2.1 and 1.5.2-b-2 or a problem with our package.json (https://github.com/CalderaWP/Caldera-Forms/blob/master/package.json) ?

We don't really have a main file...

**Comment by jimaek** [comment]
@MartinKolarik Please check out what is wrong here

**Comment by MartinKolarik** [comment]
@Shelob9 try https://cdn.jsdelivr.net/gh/CalderaWP/Caldera-Forms@1.5.2/assets/build/js/admin.min.js

**Comment by Shelob9** [comment]
@MartinKolarik That works, as does https://cdn.jsdelivr.net/combine/gh/CalderaWP/Caldera-Forms@1.5.2/assets/build/js/ajax-core.min.js,gh/CalderaWP/Caldera-Forms@1.5.2/assets/build/js/admin.min.js

Thanks, I'll update to use Github. Thanks very much for your help and for this really cool service.

Do y'all want me to leave this open since the original issue (combining based on /wp endpoint) is not resolved?

**Comment by MartinKolarik** [comment]
Let's close this for now as adding features to the WP endpoint is not a priority right now I think.
