### ISSUE TITLE
Using SRI with combined files

### ISSUE THREAD

**Issue by R3turnz** [jsdelivr/jsdelivr#18023]
The comment included in all combined files recommends against using [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).
 
I have following combined file link and can not imagine a scenario where the generated file may change: `https://cdn.jsdelivr.net/combine/npm/purecss@1.0.0/build/base-min.css,npm/purecss@1.0.0/build/buttons-min.css,npm/purecss@1.0.0/build/forms-nr-min.css`.

Also the in the comment mentioned [link](https://www.jsdelivr.com/using-sri-with-dynamic-files) doesn't seem to exist anymore.

**Comment by MartinKolarik** [comment]
>Also the in the comment mentioned link doesn't seem to exist anymore.

Not "anymore", but "yet". See #18008.

In short, when you use specific versions (which you do), the code itself is definitely not going to change. However, breaking SRI is as simple as accidentally adding one more line-feed at the end of the file, or making any other change that won't affect behavior of the code, but changes its checksum.

jsDelivr aims to be 100% reliable, which means if you got a link from us 5 years ago, it still works now, and unless something very bad happens, it's  going to work 5 years from now. However, maintaining this backward compatibility makes any code changes much harder - especially the significant ones (just two months ago we fully replaced our old backend code). This is why we do not recommend using SRI for any files that are generated dynamically. I don't see any reason why the generated file might change right now, but if there ever is one, it *will* change without notice.

**Comment by aleclarson** [comment]
Using `curl https://cdn.jsdelivr.net/npm/jquery-thin@3.2.2/jquery.min.js`, I'm getting the "Don't use SRI" header. Is that expected?

**Comment by jimaek** [comment]
Yes, because its a dynamic file. There is no min.js provided by the author.
This is the original file https://cdn.jsdelivr.net/npm/jquery-thin@3.2.2/jquery.js and doesn't have that message. You can use SRI freely.

**Comment by aleclarson** [comment]
@jimaek Are you sure `curl` uses SRI? That's what stands out to me.

**Comment by aleclarson** [comment]
@jimaek Oh, okay. So that's not the reason UglifyJS is failing. How can I find out the cause of that? Try uglifying on my own computer?

**Comment by jimaek** [comment]
Not sure why its failing. @MartinKolarik Any ideas?

**Comment by MartinKolarik** [comment]
Yeah I already checked that and it complains about a syntax error in that file.

**Comment by aleclarson** [comment]
Strange. The unminified version runs fine in Chrome, etc. I guess uglify has different requirements. I'll run it locally to see the error, I guess.
