### ISSUE TITLE
CORS enabled?

### ISSUE THREAD

**Issue by rendall** [jsdelivr/jsdelivr#18038]
Using this tag from your site

`<script src="https://cdn.jsdelivr.net/npm/rx@4.1.0/index.js" integrity="sha256-phvTBpqcsnOb1AF592NFZeTlIZu3ML8if90ElnYDA7I="></script>`

replies with this message.

> Subresource Integrity: The resource 'https://cdn.jsdelivr.net/npm/rx@4.1.0/index.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.

This is via Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

You can see an example here:
[https://rendall.tv/show/tmp/cdn.html](https://rendall.tv/show/tmp/cdn.html)

**Comment by jimaek** [comment]
Thats strange because we have CORS headers:
`access-control-allow-origin:*`

Need to look into it a bit more

**Comment by jimaek** [comment]
I found the problem, the HTML tag needs to have `crossorigin="anonymous"`

@MartinKolarik Please add `crossorigin="anonymous"` to the SRI template

**Comment by MartinKolarik** [comment]
Yep the SRI spec changed some time ago and I forgot to update the template. Thanks for reporting @rendall, the website should be updated in a few minutes.
