### ISSUE TITLE
HTTP 403 50mb exceeded on github again...?

### ISSUE THREAD

**Issue by pleasantone** [jsdelivr/jsdelivr#18035]
Similar to #17997, I'm seeing 403 messages, even if I'm just trying to read the directory.
I'm not sure if this is a new bug or I'm being an idiot.

I'm not providing a version to the repo because I want latest (this is a dev test):

    $ curl -i https://cdn.jsdelivr.net/gh/hallahan/LeafletPlayback/
    HTTP/2 403
    date: Wed, 30 Aug 2017 08:07:45 GMT
    content-type: text/plain; charset=utf-8
    content-length: 52
    access-control-allow-origin: *
    cache-control: no-cache, no-store, must-revalidate
    timing-allow-origin: *
    vary: Accept-Encoding
    etag: "34-DP18bfOBh8PjBeVBXHGYqHLLNaY"
    cf-cache-status: MISS
    server: cloudflare-nginx
    cf-ray: 3966421b9a6179f3-SEA

    Package size exceeded the configured limit of 50 MB.

I just wanted to read the directory.

Same results for pulling the actual file:

    $ curl -i https://cdn.jsdelivr.net/gh/hallahan/LeafletPlayback/dist/LeafletPlayback.min.js

The file is only 14k.  Testing on jquery/jquery@latest out of github worked fine.

Could this be some sort of misinteraction with github.io doc pages?

Since I'm here, I'll also mention the other following test cases failed, possibly because of a dot in the name?

**Comment by MartinKolarik** [comment]
See https://github.com/jsdelivr/jsdelivr#restrictions. The 50 MB limit is for the whole release, not a single file. [The release](https://github.com/hallahan/LeafletPlayback/releases) is ~86 MB unzipped, which means it's too big.

In most cases, when a package is this big, there are files that are not really needed and could be removed to reduce the size. I recommend asking about this at https://github.com/hallahan/LeafletPlayback

**Comment by MartinKolarik** [comment]
Reopen if necessary.
