### ISSUE TITLE
SVGZ isn't served with the proper headers

### ISSUE THREAD

**Issue by JoshyPHP** [jsdelivr/jsdelivr#18037]
SVGZ is a file format supported by most (all?) of the image manipulation programs that support SVG. It's nothing more than a SVG file compressed with gzip and `.svgz` support is generally implemented as an alias for `.svg.gz` files. The [recommended MIME type](https://www.w3.org/TR/SVG/mimereg.html) for .svgz file is `image/svg+xml`, the same as .svg files. That means that browsers cannot differentiate between SVG and SVGZ based on the `Content-type` header alone.

jsDelivr correctly serves .svgz files with a `Content-type: image/svg+xml` header. However, it incorrectly treats them exactly the same way as a .svg files; It compresses them with gzip if the client announces support for it, making them unusable. The correct way to serve .svgz files would be to never compress them and always serve them with a `Content-encoding: gzip` header.

I understand that jsDelivr uses a multi-CDNs structure; Is that something that can be fixed at jsDelivr's level?

**Comment by MartinKolarik** [comment]
Could you please provide a link to some SVGZ file I could check?

**Comment by JoshyPHP** [comment]
Thanks for the prompt response. The SVG 1.1 conformance test suite contains a test for SVGZ support. You can download the file from their repository using [this link](https://dev.w3.org/cvsweb/~checkout~/SVG/profiles/1.1F2/test/svg/conform-viewers-01-t.svgz?rev=1.4;content-type=application/octet-stream).

[Here's the page on dev.w3.org](https://dev.w3.org/SVG/profiles/1.1F2/test/harness/htmlObject/conform-viewers-01-t.html). You can see the .svgz file served with the appropriate headers.

```
$ curl -I https://dev.w3.org/SVG/profiles/1.1F2/test/svg/conform-viewers-01-t.svgz
HTTP/1.1 200 OK
Date: Sun, 03 Sep 2017 01:28:35 GMT
Server: Apache/2.4.25 (Debian)
Last-Modified: Mon, 29 Nov 2010 04:18:28 GMT
ETag: "88c-496295d2e8d00"
Accept-Ranges: bytes
Content-Length: 2188
Cache-Control: max-age=172800
Expires: Tue, 05 Sep 2017 01:28:35 GMT
Content-Security-Policy: upgrade-insecure-requests
Content-Type: image/svg+xml
Content-Encoding: gzip
```

Do note that if you try to access the image from a browser, it will transparently uncompress the response, making it a .svg file.

**Comment by MartinKolarik** [comment]
Sorry, I meant a link for a file directly at jsDelivr. I suppose you were trying to use some package containing .svgz files from jsDelivr since you said it didn't work.

**Comment by JoshyPHP** [comment]
The reason I'm looking into SVGZ support is because I'm going to publish a couple of emoji-related packages. Whether or not jsDelivr supports SVGZ will determine which file format I'll use. Preferably SVGZ since it's smaller than uncompressed SVG and on top of that compressing the files offline offers a better compression ratio than dynamically gzipped resources.

I'm not aware of any other packages on jsDelivr using SVGZ. The only package I (used to) use is EmojiOne's and they removed support for SVG altogether. There's also a bit of a chicken-and-egg problem between SVGZ usage in applications and proper support by web hosts and CDNs. Most web servers ship with a default configuration that recognize .svgz files but won't serve them the proper headers. In other words, most web servers have broken SVGZ support by default and need to be configured for it to work. There's a bit of a discussion about it in https://github.com/h5bp/server-configs-nginx/issues/86

If you want to see an SVGZ image served via jsDelivr you can take a look at [this image](https://cdn.jsdelivr.net/gh/s9e/s9e.github.io/emoji.svgz) I used in some informal tests. Of course it won't display in any modern browser. Some older browsers (such as Opera 12) do sniff the file's content and will display it correctly.

**Comment by MartinKolarik** [comment]
@JoshyPHP thanks for a very detailed description of the problem. Much appreciated!

We've just deployed a patch and loading SVGZ files from jsDelivr should now work correctly. You can verify it using the link you previously posted: https://cdn.jsdelivr.net/gh/s9e/s9e.github.io/emoji.svgz

That said, I need to point out that one of the advantages of SVGZ files over SVG you mentioned doesn't really apply here:

>on top of that compressing the files offline offers a better compression ratio than dynamically gzipped resources

Even if our origin servers respond with a gzipped content, the CDN providers are going to unzip it and then gzip it themselves on the fly (this is pretty much how any CDN/proxy server/... works).

**Comment by JoshyPHP** [comment]
Thanks for the awesome response time. I have to confess I have a limited knowledge of CDNs but I'll definitely look into it to see if there's anything I can do to avoid a bad recompression.
