### ISSUE TITLE
Change mimetype of TypeScript file ".ts" to text something

### ISSUE THREAD

**Issue by neurospeech** [jsdelivr/jsdelivr#18034]
TypeScript is gaining popularity and many of modules now use TypeScript. TypeScript generates source map file which corresponds to source location in TypeScript from JavaScript. This is helpful in debugging. Currently ".ts" mime type returns mime for MPEG-TS. I know it would be conflicting, but none of JS world developers would ever use ".ts" for MPEG.

Could you please change mime type for ".ts" to "text/typescript"? Or something text that will be easy to view in chrome?

**Comment by MartinKolarik** [comment]
Does the ability to use source maps linking to `.ts` files depend on the `Content-Type` header? I understand linking `.ts` files directly downloads them instead of displaying the source code, but I would expect it still works in dev tools.

Either way, can you post a link to a package like this so that I don't have to search for one?

**Comment by neurospeech** [comment]
@MartinKolarik Looks like it is working in chrome, only problem is, if I try to open url, it downloads in chrome instead if displaying source.

**Comment by MartinKolarik** [comment]
Thanks @neurospeech, I'l mark this as an enhancement.

@jimaek I think we can safely change the `Content-Type`.

**Comment by jimaek** [comment]
yeah, it should not break anything. Lets add it to TODO

**Comment by MartinKolarik** [comment]
@neurospeech we added ".ts" and ".tsx" to a list of special files that we serve as `text/plain`. Please note that you may still get responses without this header for files already cached on CDN.

**Comment by neurospeech** [comment]
@MartinKolarik I must say you guys were really quick !!
