### ISSUE TITLE
HTTP 404 on github trying to pull from the master branch...

### ISSUE THREAD

**Issue by pleasantone** [jsdelivr/jsdelivr#18036]
Companion to #18035 

Test case:

    $ curl -i https://cdn.jsdelivr.net/gh/tmroyal/Chart.HeatMap/dst/Chart.HeatMap.S.min.js
    HTTP/2 404
    date: Wed, 30 Aug 2017 08:14:27 GMT
    content-type: text/plain; charset=utf-8
    content-length: 51
    access-control-allow-origin: *
    cache-control: no-cache, no-store, must-revalidate
    timing-allow-origin: *
    vary: Accept-Encoding
    etag: "33-THk1dwrVoV7UK8IpMNtqVCzNwNk"
    cf-cache-status: MISS
    server: cloudflare-nginx
    cf-ray: 39664be7bfdc7a05-SEA

    Couldn't find the requested release version latest.

This repo has the file in the proper location, nothing has *ever* been tagged in github, so there is no latest tagged release.  My assumption would be that it would fall back to pulling from master.

I scanned the documentation, nothing there on what you folks think the expected behavior should be.  Could just be a documentation issue or operator error on my part.

**Comment by MartinKolarik** [comment]
>My assumption would be that it would fall back to pulling from master.

From README: "All packages hosted on npm and **tagged releases on GitHub** are automatically available on jsDelivr."

**Comment by pleasantone** [comment]
Thank you. My error. I was hoping latest would fall back. I'll fork his repo and tag if the author is unresponsive.

**Comment by MartinKolarik** [comment]
👍 feel free to reopen if you have any more questions.
