### ISSUE TITLE
Deleted releases

### ISSUE THREAD

**Issue by Hailiax** [jsdelivr/jsdelivr#18031]
I mistakenly released a github project under version 1.0.0 and then accessed the project from the cdn with @1. After I deleted the release and released it again under 0.0.0, I asked for the cache to be purged. However, 1.0.0 was permanently cached due to a detected 404. If I release the project under 1.0.0 again, how should I ensure the newest version is being served?

**Comment by MartinKolarik** [comment]
It is not possible to change existing files. jsDelivr will continue to serve the original files for 1.0.0. You should release a new version on GitHub.
