### ISSUE TITLE
[question] How to combine dependencies hosted on npm/GitHub with "regular old" script dependencies

### ISSUE THREAD

**Issue by wearhere** [jsdelivr/jsdelivr#18032]
By '"regular old" script dependencies' I mean like you go to https://www.jsdelivr.com and you add Underscore and jQuery to a bundle, get a URL like https://cdn.jsdelivr.net/g/underscorejs@1.8.3,jquery@3.2.1.

So that is how to combine multiple script dependencies. And https://github.com/jsdelivr/jsdelivr#combine-multiple-files explains how to combine multiple npm and/or GitHub dependencies.

But I can't figure out how to do something like (this link does not work) https://cdn.jsdelivr.net/combine/npm/punycode@1.4.1,jquery@2.1.4, where (ideally, to maintain compatibility with our existing setup) I would _not_ load jQuery from npm nor GitHub, rather load whatever script https://cdn.jsdelivr.net/g/underscorejs@1.8.3,jquery@2.1.4 had been doing previously.

Is that somehow possible?

**Comment by MartinKolarik** [comment]
No, this is not possible. The legacy files cannot be combined with the new npm/gh files. However, it is perfectly safe to load jquery v2.1.4 using the new npm endpoint.

**Comment by wearhere** [comment]
Thanks for the speedy response @MartinKolarik! That's a bit unfortunate, since even though jQuery is hosted on npm, there are a lot of scripts that are not hosted on npm (nor GitHub)—right? https://github.com/jsdelivr/jsdelivr#publishing-packages now suggests that projects _must_ be hosted on npm or GitHub (or the WordPress plugin repo) but are all the existing files on JSDelivr on GitHub as well?

**Comment by wearhere** [comment]
Thanks for the speedy response @MartinKolarik! That's a bit unfortunate, since even though jQuery is hosted on npm, there are a lot of scripts that are not hosted on npm (nor GitHub)—right? https://github.com/jsdelivr/jsdelivr#publishing-packages now suggests that projects _must_ be hosted on npm or GitHub (or the WordPress plugin repo) but are all the existing files on JSDelivr on GitHub as well?

**Comment by MartinKolarik** [comment]
Out of the 2176 legacy projects, more than 2000 are on npm/GitHub. If you ever find a project that is not hosted on neither npm nor GitHub, you can always publish it under your own account.

**Comment by wearhere** [comment]
Ok! Thanks again.
