### ISSUE TITLE
HTTP2 is not enabled in China

### ISSUE THREAD

**Issue by WoadZS** [jsdelivr/jsdelivr#18046]
Thanks for your great work on jsDelivr, so that we can use your excellent library in China.
But it does not seem to support HTTP2 in China. Could you please check that.

Here are the comparisons:
Test site: https://woadzs.me  my personal blog
Visit in China:
![_20171015172502](https://user-images.githubusercontent.com/18167899/31589334-d2dc57cc-b1cd-11e7-866e-ae6db7c9ebaf.png)

While visit in USA:
![image](https://user-images.githubusercontent.com/18167899/31589351-0c4d153c-b1ce-11e7-8b11-7661ac68e2e4.png)

Please check this. Thanks a lot.

**Comment by jimaek** [comment]
Looking into it

**Comment by jimaek** [comment]
They said it will be enabled on Monday.

**Comment by WoadZS** [comment]
@jimaek Sure, will check that then and give feedback to you. Thanks!

**Comment by WoadZS** [comment]
@jimaek 
![image](https://user-images.githubusercontent.com/18167899/31920289-f5f7cb74-b835-11e7-9ad2-10ea086f0887.png)
Problem solved, thanks

**Comment by jimaek** [comment]
They confirmed it too. Thanks for reporting
