### ISSUE TITLE
Couldn't find the requested file /build/dbc.min.js in dbc-code-contracts.

### ISSUE THREAD

**Issue by jek-nov** [jsdelivr/jsdelivr#18048]
Hello,

I am trying to get the **[dbc-code-contracts](https://www.npmjs.com/package/dbc-code-contracts)** library from your CDN, but I've got the following error: 

> Couldn't find the requested file /build/dbc.min.js in dbc-code-contracts.

I know this project doesn't have the **dbc.js** file by default. It must be built like RunKit service does. Also, there are passed tests at library repo, look at the [CI-builds](https://gitlab.com/o.oleg/orbios.dbc/-/jobs).

So, how can I get the built version of this library from the **jsdelivr** service?

**Comment by MartinKolarik** [comment]
You'll need to ask the author to add the `build` folder to the npm package.

**Comment by jek-nov** [comment]
@MartinKolarik why is it needed? Such behavior will break all CI/CD rules (running unit-tests at the remote CI). It's required to build the fresh library every time for CI to test it. 

It's the basics of the CI/tests approach. Have you ever seen the built libraries in C#/C++ projects? There aren't. If such projects exist, then those might be low quality products.

**Comment by MartinKolarik** [comment]
@jek-nov I'm not saying it has to necessarily be in the repo, just in the npm package. Either way, there's no reason why this would break CI. On the CI the files should be built from source every time, obviously. However, the distribution package (on npm, or a release on GitHub), should always contain the built files.

**Comment by MartinKolarik** [comment]
@jek-nov building the package in a `postinstall` script is definitely not a common practice in JS development, you should only do it with packages that contain node.js addons and need to be compiled separately for each OS.

**Comment by jek-nov** [comment]
> **MartinKolarik commented 7 minutes ago • edited**
>  why this would break CI

NOT the CI-servie itself, but the TDD/CI rules, I have said about the rules exactly (proof):

> **jek-nov commented 35 minutes ago**
> Such behavior will break all CI/CD rules (running unit-tests at the remote CI). It's required to build the fresh library every time for CI to test it.

> **MartinKolarik commented 7 minutes ago • edited**
> On the CI the files should be built from source every time, obviously. 

Built with the **TESTS** from the source-code, otherwise it would be just the CD-service, if actions are only:
 1. build
 2. deploy to somewhere

> building the package in a postinstall script is definitely not a common practice in JS development
Be honestly, JS-world shouldn't talk about the common practice or not, proof of the shame: 

 - https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c
 - https://github.com/stevemao/left-pad/issues/4
 - https://twitter.com/seldo/status/712414588281552900

**Comment by MartinKolarik** [comment]
@jek-nov the whole process could be something like this:
 - push to git
 - build & test on CI
 - publish the built and tested files to npm (either automatically from the CI, or manually)

There are definitely more ways to do it, and you can pick whichever you like, as long as the final step results in the builds being in the package that's distributed to your users. That's how npm packages usually work, and that's what necessary if you want to use jsDelivr (or any other public CDN, really).

**Comment by jek-nov** [comment]
> MartinKolarik commented a minute ago
> that's what necessary if you want to use jsDelivr (or any other public CDN, really).

Really? https://runkit.com/embed/wg5o4yflwtvi

![image](https://user-images.githubusercontent.com/13641042/32280850-3444b44c-bf2e-11e7-87b8-10fb50c13a6d.png)

**Comment by MartinKolarik** [comment]
Runkit is not a CDN, is it?

**Comment by jek-nov** [comment]
Ok, it isn't. But why can't you run postinstall script?

**Comment by MartinKolarik** [comment]
@jek-nov 
 - Running user scripts on our servers would require a different, and significantly more complex implementation, because each project would have to be built in an isolated environment (for security reasons). Also, our CDN gets ~300 000 requests per minute, and about 3000 / minute makes it to our origin servers, so any kind of virtualization per project would require a huge amount of resources.
 - A build process can easily take a minute or two for more complex projects, but we need to get the files in a few seconds at most, otherwise the request would time out.
 - It is not needed for 99 % of projects.
 - ...
