### ISSUE TITLE
Babel (& perhaps other monorepos) broken

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#18053]
[Babel](https://github.com/babel/babel) changed its repo & file structure some time back.  It also (reabsorbed) changed where the live-browser code lives:
https://github.com/babel/babel/tree/master/packages/babel-standalone
which used to live at: https://github.com/babel/babel-standalone
Older versions of Babel had different locations & runtimes.

Not sure what the fix would be that is also backwards-comparable?  Also, should the API be similar to [UNPKG](https://github.com/babel/babel-standalone), or shorter?

**Comment by MartinKolarik** [comment]
What exactly is broken?

**Comment by tomByrer** [comment]
I was expecting to use a v6.0.0 file found at
https://www.jsdelivr.com/package/npm/babel
But the 'standalone' (for browser use) doesn't exist there.  Even the website complains "Sadly, this package doesn't have a default file set."

But the 7..0.0-beta (not 6.* versions) does live here:
https://www.jsdelivr.com/package/npm/@babel/standalone

**Comment by MartinKolarik** [comment]
I think you want this https://www.jsdelivr.com/package/npm/babel-standalone
Since we simply proxy whatever is on npm, there's nothing that could get broken in the process - you just need to find the correct package for v6.

**Comment by tomByrer** [comment]
That repo is good for v6, but outdated & remerged back into Babel as of v7:
https://github.com/babel/babel-standalone#babel-standalone-is-now-part-of-babel-go-check-it-out-warningwarningwarningwarning

Not sure if jsDelivr should alias, or at least warn location changes though?

**Comment by MartinKolarik** [comment]
Yes but I don't think there's anything we can do about it. You want to use a new major version -> you should read release notes -> you learn about new packages.

We show a "deprecated" badge for packages marked as deprecated on npm, such as https://www.jsdelivr.com/package/npm/babel (and maybe it could be made more visible), but https://www.jsdelivr.com/package/npm/babel-standalone is a legitimate package someone might be looking for if they want to stay on 6.x.x.

**Comment by tomByrer** [comment]
Agreed.

Though I wish there was an easier way to discover the changes within jsdelivr.com (perhaps the conversation should move there?).
EG, that's alot of clicks & searching for me to go from 
https://www.jsdelivr.com/package/npm/babel-standalone
to
https://github.com/babel/babel-standalone
to
https://github.com/babel/babel/tree/master/packages/babel-standalone
to
https://www.jsdelivr.com/package/npm/babel
to
"WTH... where is `packages/babel-standalone`"??
20 minutes later...
https://www.jsdelivr.com/
find search bar
search `babel standalon`
ahhh: https://www.jsdelivr.com/package/npm/@babel/standalone

'related' fields?

**Comment by MartinKolarik** [comment]
Closing as I think there isn't anything more we could do.
