### ISSUE TITLE
Unable to select Modernizer

### ISSUE THREAD

**Issue by andrewjohnstrong** [jsdelivr/jsdelivr#18055]
I think I've found a bug here https://www.jsdelivr.com/package/npm/modernizr

I can't select Modernizr. The first "add to collection" option doesn't work.

<img width="796" alt="screen shot 2017-12-30 at 8 17 50 pm" src="https://user-images.githubusercontent.com/654760/34453435-abcb0f8a-eda9-11e7-8596-03eb954b1e8d.png">

**Comment by MartinKolarik** [comment]
This happens because the file set as default doesn't exist, but it would have been a wrong file anyway - Modernizr doesn't ship build files in their package so there isn't an easy way to use it. You can use a custom build hosted at our legacy endpoint https://cdn.jsdelivr.net/modernizr/3.3.1/modernizr.min.js, or build and host it yourself if you need a newer version.

**Comment by andrewjohnstrong** [comment]
I suspected so. Are you able to clarify what selection of items is equivalent to https://html5boilerplate.com/ 's Modernizr 3.5.0 local inclusion?

**Comment by MartinKolarik** [comment]
```
/*! modernizr 3.5.0 (Custom Build) | MIT *
 * https://modernizr.com/download/?-cssanimations-csscolumns-customelements-flexbox-history-picture-pointerevents-postmessage-sizes-srcset-webgl-websockets-webworkers-addtest-domprefixes-hasevent-mq-prefixedcssvalue-prefixes-setclasses-testallprops-testprop-teststyles !*/
```

**Comment by andrewjohnstrong** [comment]
Thanks Martin, but I was referring to a cdn equal on jsdelivr? :)

**Comment by MartinKolarik** [comment]
If you meant what individual files you'd have to use, that comment contains names of all files but it'll only work if you use require.js in production.

**Comment by andrewjohnstrong** [comment]
Thanks Martin, and sorry to be a pain, but you lost me on "but it'll only
work if you use require.js in production."

Is the below screenshot:


​

 equivalent to the below custom build (with the obvious benefit that it is
being served from the CDN)?

/*! modernizr 3.5.0 (Custom Build) | MIT *
 * https://modernizr.com/download/?-cssanimations-csscolumns-customelements-flexbox-history-picture-pointerevents-postmessage-sizes-srcset-webgl-websockets-webworkers-addtest-domprefixes-hasevent-mq-prefixedcssvalue-prefixes-setclasses-testallprops-testprop-teststyles
!*

**Comment by MartinKolarik** [comment]
@andrewjohnstrong looks like the screenshot got lost somewhere.

**Comment by andrewjohnstrong** [comment]
Try now :) https://user-images.githubusercontent.com/654760/34519935-a2cf62e4-f0da-11e7-8d4d-e083cec16c21.png

**Comment by MartinKolarik** [comment]
a) no, you need files from here: https://www.jsdelivr.com/package/npm/modernizr?path=feature-detects
b) the files assume [require.js](https://www.jsdelivr.com/package/npm/requirejs) is available, which means you would have to load it as well. Unless you already use require.js (and I assume you don't), I recommend downloading a custom build and hosting it yourself (alternatively, you can publish your own package with such build to npm and then use it from jsDelivr).

**Comment by andrewjohnstrong** [comment]
Thanks for your help Martin :)
