### ISSUE TITLE
Request: Enable Macau POP by change the route to Quantil

### ISSUE THREAD

**Issue by brentybh** [jsdelivr/jsdelivr#18050]
Quantil has a Macau POP. I found it when request the URL:
http://quantil.jsdelivr.net/
It will be faster for Macau users if you change the route to Quantil for Macau users.
There is few CDN provider offering Macau POP, however Quantil's share holder ChinaNetCenter does.

**Comment by jimaek** [comment]
The automated system was probably not able to see it. I changed the code to use Quantil in Macau. 
It will be live soon.  I will let you know when to test.

**Comment by jimaek** [comment]
Deployed
