### ISSUE TITLE
Test "the bus factor"

### ISSUE THREAD

**Issue by dcanning** [jsdelivr/jsdelivr#18056]
While it is probably complicated and time consuming, given the amount of people using the service it would be a good idea to test the process behind [The Bus Factor](https://github.com/jsdelivr/jsdelivr/wiki/What-to-do-if-I-die-aka-The-bus-factor) before it is actually needed (hopefully not for a long time).

**Comment by jimaek** [comment]
I am not sure how we could test it. Just email all the related people and ask them if they got the email? :)
This kind of things only happen once and are hard things to do. I don't think it makes sense to even try to test it.
