### ISSUE TITLE
Blacklist/Exclude of Some Files

### ISSUE THREAD

**Issue by julmot** [jsdelivr/jsdelivr#18057]
From a copyright point of view it would be nice to have the possibility for example to say that files inside `src/` should not be able to be used from JSDelivr. Source files are often available without copyright headers, they may only be added during the build. Then they are available as `dist/` files. Therefore serving files from `src/` without copyright might be against the corresponding license. It might also be helpful when you don't want e.g. test data to be used from third parties.

**Comment by MartinKolarik** [comment]
Sorry for a late response. You can use `.npmignore` for npm packages, and for GitHub, it's possible to make releases from a branch other than master if you want to pick/reorganize the files (some projects use this to make releases that only contain "dist"). Additionally, your suggestion would probably break many 3rd party services that rely on any file being available.
