### ISSUE TITLE
JSDelivr Purge API inquiries

### ISSUE THREAD

**Issue by hillct** [jsdelivr/jsdelivr#18052]
Your Purge API inquiries documentation suggests those interested should send email to contact@jsdelivr.com https://github.com/jsdelivr/jsdelivr#purge-cache however that mailbox is over quota and thus undeliverable. Is there another process for making purge API inquiries? alternatively, can someone please address the incoming mail backlog. Thanks.

**Comment by jimaek** [comment]
Hey, I fixed that error and replied to you. Sorry about that.
