### ISSUE TITLE
Some binary file types from /wp endpoint return 403 error

### ISSUE THREAD

**Issue by dimadin** [jsdelivr/jsdelivr#18060]
When using CSS file from `/wp` endpoint that references image file for background, I noticed that image file is returning error with 403 status code. After little manual testing, it looks like this is happening for more binary file types.

Here are some examples:

- [JPG](https://cdn.jsdelivr.net/wp/woocommerce/tags/3.3.1/assets/images/storefront-bg.jpg) ([original](https://plugins.svn.wordpress.org/woocommerce/tags/3.3.1/assets/images/storefront-bg.jpg))
- [PNG](https://cdn.jsdelivr.net/wp/woocommerce/tags/3.3.1/assets/images/placeholder.png) ([original](https://plugins.svn.wordpress.org/woocommerce/tags/3.3.1/assets/images/placeholder.png))
- [GIF](https://cdn.jsdelivr.net/wp/woocommerce/tags/3.3.1/assets/images/select2-spinner.gif) ([original](https://plugins.svn.wordpress.org/woocommerce/tags/3.3.1/assets/images/select2-spinner.gif))
- [WOFF2](https://cdn.jsdelivr.net/wp/easy-video-player/tags/1.1.6/lib/skin/icons/flowplayer.woff2) ([original](https://plugins.svn.wordpress.org/easy-video-player/tags/1.1.6/lib/skin/icons/flowplayer.woff2); but [other](https://plugins.svn.wordpress.org/easy-video-player/tags/1.1.6/lib/skin/icons/) font types work)
- [SWF](https://cdn.jsdelivr.net/wp/easy-video-player/tags/1.1.6/lib/flowplayer.swf) ([original](https://plugins.svn.wordpress.org/easy-video-player/tags/1.1.6/lib/flowplayer.swf))
- [XAP](https://cdn.jsdelivr.net/wp/hana-flv-player/tags/3.1.3/mediaelement/build/silverlightmediaelement.xap) ([original](https://plugins.svn.wordpress.org/hana-flv-player/tags/3.1.3/mediaelement/build/silverlightmediaelement.xap))

These are example file types I have found and all those file types work on `/npm` endpoint ([example](https://www.jsdelivr.com/package/npm/mediaelement?version=2.23.5&path=build)).

**Comment by MartinKolarik** [comment]
Indeed, we only allow the following extensions: css, js, ttf, woff, eot, otf, svg.

At the very least, I believe we should enable woff2, and probably the image files as well. @jimaek ?

**Comment by MartinKolarik** [comment]
Also, the list of supported files types should be documented in the README and at jsdelivr.com

**Comment by dimadin** [comment]
Since any of types I mentioned (and some other as well) can be loaded from CSS or JS files (by using relative path), not having them supported makes `/wp` worthless.

Using that blacklist makes more sense since someone would noticed problems by now.

**Comment by jimaek** [comment]
Indeed, we should allow font files and images

**Comment by MartinKolarik** [comment]
@dimadin we are going to allow all files that are allowed at `/npm`. This change should go live in a few minutes.

**Comment by jimaek** [comment]
@dimadin The change was deployed, all linked files are now working

**Comment by dimadin** [comment]
Awesome! Thank you both for speedy response and resolution.
