### ISSUE TITLE
Can resolve short URL for NPM packages supporting both JS and MJS

### ISSUE THREAD

**Issue by IvanGoncharov** [jsdelivr/jsdelivr#18061]
The only way to support both `js` and `mjs` in single NPM package is to make `main: index` and include both `index.js` and `index.mjs`.
For example, this done for `graphql` package:
https://github.com/graphql/graphql-js/blob/master/package.json#L6

However, when I try http://cdn.jsdelivr.net/npm/graphql I got:
```
Couldn't find the requested file /index in graphql.
```

BTW. It forks in unpkg: https://unpkg.com/graphql

**Comment by MartinKolarik** [comment]
Right now we only support full filenames that include the extension, adding a smarter resolution algorithm is in our todo list. You can use `jsdelivr` which takes precedence over `main` in this case.

**Comment by MartinKolarik** [comment]
Feel free to reopen if necessary.
