### ISSUE TITLE
Problem occured after deleting and creating the same repo.

### ISSUE THREAD

**Issue by akashpinnaka** [jsdelivr/jsdelivr#18069]
I generated CDN for my frontend framework 
https://cdn.jsdelivr.net/gh/akashpinnaka/cakewalkcss@1.0/cakewalk.css

After that, I deleted the repo from github and created a repo with same name.

Now version 1.0 has same files with different content. But CDN remains cached.

How do I purge the cache and update according to new content?

**Comment by MartinKolarik** [comment]
Hi @akashpinnaka, we don't allow modifying files after a release has been made. You'll need to publish a new version to make the changes available via the CDN (I'd suggest 1.0.0 to have the version number semver compatible).

**Comment by akashpinnaka** [comment]
Thanks for the response @MartinKolarik. I release the new version.
