### ISSUE TITLE
please add missing x-content-type-options header

### ISSUE THREAD

**Issue by aaronfi-skilljar** [jsdelivr/jsdelivr#18076]
Hi.
Super small ask:

Would you mind adding the "x-content-type-options: nosniff" response header to http://cdn.jsdelivr.net/algoliasearch/3.24.7/algoliasearch.min.js ?

Or add this in general to files served up from jsdelivr?

This concern came to our attention during a recent security scan.

Thanks!

**Comment by jimaek** [comment]
I don't see any security risk here. That header simply forces the browser to use the content-type sent by us and not guess it. I believe they will already do that by default.

**Comment by MartinKolarik** [comment]
It's a general security recommendation and I don't see any problem with adding it.

**Comment by MartinKolarik** [comment]
@aaronfi-skilljar we added this header to all files. Right now you'll only see it for the [HTTPS version of the link](https://cdn.jsdelivr.net/algoliasearch/3.24.7/algoliasearch.min.js) but it'll appear for the HTTP version later as well (if you cared about this header, I'm sure you use HTTPS anyway 😄).

**Comment by MartinKolarik** [comment]
Also thanks for the suggestion 👍
