### ISSUE TITLE
UglifyJS can not minify the file

### ISSUE THREAD

**Issue by id1172** [jsdelivr/jsdelivr#18075]
Why UglifyJS can not minify the following file [https://cdn.jsdelivr.net/gh/id1172/1@3/app.min.js](https://cdn.jsdelivr.net/gh/id1172/1@3/app.min.js)?

**Comment by MartinKolarik** [comment]
`Error: There were errors when running UglifyJS: In strict mode code, functions can only be declared at top level or immediately within another function.`

**Comment by id1172** [comment]
@MartinKolarik, Thank You.
