### ISSUE TITLE
Make it easier to copy the SRI

### ISSUE THREAD

**Issue by plaa** [jsdelivr/jsdelivr#18072]
Please make it easier to copy the SRI of a file. We configure the URL and SRI separately, and currently it's a pain.

[On cdnjs](https://cdnjs.com/libraries/d3):

1. Click the "Copy" dropdown and select "Copy SRI"

[On jsdelivr](https://www.jsdelivr.com/package/npm/d3):

1. Choose the file to the "basket"
2. Click "Show & configure all links"
3. Click "SRI"
4. Copy the script tag
5. Paste the script tag to a text editor
6. Select the SRI part and copy it (you can't even select the SRI on the HTML snippet)

**Comment by MartinKolarik** [comment]
Thanks for the suggestion @plaa. I moved it to the website repo. Feel free to send a PR over there.

**Comment by MartinKolarik** [comment]
Thanks for the suggestion @plaa - the website now has a dropdown to make this easier: https://www.jsdelivr.com/package/npm/jquery
