### ISSUE TITLE
error: "Failed to fetch version info for ..."

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#18078]
Happened twice today, I followed a link from jsDelivr.com's listing for a project, & the output in my browser was "Failed to fetch version info for", not the expected JS code.  A refresh fetches the expected code, but I'm wondering why it immediately fails & doesn't retry?

![jsdelivr_20180626_failed-version](https://user-images.githubusercontent.com/1308419/41930906-17d15634-7942-11e8-87d9-83559e00d695.png)

**Comment by tomByrer** [comment]
Might be related; got a `503 first byte timeout` error for a combine error also.  Let me know if you want the screenshot.

**Comment by MartinKolarik** [comment]
>A refresh fetches the expected code, but I'm wondering why it immediately fails & doesn't retry?

Not sure why it failed because we don't log the related error info but we make a request to two different registry mirrors so both must have returned an error.

**Comment by tomByrer** [comment]
> Not sure why it failed

GitHub needs a :thinking: emote in the dropdown...

**Comment by MartinKolarik** [comment]
I'm going to add logging for this and hopefully we'll know more then.

**Comment by MartinKolarik** [comment]
This turned out to be a bug in one of our dependencies and was fixed yesterday. We also have better logging in place now.
