### ISSUE TITLE
ERROR with CDN

### ISSUE THREAD

**Issue by ahierro** [jsdelivr/jsdelivr#18079]
I am getting binary file instead of the js file
https://cdn.jsdelivr.net/webjars/jquery/3.1.1-1/jquery.min.js

![image](https://user-images.githubusercontent.com/1620155/42008485-2a06c8d2-7a5c-11e8-9112-1d1aafc42dd5.png)

**Comment by MartinKolarik** [comment]
Hi @ahierro, this is an issue we've most likely already fixed. I purged the CDN cache for this file so that it gets updated. Please let us know in case you see this again.

**Comment by ahierro** [comment]
Still not working in http 
http://cdn.jsdelivr.net/webjars/jquery/3.1.1-1/jquery.min.js

**Comment by MartinKolarik** [comment]
Indeed, our purge api only works for https right now and we'll be deprecating http soon. Pinging @jimaek in case he's able to purge the http version too.

**Comment by jimaek** [comment]
I manually purged all CDNs. should be fixed

**Comment by ahierro** [comment]
@jimaek @MartinKolarik  Thank you!
