### ISSUE TITLE
Version Not Found

### ISSUE THREAD

**Issue by ihoman** [jsdelivr/jsdelivr#18081]
Hi it's Ian, I am hosting my site through github and followed your documentation through and even went as far as creating a package.json file and still have issues getting the CDN to see it. I have read the documentation over and over and have posted help on reddit stating the exact same info I stated here. I can't seem to get it work. What can I do. I tried everything including npm but npm won't let me publish my package without an enterprise account, keep in mind I am going to college for dual degree web / app design & network specialist & network admin. I have spent days trying to get it exactly like your documentation but all I get is an error saying it can't find the version. 

So in the end should I put all my CSS & Java files on separate github repository and not tied to the master folder of the main site I am creating?

**Comment by MartinKolarik** [comment]
Hi @ihoman, what GitHub package are you trying to load, what CDN URL have you tried, and what error do you get?

**Comment by ihoman** [comment]
I am trying to link my own project to the jsdelivr website.


https://cdn.jsdelivr.net/gh/ihoman/ihoman.github.io/files/css.css

https://cdn.jsdelivr.net/gh/ihoman/ihoman.github.io@latest/files/css.css

The above is an attempt of various versions of yours below (shown in
documentation)

/gh/user/repo@version/file

**Comment by MartinKolarik** [comment]
There are no releases in your repo: https://github.com/ihoman/ihoman.github.io/releases

You need to either make a release, or use a commit hash as version:
https://cdn.jsdelivr.net/gh/ihoman/ihoman.github.io@5e5797d2e6d92092f76775a9ebd9c30aec152894/files/css.css

Right now your repository is too big, so I recommend setting up another one just with the files you want on the CDN.

**Comment by ihoman** [comment]
Thanks will do I'll report back the results

**Comment by ihoman** [comment]
I confirm MartinKolarik's result worked Thanks!
