### ISSUE TITLE
Add Google Analytics en Tag Manager into CDN

### ISSUE THREAD

**Issue by batata004** [jsdelivr/jsdelivr#18089]
Hi,

I already use the COMBINE feature of JSDELIVR (which works great, thanks!) and I am wondering if you could add googletagmanager and analytics JS codes to your CDN.

I ask that for 2 reasons: I can make use of COMBINE to load those libraries instead of making separate requests to each library AND the second reason is attached.

See, those 2 requests are not cacheable by Google (at least the PAGESPEED tool says that).

Would be any possibility to JSDELIVR host those 2 JS codes?

https://www.googletagmanager.com/gtag/js
https://www.google-analytics.com/analytics.js

![image](https://user-images.githubusercontent.com/8988923/45249652-4096e880-b2fa-11e8-8a51-3563b9c29350.png)

**Comment by jimaek** [comment]
Unfortunately not. I dont see a way to keep the files updated since there is no versioning and we don't know how often they update them.

**Comment by batata004** [comment]
Thnanks! I will close this despite the fact that JS code from analytics and ga does not change much, actually any code from 2013 still works today. I have a website where I hosted on my own the analytcs.js code and it still works flaulessly till today, all data is display in analytics.google.com with no warning.

**Comment by SukkaW** [comment]
@batata004 In fact, you can check the `Last-Modified` response header of those analytics related lib files and then you can find out that they actually changed recently.

**Comment by batata004** [comment]
@SukkaW  good point! However my file from 2013 still works fine, so those changes certainly does not break anything.
