### ISSUE TITLE
Serious bug with combine

### ISSUE THREAD

**Issue by batata004** [jsdelivr/jsdelivr#18087]
Hi,

I've been using COMBINE of jsdelivr for a long time. IT'S a very nice feature. Other major CDNs like Cloudflare does not provide it, and it is very good.

But recently I encountered a bug with it. I am trying to combine 2 libraries: SEMANTIC UI and VEGAS. I use the URL https://cdn.jsdelivr.net/combine/npm/semantic-ui@2.3.1/dist/semantic.min.css,npm/vegas@2.4.0/dist/vegas.min.css

It works fine and the codes are correctly concatenated into a single file. BUT after SEMANTIC UI loads, it fetches some other files (like font files) and because of the COMBINE feature, those files are fecthed from the wrong place.

You can see the bug here, in a very tiny code with just the necessary to reproduce the bug:

http://quemfazsite.com.br/temp/teste4.php

If you take a look at the DEVTOOLS in the NETWORK tab you will see something like the file aa.jpg attached. You can cleary see that some requests return 404 error. On the other hand, if I dont use COMBINE everything works fine, check link below:

http://quemfazsite.com.br/temp/teste6.php

So clearly, COMBINE has some serious bug cause it's not allowing browsers to correctly fetch URLs of resources.

I am amazed how other people didnt report this type of problem. If you have any stylesheet and inside of it you call an external image/css it will be fetched from the wrong place if you use COMBINE.

Is there some workaround this?

![aa](https://user-images.githubusercontent.com/8988923/44958811-aaa72c00-aebb-11e8-8894-e2a4a8fb2794.jpg)

**Comment by MartinKolarik** [comment]
This is a know and expected problem. We even show a warning on our website: "Using the combined link may cause problems with relative imports, such as images or font files referenced by one of the files. You need to use the regular, single-file links for any files that use relative imports (e.g., font-awesome)."

**Comment by batata004** [comment]
Thanks my friend, would you mind telling me the link where that warning shows? Cause I read the entire page at https://github.com/jsdelivr/jsdelivr and didnt see that warning

**Comment by MartinKolarik** [comment]
It isn't in the docs, just on the website: https://www.jsdelivr.com/package/npm/slick-carousel?tab=collection

**Comment by batata004** [comment]
THANKS YOU!!!
