### ISSUE TITLE
default priority /dist over "main"

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#18080]
`package.json`'s `main` field seems to be aimed directly at npm, not browsers.  So perhaps if there are no `jsdelivr` or `browser` fields, then the `/dist` folder should be the next highest priority when looking for the default file?

Example:
[spectacle](https://www.jsdelivr.com/package/npm/spectacle): `main` (so jsdelivr's default) = [/lib/index.js](https://cdn.jsdelivr.net/npm/spectacle@4.3.1/lib/index.min.js) is broken, but [dist/spectacle.min.js](https://cdn.jsdelivr.net/npm/spectacle@4.3/dist/spectacle.min.js) is really the file that works.

I could improve the documentation &/or write a blog post to help.  Though more automation is helpful.

**Comment by tomByrer** [comment]
> Also there are commonly multiple files in dist/

I see your point.  So far it seems that the correct file in that folder is either [repo name].(min.).js or 'index'.

> main is useful for packages that ship umd builds

I wonder how often that is now?  Seemed more true a few years ago, but I it seems the assumption is most code is intended for npm & browser-ready is an afterthought (eg not main).

**Comment by MartinKolarik** [comment]
I would consider ideas/PRs for trying to hint what's the correct file on the UI side (package listing at www.jsdelivr.com). As I said this isn't possible (or desirable) on the backend.

**Comment by tomByrer** [comment]
Cool, mind pointing me to where this is chosen in your code please?

**Comment by MartinKolarik** [comment]
It comes from our API [here](https://github.com/jsdelivr/www.jsdelivr.com/blob/master/src/views/components/package-file-browser.html#L154) but if it's set (even if only as `main`), we'd want to use it. Possible improvements I had in mind are:
 - [if no value is set](https://www.jsdelivr.com/package/npm/font-awesome) we show instructions how to set it (that's implemented [here](https://github.com/jsdelivr/www.jsdelivr.com/blob/master/src/views/components/package-file-browser.html#L36-L37)) - this could be improved by also suggesting what the correct file might be based on some common naming patterns
 - if the value is set but appears wrong - display some kind of additional suggestion/highlight the file/... - this would need to be designed first

**Comment by MartinKolarik** [comment]
Sorry I forgot to reply earlier. Yes I think it would work, we already considered doing that in other places (aspnet/LibraryManager#343). I'm not sure about design though: we should still display whatever is set in `package.json` as main, and there might be multiple files with many hits (often at least one js + css).

**Comment by ckedwards** [comment]
Another option is to add support a jsdelivr field in the package.json. This would be similar to what upkg does. (Sorry to reference unpkg twice, but they seem to have solved these two particular issues)

>If you omit the file path (i.e. use a “bare” URL), unpkg will serve the file specified by the unpkg field in package.json, or fall back to main.

Source:
https://unpkg.com

**Comment by MartinKolarik** [comment]
@ckedwards we support `jsdelivr` already, it's even mentioned in the original post.

**Comment by ckedwards** [comment]
> @ckedwards we support `jsdelivr` already, it's even mentioned in the original post.

Sorry, I misread that part of the issue and I was not aware that a jsdelivr field is supported. 

To me it seems like there are two options:
1) Specify `https://cdn.jsdelivr.net/npm/spectacle@4.3/dist/spectacle.min.js` rather than `https://cdn.jsdelivr.net/npm/spectacle@4.3` in your html page.
2) Make a PR for spectacle to add a jsdelivr field.

Having the "requested the most" behavior has more potential to cause more unexpected behavior than problems that it would solve. For example, what if main pointed to `dist/umd/spectacle.js`, but another, more popular, page uses `dist/esm/spectacle.js`. The page that wanted to use umd would unexpectedly break because the default switched to esm.

That's just my 2 cents though.

**Comment by MartinKolarik** [comment]
This is going to be done soon in a redesign, based on our new API endpoint: https://github.com/jsdelivr/data.jsdelivr.com#get-package-entry-points
