### ISSUE TITLE
sweetalert2 is the 62th most popular package on jsDelivr

### ISSUE THREAD

**Issue by limonte** [jsdelivr/jsdelivr#18088]
https://www.jsdelivr.com/package/npm/sweetalert2

![image](https://user-images.githubusercontent.com/6059356/45089091-bdb43900-b113-11e8-9735-4100c22d0abe.png)

It should be **62nd**, not 62th.

**Comment by MartinKolarik** [comment]
Thanks for reporting. The rules are indeed a little more complex. Should be fixed in a few minutes.

**Comment by limonte** [comment]
That was quick, thank you @MartinKolarik!
