### ISSUE TITLE
DNS resolving for jsDelivr 

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18094]
I found that all traffic was directed to Cloudflare:

```bash
$ dig cdn.jsdelivr.net @80.80.80.80

;; ANSWER SECTION:
cdn.jsdelivr.net.       98      IN      CNAME   cdn.jsdelivr.net.cdn.cloudflare.net.
cdn.jsdelivr.net.cdn.cloudflare.net. 255 IN A   104.16.86.20
cdn.jsdelivr.net.cdn.cloudflare.net. 255 IN A   104.16.88.20
cdn.jsdelivr.net.cdn.cloudflare.net. 255 IN A   104.16.87.20
cdn.jsdelivr.net.cdn.cloudflare.net. 255 IN A   104.16.85.20
cdn.jsdelivr.net.cdn.cloudflare.net. 255 IN A   104.16.89.20
```
```bash
$ dig cdn.jsdelivr.net @8.8.8.8

;; ANSWER SECTION:
cdn.jsdelivr.net.       23      IN      CNAME   cdn.jsdelivr.net.cdn.cloudflare.net.
cdn.jsdelivr.net.cdn.cloudflare.net. 181 IN A   104.16.89.20
cdn.jsdelivr.net.cdn.cloudflare.net. 181 IN A   104.16.86.20
cdn.jsdelivr.net.cdn.cloudflare.net. 181 IN A   104.16.87.20
cdn.jsdelivr.net.cdn.cloudflare.net. 181 IN A   104.16.85.20
cdn.jsdelivr.net.cdn.cloudflare.net. 181 IN A   104.16.88.20
```

```bash
$ dig cdn.jsdelivr.net @1.1.1.1

;; ANSWER SECTION:
cdn.jsdelivr.net.       49      IN      CNAME   cdn.jsdelivr.net.cdn.cloudflare.net.
cdn.jsdelivr.net.cdn.cloudflare.net. 206 IN A   104.16.86.20
cdn.jsdelivr.net.cdn.cloudflare.net. 206 IN A   104.16.88.20
cdn.jsdelivr.net.cdn.cloudflare.net. 206 IN A   104.16.87.20
cdn.jsdelivr.net.cdn.cloudflare.net. 206 IN A   104.16.85.20
cdn.jsdelivr.net.cdn.cloudflare.net. 206 IN A   104.16.89.20
```

I also checked the record at ADNS for jsdelivr.net:

```bash
dig cdn.jsdelivr.net @dns1.p03.nsone.net

;; ANSWER SECTION:
cdn.jsdelivr.net.       200     IN      CNAME   cdn.jsdelivr.net.cdn.cloudflare.net.
```

```bash
dig cdn.jsdelivr.net @ns1.r4ns.net

;; ANSWER SECTION:
cdn.jsdelivr.net.       60      IN      CNAME   2-01-2cd3-000f.cdx.cedexis.net.
```

It looks like the record at NS1 has changed from cedexis to cloudflare directly.
Is it supposed to be happened?

**Comment by MartinKolarik** [comment]
Yes, this is a temporary change because cedexis had issues earlier this week, causing random DNS resolution failures for some users (#18093). We're currently looking into how to enable it again while making sure it'll be 100% reliable.

**Comment by SukkaW** [comment]
Emmm, as far as I know that Azure has some specific issue related to NS1. When an Azure server send DNS requesr to NS1, the request will be sent to South America Region in NS1 Anycast Network due to some misconfiguration of BGP routing rules. It might cause that issue #18093, I think.

**Comment by SukkaW** [comment]
When I'm running test for `https://tools.ipip.net/dns.php` at https://tools.ipip.net/dns.php I couldn't tell some thing wrong with cedexis gslb.

**Comment by MartinKolarik** [comment]
Despite the title it wasn't specific to Azure, we got reports from many other people on Twitter and it was definitely a cedexis issue.

**Comment by SukkaW** [comment]
Oh I see. Thanks for the insight.

**Comment by iflamed** [comment]
How is issue this going? I'm based at Beijing, Also find out the cdn's dns result to cloudflare.

**Comment by rnotley** [comment]
Hopefully this is the best spot to add this - if not, my apologies.

I noticed my home DNS server was unable to resolve cdn.jsdelivr.net.  Looking in my DNS server logs, this was apparently a DNSSEC failure (My DNS resolver validates DNSSEC.)  When I temporarily disabled DNSSEC support, resolving cdn.jsdelivr.net worked fine.

You can see specific DNSSEC errors here:
https://dnssec-debugger.verisignlabs.com/cdn.jsdelivr.net

**Comment by jimaek** [comment]
I asked CF's support about that. There is nothing I can do since I have not enabled DNSSEC. Maybe its an issue on their side

**Comment by Yexiaoxing** [comment]
Looks like this issue remains. Is there any update on this issue? 
It seems that Cloudflare is not that reliable in China, as I can see some issues (and I am getting a bad speed).

**Comment by jimaek** [comment]
Please check again. China should be getting Quantil again. Everything should be back to normal.

**Comment by SukkaW** [comment]
@jimae Is the cedexis went wrong again? I find that all the traffic is now directed to cloudflare again.

**Comment by MartinKolarik** [comment]
Yes, we had to revert it again. Tracking in #18093.

**Comment by SukkaW** [comment]
@MartinKolarik 
Is there any updates now? All the traffic is still directed to Cloudflare.

**Comment by MartinKolarik** [comment]
@SukkaW unfortunately yes, we'll comment here when this is resolved permanently.
