### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/jsdelivr#18091]
### November 2019 update

We could also use your help with the promotion of our CDN and everything built on top of it. Writing blog posts, tweeting, sending PRs with jsDelivr links to your favorite projects, simply engaging in relevant discussions on GitHub, or whatever else you think of.

**What we built since starting this issue:**
Atom plugin: https://github.com/jsdelivr/plugin-atom
IntelliJ plugin: https://github.com/jsdelivr/plugin-intellij
VS Code: https://github.com/jsdelivr/plugin-vs-code
VS Libman integration: https://github.com/aspnet/LibraryManager
FontFamous: https://github.com/jsdelivr/FontFamous
WordPress plugin (unofficial): https://wordpress.org/plugins/commonwp/

**In progress:**
WordPress plugin: https://github.com/jsdelivr/plugin-wordpress
Chrome extension: https://github.com/jsdelivr/jsdelivr-chrome

### Original text

We would like to build many additional tools on top of jsDelivr CDN. Right now we are mostly thinking about:
 - plugins for popular CMSs,
 - plugins for popular IDEs,
 - integrations to online code playgrounds

but in general it could be anything that helps either:

 - developers using jsDelivr directly in their projects,
 - people running websites (who might not necessarily be developers),
 - someone else we didn't think of?

We are already working on a [WordPress plugin](https://github.com/jsdelivr/plugin-wordpress) and [Visual Studio plugin](https://github.com/aspnet/LibraryManager/pull/338) but there are a lot of CMSs/IDEs so let us know if you can integrate jsDelivr into your favorite platform.

**Comment by vtulse** [comment]
How I can help you to develop the Drupal 8 cms plugin

**Comment by MartinKolarik** [comment]
@vtulse do you have experience in PHP, or Drupal development specifically? We already have an almost complete [WordPress plugin](https://github.com/jsdelivr/plugin-wordpress) so the Drupal version would most likely be similar (I'll update the readme there to outline how it works).

**Comment by orangenightmare** [comment]
I've used wordpress and drupal on and off for years and everything that's listed as a goal I'd be happy to work on as a way to help. If there is any sort of list of projects aside from wordpress and drupal to look to integrate with I have plenty of free time as I'm unemployed. Otherwise I'll just start researching any way I can integrate the jsDelivr cdn with.

**Comment by MartinKolarik** [comment]
@orangenightmare 

>If there is any sort of list of projects aside from wordpress and drupal

Does that mean you'd like to help with something else but not with a Drupal plugin?

**Comment by lordspace** [comment]
This guy has created commonwp to use with your service.
https://milandinic.com/2018/09/18/introducing-commonwp/

His plugin was featured here: https://wptavern.com/new-commonwp-plugin-enables-wordpress-sites-to-use-the-free-jsdelivr-cdn

**Comment by MartinKolarik** [comment]
@lordspace yep, we're aware, he was in touch before publishing it.

**Comment by styfle** [comment]
Here are some IDE's worth integrating with: https://github.com/styfle/awesome-online-ide

In particular, CodeSandbox and StackBlitz would be good to download directly from jsdelivr.

**Comment by MartinKolarik** [comment]
@styfle both of them already use jsDelivr to power their "npm install" features 😉

**Comment by ellisonleao** [comment]
I can try something for VIM if you guys want

**Comment by MartinKolarik** [comment]
@ellisonleao sure! Check the Intellij plugin for inspiration and let me know if you need help with anything,

**Comment by shridhar-patil** [comment]
@MartinKolarik Let me know to develop any plugins for php , python or javascript based projects

**Comment by MartinKolarik** [comment]
@shridhar-patil a plugin for Joomla or Drupal (similar to the [WP version](https://github.com/jsdelivr/plugin-wordpress)) would be definitely useful if that sounds interesting to you.

**Comment by harry-hov** [comment]
I would like to try something for "Brackets"

**Comment by MartinKolarik** [comment]
@harry-hov check https://github.com/jsdelivr/plugin-intellij, I think something similar could be done for Brackets?

**Comment by harry-hov** [comment]
I'll take a look at this 
@MartinKolarik

**Comment by wfoojjaec** [comment]
This might be useful, or might not. A [MODx integration package](https://modx.com/extras/package/jsdelivr.net).

**Comment by devTimmy** [comment]
Let me do some research on how to do this in visual studio

**Comment by MartinKolarik** [comment]
@devTimmy we're going to publish an extension for VS Code soon, but for the regular VS we'd definitely love some help.

**Comment by devTimmy** [comment]
Oh yeah @MartinKolarik, i meant the IDE.

**Comment by phetter** [comment]
I recommend starting a github project board for each initiative.

**Comment by varunsridharan** [comment]
@MartinKolarik i am a wordpress developer. i would love to help in a way i could.

**Comment by MartinKolarik** [comment]
@varunsridharan we have a WP plugin in development [already](https://github.com/jsdelivr/plugin-wordpress) but it still needs some work and we don't have the time right now. If you'd like to help us finish it that would be great.

**Comment by varunsridharan** [comment]
@MartinKolarik awesome. i can help on it. show i can proceed and whats the pending tasks ?

**Comment by MartinKolarik** [comment]
@varunsridharan I'll take a look at what is needed and ping you in that repo later, ok?

**Comment by varunsridharan** [comment]
@MartinKolarik Awesome great :-)

**Comment by rishirajpurohit** [comment]
@MartinKolarik  I have experience with laravel but not sure what I can help. let me know if I can do anything to contribute

**Comment by farhanhalai30** [comment]
Hey @MartinKolarik is there anything that need to build in Javascript? 
Let me know if I can help!!

Thanks.

**Comment by wellington1993** [comment]
I'm thinking in a browser plugin to load page assets direct from jsDelivr instead non optimized sources.

**Comment by dutiyesh** [comment]
Hey @MartinKolarik , how about a browser extension that adds a jsDelivr button on GitHub and NPM pages?
Providing users with an alternate option of consuming a package.

**A jsDelivr button can be placed beside GitHub's "Clone or download" button.**
<img width="640" alt="jsdelivr-github-01" src="https://user-images.githubusercontent.com/12200583/65369371-c79ad280-dc69-11e9-9994-22d00b7594d2.png">

---

**When user clicks on jsDelivr button, we can provide user an option to copy a CDN link or download a ZIP file.**
<img width="640" alt="jsdelivr-github-02" src="https://user-images.githubusercontent.com/12200583/65369374-ca95c300-dc69-11e9-94b5-3035a9374e3d.png">

---

**And for NPM, a CDN link can be displayed just below NPM's install command.**
<img width="640" alt="jsdelivr-npm" src="https://user-images.githubusercontent.com/12200583/65369355-899dae80-dc69-11e9-855a-29aa8c0350b7.png">


What do you think?

**Comment by jimaek** [comment]
That looks really cool! Would you be able to do that?
We can create repo and make it open source

**Comment by dutiyesh** [comment]
@jimaek Sure! We can do that.

**Comment by jimaek** [comment]
Awesome, here is the repo https://github.com/jsdelivr/jsdelivr-chrome
Lets move all dev and discussion about the extension over there

**Comment by dutiyesh** [comment]
Lets do it.

**Comment by MartinKolarik** [comment]
Some updates in the original comment: https://github.com/jsdelivr/jsdelivr/issues/18091#issue-360647914

**Comment by orn0t** [comment]
Just drafted a Sublime plugin - https://github.com/orn0t/jsdelivr-sublime-plugin.

**Comment by MartinKolarik** [comment]
@orn0t that looks great! Left you some comments in your repo.

**Comment by Ultra-Instinct-05** [comment]
Here's a gif of a Sublime plugin I made that follows the Atom plugin quite closely. 

![example5](https://user-images.githubusercontent.com/34304644/74246685-eda13c00-4d0a-11ea-89e0-8ed069735b3e.gif)

**Comment by kimbo** [comment]
@ellisonleao Any update on the vim plugin?

**Comment by ellisonleao** [comment]
@kimbo not yet. Unfortunately i had to stop working on it and it's very raw at the moment. Do you have anything implemented already?

**Comment by kimbo** [comment]
No I don't. I was just searching for a free CDN and found this. I'd be down to help out with it tho

**Comment by ellisonleao** [comment]
@kimbo sure! i will create a repo and ping you here if that's ok

**Comment by kimbo** [comment]
@ellisonleao sounds great!

**Comment by ParitoshikPaul** [comment]
@MartinKolarik : I can help with Drupal 8 module as I am working on it and I need that integration in one of my projects.

**Comment by ParitoshikPaul** [comment]
I see no module for drupal 8

**Comment by MartinKolarik** [comment]
@ParitoshikPaul absolutely, you can ping me if you have any questions regarding the necessary jsDelivr APIs.

**Comment by sashafirsov** [comment]
Hi, my area of interest resides in Web Components toolchain and for CMS in Liferay and Adobe AEM where I could give a hand.

In order to promote jsDelivr there, integration into existing build of JS app is a requirement.  I.e. there is a need for guide "how to build npm project with dependencies located on jsDelivr CDN". 

RollUp has plugins for URL maps, I guess same exist for WebPack. But have not seen any guide focusing on jsDelivr build integration.

**Comment by MartinKolarik** [comment]
@sashafirsov I believe most people use the CDN files by directly including the files via `<script>` but I've seen some attempts on build process integration too, e.g. https://www.npmjs.com/package/webpack-cdn-plugin

**Comment by equinusocio** [comment]
Native Elements is sponsoring JsDelivr as CDN:
https://native-elements.dev/docs/getting-started/installation

**Comment by sashafirsov** [comment]
@equinusocio , Native Elements in JsDelivr are shared as custom build in dist/ sub-folder where dependencies are embedded. Which is antipattern if we are talking about use CDN for shareable components. Same concept as Ionic btw.

**Comment by WhatZ2333** [comment]
typecho:https://whatz2333.top/index.php/archives/46/

**Comment by MattMarquise** [comment]
Hey @MartinKolarik, if there is anything I could build, either in front end using HTML, CSS, and or JS, or anything backend using Laravel please let me know! Would love to help out!

**Comment by MartinKolarik** [comment]
@MattMarquise could you maybe take a look at https://github.com/jsdelivr/www.jsdelivr.com/issues/370 for a start?

**Comment by MattMarquise** [comment]
@MartinKolarik I have read over that issue.

**Comment by rudiansyah1** [comment]
i have read over and that issue

**Comment by arslanramay** [comment]
@MartinKolarik I would love to help with Shopify and Laravel integrations. I see that WordPress version is already developed. Please let me know if I could be of any help. Thanks :)

**Comment by MartinKolarik** [comment]
@arslanramay we don't have resources to start a project for those platforms atm, but if you'd like to start one of those projects yourself, we'll be happy to provide support (e.g., in terms of integrations with our APIs) and answer any questions you have during the development.

**Comment by elmoustaphahoueibib** [comment]
I'd love to help

**Comment by jimaek** [comment]
For everyone here still interested to contribute, we could really use your help!

If you want to build a cool new integration or addon that we don't already have just message me and I will create a separate repo.

If you want to just start helping the project overall then the best way to get started is to check the open issues we have in our repos. Start with something small and as you work on it you will get more understanding on how everything works.
Leave comments with questions in the correct issues. 

If you want to dedicate a lot of time to help us build bigger features let me know and I will invite you to our group chat to discuss the more complex issues.

If you are not a coder but still want to help then just let me know!
Some ideas of non-coding related help:
- We could always use designers to improve our website, 
- Content writers for our blog
- Better documentation would be great!
- Marketing ideas and implementation to let more people know that we are here and we are the best :p 


You can always reach me at dak@prospectone.io with questions or feedback

**Comment by ParveenBhadooOfficial** [comment]
> ### November 2019 update
> We could also use your help with the promotion of our CDN and everything built on top of it. Writing blog posts, tweeting, sending PRs with jsDelivr links to your favorite projects, simply engaging in relevant discussions on GitHub, or whatever else you think of.
> 
> **What we built since starting this issue:**
> Atom plugin: https://github.com/jsdelivr/plugin-atom
> IntelliJ plugin: https://github.com/jsdelivr/plugin-intellij
> VS Code: https://github.com/jsdelivr/plugin-vs-code
> VS Libman integration: https://github.com/aspnet/LibraryManager
> FontFamous: https://github.com/jsdelivr/FontFamous
> WordPress plugin (unofficial): https://wordpress.org/plugins/commonwp/
> 
> **In progress:**
> WordPress plugin: https://github.com/jsdelivr/plugin-wordpress
> Chrome extension: https://github.com/jsdelivr/jsdelivr-chrome
> 
> ### Original text
> We would like to build many additional tools on top of jsDelivr CDN. Right now we are mostly thinking about:
> 
> * plugins for popular CMSs,
> * plugins for popular IDEs,
> * integrations to online code playgrounds
> 
> but in general it could be anything that helps either:
> 
> * developers using jsDelivr directly in their projects,
> * people running websites (who might not necessarily be developers),
> * someone else we didn't think of?
> 
> We are already working on a [WordPress plugin](https://github.com/jsdelivr/plugin-wordpress) and [Visual Studio plugin](https://github.com/aspnet/LibraryManager/pull/338) but there are a lot of CMSs/IDEs so let us know if you can integrate jsDelivr into your favorite platform.

WordPress plugin link shows 404. WordPress really needs jsdelivr CDN Plugin. Any possibility for maintained plugin for WordPress?

**Comment by jimaek** [comment]
Soon we plan to launch even more features related to ESM, including a site redesign.

Our problem is the promotion part. We struggle reaching people to notify them of our updates and then in turn struggle to amplify our message.
I would appreciate all ideas and help regarding the marketing and promotion and SEO optimization of jsDelivr!

Ping me at dak@prospectone.io!
