### ISSUE TITLE
jsdelivr combine issues | Angularjs | Outdated Libraries 

### ISSUE THREAD

**Issue by sagargulati** [jsdelivr/jsdelivr#18099]
Greetings,
I have been struggling out using multiple combined js files and loading them on an Angularjs website but it's giving errors. 

Here is what I'm using:

`  <script src="https://cdn.jsdelivr.net/combine/npm/angular@1.7.5/angular.min.js,npm/angular-aria@1.7.5/angular-aria.min.js,npm/angular-animate@1.7.5/angular-animate.min.js,npm/angular-cookies@1.7.5/angular-cookies.min.js,npm/angular-message-format@1.7.5/angular-message-format.min.js,npm/angular-messages@1.7.5/angular-messages.min.js,npm/angular-route@1.7.5/angular-route.min.js,npm/angular-sanitize@1.7.5/angular-sanitize.min.js,npm/angular-ui-router@1.0.20/release/ui-router-angularjs.min.js,npm/angular-material@1.1.10/angular-material.min.js,npm/angular-recaptcha@4.2.0/release/angular-recaptcha.min.js,npm/angular-material-data-table@0.10.10/dist/md-data-table.min.js,npm/ng-notify@0.7.1/src/scripts/ng-notify.min.js,npm/@bmvantunes/ngprogress@1.1.3/build/ngprogress.min.js"></script>
`

Loading them like this just give errors, while loading each file one by one works fine (not combined.)
Any idea what could be wrong?
Also, there are a lot of libraries which aren't updated and the CDN doesn't recognize even though they are on GitHub.

The issue is with both `/combine` and path `/g ` which doesn't fetch latest libraries.

**Example:** 
`https://cdn.jsdelivr.net/gh/angular/code.angularjs.org@1.7.5/angular.min.js`
**However:**
`https://github.com/angular/code.angularjs.org` have all the latest versions.

Please check and tell, it might be modifying the source.
Thanks!

**Comment by MartinKolarik** [comment]
The combine feature doesn't modify files in any way and I get the exact same error (coming from `angular-ui-router`) if I load all the files separately. Please provide more information and/or a live demo if you see anything different.

As for `https://github.com/angular/code.angularjs.org`, it has [no releases](https://github.com/angular/code.angularjs.org/releases) = it has no versions. Please check the documentation for GitHub: https://github.com/jsdelivr/jsdelivr#github

**Comment by sagargulati** [comment]
What is the issue with ui-router?
Why are the libraries outdated on jsdelivr?
Please check [this](http://plnkr.co/edit/1kGuQ9meSsED1IPMQ40L?p=preview).
Also, https://github.com/angular/code.angularjs.org isn't considered by the folders in it? It had to be pushed on releases?

**Comment by MartinKolarik** [comment]
>Also, https://github.com/angular/code.angularjs.org isn't considered by the folders in it?

Yes, the folders inside don't matter at all.

**Comment by sagargulati** [comment]
Ok, waiting for the other updates with the script.
