### ISSUE TITLE
Get 503 Error on jsDelivr

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18090]
![image](https://user-images.githubusercontent.com/40715044/45261447-3af1ed80-b435-11e8-8327-3df6df306cb8.png)

My IP Address is `52.197.247.110` (AWS JP)

Is there anything wrong with jsDelivr backend cluster?

**Comment by jimaek** [comment]
It was a problem affecting non-cached files. Its fixed and everything is working fine now.
I am sorry about this.

**Comment by charpstar** [comment]
Getting this issue now again. The main jQuery scripts work but my own script does not work and gives out this error

**Comment by jimaek** [comment]
There is a small issue with the backend that impacts new uncached files, we are working to fix this. But it should not impact any old files

**Comment by MartinKolarik** [comment]
We're still investigating whether this was some kind of DDoS or some other issue but the origin servers should operate normally now.

**Comment by mootari** [comment]
I'm encountering this right now:
```
Error 503 No healthy backends
No healthy backends

Guru Mediation:
Details: cache-fra19146-FRA 1605796789 3020031747

Varnish cache server
```

**Comment by jimaek** [comment]
Some uncached files are unfortunately having issues, We are working on this and everything should be back to normal soon

**Comment by jimaek** [comment]
It looks like everything is back to normal now. I am sorry for this small outage, it was limited to certain regions and certain uncached files, so most people should not have noticed anything.

**Comment by jrobinso** [comment]
In enountering this error now for (newly published) https://cdn.jsdelivr.net/npm/igv@2.9.3/dist/igv.min.js

```
Error 503 No healthy backends
No healthy backends

Guru Mediation:
Details: cache-bur17546-BUR 1627066520 1900813918

Varnish cache server
```

**Comment by jimaek** [comment]
Indeed newly published (uncached) packages need a few hits to start properly working. We are on top of this.
Existing cached files are not impacted.

**Comment by jrobinso** [comment]
@jimaek Perhaps you fixed this now?  It appears to be working.

**Comment by jrobinso** [comment]
Would it be advisable, as a workaround,  to script a few hits to the CDN upon publishing?

**Comment by jimaek** [comment]
Its not fixed yet, you just have to refresh a few times to get it work, but after that it becomes cached and you wont notice any issues. 

>Would it be advisable, as a workaround, to script a few hits to the CDN upon publishing?

It shouldn't make a big difference really, but you could add it if you dont have too many users hitting your new versions naturally.
