### ISSUE TITLE
Github url does not work

### ISSUE THREAD

**Issue by H27-VEN** [jsdelivr/jsdelivr#18106]
Here is the github url I want to use with jsdelivr.

[react-bundle](https://github.com/H27-VEN/react-bundle) 
within this repo there is a file called bundle-inbox.js

Now when I use this with jsdeliver I am using the following url
https://cdn.jsdelivr.net/gh/H27-VEN/react-bundle/bundle-inbox.js

But I get the following error: 
**Couldn't find the requested release version latest.**

**Comment by MartinKolarik** [comment]
You release numbers need to be valid semver for this to work - `0.1.5` or `0.15.0` instead of `0.15`.

**Comment by MartinKolarik** [comment]
Reopen if you have other questions.
