### ISSUE TITLE
Github url for development purpose doesn't not seem to work.

### ISSUE THREAD

**Issue by H27-VEN** [jsdelivr/jsdelivr#18107]
Here is the github url I want to use with jsdelivr.

[react-bundle](https://github.com/H27-VEN/react-bundle) 
within this repo there is a file called bundle-inbox.js

Now when I use this with jsdeliver I am using the following url
https://cdn.jsdelivr.net/gh/H27-VEN/react-bundle/bundle-inbox.js

But I get the following error: 
**Couldn't find the requested release version latest.**

**Comment by MartinKolarik** [comment]
#18106
