### ISSUE TITLE
Please stop opening issues on twbs/bootstrap

### ISSUE THREAD

**Issue by wolfy1339** [jsdelivr/jsdelivr#18109]
Can a developer of jsdelivr stand up to the community and ask them to stop making issues on Bootstrap (I'm in no way affiliated with them).

It gets very annoying to have to repeat to everyone that Bootstrap doesn't have a 'main' file since it is a CSS+JS framework, plus it generates lots of noise for the people that subscribed to the updates of the repository

**Comment by MartinKolarik** [comment]
I think we could update the code to check if an issue with such title already exists and link to it rather than offering creating a new one in that case. Sounds good?

**Comment by wolfy1339** [comment]
That would be a viable option.
________________________________

**Comment by MartinKolarik** [comment]
Created a task in the website repository. If you would like to see it changed quickly, PRs are welcome.
