### ISSUE TITLE
Using timestamp instead of version number

### ISSUE THREAD

**Issue by ETHproductions** [jsdelivr/jsdelivr#18114]
Hey all,

I'm working on a remake of a personal online project (used recreationally by myself and a few others) where the version to use is specified in the permalink. This project has breaking updates fairly frequently; in the original, I had resorted to waiting to make the breaking changes until I was ready to release the next minor version. Additionally, I had to hardcode the latest version number in the code, and update it with every release, to ensure that the permalinks generated stayed permanent.

To improve the versioning system in the remake, I began using the timestamp (down to the minute) as the version. This got rid of both issues: I no longer have to worry about breaking updates or hardcoding the version number. An example URL using this method:

- GitHub link: [https://github.com/ETHproductions/japt-2/blob/dev@{2018-06-30T14:25Z}/src/japt.js](https://github.com/ETHproductions/japt-2/blob/dev@%7B2018-06-30T14:25Z%7D/src/japt.js)
- RawGit link: [https://rawgit.com/ETHproductions/japt-2/dev@{2018-06-30T14:25Z}/src/japt.js](https://rawgit.com/ETHproductions/japt-2/dev@%7B2018-06-30T14:25Z%7D/src/japt.js)

With RawGit entering sunset phase, I tried migrating to jsDelivr, only to find that this kind of timestamp commit reference is not possible. Might it be too much to ask to add this feature? Or is there a security risk or practical reason why this isn't supported? (I won't be offended if you inform me that my timestamp versioning system is an absolutely awful idea :wink:)

Thanks in advance.

**Comment by MartinKolarik** [comment]
I didn't even know this was possible but it actually is supported if you encode the "version" part correctly: https://cdn.jsdelivr.net/gh/ETHproductions/japt-2@dev%40%7B2018-06-30T14:25Z%7D/src/japt.js

I updated the migration tool to reflect this, it should be live in a couple of minutes.

**Comment by ETHproductions** [comment]
Sweet, thank you so much! Didn't realize two `@`s were required, but the migration tool makes it easy now :-)
