### ISSUE TITLE
Is there any API endpoint to get the overall position and dewnloads per month of a given plugin?

### ISSUE THREAD

**Issue by limonte** [jsdelivr/jsdelivr#18118]
From https://www.jsdelivr.com/package/npm/sweetalert2 users can see that sweetalert2 is the 25th most popular package on jsDelivr, with 206 181 153 CDN hits in the last month

I would like to show the same information on https://sweetalert2.github.ioand for that I would need API endpoints for 
- getting the overall position of a plugin (for sweetalert2 it would be 25)
- getting the number of downloads per month

Is there anything like that? If no, any plans to implement and make that API public?

Thanks in advance!

**Comment by MartinKolarik** [comment]
https://data.jsdelivr.com/v1/package/npm/sweetalert2/stats/month
docs: https://github.com/jsdelivr/data.jsdelivr.com

**Comment by limonte** [comment]
Perfect, thank you @MartinKolarik
