### ISSUE TITLE
Support for ES modules

### ISSUE THREAD

**Issue by JosefJezek** [jsdelivr/jsdelivr#18115]
Could you add option for ES modules as unpkg.com?

Example `https://unpkg.com/@material/mwc-button@latest/mwc-button.js?module`

**Comment by MartinKolarik** [comment]
Most likely yes, at some point, but no ETA. The current unpkg implementation shouldn't be used for anything other than quick demos in online code editors because it often results in hundreds of requests causing terrible page load times. Unfortunately not everyone is aware of this and we don't want to encourage people using this in production until it works in some better way.

**Comment by gugadev** [comment]
@MartinKolarik IMO, this is a must-have feature in modern stacks. If you are planning to serve native ESModules to browsers that support it -**almost all brosers**- you haven't another alternative than using unpkg when the caveats you said.

**Comment by fusionstrings** [comment]
@gugadev @MartinKolarik is right. Read more here https://jspm.io/ and here https://jspm.org/about/introduction#cdn

But option can be provided with caution.

**Comment by ConradSollitt** [comment]
I just came across this issue and **I've been using ES Modules with jsDelivr** for a 3 months now. It works perfectly in my opinion.

Is there something not supported? If not I think this issue could be closed out.

Here is a demo of ES Modules using Web Components from jsDelivr.
https://www.dataformsjs.com/examples/places-demo-web.htm

In DevTools you can see that several modules are loaded from JavaScript files.
![DevTools_ES_Module_Loaded_from_jsdelivr](https://user-images.githubusercontent.com/57777521/73406244-d134e680-42aa-11ea-997c-217b713bdd68.png)

In the code you can see the import statement is used and works as expected with jsDelivr. Note - this print screen is of a non `*.min.js` file while the above print screen uses `*.min.js` files.
![Code_ES_Module_Import](https://user-images.githubusercontent.com/57777521/73406245-d134e680-42aa-11ea-8356-f41ef17bd13f.png)

**Comment by MartinKolarik** [comment]
This now works! https://esm.run/@material/mwc-button@latest/mwc-button.js (details in #18263).
