### ISSUE TITLE
Replicating some RawGit behavior

### ISSUE THREAD

**Issue by paulmasson** [jsdelivr/jsdelivr#18111]
With RawGit one could easily see older versions of static HTML files rendered in a browser. It was a nice way to view older versions of documentation on GitHub.

Is it possible to do the same with your service? Accessing HTML with a CDN subdomain shows only raw HTML.

If this is not a good place to ask this question, tell me where else to post it. Thanks!

**Comment by MartinKolarik** [comment]
Unfortunately we don't serve files with `Content-Type: text/html` for security reasons. Doing that was the main reason RawGit was forced to shut down because it's very easy to abuse.

**Comment by paulmasson** [comment]
Thanks for the response.
