### ISSUE TITLE
Connection Refused Android 4.4.2

### ISSUE THREAD

**Issue by sunnygb** [jsdelivr/jsdelivr#18110]
After publishing to npm, i managed to serve throught jsDelivr and successfully get response on desktop, but on some android devices, i got the messeges of connection refused as shown below..

![image](https://user-images.githubusercontent.com/13783116/47953366-7c6ac900-df9e-11e8-9501-318a99ade01a.png)

After digging up deeply, i found out that the domain  `cdn.jsdelivr.net ` wasnt responding as aspected,
On some devices its responding perfectly, while on some devices its not.
I couldnt figure out, its the problem in site certificate, or related to jsdelivr domain.. any help will be appriciated

**Comment by MartinKolarik** [comment]
@jimaek do we still support TLS 1.1 everywhere?

**Comment by dimadin** [comment]
I have two older different devices with Android 4.2.2, and I tried bundled browser and everything works.
However, for address from your screenshot, I do get blank page in bundled browser but in other browsers installed as apps, site loads.

**Comment by jimaek** [comment]
We should. Can you tell me the IP of the server when you are getting the error?

**Comment by sunnygb** [comment]
@jimaek  i hosted my site on server with IP 159.89.175.209,

**Comment by SukkaW** [comment]
@sunnygb Emmm, what they asked is which IP of jsDelivr did you connected.

**Comment by sunnygb** [comment]
Sorry is there any option of choosing IP of JsDelivr? I mean i uploaded to npm and append the jsdeliver url to get cdn working as prescribed on official page of JsDelivr. There isnt any kind of Ip mention on official website.. Could i change the ip of Jsdelivr for my site..? Any help would be appriciated

Here are my request headers, but it seems it is dropped by the browser due to connection refused..

![image](https://user-images.githubusercontent.com/13783116/47962999-20a84a80-e047-11e8-927e-3bf9a0afad54.png)

**Comment by SukkaW** [comment]
@sunnygb Could you please run `dig cdn.jsdelivr.net +short` since we can't got connected IP from browser?

**Comment by sunnygb** [comment]
I am using windows thus dig command isnt working, i tried also standalone dig package but still same issue.
But i google it to find out the IP address of cdn.jsDelivr.net  I got following results on windows, Hope it helps

![image](https://user-images.githubusercontent.com/13783116/47963543-8ef10b00-e04f-11e8-857d-d927de9d1a11.png)

**Comment by SukkaW** [comment]
@sunnygb If you are using CMD or Powershell, you can run `nslookup cdn.jsdelivr.net` instead.

**Comment by sunnygb** [comment]
Ok this is what i get on powershell..

![image](https://user-images.githubusercontent.com/13783116/47963716-bcd74f00-e051-11e8-84a2-9bceef99f90a.png)

**Comment by SukkaW** [comment]
I check [SSL Capabilities on Android 4.4.2](https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2) and it says either SNI or TLS 1.2 is supported.
I think there must be some issues related to DNS resolution on your test android devices. After all, if there is a SSL error, the browser shouldn't give you `CONNECTION_REFUSED`.

**Comment by sunnygb** [comment]
But i have tested on multiple devices. @dimadin  also tested on his device, same error presist. There must be something wrong on JsDelivr side server.

**Comment by sunnygb** [comment]
I thinks thats an issue of dns resolving on android 4.4.2 when try to connect cdn.jsdelivr.net, Since all other libraries coming from cdn.jsdelivr.net arent resolving as expected.

**Comment by sunnygb** [comment]
I tested the nslookup cdn.jsdelivr.net on my android 4.4.2, it resolves back to localhost i.e 127.0.0.1.
There is something not good in about dns of cdn.jsdelivr.net on bundled browsers as u can see here..

![image](https://user-images.githubusercontent.com/13783116/47965178-b0f58800-e065-11e8-955b-3fc04e996828.png)

**Comment by jimaek** [comment]
I don't know how the android emulator works so I can't tell you for sure. But we know that at the moment nobody is experiencing issues in production.
Also I suggest to check your local hosts file and search for jsdelivr in case there is a manual override for our domain

**Comment by sunnygb** [comment]
I double checked the host files and Flushed dns, still no success.
This issue has been seen on old devices of android 4.4.2 here i tested. while all other new devices its working perfectly.  And its strange that this only exist on native bundled browsers.

Is there subdomain other than cdn.jsdelivr.net? it would be very helpful..

**Comment by sunnygb** [comment]
@jimaek  Thankyou very much for clerification, I think there is a compatibility issue in my web app, thats why other devices show blank page. and also there is a problem in my mobile, due to which cdn.jsdelivr.net is blocked. While on other devices, logs show its working fine..
Thus im gonna close the issue
