### ISSUE TITLE
Serious: Problem with DNS resolving

### ISSUE THREAD

**Issue by batata004** [jsdelivr/jsdelivr#18113]
Since last week many customers of ours are complaining about problems with our website. We couldnt never check that on our ending cause everything looked working. So we setted up a virtual machine to access our website every hour, cleaning the cache of the browser before every access. So we checked the results. After 3 days, from almost 70 tests, in 8 of them there were problems with DNS resolving on resources provided by jsdelivr! 

So I decided to access on my own a few websites since yersterday, always clearing the cache before opening the websites and indeed on browser console I saw many messages of resources not being loaded because of problems with DNS resolution.

I never EVER had this problem with CDNJS. I just decided to move to JSDELIVR because of the COMBINE feature, however I am looking to going back to CDNJS since this problem with DNS resolution is killing me.

I am located at Santa Catarina (state at South of Brazil) but my customers all accross brazil are complaining of this exactly same problem. 

Could you check what could be causing this? Yesterday I was using Google's DNS and today I started using Cloudflare DNS and I am still having problems.

**Comment by jimaek** [comment]
Hello, can you provide us more technical details?
In the past we had users complain of similar issues but it turned to be an issue with their firewall and other LAN configurations.

Could you run the following:
```
dig cdn.jsdelivr.net
dig 2-01-2cd3-000f.cdx.cedexis.net
dig +trace cdn.jsdelivr.net
dig +trace 2-01-2cd3-000f.cdx.cedexis.net.
```
 Also a screenshot of the exact error you see in your browser.

**Comment by batata004** [comment]
Sorry I dont have linux, only windows. But I used tracert, could you check the prints attached?

![image](https://user-images.githubusercontent.com/8988923/48154643-46845800-e2b0-11e8-820e-caa97366ace7.png)
