### ISSUE TITLE
Worked once but then stopped working for a repo

### ISSUE THREAD

**Issue by ORESoftware** [jsdelivr/jsdelivr#18119]
this url resolves fine, I can download the file
https://raw.githubusercontent.com/typeaware/tarballs/master/docgen/styles-1.js

but when I hit this url:
https://cdn.jsdelivr.net/gh/typeaware/tarballs/master@docgen/styles-1.js

I get:

> Couldn't find the requested file /master@docgen/styles-1.js in typeaware/tarballs.

weird :(

**Comment by MartinKolarik** [comment]
Your jsDelivr URL isn't formatted correctly, it should be https://cdn.jsdelivr.net/gh/typeaware/tarballs@master/docgen/styles-1.js, or just https://cdn.jsdelivr.net/gh/typeaware/tarballs/docgen/styles-1.js
