### ISSUE TITLE
WordPress@latest pointing to previous version

### ISSUE THREAD

**Issue by ashucg** [jsdelivr/jsdelivr#18120]
[WordPress/WordPress@latest](https://cdn.jsdelivr.net/gh/WordPress/WordPress@latest/) is still pointing to [WordPress/WordPress@4.9.8/](https://cdn.jsdelivr.net/gh/WordPress/WordPress@4.9.8/)

**Comment by MartinKolarik** [comment]
`@latest` requires a valid semver version, which `5.0` is not. I guess it'll work once they release `5.0.1`
