### ISSUE TITLE
Webfonts 

### ISSUE THREAD

**Issue by iskrisis** [jsdelivr/jsdelivr#18122]
Hi i have few questions about webfonts on jsdelivr.

1. If i have webfont like this https://github.com/floriankarsten/space-grotesk/tree/master/fonts/webfont with web version in repo JSdelivr mirrors github like so https://cdn.jsdelivr.net/gh/floriankarsten/space-grotesk@latest/fonts/webfont/ 
Is it OKAY for me to use this as webfonts on my website - isnt jsdelivr just for Javascript?

2. If it is okay can use those JSdelivr link in code snippets for example font github page or product page? Examples
https://github.com/floriankarsten/space-grotesk and here https://fonts.floriankarsten.com/space-grotesk

Why i am asking is because Google Fonts is notorious for not adding new fonts. This leaves lot of open-source typefaces out. There are lists like this https://open-foundry.com/fonts but you cant easily link them on your website like with google fonts (so nobody uses it). If JSdelivr would allow things like that then it would allow someone to make mini google fonts alternative powered by JSdelivr.

**Comment by jimaek** [comment]
Hey,

1. No problem, you can serve webfonts as well
2. No problem too :)

At some point we want to add a fonts section to our website as well, but for now we do not have the time and resources. But in the meantime you can use jsDelivr for fonts, we officially support them!
