### ISSUE TITLE
Problem with dot in repository name

### ISSUE THREAD

**Issue by flopanzer** [jsdelivr/jsdelivr#18127]
Tried to use jsdelivr with my repo: 'somewhere.gl'
'https://cdn.jsdelivr.net/gh/flopanzer/somewhere.gl@9012d38989d5be397e3b3c80c5627fd9ade8e6f4/'
This throws a package-size exceed 'error'

Worked with another repository of mine, which doesn't contain a dot:
'https://cdn.jsdelivr.net/gh/flopanzer/random@7a6f0f71a75df072d351044fcbbbede5e38c9879/'

**Comment by MartinKolarik** [comment]
The error message is rather clear, is it not?

**Comment by MartinKolarik** [comment]
You may still access individual files but directory listings won't work because your repo is too big.

**Comment by flopanzer** [comment]
Thanks for  your quick response!
Your absolutely right, I'm sorry! I thought I found something to contribute.
Do you have a hint on how to access an individual file?

**Comment by MartinKolarik** [comment]
Use the [URL from the error message](https://github.com/flopanzer/somewhere.gl/tree/9012d38989d5be397e3b3c80c5627fd9ade8e6f4/) to find the file you want and add its path to the jsDelivr URL. Example: https://cdn.jsdelivr.net/gh/flopanzer/somewhere.gl@9012d38989d5be397e3b3c80c5627fd9ade8e6f4/README.md
