### ISSUE TITLE
Omitting version tag or using @latest version tag is not working as expected

### ISSUE THREAD

**Issue by tekNorah** [jsdelivr/jsdelivr#18128]
JsDelivr not releflecting latest release when tag ommitted or @latest tag is used

Github Release: https://github.com/tekNorah/tekAura/releases/tag/v1.0

**What Works:**
Specific version: https://cdn.jsdelivr.net/gh/tekNorah/tekAura@1.0/css/main.css

**What Does NOT Work:**
Without Tag: https://cdn.jsdelivr.net/gh/tekNorah/tekAura/css/main.css
With @latest Tag: https://cdn.jsdelivr.net/gh/tekNorah/tekAura@latest/css/main.css

What I tried:
Purge Without Tag: https://purge.jsdelivr.net/gh/tekNorah/tekAura/css/main.css
Purge With @latest Tag: https://purge.jsdelivr.net/gh/tekNorah/tekAura@latest/css/main.css
Purge With version Tag: https://purge.jsdelivr.net/gh/tekNorah/tekAura@1.0/css/main.css

I know usually updates take 24 hours.  But, read that there was a way to purge via the API and emailed Dimitriy for access, who in turn, asked that I submit this as an issue here.

**Comment by tekNorah** [comment]
hmmm... did someone "manually" purge on the server?  Or give me access?  I just did another purge attempt on tagless and @latest and now it is showing the new version.

**Comment by MartinKolarik** [comment]
@tekNorah I see you made a lot of releases recently. Which was the most recent one at the time of opening this issue and what response exactly did you get?

The @latest feature requires version numbers to be valid semver, so `1.0` and `1.1` are ignored. `1.1.1` on the other hand should be picked up without delay.

**Comment by tekNorah** [comment]
huh, ok... that kind of makes sense.  I encountered the issue on major versions 1.0 and 1.1.  So for major versions, maybe for my next major version, I need to use 1.2.0.

Would that work?

**Comment by MartinKolarik** [comment]
Yep, use `1.2.0` and it'll work as expected.

**Comment by tekNorah** [comment]
Ok, thank you! Closing issue as resolved!
