### ISSUE TITLE
Malicious file

### ISSUE THREAD

**Issue by Tehchy** [jsdelivr/jsdelivr#18129]
https://cdn.jsdelivr.net/gh/Sam-DevZ/io-games/gamenew.js
Hacked client for a popular io game

**Comment by MartinKolarik** [comment]
Can you provide more details? Which part exactly do you consider malware and why? Is there a public version of the original code to check what's been added?

**Comment by Tehchy** [comment]
Public link. https://krunker.io/js/game.js

**Comment by MartinKolarik** [comment]
Sorry but I don't see any problem with that link. Can you point out what part exactly do you consider malware?

**Comment by Tehchy** [comment]
i said its A Malicious file not directly malware. this file is a reuploaded file that i showed you except it has aimbot hacks added to it. this file is bundled with a userscript
