### ISSUE TITLE
How to see git updated content on cdn？

### ISSUE THREAD

**Issue by SingularityZed** [jsdelivr/jsdelivr#18125]
/package/gh/:user/:repo@:version/:structure
How to update cdn after GitHub update, why the updated file is not found on cdn. What do I need to do, thank you.

**Comment by MartinKolarik** [comment]
What file exactly?

**Comment by SingularityZed** [comment]
Picture , js, css and etc.But the point is that after git adds the file I can't see the updated file on cdn.
I’m a beginner, what should I do for this? veteran.

**Comment by MartinKolarik** [comment]
You should see all files. Please share specific CDN links that you think should work and don't.

**Comment by nandubatchu** [comment]
@MartinKolarik I have a similar issue. The sibling files are accessible via cdn. But, not this specific file. https://cdn.jsdelivr.net/gh/nandubatchu/lit-sink/components/beta/nandubatchu/basic/blue-button.js

**Comment by nandubatchu** [comment]
> @MartinKolarik I have a similar issue. The sibling files are accessible via cdn. But, not this specific file. https://cdn.jsdelivr.net/gh/nandubatchu/lit-sink/components/beta/nandubatchu/basic/blue-button.js

I guess the CDN realises the file changes very slowly. The above file is now available. But again facing the same problem: https://cdn.jsdelivr.net/gh/nandubatchu/lit-sink/components/beta/nandubatchu/basic/pink-button6.js

**Comment by MartinKolarik** [comment]
Indeed, if you use a branch reference, such as `master` it may take some time. For releases and commits there's no delay.

**Comment by SingularityZed** [comment]
https://cdn.jsdelivr.net/gh/singularityzed/assets@19.1.9/

This is my cdn for someone else, I added something but can't see it.
Thanks.

**Comment by MartinKolarik** [comment]
@SingularityZed your link is for a specific version - [release 19.1.9](https://github.com/SingularityZed/assets/releases). You'd have to make a new release and update the link for new files to be included.

**Comment by nandubatchu** [comment]
> Indeed, if you use a branch reference, such as `master` it may take some time. For releases and commits there's no delay. We'll check if this could be improved.

@MartinKolarik As you said, it might take some time for reflecting the files on the CDN, once they reflect, are there chances of vanishing again? I mean can we rely upon the first successful availability of the file on the CDN?

**Comment by MartinKolarik** [comment]
@nandubatchu good question. For branch references, it is possible the files become available at different servers at different times, which would result in different responses depending on your location. I'll try to get this fixed this week. That said, we still recommend using releases or commit hashes for production use cases.

**Comment by MartinKolarik** [comment]
We've just deployed an update which should eliminate the delay for new files. Existing files may take up to 12 hours to update, as was the case before. This also solves the problem described by @nandubatchu.

@nandubatchu @SingularityZed you are welcome to test this before I close this issue.

**Comment by sshaw** [comment]
This is an npm package: https://www.jsdelivr.com/package/npm/reveal.js

Not seeing latest version: http://cdn.jsdelivr.net/reveal.js/3.7.0/.

**Comment by MaverickDe** [comment]
use this method on this GitHub repo, with this your CDN file will be updated as you update your repo
https://github.com/MaverickDe/GITHUBCDN.git
