### ISSUE TITLE
Combine shorthand for multiple files

### ISSUE THREAD

**Issue by tis-rpage** [jsdelivr/jsdelivr#18135]
I've seen this `/g/<project>,<project>(file1+file2...)` interface used on various websites discussing jsdelivr, but it's not documented on the wiki/website. Can this shorthand notation for file inclusion be extended to the /combine/ interface?

Excerpt from https://www.diycode.cc/projects/dimsemenov/jsdelivr:
//cdn.jsdelivr.net/g/jquery,angularjs(angular.min.js+angular-resource.min.js+angular-animate.min.js+angular-cookies.min.js+angular-route.min.js+angular-sanitize.min.js)

I'd like the feature extended to the combine interface such that the following shorthand would work:
curl "https://cdn.jsdelivr.net/combine/npm/@mdi/svg@3/svg/(account.svg+access-point.svg)"

I'm aware this works:
 curl -s "https://cdn.jsdelivr.net/combine/npm/@mdi/svg@3/svg/account.svg,npm/@mdi/svg@3/svg/linkedin.svg"

**Comment by MartinKolarik** [comment]
This is intentionally not supported on the new endpoint, to make the URLs easier to generate and parse.

**Comment by tis-rpage** [comment]
Can you update the documentation for /g/ and /combine/ and make it clear the former is for javascript projects only and the latter doesn't support the shorthand combinations?

**Comment by MartinKolarik** [comment]
/g/ wasn't for JS only, but it's deprecated and not documented anymore. You should use /combine/ in all new projects.
