### ISSUE TITLE
Support listing files as JSON on the main CDN via Accept header

### ISSUE THREAD

**Issue by ggoodman** [jsdelivr/jsdelivr#18139]
I'm aware that the [API supports listing files](https://github.com/jsdelivr/data.jsdelivr.com#list-package-files) as JSON, but the availability guarantees and infrastructure for that service don't provide the same level of confidence as the main CDN.

Please consider supporting `Accept: application/json` on the directory listing pages so that these can serve the same content as their API-equivalents with the benefits of the main CDN's infrastructure.

<3 all your work :)

**Comment by MartinKolarik** [comment]
Moving the listings to the CDN would have an overall negative effect, not a positive one. The file listings are much more expensive (in terms of CPU and network), slower, and harder to cache than individual files directly at the origin.

That's why we decided to make them available via a separate service, which caches all data more effectively and makes most requests considerably faster. The API should be reliable enough for most use cases when used correctly.

**Comment by ggoodman** [comment]
Hi @MartinKolarik, thanks for the quick reply! Sounds like you have already evaluated this and clearly have more context than me.

I feel like caching the file listings should be feasible given that versions are (for all intents and purposes) are immutable on npm and are immutable for a given `tree sha` that can be derived from the git repo.

I'm working on something that (if deployed to production) will generate significant listing traffic that will be run client-side and so caching can't easily be shared and want to make sure services can support the load (and are willing to receive it). I'm currently using unpkg's `?meta` flag to achieve this but have noticed intermittent 500s.

It should also be noted, that I have no intention of listing files on 'abstract' versions and always first resolve the 'canonical' url for a given resource. (I do this by requesting the `package.json` on the 'abstract' version).

**Comment by MartinKolarik** [comment]
Hi - some additional context:

You are right that file listings are suitable for caching, we just didn't want to do that directly at origin level. From the beginning, our goal was keeping the origin as simple as possible to reduce potential points of failure. It's also why each server works entirely on its own and doesn't share any cache/storage directly with other servers (with one exception not important in this case).

The API uses redis to permanently store all listings, so for any previously requested package version, it's very fast. For new packages/versions, it gets the listing from the CDN. Is also sits behind Cloudflare, which caches all package listings for one year.

This design ensures that the API can handle a large amount of traffic and the only problematic scenarios are:
 - requesting a huge amount of listings which aren't cached in redis at the same time - but in this case, the bottleneck will be the CDN,
 - problems with the redis server or the [API cloud](https://clever-cloud.com) - unlike origin, it doesn't run in multiple datacenters - this is mostly the reason why we don't claim 100% availability, but it still runs completely fine most of the time.

Give it a try and ping me anytime if there are any issues or you have questions.

**Comment by MartinKolarik** [comment]
Btw, I checked our Cloudflare stats for jsdelivr.com now - it includes both data.jsdelivr.com (API) and jsdelivr.com (website) so I can't say exactly what part of it is just the API, but:
 - CF served 520M requests
 - our API servers got 73M requests, of which 70M were not cachable by CF (unlike listings); for cacheable requests, the CDN cache hit rate was 99.4%
 - our website servers got 3.2M requests

**Comment by ggoodman** [comment]
Thanks for the feedback @MartinKolarik, I will indeed take it for a spin and let you know if there are problems. I'm closing the issue because I don't think there is anything actionable left.
