### ISSUE TITLE
CDN does not update content for version range in MinnoJS

### ISSUE THREAD

**Issue by eladzlot** [jsdelivr/jsdelivr#18138]
First of all, thanks for this amazing project - you're doing some fantastic work here.

We are using a version range to access a file in minnojs:
https://cdn.jsdelivr.net/gh/minnojs/minno-quest@0.2/dist/pi-minno.js

We requested and received the purge url, but despite an attempt to purge, and two weeks that have passed since the last release (0.2.30) the url is still pointing at version 0.2.28 instead of 0.2.30

The direct link is working properly:
https://cdn.jsdelivr.net/gh/minnojs/minno-quest@0.2.30/dist/pi-minno.js

Any idea why this would be happening?

**Comment by MartinKolarik** [comment]
Hi, you have an actual release "v0.2" [here](https://github.com/minnojs/minno-quest/releases) so "0.2" is interpreted as that specific release and not "latest in 0.2.x".

The best solution is probably making a new 0.3.0 release and using `@0.3` in the link.

**Comment by eladzlot** [comment]
Works perfectly. Thank you.
