### ISSUE TITLE
please fix this

### ISSUE THREAD

**Issue by rpeveri** [jsdelivr/jsdelivr#18137]
First of all thank you very much for the incredible service they give. greetings and thanks again

https://cdn.jsdelivr.net/wp/themes/innofit/images/testimonial-bg.jpg

Not Found

The requested URL /innofit/images/testimonial-bg.jpg was not found on this server.
Apache/2.4.25 (Debian) Server at themes.svn.wordpress.org Port 80

**Comment by MartinKolarik** [comment]
The URL is missing version of the theme: https://cdn.jsdelivr.net/wp/themes/innofit/1.0.2/images/testimonial-bg.jpg
