### ISSUE TITLE
Long module contents truncated

### ISSUE THREAD

**Issue by tmcw** [jsdelivr/jsdelivr#18131]
Hi,

We're happily using jsdelivr with [Observable](https://beta.observablehq.com/) and today noticed an issue with the `lodash` package that might affect other packages as well. The module’s entry point:

https://cdn.jsdelivr.net/npm/lodash@4.17.11/lodash.js

Is truncated, when delivered through jsDelivr. The final lines are

```
    /**
     * Creates a clone of  `buffer`.
     *
     * @private
     * @param {Buffer} buffer The buffer to clone.
     * @param {boolean} [isDeep] Specify a deep clone.
     * @returns {Buffer} Returns the cloned buffer.
     */
    function cloneBuffer(buffer, isDeep) {
      if (isDeep) {
        return buffer.slice();
      }
      var length = buffer.length,
          result = allocUnsafe ?
```

And then it simply ends, leaving clients with an invalid script. Compare to the [unpkg URL for the same resource](https://unpkg.com/lodash@4.17.11/lodash.js), and the file continues past that point.

Thanks for any help, and happy to provide additional information.

**Comment by MartinKolarik** [comment]
Please try now.

**Comment by cedx** [comment]
Same problem here:
https://cdn.jsdelivr.net/npm/@sab-international/rich-text-editor@1/build/editor.js => truncated contents
https://cdn.jsdelivr.net/npm/@sab-international/rich-text-editor@1.2.0/build/editor.js => contents is OK

**Comment by MartinKolarik** [comment]
@cedx please try now.

**Comment by cedx** [comment]
Thanks @MartinKolarik : now the contents is up to date.

**Comment by MartinKolarik** [comment]
Thanks for the reports. CDN servers in some locations cached an incomplete file (in my case both files were ok). We're currently investigating why this happened.

**Comment by 1player** [comment]
Also this is truncated: https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js

**Comment by MartinKolarik** [comment]
@1player check now

**Comment by Mustack** [comment]
I've had reports today from users that https://cdn.jsdelivr.net/gh/Kandy-IO/kandy-link-js-sdk@v3.1.0/dist/kandy.js has been truncated but right now it's working well for me. I'm worried that maybe some caches have an incomplete version. Could you please purge this one for me?

**Comment by MartinKolarik** [comment]
@Mustack done. We'll be deploying a (hopefully) permanent fix for this tomorrow.

**Comment by ivuorinen** [comment]
Hi there!

I just noticed ApexCharts are experiencing the same problem.
I opened an issue in their repository, but this looks like the place where it should belong.

https://github.com/apexcharts/apexcharts.js/issues/354

Any news why this happened?

**Comment by MartinKolarik** [comment]
@ivuorinen purged and should be ok now. We deployed a possible fix for this yesterday evening, not sure yet if this happened before or after that.

**Comment by ivuorinen** [comment]
Thank you!

**Comment by MartinKolarik** [comment]
In case anyone else has this issue, please paste all headers from the response here in addition to the URL.

**Comment by iagox86** [comment]
I'm running into this issue on this page:

https://cdn.jsdelivr.net/npm/cytoscape@3.4.2/dist/cytoscape.min.js

It ends with:

```
...t){var n=t._private.aniEles,r=[];function i(t,n){var i=t._private,a=i.animation.
```

Here's the headers, as requested:

```
$ curl --head 'https://cdn.jsdelivr.net/npm/cytoscape@3.4.2/dist/cytoscape.min.js'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: *
Timing-Allow-Origin: *
Cache-Control: public, max-age=31536000, s-maxage=31536000, immutable
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Type: application/javascript; charset=utf-8
ETag: W/"20000-zYT2gnQctjhx6XuoKNpIwb+D5FM"
Content-Length: 131072
Accept-Ranges: bytes
Date: Sat, 18 May 2019 23:11:31 GMT
Connection: keep-alive
X-Served-By: cache-ams21027-AMS, cache-dfw18642-DFW
X-Cache: HIT, HIT
Vary: Accept-Encoding
```

I'm not involved with the cytoscape project, but instead I'm using it as a dependency and it's broken (for me).

**Comment by MartinKolarik** [comment]
@iagox86 please check now.

**Comment by iagox86** [comment]
Verified, it's fixed and working. Thanks for the super fast turnaround!

**Comment by jtiser** [comment]
Hello,

Running this issue on this page:  https://cdn.jsdelivr.net/npm/vue@2.6.7/dist/vue.js 

I currently don't have the headers

**Comment by MartinKolarik** [comment]
@jtiser should be ok now.
