### ISSUE TITLE
Statistics of hits is broken for sweetalert2

### ISSUE THREAD

**Issue by limonte** [jsdelivr/jsdelivr#18133]
Something has happened to the calculation of CDN hits.

https://data.jsdelivr.com/v1/package/npm/sweetalert2/stats/month

![image](https://user-images.githubusercontent.com/6059356/52940968-742d7280-3370-11e9-8e31-9e225b053518.png)

Expected values are the same as on previous days

**Comment by MartinKolarik** [comment]
The stats processing service has fallen behind a bit past few days. We doubled its hardware yesterday evening and expect it to process most of the existing logs today.

**Comment by limonte** [comment]
It seems like stats are being processed correctly now, closing this issue.

**Comment by limonte** [comment]
The same issue:

![image](https://user-images.githubusercontent.com/6059356/55151224-709ebf80-5156-11e9-88d1-11050fe88fbf.png)

**Comment by MartinKolarik** [comment]
There were some issues with log processing again, the service should catch up within a few days.

**Comment by MartinKolarik** [comment]
Back to normal now.
