### ISSUE TITLE
Allow JSONpath expressions

### ISSUE THREAD

**Issue by ghost** [jsdelivr/jsdelivr#18130]
Please add JSONpath expression syntax to jsDelivr enabling individuals to find even more value in this service by making it their canonical link destination for JSONpath expressions.

JSONpath fork with better semantics: https://github.com/livereach/jsonpath
Example JSONpath used by shields.io to produce a dynamic image: https://img.shields.io/badge/dynamic/json.svg?url=https://git.habd.as/comfusion/toxic-swamp/raw/branch/master/package.json&label=after%20dark&query=$..['after-dark']&colorB=000000&style=for-the-badge&longCache=false&maxAge=86400

Why do this? So individuals can add `softwareRequirements` to their [`SoftwareApplication`](https://schema.org/SoftwareApplication) structured data, e.g.:

```html
<link itemprop="softwareRequirements" href="jsdelivr-jsonpath-url">
```

**Comment by MartinKolarik** [comment]
Hi @ghost, I'm not familiar with jsonpath, can you explain better what you're asking for?
