### ISSUE TITLE
Hosting a CSS framework on JSDelivr?

### ISSUE THREAD

**Issue by GiacomoLaw** [jsdelivr/jsdelivr#18141]
Hi all,

Anyone know how I can do this? Can't seem to find any guides, and am completely new to JSDelivr.

Thanks in advance!

**Comment by MartinKolarik** [comment]
Just publish it to npm or GitHub: https://github.com/jsdelivr/jsdelivr#usage

**Comment by GiacomoLaw** [comment]
Awesome, thank you! Will try it out
