### ISSUE TITLE
502 Bad Gateway - cdn.jsdelivr.net

### ISSUE THREAD

**Issue by ashucg** [jsdelivr/jsdelivr#18142]
Getting **Bad Gateway** for some resources

![image](https://user-images.githubusercontent.com/11291284/55667177-5ea0d900-5848-11e9-894f-fed57a79fbfa.png)

**Comment by jimaek** [comment]
Looks like MaxCDN had a problem, I disabled them completely just in case until we find out what happened

**Comment by ashucg** [comment]
Thanks!

**Comment by jimaek** [comment]
Can you do a traceroute to this hostname?
jsdelivr3.dak.netdna-cdn.com

Also does this link work for you? https://cdn.jsdelivr.net/npm/jquery

**Comment by ashucg** [comment]
Here is the traceroute as you requested:
```
traceroute to jsdelivr3.dak.netdna-cdn.com (151.139.104.66), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.477 ms  0.422 ms  34.294 ms
 2  100.66.64.2 (100.66.64.2)  3.881 ms  4.209 ms  4.346 ms
 3  192.168.241.37 (192.168.241.37)  4.801 ms  4.887 ms  5.199 ms
 4  192.168.249.5 (192.168.249.5)  5.817 ms * *
 5  192.168.241.2 (192.168.241.2)  11.813 ms  13.765 ms  17.672 ms
 6  aes-static-125.34.144.59.airtel.in (59.144.34.125)  26.885 ms  13.916 ms  18.067 ms
 7  * * *
 8  151.139.58.3 (151.139.58.3)  137.437 ms  137.308 ms  137.477 ms
 9  151.139.58.8 (151.139.58.8)  136.315 ms 151.139.58.10 (151.139.58.10)  138.725 ms  138.574 ms
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```
I am now able to access the resources that were failing earlier on.

**Comment by jimaek** [comment]
Can you also tell me your IP address?

**Comment by ashucg** [comment]
My IP is `103.41.26.131`

**Comment by jimaek** [comment]
Thank you, MaxCDN confirmed the issue on their side in Hong Kong.
We will enable them back only after we make sure the issue was fixed 100%
