### ISSUE TITLE
Couldn't find the requested file

### ISSUE THREAD

**Issue by Tomotoes** [jsdelivr/jsdelivr#18140]
**Thank you very much for your help to the developers.**

My Github has uploaded the corresponding files
![image](https://user-images.githubusercontent.com/32236122/54811280-4b780000-4cc3-11e9-849d-c7527ddaa411.png)

However, when I requested the file, I was prompted as follows:
![image](https://user-images.githubusercontent.com/32236122/54811311-5d59a300-4cc3-11e9-8471-9007ecc7ae79.png)

`https://cdn.jsdelivr.net/gh/Tomotoes/blog/css/home-83012c2f82.css`
I am sure there are no mistakes in the link above.

Now, [my blog](https://tomotoes.com/blog) is no longer working properly.

[My corresponding project address](https://github.com/Tomotoes/blog/)

**Comment by Tomotoes** [comment]
`https://cdn.jsdelivr.net/gh/Tomotoes/blog/css/home-83012c2f82.css`
I am sure there are no mistakes in the link above.

Now, [my blog](tomotoes.com/blog) is no longer working properly.

**Comment by MartinKolarik** [comment]
I see you added that file shortly before opening this issue. When using `@master` URLs, it may take several hours for new files to be available.

**Comment by Tomotoes** [comment]
Thank you for your answer. I have already solved this problem.
I wrote a version control script that automatically updates the version number of the file every time it is updated.
