### ISSUE TITLE
CDN certificate expired in China

### ISSUE THREAD

**Issue by NimaQu** [jsdelivr/jsdelivr#18147]
![9G XEYT6)R1LT2P_Q`U6Q9F](https://user-images.githubusercontent.com/26685881/56450155-bb76b600-6355-11e9-83ef-08e0aa077ad2.png)

**Comment by paraself** [comment]
Same

**Comment by jr-november** [comment]
Top

**Comment by jsdtxsx** [comment]
Same

**Comment by jsjzh** [comment]
me too

**Comment by paraself** [comment]
Out site is down, customers are complaining...

**Comment by jsdtxsx** [comment]
wake up！wake up！

**Comment by lincanli** [comment]
please, fix this

**Comment by hifocus** [comment]
Please do fix this ASAP...

**Comment by abc1763613206** [comment]
fix plz

**Comment by easychen** [comment]
waiting  ...

**Comment by jr-november** [comment]
> wake up！wake up！

wake up!

**Comment by zlzdp** [comment]
help!

**Comment by dadianzi** [comment]
help!!!

**Comment by 4tj** [comment]
help

**Comment by paizi** [comment]
I use jsdelivr on all my projects, so you know...

**Comment by Ruikoto** [comment]
same,help!!!

**Comment by xieqiqiang00** [comment]
Websites prove their identity via certificates, which are valid for a set time period. The certificate for cdn.jsdelivr.net appears to be expired. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by anthinkingcoder** [comment]
help me

**Comment by kasuganosoras** [comment]
现在一大堆网站排版都炸了，GG

**Comment by taoliujun** [comment]
it's too bad. 100+ website were broken because jsdelivr cdn ssl expired. just in China?

**Comment by yoyo837** [comment]
Has quickly switched to unpkg.

**Comment by taoliujun** [comment]
i resolved it, just replace `https` to `http`. but http could be hack by DNS.

**Comment by beijibingdong** [comment]
用这个的都炸了吧。。。

**Comment by jsdtxsx** [comment]
> 用这个的都炸了吧。。。

我们已经换了

**Comment by paizi** [comment]
> i resolved it, just replace `https` to `http`. but http could be hack by DNS.

cdn.jsdelivr.net has been hsts preload. Your browser not support hsts preload?

**Comment by paraself** [comment]
Is it working correctly right now? Mine seems to be ok now.

**Comment by kasuganosoras** [comment]
截至目前仍然还是不可用的状态
![img](https://i.imgur.com/6O1XoPE.png)

**Comment by paizi** [comment]
> Is it working correctly right now? Mine seems to be ok now.

Still have problems.

**Comment by paraself** [comment]
Stopped working again....

**Comment by jr-november** [comment]
finally
