### ISSUE TITLE
CDN Certificate Expired

### ISSUE THREAD

**Issue by Alan-Liang** [jsdelivr/jsdelivr#18145]
The CDN Cert has expired on 2019/4/20 GMT+8 7:59:59 AM, while the time now is 09:21 AM. All files couldn't be loaded because of HSTS. This issue is caused by WangSu, and mainly affects China and surrounding areas. The cert is:
```
-----BEGIN CERTIFICATE-----
MIIFVjCCBD6gAwIBAgIRALV/mjO4Y/LljJrgbLAT9bMwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTQwNDIwMDAwMDAwWhcNMTkwNDE5MjM1OTU5WjBUMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAsTC1Bvc2l0aXZlU1NMMRkw
FwYDVQQDExBjZG4uanNkZWxpdnIubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAyC3cxzneQ4nyC+F0krIGfi1EkjRx+FEa0Uxae+395mPAqoYlGB12
8E3Oz4qFaHwVqFd/SWzxKQAdJf6qManzmtf3JlAH8R0UYHzYhWbaFzicwYOK0kQm
tfktblxXj8Ftr+IvRR9uJ6OyjwgE7zsXFhhkqsizTANX08wTsDYTFlw+NbT7OseP
l6wKh71i2IbN5P+VE+tlBzrQXGur9nXaQptiV+UN226YeC+qdvdBGHJWzmqkjwgM
At+2CX8ckD32pwAbg/mvJt1co7hnFm8LR+/uDNwFFo5xtssVinozcl6Z/44TOAsB
hf5lBezgTBwXPEiZ30PhoZmjH2lZhEOdrwIDAQABo4IB5DCCAeAwHwYDVR0jBBgw
FoAUkK9qOpRaC9iQ6hJWc99DtDoo2ucwHQYDVR0OBBYEFA+It8osORm8/NIdBm2K
dD0f9yMJMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQG
CCsGAQUFBwMBBggrBgEFBQcDAjBQBgNVHSAESTBHMDsGDCsGAQQBsjEBAgEDBDAr
MCkGCCsGAQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8ubmV0L0NQUzAIBgZn
gQwBAgEwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5jb21vZG9jYS5jb20v
Q09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNybDCBhQYI
KwYBBQUHAQEEeTB3ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LmNvbW9kb2NhLmNv
bS9DT01PRE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCQG
CCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wMQYDVR0RBCowKIIQ
Y2RuLmpzZGVsaXZyLm5ldIIUd3d3LmNkbi5qc2RlbGl2ci5uZXQwDQYJKoZIhvcN
AQELBQADggEBADwjPKnofDPqn6iftqhA/IO1+rT4gxiJgOwa4r6mjjSUhmspV56j
wvenEXp5WAwT+06aFfeXvlPHDKpHIKhqvPdFcFNnIRwRYnelhpWUlBNAvMIdR24u
NYcDm/8W5/GVUxhBm3XL2QXKHJjXsYjq0/SAq1enSkb1XmelQQN8ki9hNzPByJFv
y7PTW3lsYHw41qE2N599/Fjc9SGj/mCsT2QT0HFrzongqMTs/aM2FJb3nG/i2SHu
+xW3ECve1JCK23ix7mGu7mcLAuiOvKMXpDstkDKpacg6VUnmMD+PScIXb+jn80up
9Tsi650LXkGxPaZkwMGW9othYrlH2mzsXPQ=
-----END CERTIFICATE-----
```

**Comment by lucasleelz** [comment]
Yes, expired, huge pit, and still weekend

**Comment by wangzhilongh** [comment]
disaster

**Comment by wangzhilongh** [comment]
disaster

**Comment by abc1763613206** [comment]
disaster

**Comment by elevenLianm** [comment]
disaster

**Comment by mrsai** [comment]
What a pity！

**Comment by paraself** [comment]
disaster!!!!!

**Comment by badboy-tian** [comment]
disaster!!!!!

**Comment by jr-november** [comment]
你们怎么处理的

**Comment by Alan-Liang** [comment]
@jr-november 紧急更换呗 npm的话unpkg能解决 gh上的话用rawgit暂时用一下吧……虽然被墙了

**Comment by MinecraftFuns** [comment]
NET::ERR_CERT_DATE_INVALID

Subject: cdn.jsdelivr.net

Issuer: COMODO RSA Domain Validation Secure Server CA

Expires on: 2019年4月20日

Current date: 2019年4月20日

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIFVjCCBD6gAwIBAgIRALV/mjO4Y/LljJrgbLAT9bMwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTQwNDIwMDAwMDAwWhcNMTkwNDE5MjM1OTU5WjBUMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAsTC1Bvc2l0aXZlU1NMMRkw
FwYDVQQDExBjZG4uanNkZWxpdnIubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAyC3cxzneQ4nyC+F0krIGfi1EkjRx+FEa0Uxae+395mPAqoYlGB12
8E3Oz4qFaHwVqFd/SWzxKQAdJf6qManzmtf3JlAH8R0UYHzYhWbaFzicwYOK0kQm
tfktblxXj8Ftr+IvRR9uJ6OyjwgE7zsXFhhkqsizTANX08wTsDYTFlw+NbT7OseP
l6wKh71i2IbN5P+VE+tlBzrQXGur9nXaQptiV+UN226YeC+qdvdBGHJWzmqkjwgM
At+2CX8ckD32pwAbg/mvJt1co7hnFm8LR+/uDNwFFo5xtssVinozcl6Z/44TOAsB
hf5lBezgTBwXPEiZ30PhoZmjH2lZhEOdrwIDAQABo4IB5DCCAeAwHwYDVR0jBBgw
FoAUkK9qOpRaC9iQ6hJWc99DtDoo2ucwHQYDVR0OBBYEFA+It8osORm8/NIdBm2K
dD0f9yMJMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQG
CCsGAQUFBwMBBggrBgEFBQcDAjBQBgNVHSAESTBHMDsGDCsGAQQBsjEBAgEDBDAr
MCkGCCsGAQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8ubmV0L0NQUzAIBgZn
gQwBAgEwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5jb21vZG9jYS5jb20v
Q09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNybDCBhQYI
KwYBBQUHAQEEeTB3ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LmNvbW9kb2NhLmNv
bS9DT01PRE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCQG
CCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wMQYDVR0RBCowKIIQ
Y2RuLmpzZGVsaXZyLm5ldIIUd3d3LmNkbi5qc2RlbGl2ci5uZXQwDQYJKoZIhvcN
AQELBQADggEBADwjPKnofDPqn6iftqhA/IO1+rT4gxiJgOwa4r6mjjSUhmspV56j
wvenEXp5WAwT+06aFfeXvlPHDKpHIKhqvPdFcFNnIRwRYnelhpWUlBNAvMIdR24u
NYcDm/8W5/GVUxhBm3XL2QXKHJjXsYjq0/SAq1enSkb1XmelQQN8ki9hNzPByJFv
y7PTW3lsYHw41qE2N599/Fjc9SGj/mCsT2QT0HFrzongqMTs/aM2FJb3nG/i2SHu
+xW3ECve1JCK23ix7mGu7mcLAuiOvKMXpDstkDKpacg6VUnmMD+PScIXb+jn80up
9Tsi650LXkGxPaZkwMGW9othYrlH2mzsXPQ=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIGCDCCA/CgAwIBAgIQKy5u6tl1NmwUim7bo3yMBzANBgkqhkiG9w0BAQwFADCB
hTELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKzApBgNV
BAMTIkNPTU9ETyBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMjEy
MDAwMDAwWhcNMjkwMjExMjM1OTU5WjCBkDELMAkGA1UEBhMCR0IxGzAZBgNVBAgT
EkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMR
Q09NT0RPIENBIExpbWl0ZWQxNjA0BgNVBAMTLUNPTU9ETyBSU0EgRG9tYWluIFZh
bGlkYXRpb24gU2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAI7CAhnhoFmk6zg1jSz9AdDTScBkxwtiBUUWOqigwAwCfx3M28Sh
bXcDow+G+eMGnD4LgYqbSRutA776S9uMIO3Vzl5ljj4Nr0zCsLdFXlIvNN5IJGS0
Qa4Al/e+Z96e0HqnU4A7fK31llVvl0cKfIWLIpeNs4TgllfQcBhglo/uLQeTnaG6
ytHNe+nEKpooIZFNb5JPJaXyejXdJtxGpdCsWTWM/06RQ1A/WZMebFEh7lgUq/51
UHg+TLAchhP6a5i84DuUHoVS3AOTJBhuyydRReZw3iVDpA3hSqXttn7IzW3uLh0n
c13cRTCAquOyQQuvvUSH2rnlG51/ruWFgqUCAwEAAaOCAWUwggFhMB8GA1UdIwQY
MBaAFLuvfgI9+qbxPISOre44mOzZMjLUMB0GA1UdDgQWBBSQr2o6lFoL2JDqElZz
30O0Oija5zAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwGwYDVR0gBBQwEjAGBgRVHSAAMAgG
BmeBDAECATBMBgNVHR8ERTBDMEGgP6A9hjtodHRwOi8vY3JsLmNvbW9kb2NhLmNv
bS9DT01PRE9SU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDBxBggrBgEFBQcB
AQRlMGMwOwYIKwYBBQUHMAKGL2h0dHA6Ly9jcnQuY29tb2RvY2EuY29tL0NPTU9E
T1JTQUFkZFRydXN0Q0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21v
ZG9jYS5jb20wDQYJKoZIhvcNAQEMBQADggIBAE4rdk+SHGI2ibp3wScF9BzWRJ2p
mj6q1WZmAT7qSeaiNbz69t2Vjpk1mA42GHWx3d1Qcnyu3HeIzg/3kCDKo2cuH1Z/
e+FE6kKVxF0NAVBGFfKBiVlsit2M8RKhjTpCipj4SzR7JzsItG8kO3KdY3RYPBps
P0/HEZrIqPW1N+8QRcZs2eBelSaz662jue5/DJpmNXMyYE7l3YphLG5SEXdoltMY
dVEVABt0iN3hxzgEQyjpFv3ZBdRdRydg1vs4O2xyopT4Qhrf7W8GjEXCBgCq5Ojc
2bXhc3js9iPc0d1sjhqPpepUfJa3w/5Vjo1JXvxku88+vZbrac2/4EjxYoIQ5QxG
V/Iz2tDIY+3GH5QFlkoakdH368+PUq4NCNk+qKBR6cGHdNXJ93SrLlP7u3r7l+L4
HyaPs9Kg4DdbKDsx5Q5XLVq4rXmsXiBmGqW5prU5wfWYQ//u+aen/e7KJD2AFsQX
j4rBYKEMrltDR5FL1ZoXX/nUh8HCjLfn4g8wGTeGrODcQgPmlKidrv0PJFGUzpII
0fxQ8ANAe4hZ7Q7drNJ3gjTcBpUC2JD5Leo31Rpg0Gcg19hCC0Wvgmje3WYkN5Ap
lBlGGSW4gNfL1IYoakRwJiNiqZ+Gb7+6kHDSVneFeO/qJakXzlByjAA6quPbYzSf
+AZxAeKCINT+b72x
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIF2DCCA8CgAwIBAgIQTKr5yttjb+Af907YWwOGnTANBgkqhkiG9w0BAQwFADCB
hTELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKzApBgNV
BAMTIkNPTU9ETyBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTAwMTE5
MDAwMDAwWhcNMzgwMTE4MjM1OTU5WjCBhTELMAkGA1UEBhMCR0IxGzAZBgNVBAgT
EkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMR
Q09NT0RPIENBIExpbWl0ZWQxKzApBgNVBAMTIkNPTU9ETyBSU0EgQ2VydGlmaWNh
dGlvbiBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCR
6FSS0gpWsawNJN3Fz0RndJkrN6N9I3AAcbxT38T6KhKPS38QVr2fcHK3YX/JSw8X
pz3jsARh7v8Rl8f0hj4K+j5c+ZPmNHrZFGvnnLOFoIJ6dq9xkNfs/Q36nGz637CC
9BR++b7Epi9Pf5l/tfxnQ3K9DADWietrLNPtj5gcFKt+5eNu/Nio5JIk2kNrYrhV
/erBvGy2i/MOjZrkm2xpmfh4SDBF1a3hDTxFYPwyllEnvGfDyi62a+pGx8cgoLEf
Zd5ICLqkTqnyg0Y3hOvozIFIQ2dOciqbXL1MGyiKXCJ7tKuY2e7gUYPDCUZObT6Z
+pUX2nwzV0E8jVHtC7ZcryxjGt9XyD+86V3Em69FmeKjWiS0uqlWPc9vqv9JWL7w
qP/0uK3pN/u6uPQLOvnoQ0IeidiEyxPx2bvhiWC4jChWrBQdnArncevPDt09qZah
SL0896+1DSJMwBGB7FY79tOi4lu3sgQiUpWAk2nojkxl8ZEDLXB0AuqLZxUpaVIC
u9ffUGpVRr+goyhhf3DQw6KqLCGqR84onAZFdr+CGCe01a60y1Dma/RMhnEw6abf
Fobg2P9A3fvQQoh/ozM6LlweQRGBY84YcWsr7KaKtzFcOmpH4MN5WdYgGq/yapiq
crxXStJLnbsQ/LBMQeXtHT1eKJ2czL+zUdqnR+WEUwIDAQABo0IwQDAdBgNVHQ4E
FgQUu69+Aj36pvE8hI6t7jiY7NkyMtQwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB
/wQFMAMBAf8wDQYJKoZIhvcNAQEMBQADggIBAArx1UaEt65Ru2yyTUEUAJNMnMvl
wFTPoCWOAvn9sKIN9SCYPBMtrFaisNZ+EZLpLrqeLppysb0ZRGxhNaKatBYSaVqM
4dc+pBroLwP0rmEdEBsqpIt6xf4FpuHA1sj+nq6PK7o9mfjYcwlYRm6mnPTXJ9OV
2jeDchzTc+CiR5kDOF3VSXkAKRzH7JsgHAckaVd4sjn8OoSgtZx8jb8uk2Intzna
FxiuvTwJaP+EmzzV1gsD41eeFPfR60/IvYcjt7ZJQ3mFXLrrkguhxuhoqEwWsRqZ
CuhTLJK7oQkYdQxlqHvLI7cawiiFwxv/0Cti76R7CZGYZ4wUAc1oBmpjIXUDgIiK
boHGhfKppC3n9KUkEEeDys30jXlYsQab5xoq2Z0B15R97QNKyvDb6KkBPvVWmcke
jkk9u+UJueBPSZI9FoJAzMxZxuY67RIuaTxslbH9qh17f4a+Hg4yRvv7E491f0yL
S0Zj/gA0QHDBw7mh3aZw4gSzQbzpgJHqZJx64SIDqZxubw5lT2yHh17zbqD5daWb
QOhTsiedSrnAdyGN/4fy3ryM7xfft0kL0fJuMAsaDk527RH89elWsn2/x20Kk4yl
0MC2Hb46TpSi125sC8KKfPog88Tk5c0NqMuRkrF8hey1FGlmDoLnzc7ILaZRfyHB
NVOFBkpdn627G190
-----END CERTIFICATE-----

**Comment by MinecraftFuns** [comment]
那js呢

**Comment by aliglelo** [comment]
yes i also have reported this issue for pakistan

**Comment by MinecraftFuns** [comment]
还有这是中国的问题还是全球的问题

**Comment by yoyo837** [comment]
Has quickly switched to unpkg.

**Comment by yoyo837** [comment]
@MinecraftFuns 有日本和巴基斯坦的网友说也遇到了

**Comment by beijibingdong** [comment]
> 还有这是中国的问题还是全球的问题

证书过期，应该是全球性的

**Comment by Alan-Liang** [comment]
@MinecraftFuns @beijibingdong 网宿的锅，中国及周边都受影响

**Comment by jimaek** [comment]
I am really sorry about this, it has now been fixed.

**Comment by abc1763613206** [comment]
> I am really sorry about this, it has now been fixed.

happy about that

**Comment by liub1934** [comment]
it's ok now

**Comment by ehaaaaaaaaa** [comment]
ERR_CERT_COMMON_NAME_INVALID

hi, receive above error from cdn.jsdelivr.net. please help
