### ISSUE TITLE
SSL Certificate Expired on Quantil in China

### ISSUE THREAD

**Issue by brentybh** [jsdelivr/jsdelivr#18146]
The SSL certificate used on Quantil in China expired today.
The certificate infomation:
https://censys.io/certificates/8ae6787465ba0b7a7dc94eec50b90f9d322443cdaa547cb81ae44f17e9c81dee

**Comment by brentybh** [comment]
Not only in China.

 * Quantil (EXPIRED)
 * Fastly ([certificate](https://censys.io/certificates/4b0f6ec09e1a54069be2909f26d0cc3e5292ed7f6338c6cfa27d3fb61ad0de29) will expire in a week)
 * Cloudflare (auto-renewed)
 * CDNetworks (EXPIRED)

**Comment by xiaohuilam** [comment]
it seems that fastly cert will auto renew, because it's a cdn supplier hosted cert.

**Comment by jimaek** [comment]
I am really sorry about this, it has now been fixed.

**Comment by uxiaohan** [comment]
cdn.jsdelivr.net中国大陆多地显示证书错误

**Comment by 89trillion-feiyang** [comment]
expired again

**Comment by sdaylee** [comment]
expired again

**Comment by SAKURAFLY0910** [comment]
中国cdn证书似乎过期了

**Comment by uxiaohan** [comment]
看一下证书，是颁发给 default.chinanetcenter.com
