### ISSUE TITLE
File size incorrectly reported

### ISSUE THREAD

**Issue by IbrahimTanyalcin** [jsdelivr/jsdelivr#18143]
I have some an example file here: 

`https://github.com/IbrahimTanyalcin/lexicon-mono-seq/tree/master/datasets`

the files are capped at 40MB, however if I try to request one of them like this:

`https://cdn.jsdelivr.net/gh/IbrahimTanyalcin/lexicon-mono-seq/datasets/hs_ref_GRCh38.p12_chrX_part4`

I will get:
> Package size exceeded the configured limit of 50 MB. Try https://github.com/IbrahimTanyalcin/lexicon-mono-seq/tree/v0.15.12/datasets/hs_ref_GRCh38.p12_chrX_part4 instead.

Anything I am missing?

**Comment by MartinKolarik** [comment]
Package size means the whole release. We are also able to load individual files but the limit there is 20 MB. When that fails, the server tries to get the whole package, but that exceeds the 50 MB limit.

**Comment by IbrahimTanyalcin** [comment]
Aha, I see it, so I truncate them at ~20Mb then. Let's say I have 10 19Mb files, now I presume the request would not return 503 because the package size is not checked. Correct?

**Comment by MartinKolarik** [comment]
Yes.

**Comment by IbrahimTanyalcin** [comment]
Okii, I'm closing this issue.
