### ISSUE TITLE
cdn.jsdelivr.net returning 404 on previously available resources

### ISSUE THREAD

**Issue by crdnl** [jsdelivr/jsdelivr#18150]
I started receiving complaints that the following resource is not connecting.
https://cdn.jsdelivr.net/npm/semantic-ui@2.3.1/dist/semantic.min.js

Running `nslookup` on `cdn.js.delivr.com` returns `dualstack.f3.shared.global.fastly.net`.

**Comment by MartinKolarik** [comment]
The title says `.net` but in the text you say `.com`. Are you actually using the correct domain?

**Comment by crdnl** [comment]
Sorry, typing mistake. Should be `cdn.jsdelivr.net`. Either way, it's still not connecting.

**Comment by jimaek** [comment]
Can you provide the full HTTP headers from the response of that URL?

**Comment by crdnl** [comment]
It's working now. Wasn't for a solid 12+ hours.
