### ISSUE TITLE
Everything is the 17th most popular package on jsDelivr

### ISSUE THREAD

**Issue by Simonwep** [jsdelivr/jsdelivr#18156]
Why are all or most of the packages the 17th most populares :suspect: ?
See this [google search for the 17th most popular packages on jsDelivr](https://www.google.com/search?q=%22is+the+17th+most+popular+package+on+jsDelivr%22&oq=%22is+the+17th+most+popular+package+on+jsDelivr%22&aqs=chrome..69i57.823j0j4&sourceid=chrome&ie=UTF-8).

There are part-wise cdn-hit differences around hundredths of millions...

**Comment by MartinKolarik** [comment]
Thanks for reporting.
