### ISSUE TITLE
PerfOps rum.js issue

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18153]
I don't know where this issue should report, so I open this issue here.

I added `rum3.min.js` tp my website using the code below:

```html
<script>
     // load rum after the page is loaded to avoid performance issue because rum.perfops.net is very slow in China
    (function () {
        function perfops() {
            var js = document.createElement('script');
            js.src = 'https://rum.perfops.net/rum3.min.js';
            document.body.appendChild(js);
        }

        if (document.readyState === 'complete') {
            perfops();
        } else {
            window.addEventListener('load', perfops);
        }
    })();
</script>
```

But the RUM didn't work.

In `https://rum.perfops.net/rum3.js` I found this:

```javascript
  window.addEventListener('load', function () {
    if (typeof window.performance === 'undefined') {
      return;
    }

    if (typeof Promise === 'function') {
      return run();
    }

    fetchJs('https://cdn.jsdelivr.net/npm/es6-promise@4.2.4/dist/es6-promise.min.js', function () {
      Promise = window.ES6Promise;
      run();
    });
  });
```

The lib only add listener to window, but doesn't check whether window is already loaded.

**Comment by MartinKolarik** [comment]
The script already waits for load + 3 seconds so loading it like that is unnecessary.

**Comment by SukkaW** [comment]
@MartinKolarik The domain `rum.perfops.net` is very slow in China, and it just block the page's `onload` event, I have to try to load `rum3.min.js` after `load` event.

**Comment by MartinKolarik** [comment]
@jimaek that might be something for you to check.

@SukkaW  I updated the PerfOps code to work even in this case, a new version will be live shortly.

**Comment by SukkaW** [comment]
@MartinKolarik I have checked the `https://rum.perfops.net/rum3.js`, it has been updated. Now I only need to wait for `https://rum.perfops.net/rum3.min.js` cache expired.

By the way, why not publish `rum.min.js` to NPM and deliver through jsDelivr?

**Comment by MartinKolarik** [comment]
> By the way, why not publish rum.min.js to NPM and deliver through jsDelivr?

Good question. We might actually do that.

**Comment by MartinKolarik** [comment]
`<script async src="https://cdn.jsdelivr.net/npm/perfops-rom"></script>`

**Comment by jimaek** [comment]
I believe this is now fixed, Chinese performance should be great now

**Comment by SukkaW** [comment]
@jimaek Good to hear!
