### ISSUE TITLE
jsdelivr in script doesnt work

### ISSUE THREAD

**Issue by PeterHdd** [jsdelivr/jsdelivr#18155]
Hello,

Im trying to do the following:

    <script  type="module" src="https://cdn.jsdelivr.net/npm/date-filtersjs@1.0.0/filter/filter.min.js">
       let obj = [{"name":"peter"}];
       let filter = new Filter(obj);
       console.log(filter);
    </script>

But nothing appears in the console, while if I do the following:

    <script type="module">
         import { Filter } from 'https://cdn.jsdelivr.net/npm/date-filtersjs@1.0.0/filter/filter.min.js'
         let obj = [{"name":"peter"}];
         let filter = new Filter(obj);
         console.log(f);
    </script>

it works. Can someone explain why this is the case? I know it might be a silly question but it's been a while and I cannot find any explanation about this.

**Comment by MartinKolarik** [comment]
You can't have a `src` attribute and inline content on one `script` element:

```
<script type="module" src="https://cdn.jsdelivr.net/npm/date-filtersjs@1.0.0/filter/filter.min.js"</script>
<script type="module">
   let obj = [{"name":"peter"}];
   let filter = new Filter(obj);
   console.log(filter);
</script>
```
