### ISSUE TITLE
Console errors on multiple browsers

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jsdelivr/jsdelivr#18159]
I get multiple console errors similar to this and not sure how exactly to fix this. 
```
[Report Only] Refused to load the stylesheet 'https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

Any advice?

**Comment by MartinKolarik** [comment]
Change your CSP to allow the jsDelivr domain: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by abishekrsrikaanth** [comment]
Is this something new, does it have issues only to certain environments? I don't see these issues on local development environments.

**Comment by MartinKolarik** [comment]
Please read about how CSP works. This has nothing to with jsDelivr, it's an issue with the configuration of your web server/framework/... which sets the CSP policy.
