### ISSUE TITLE
Load private github repos

### ISSUE THREAD

**Issue by AdaptCharm** [jsdelivr/jsdelivr#18157]
Is there any documentation on how to use private github repositories?

**Comment by MartinKolarik** [comment]
Not possible at the moment. What would be the point of using a private repo if you make the files public on the CDN?

**Comment by AdaptCharm** [comment]
Say you want to make your `assets` folder public and serve the static files using jsdelivr.

**Comment by MartinKolarik** [comment]
> The way I'm doing it now is serving them using a different public repo.

That's probably the best way.

**Comment by AdaptCharm** [comment]
> > The way I'm doing it now is serving them using a different public repo.
> 
> That's probably the best way.

So there won't be support for this?

**Comment by MartinKolarik** [comment]
No, GitHub doesn't support anything like making a part of the repo public, so for this to work, you would have to give jsDelivr access to the full repo, and at that point, it may as well be a public repo.
