### ISSUE TITLE
No IPv6 on Stackpath

### ISSUE THREAD

**Issue by miyurusankalpa** [jsdelivr/jsdelivr#18163]
Maybe adding a IPv6 address to stackpath or not serving Stackpath for IPv6 will be the best idea. Current configuration breaks on IPv6 only clients.

```
Server:  one.one.one.one
Address:  2606:4700:4700::1111

Non-authoritative answer:
Name:    jsdelivr3.dak.netdna-cdn.com
Address:  151.139.107.233
Aliases:  cdn.jsdelivr.net
          jsdelivr.a7e454.flexbalancer.net
```

```
; <<>> DiG 9.10.3-P4-Debian <<>> cdn.jsdelivr.net aaaa @2606:4700:4700::1111
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40880
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;cdn.jsdelivr.net.              IN      AAAA

;; ANSWER SECTION:
cdn.jsdelivr.net.       41      IN      CNAME   jsdelivr.a7e454.flexbalancer.net.
jsdelivr.a7e454.flexbalancer.net. 5 IN  CNAME   jsdelivr3.dak.netdna-cdn.com.

;; AUTHORITY SECTION:
netdna-cdn.com.         612     IN      SOA     ns-97.awsdns-12.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 91 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111)
;; WHEN: Tue Jul 23 16:16:13 +0530 2019
;; MSG SIZE  rcvd: 221
```

**Comment by jimaek** [comment]
Hey, this is an interesting idea and we will have to look into it more closely internally. Thank you!

**Comment by ikomwrestling** [comment]
Hi, any update regarding IPv6 support for cdn.jsdelivr.net?

For reference, Jquery also uses StackPath, and they recently enabled IPv6 for their CDN endpoint (code.jquery.com).

Thank you.

**Comment by miyurusankalpa** [comment]
@ikomwrestling there is already support for IPv6 on cdn.jsdelivr.net, for most the users. It is only the stackpath domain that is missing AAAA records.

This issue has led me to not use jsdelivr cdn on my new projects as this breaks the sites for IPv6 only clients.

**Comment by jimaek** [comment]
Hey all, I am talking with them about enabling Ipv6. I will keep you posted

**Comment by ikomwrestling** [comment]
Hi @jimaek , any update about IPv6 on stackpath?

**Comment by jimaek** [comment]
We are still on their maxcdn system which doesn't have it and they have no plans to migrate us to their stackpath system. So this might take a while

**Comment by jimaek** [comment]
Closing since we stopped using stackpath a while ago.
