### ISSUE TITLE
Last Modified displays wrong date/time

### ISSUE THREAD

**Issue by GordonSmith** [jsdelivr/jsdelivr#18169]
![image](https://user-images.githubusercontent.com/966863/62851011-a21ac080-bcdc-11e9-92df-7585407abecf.png)

Looks like some generic default?

**Comment by MartinKolarik** [comment]
See https://github.com/npm/npm/pull/20027#discussion_r173985677

**Comment by GordonSmith** [comment]
Hmm interesting - might be better to not show it all then?  Perhaps replace it with the "gzip size"?

**Comment by MartinKolarik** [comment]
Yes, I only learned about this yesterday and was thinking we should probably stop showing them.

**Comment by wesinator** [comment]
I also noticed this - https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/
