### ISSUE TITLE
Wrong default file for package ulid

### ISSUE THREAD

**Issue by thangngoc89** [jsdelivr/jsdelivr#18166]
I requested package info using this link:

https://data.jsdelivr.com/v1/package/npm/ulid@2.3.0/flat

It returns `default: "/dist/index.umd.min.js"`

And it's a wrong file. I checked `package.json` and it doesn't contains any mentions of that particular file:

https://unpkg.com/ulid@2.3.0/package.json

![image](https://user-images.githubusercontent.com/3049054/62426272-c3901100-b70c-11e9-9599-1c4661afcc5f.png)

**Comment by MartinKolarik** [comment]
As per our docs, default file is always minified. It's generated from the unminified file.

**Comment by thangngoc89** [comment]
Ah I see. I was checking in `files` field before hitting jsdelivr endpoint. Thank you for your response

**Comment by MartinKolarik** [comment]
https://cdn.jsdelivr.net/npm/ulid@2.3.0/dist/index.umd.min.js

**Comment by thangngoc89** [comment]
@MartinKolarik I'm aware of that. That I'm saying is that my application check `files` field before hitting jsdelivr to avoid extra requests. I'll handle this edge case.
