### ISSUE TITLE
"antd" exceeded 50 MB,  may need more spaces.

### ISSUE THREAD

**Issue by flyinghail** [jsdelivr/jsdelivr#18162]
see: https://www.jsdelivr.com/package/npm/antd

[antd](https://www.npmjs.com/package/antd) 3.20.4 and 3.20.5 is larger than 50 MB.

This package is very large, and seems no useless files can be deleted.
Is it possible to give this package a higher limit?

related: https://github.com/ant-design/ant-design/issues/17778

**Comment by MartinKolarik** [comment]
Hi, the limit was increased and files are now accessible on the CDN: https://cdn.jsdelivr.net/npm/antd/. The website listing page should start working within a few hours.

**Comment by flyinghail** [comment]
@MartinKolarik Thanks
