### ISSUE TITLE
PerfOps RUM related issue - Edgecast test got 404

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18167]
![image](https://user-images.githubusercontent.com/40715044/62520480-4675b080-b860-11e9-8f0e-9133c81dc13b.png)

It seems that `https://edgecast.perfstack.net/8086B5F/bench/500b-bench.jpg` has become 404 so XHR can not load the test file.

**Comment by jimaek** [comment]
We are working on that, but it should not generate any problems to anyone

**Comment by SukkaW** [comment]
@jimaek Yes, not any impact to anyone or any website, except perfops.

**Comment by jimaek** [comment]
The issue was fixed, thanks for reporting
