### ISSUE TITLE
Cannot request jquery-ui v1.11.4

### ISSUE THREAD

**Issue by someblue** [jsdelivr/jsdelivr#18173]
When I try to use  [jquery-ui v1.11.4](https://www.jsdelivr.com/package/npm/jquery-ui). It display "Couldn't find the requested release version 1.11.4.". Maybe something is broken. If so hope it will be fixed :)

Thanks for jsdevlivr! It really help a lots!

**Comment by MartinKolarik** [comment]
There's no such version of jquery ui on npm. All available versions are listed at the page you linked.

**Comment by someblue** [comment]
I see this version in the bottom of the link.

![image](https://user-images.githubusercontent.com/5562124/63663320-84794b00-c7f4-11e9-9e90-7dcac859c996.png)

It seem confused if v1.11.4 is invalid version :confounded:

**Comment by MartinKolarik** [comment]
Oh I see. You can use this link then: https://cdn.jsdelivr.net/jquery.ui/1.11.4/jquery-ui.min.js

**Comment by someblue** [comment]
Thanks!
