### ISSUE TITLE
Package size exceeded the configured limit of 50 MB

### ISSUE THREAD

**Issue by zdrawku** [jsdelivr/jsdelivr#18177]
We've just released our 8.2.0 version of [Ignite UI for Angular product](https://github.com/IgniteUI/igniteui-angular), and we've encountered the error "Package size exceeded the configured limit of 50 MB"

Steps to reproduce:
1. Open https://cdn.jsdelivr.net/npm/igniteui-angular@8.2.0
2. Error is returned.

This issue is a showstopper for our [Samples release](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html) as we are using StackBlitz for live-editing and they are using jsdeliver cdn service.

Your help will be highly appreciated!

**Comment by zdrawku** [comment]
@MartinKolarik as you recommended in other issues, we limited as much as possible our bundle size, so could you help us with the increase of the limit?

**Comment by SukkaW** [comment]
There is a workwround: publish a package with only prebuilt files included.

**Comment by MartinKolarik** [comment]
> @MartinKolarik as you recommended in other issues, we limited as much as possible our bundle size, so could you help us further with limit increase or something else?

The limit for your package will be removed shortly.

**Comment by zdrawku** [comment]
Thank you @MartinKolarik! Everything is working just fine now, stackblitz is loading correctly our package https://stackblitz.com/angular/bqbqggemmpo
Thanks again :)

**Comment by topbestcoder** [comment]
Same problem with a **2 Ko** file size !!
Package size exceeded the configured limit of 50 MB. Try https://github.com/........../BugA.atlas instead.

**Comment by topbestcoder** [comment]
Forget my last comment. The github file was missing but why this strange error message?
