### ISSUE TITLE
Website not loading ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by naiduasn** [jsdelivr/jsdelivr#18175]
Unable to load websites on any browsers

Try to open : https://www.jsdelivr.com/

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by jokin1999** [comment]
same

**Comment by MartinKolarik** [comment]
I'm currently talking with our cloud provider, they say the issue should be fixed within 15 minutes.

**Comment by MartinKolarik** [comment]
They are still looking into what happened but it loads now.

**Comment by naiduasn** [comment]
Working fine now.
