### ISSUE TITLE
There is no way to get the latest version

### ISSUE THREAD

**Issue by sarnor** [jsdelivr/jsdelivr#18171]
Hey. I have been using your service not so long ago. But ran into some inconvenience.
Suppose I connect some styles. The first time I connect, I get a link. Then, if I changed something in the github or npm repository, I don’t see the changes, I get the original version from this link
Quick-mixins-less
Further, if I want to get the current version with all the changes, I am obligated to version @n .n .n version on the path
Quick-mixins-less version 0.0.1-3
This is somewhat inconvenient. Since I use this link in many places. Next, I will have to change versions of this link throughout.
Maybe I'm doing something wrong and I don’t quite understand how to use your service or is it a bug?

**Comment by MartinKolarik** [comment]
https://cdn.jsdelivr.net/npm/quick-mixins-less@0/quick-mixins.less but it only works with stable versions, not pre-releases. E.g. `0.y.z` but not `0.y.z-something`

**Comment by MartinKolarik** [comment]
See also https://www.jsdelivr.com/features#npm

**Comment by sarnor** [comment]
Ok thank you...
