### ISSUE TITLE
Add a response header to show current CDN

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18172]
QUANTIL has its specific response header: `x-via`.
Cloudflare has its specific response header: `cf-ray`, `server: cloudflare`
Stackpath has its specific response header: `server: NetDNA-cache/2.2`
Fastly has its specific response header: `x-served-by`, but since jsDelivr uses Fastly as middle load balancer and cache layer, for cdn.jsdelivr.net it is not unique.

I suggest adding a response header like 'x-jsdelivr-cdn: fastly' 'x-jsdelivr-cdn: stackpath' 'x-jsdelivr-cdn: cloudflare', and if no 'x-jsdelivr-cdn' header is given, then the request could have hit QUANTIL. I believe it could be helpful when debugging.

**Comment by MartinKolarik** [comment]
This would have to be done by each provider separately and I'm not sure if all of them support setting custom headers. The correct detection logic is this though:

 - `server: cloudflare` - Cloudflare
 - `server: NetDNA-cache/2.2` - StackPath
 - `x-via` - Quantil
 - none of the above - Fastly

**Comment by SukkaW** [comment]
@MartinKolarik 

Stackpath and Fastly support custom header: 

- https://support.stackpath.com/hc/en-us/articles/360001417983-Getting-Started-with-Custom-CDN-EdgeRules
- https://docs.fastly.com/en/guides/adding-or-modifying-headers-on-http-requests-and-responses

Cloudflare doesn't mentioned custom headers in their docs but I wonder if you can ask Cloudflare Engineer to help setup a custom response header.

QUANTIL doesn't support custom response headers.

**Comment by MartinKolarik** [comment]
Closing this as it wouldn't work with quantil and the detection is still possible as per my previous comment.
