### ISSUE TITLE
PageSpeed Insights: "Serve static assets with an efficient cache policy"

### ISSUE THREAD

**Issue by wellington1993** [jsdelivr/jsdelivr#18174]
Google page insight says:
![Screenshot_2019-09-03 PageSpeed Insights(2)](https://user-images.githubusercontent.com/6920053/64182238-4c9a8500-ce3e-11e9-9752-55eb2517fc7c.png)
![Screenshot_2019-09-03 PageSpeed Insights(1)](https://user-images.githubusercontent.com/6920053/64182240-4c9a8500-ce3e-11e9-81bc-3f0993f82d65.png)
![Screenshot_2019-09-03 PageSpeed Insights](https://user-images.githubusercontent.com/6920053/64182241-4c9a8500-ce3e-11e9-800e-6f59acfbb030.png)

The report:
[https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbac.hotsoft.com.br](
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbac.hotsoft.com.br)

Could the cache time be increased?

Thanks!

**Comment by MartinKolarik** [comment]
You're using `@latest` links for all files. If you want longer cache time you have to switch to specific versions.

**Comment by wellington1993** [comment]
Yes, make sense.

Should be possible to use ```@latest``` with more cache time?
Maybe 14 days... Maybe passing extra parameter in GET query?

Something like a happy medium.

Thanks!

**Comment by MartinKolarik** [comment]
7 days is already quite long. If you check #18121 you'll see other people would prefer a lot less 😃

**Comment by wellington1993** [comment]
> 7 days is already quite long. If you check #18121 you'll see other people would prefer a lot less smiley

Discussing. Thanks!
