### ISSUE TITLE
how can i put jsdelivr on prestashop 1.7.5 ?

### ISSUE THREAD

**Issue by antoniopineapple** [jsdelivr/jsdelivr#18179]
how can i put jsdelivr on prestashop 1.7.5 ?

**Comment by jimaek** [comment]
Unfortunately we don't have a plugin for it yet, so you would have to do it manually and edit the code

**Comment by antoniopineapple** [comment]
Is there a tutorial?

⁣Ottieni BlueMail per Android ​

Il giorno 2 Ott 2019, 5:29 PM, alle ore 5:29 PM, Dmitriy Akulov <notifications@github.com> ha scritto:

**Comment by jimaek** [comment]
There is not, Maybe in the future we can build addons for popular CMSs
