### ISSUE TITLE
document options used for minification

### ISSUE THREAD

**Issue by catdad** [jsdelivr/jsdelivr#18185]
Recently, I got a report that some of my modules do not work when served by jsdelivr, and I traced it to the minification process (they work wen requesting the non `min` version). This may happen with any minification process, of course. I have a fix, but I would like to add testing to my project locally to make sure that it will work once published.

I see that Terser v3.14.1 is used to minify files, but when I use it locally with default options, I get a different minified output. Can you please document the options used by jsdelivr, so that we may add it in our testing pipelines?

**Comment by MartinKolarik** [comment]
We don't use any special options other than `sourceMap` so when using the exact same version, the result should be the same, except the comment at the top and source map link at the bottom.

The only thing I can think of that could make a difference is different versions of terser's dependencies - if it doesn't pin specific versions, maybe it produces slightly different output with their latest versions.

**Comment by MartinKolarik** [comment]
Also if terser broke your code, you might want to check if the latest version has the same problem and report it to them if yes (we'll likely upgrade to v4 soon).

**Comment by catdad** [comment]
This information does match the results that I am seeing.

The comment at the top of [this file](https://cdn.jsdelivr.net/npm/canvas-confetti@1.0.0/dist/confetti.browser.min.js) says that terser 3.14.1 is used. So I installed that as well and am running this command:

```
terser -o output.min.js src/confetti.js
```

I am seeing the following differences from a very cursory look:

* the code is wrapped in a function that provides `window` and `module`. I assumed this is the `--wrap` option, but when I use that option, I get a different wrapping function locally which only wraps one variable, and it is `exports`.
* the code has variable names changed (obfuscated). This is non-default, and has to do with specific options passed to `--compress` and `--mangle`. By default, no variable names are changed.

So there are definitely additional options being passed in, as these changes are not caused by slight differences in dependencies.

**Comment by MartinKolarik** [comment]
We use the JS API, not CLI, so that may have different defaults. E.g. I'm surprised `--compress` and `--mangle` are not on by default in the CLI version as that makes minification way less efficient but they are enabled in JS defaults.
