### ISSUE TITLE
Malicious file

### ISSUE THREAD

**Issue by carrasco12345** [jsdelivr/jsdelivr#18187]
Good night
I need you to eliminate all the files of these two:

if they can do that, it would be bad because I don't know how to delete them. I really need them to do that.

//cdn.jsdelivr.net/gh/alexandre2311/player@player1/Autobot.js
//cdn.jsdelivr.net/gh/alexandre2311/bot8@bot9/

**Comment by MartinKolarik** [comment]
What is wrong with those files?

**Comment by carrasco12345** [comment]
I created them but I can't eliminate them I need them to delete them they can't be there

**Comment by MartinKolarik** [comment]
The files are from a different GitHub account.

**Comment by carrasco12345** [comment]
yes they are mine

**Comment by carrasco12345** [comment]
how to remove packages "CDN files"  jsdelivr.net ? 

//cdn.jsdelivr.net/gh/alexandre2311/player@player1/Autobot.js
//cdn.jsdelivr.net/gh/alexandre2311/bot8@bot9/

**Comment by MartinKolarik** [comment]
We don't generally remove files and in this case, we can't verify you really are the owner of the other account.

**Comment by alexandre2311** [comment]
i have these two accounts, i need to remove cdn files 
//cdn.jsdelivr.net/gh/alexandre2311/player@player1/Autobot.js
//cdn.jsdelivr.net/gh/alexandre2311/bot8@bot9/ 

everything clean everything please frend

**Comment by MartinKolarik** [comment]
Do you want to delete only `player1` and `bot9` versions or is it ok if we block the whole `alexandre2311/player` and `alexandre2311/bot8` repositories? The second option is currently significantly easier for us.

**Comment by alexandre2311** [comment]
second option

**Comment by MartinKolarik** [comment]
Deleted.
