### ISSUE TITLE
Please Block My GitHub Repo from jsDelivr

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18188]
I am using GitHub Repo to host some binary `.dat` files for people to download (through GitHub Pages and Cloudflare).

Recently I have noticed somebody is trying to download those files through jsDelivr (Since the repo is public). I believe it is not appropriate for jsDelivr to deliver binary files, so I am here to ask for blocking my repo from jsDelivr completely: `SukkaW/qqwry-mirror`.

**Comment by MartinKolarik** [comment]
Unless a repository contains malware or something that violates copyright (which would be against GitHub's ToS too), we have no reason to block it. All files that can be loaded via jsDelivr are "appropriate", including binary ones.

**Comment by SukkaW** [comment]
@MartinKolarik Understood. Thanks!
