### ISSUE TITLE
Twemoji - Package size exceeded the configured limit of 50 MB.

### ISSUE THREAD

**Issue by willstocks** [jsdelivr/jsdelivr#18183]
Hey guys,

Quick question, I've been using links such as https://cdn.jsdelivr.net/gh/twitter/twemoji@12.1.3/2/svg/2600.svg for Twemoji for some time now

However, I noticed that upon upgrading to Twemoji 12.1.3, I now receive the following error:
`Package size exceeded the configured limit of 50 MB.`

Previous versions worked, but now whenever I hit a URL I was using previously (12.1.1 for example), I'm still seeing the same error?

Is there any way around this?

I use the GH link as the actual SVG/PNG assets aren't served up as part of Twemoji's NPM package.

**Comment by willstocks** [comment]
Hi @MartinKolarik 
I can see what the issue is - they have changed `2` to `assets` recently.
That, however, would not explain why I receive this error:
![image](https://user-images.githubusercontent.com/43744514/68952113-36eaf980-07b7-11ea-916d-32501db91bb8.png)

Fair enough a 404 or a "incorrect url". But a 403 and repo size warning is the wrong error to show?

**Comment by MartinKolarik** [comment]
It's mostly for historical reasons. When we switched to fetching individual files instead of tarballs, we kept the tarball logic as a fallback, so when a file doesn't exist (or fails for any other reason), we attempt to fetch the whole tarball, which triggers this error.

**Comment by willstocks** [comment]
Ah, OK that makes some sense!
Well, with the corrected URL it works fine now which is good news. I'll close this one off as I don't anticipate that error thrown will change any time soon?
