### ISSUE TITLE
Suggestion: Use 'https://cdn.jsdelivr.net/gh/' as 'npm' warehouse

### ISSUE THREAD

**Issue by masx200** [jsdelivr/jsdelivr#18181]
Suggestion: Use 'https://cdn.jsdelivr.net/gh/' as 'npm' warehouse

for example:

```powershell
yarn add https://cdn.jsdelivr.net/gh/masx200/dom-element-attribute-agent-proxy.git
```

```powershell
cnpm i  https://cdn.jsdelivr.net/gh/masx200/dom-element-attribute-agent-proxy.git
```

**Comment by wusatosi** [comment]
This is more like a mirror to the whole github repo than.

**Comment by SukkaW** [comment]
jsDelivr is not a git server or npm registry. It serves static file for front-end purpose.

Use `npmreg.proxy.ustclug.org` or `https://registry.npm.taobao.org/` if npm registry is not accessible in your region.

Use `npm i user/repo` or `yarn add user/repo` to install packages from GitHub.
