### ISSUE TITLE
github version visible in cdn.jsdelivr but not in data.jsdelivr

### ISSUE THREAD

**Issue by cristianbogdan** [jsdelivr/jsdelivr#18180]
Version 0.1.1 of a github project in cdn
https://cdn.jsdelivr.net/gh/cristianbogdan/react-basic-draw-presentation@0.1.1/package.json

But data.jsdelivr shows no versions and no tags
https://data.jsdelivr.com/v1/package/gh/cristianbogdan/react-basic-draw-presentation

```
{
	"tags": [],
	"versions": []
}
```

https://data.jsdelivr.com/v1/package/gh/cristianbogdan/react-basic-draw-presentation@0.1.1 is then a 404 not found
````
{
	"status": 404,
	"message": "Couldn't find version 0.1.1 for cristianbogdan/react-basic-draw-presentation. Make sure you use a specific version number, and not a version range or a tag."
}
````

Also another project hasn't got the latest 0.1.0 version visible in data.jsdelivr, which shows only 0.0.1 and 0.0.2

https://data.jsdelivr.com/v1/package/gh/cristianbogdan/react-redux-basic-draw 
`````
{
	"tags": [],
	"versions": [
		"0.0.2",
		"0.0.1"
	]
}
`````
but the 0.1.0 does exist in github
https://cdn.jsdelivr.net/gh/cristianbogdan/react-redux-basic-draw@0.1.0/package.json

For this project, I had a similar problem, 0.0.2 was not visible in data.jsdelivr and it suddenly showed up when I made the 0.1.0 branch. Not sure if the two events are related.

data.jsdelivr is used by stackblitz where I want to use these packages. 

What am I doing wrong in github? Thanks!

**Comment by MartinKolarik** [comment]
The API only returns GitHub releases (git tags), not branches. The CDN falls back to serving branches if no release exists with that name, that's why you see this difference.

**Comment by cristianbogdan** [comment]
thanks!
But then the error message is confusing
```
 Make sure you use a specific version number, and not a version range or a tag.
```

**Comment by MartinKolarik** [comment]
Indeed, it's because the API has the same format for npm and GitHub projects but those two use slightly different terminology: https://github.com/jsdelivr/data.jsdelivr.com#list-package-versions

The message is about npm tags (and everywhere in ours docs, tag = npm tag). GitHub projects don't have an equivalent of that. They only have static versions, which, unfortunately, are also called tags in git terminology.

**Comment by cristianbogdan** [comment]
I now have created both a tag and a branch 0.1.4 
https://github.com/cristianbogdan/react-basic-draw-presentation/tree/0.1.4

but 0.1.4 is still not listed in 
https://data.jsdelivr.com/v1/package/gh/cristianbogdan/react-basic-draw-presentation

0.1.1 was listed immediately after I created the 0.1.1 tag/release. Is there any delay involved? 
Thanks!

**Comment by cristianbogdan** [comment]
Now I found that there is a lag of about 10 min.
