### ISSUE TITLE
Auto minify does not always work

### ISSUE THREAD

**Issue by BSG-75** [jsdelivr/jsdelivr#18184]
For example, it looks like https://cdn.jsdelivr.net/npm/typescript@3.7.3/lib/typescript.min.js will still return the original file (i.e. https://cdn.jsdelivr.net/npm/typescript@3.7.3/lib/typescript.js)

**Comment by MartinKolarik** [comment]
The file is too big, so the minification times out, and we serve the original instead. There isn't much we can do about this.
