### ISSUE TITLE
Issue with NordVPN

### ISSUE THREAD

**Issue by chrisjbrown** [jsdelivr/jsdelivr#18199]
Seem to be experiencing the same issue described in this old issue
https://github.com/jsdelivr/jsdelivr/issues/749

<img width="1600" alt="Screenshot 2020-03-20 at 15 42 58" src="https://user-images.githubusercontent.com/1250638/77174538-80c75180-6ac1-11ea-8bc5-6ea499d334c7.png">

This happens when I have my VPN enabled using a netherlands server
ip: 212.232.87.92

I also tried using a US server and have the same issue
ip: 195.181.168.211

**Comment by MartinKolarik** [comment]
If it works in the same browser without a VPN, it's likely a problem with the VPN, not our certificates.

**Comment by hdpe1399** [comment]
Is your vpn provider nordvpn? 
Because I seem to be having the same issue right now...

**Comment by jimaek** [comment]
Could the users of NordVPN please contact their support? Its something on their side and we can't do anything about that.

**Comment by hdpe1399** [comment]
> Could the users of NordVPN please contact their support? Its something on their side and we can't do anything about that.

So cdn.jsdelivr.net didn't block any vpn servers, right?

**Comment by jimaek** [comment]
Of course not. It looks like their DNS server uses their own IP address for responses instead of ours. So you are connecting to the wrong place completely.

**Comment by MartinKolarik** [comment]
We're no longer getting reports about this so I'm assuming the issue was resolved. If anyone has this problem again please contact NordVPN support.
