### ISSUE TITLE
What is the Point of .min when jsdeliver downloads the non .min anyways?

### ISSUE THREAD

**Issue by tygari** [jsdelivr/jsdelivr#18196]
In my project for some reason jsdelivr is downloading two copies of every file.
One targeted with .min.
And an unminified version with @master.

Testing has revealed removing the .min causes only a single unminified copy to be downloaded.

Instead of resulting in less space stored in memory .min is using up more space.

![jsdelivrmin](https://user-images.githubusercontent.com/26011255/76265182-41377480-623a-11ea-9815-e2a67ab98da3.jpg)

**Comment by MartinKolarik** [comment]
This happens only when you have devtools open. https://www.google.com/search?q=js+source+maps
