### ISSUE TITLE
Relative ES6 JS imports

### ISSUE THREAD

**Issue by obnoxiousnerd** [jsdelivr/jsdelivr#18193]
Hello! I am the author of [TeddyTags](https://github.com/teddytags/teddytags). We always use jsDelivr as our CDN for the package but lately things are not working. We are importing some modules from another file in the main file directory to the main file: 
https://github.com/teddytags/teddytags/blob/eb9e54017c3ba1925c19b495fe1a6908c204f56a/src/teddytags.ts#L16
But it seems that jsDelivr is loading another package which has the same name as the file:
![Untitled1](https://user-images.githubusercontent.com/52596591/75095740-3801a300-55be-11ea-8b41-8a5faf27dbae.png)
And the endpoint user will end up in an unexpected error: 
![Untitled](https://user-images.githubusercontent.com/52596591/75095742-3afc9380-55be-11ea-92f7-6c3b026eeaa8.png)
Please try to resolve the issue as soon as possible.
Link used for fetching TeddyTags from jsDelivr: https://https://cdn.jsdelivr.net/npm/teddytags

**Comment by MartinKolarik** [comment]
This has nothing to do with jsDelivr, it's how resolving relative URLs in the browser works. When you load a file from `https://cdn.jsdelivr.net/npm/teddytags` and that file imports `./vdom.js`, the browser resolves that to `https://cdn.jsdelivr.net/npm/vdom.js` which is indeed a different npm package.

If your package includes relative paths to other files, you need to load it using the full URL: https://cdn.jsdelivr.net/npm/teddytags@0.4.0/lib/teddytags.js
