### ISSUE TITLE
the address cannot be updated in real time with GitHub

### ISSUE THREAD

**Issue by Alvin9999** [jsdelivr/jsdelivr#18190]
My problem is that the address cannot be updated in real time with GitHub.

For example, I modified the file https://raw.githubusercontent.com/Alvin9999/PAC/master/guiNConfig.json on GitHub, but when I downloaded the file through the address https://cdn.jsdelivr.net/gh/Alvin9999/PAC/guiNConfig.json, it could not be updated in real time. According to the test, it took six hours or even more than one day to update the previous content. Can this problem be solved? Thank you.

**Comment by MartinKolarik** [comment]
See #18063

**Comment by Alvin9999** [comment]
Many days ago, I sent an email to dak@prospectone.io, but I didn't get a reply.

**Comment by MartinKolarik** [comment]
@jimaek ?

**Comment by jimaek** [comment]
Maybe went to spam, I don't think I got it

**Comment by Alvin9999** [comment]
> Maybe went to spam, I don't think I got it

I sent it to you again. Please check it. Thank you.

**Comment by Alvin9999** [comment]
@jimaek
