### ISSUE TITLE
consider jsDelivr named combinations?

### ISSUE THREAD

**Issue by iskitz** [jsdelivr/jsdelivr#18207]
I love jsDelivr’s on-demand file combination feature but wish that it provided the ability to **give combinations concise names** that were shorter than the current, sometimes very long, combination url.

For example, it’d be very helpful to have:

https://cdn.jsdelivr.net/combine/gh/ionify/ionify@0.1/web.js,gh/ionify/ionify@0.1/ions/on.ion.js,gh/ionify/ionify@0.1/ions/next.id.js,gh/ionify/ionify@0.1/ions/id.js,gh/ionify/ionify@0.1/ions/on.error.js,gh/ionify/ionify@0.1/ions/on.errors.js,gh/ionify/ionify@0.1/ions/find.link.share.js,gh/ionify/ionify@0.1/ions/no.js,gh/ionify/ionify@0.1/ions/on.aeon.js,gh/ionify/ionify@0.1/ions/do.js,gh/ionify/ionify@0.1/ions/on.ions.js,gh/ionify/ionify@0.1/ions/on.action.js,gh/ionify/ionify@0.1/ions/on.storie.js,gh/ionify/ionify@0.1/ions/use.js,gh/ionify/ionify@0.1/ions/ions.js,gh/ionify/ionify@0.1/ions/web.log.js

also be accessible via a new & more concise `/combined/` path like:

https://cdn.jsdelivr.net/combined/gh/ionify/ionify@0.1/my.named.combination.js

or via the existing `/combine/` path by overloading that to reference named combinations when only 1 resource is specified:

https://cdn.jsdelivr.net/combine/gh/ionify/ionify@0.1/my.named.combination.js

I’d like [ionify](https://api.ionify.net/) to programmatically create & reference cdn-served combinations based on runtime-defined dependencies & fetch requests. Having a cdn like jsDelivr do that on-demand & then persist the combination & recall that exact instance by name would be fantastic.

**Comment by MartinKolarik** [comment]
I don't quite see how this would work. We'd have to provide an interface to create those and then store the mappings from the name to a list of files. That sounds very complicated just to have shorter URLs.

**Comment by jimaek** [comment]
I think this simply adds another point of failure. If the DB storing the mappings goes down it could potentially take down all short URLs. It would require a lot of work to make this reliable. I dont think its worth all the dev effort.
