### ISSUE TITLE
jsdelivr not working with pixi.js

### ISSUE THREAD

**Issue by greggman** [jsdelivr/jsdelivr#18202]
not sure this is the right place to bring this up but if I try

```
<script src="https://cdn.jsdelivr.net/npm/pixi.js@5.2.1/lib/pixi.min.js"></script>
```

with the example from [the readme of pixi.js](https://github.com/pixijs/pixi.js/blob/dev/README.md) it doesn't work: https://jsfiddle.net/greggman/o9aeuxsn/

The errors in the js console are

```
Uncaught ReferenceError: exports is not defined
    at jsdelivr-header.js:7
(index):32 Uncaught SyntaxError: Identifier 'app' has already been declared
    at (index):32
```

If all I do is change the script line to use cdnjs

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.2.1/pixi.min.js"></script>
```

It does work: https://jsfiddle.net/greggman/fngq97tx/

Is it a known issue that some libraries don't work on jsdelivr? Is pixi.js doing something wrong?

**Comment by MartinKolarik** [comment]
The file you want is https://cdn.jsdelivr.net/npm/pixi.js@5.2.1/dist/pixi.min.js

**Comment by greggman** [comment]
Thanks. I guess that means pixi.js has it's package.json wrong? because the page for it

https://www.jsdelivr.com/package/npm/pixi.js

Links to the `lib` file not the `dist` file.

**Comment by MartinKolarik** [comment]
Yes, the default files is read from package.json as explained here: https://github.com/jsdelivr/jsdelivr#configuring-a-default-file-in-packagejson
