### ISSUE TITLE
purge cache timing

### ISSUE THREAD

**Issue by kernyden** [jsdelivr/jsdelivr#18205]
how much time does purge cache need to cdn link gets update? im trying it such more times with multiple scenarios (i havent release version in forked package, so i do the next'):

named repo:
1. https://purge.jsdelivr.net/gh/kernyden/bug@master
2. https://purge.jsdelivr.net/gh/kernyden/bug@latest
3. https://purge.jsdelivr.net/gh/kernyden/bug

without named:
1. https://purge.jsdelivr.net/gh/bug@latest
2. https://purge.jsdelivr.net/gh/bug@master
3. https://purge.jsdelivr.net/gh/bug

In one case it happens (cache has reseted, didn't know in which cause of time), but now i have been waiting for more then 30 min, and nothing happens. It doesnt update to the latest version (old version https://cdn.jsdelivr.net/gh/kernyden/bug@master/bug-min.js). Only hashed commit version of cdn gets changes https://cdn.jsdelivr.net/gh/kernyden/bug@a75e751316327c5ec465f2157cdc8cef6c8ea597/bug-min.js. Can u explain some of these case, pls

updated:
wow, this case is also worked - https://purge.jsdelivr.net/gh/kernyden/bug@master/bug-min.js, and it was fast enough. 

so now my question is: why does 'purge' main directory do nothing ?

**Comment by MartinKolarik** [comment]
Purge is always only for that one specific path, it doesn't know anything about directories and their contents. If you want to purge several files you need to explicitly list them.

**Comment by kernyden** [comment]
@MartinKolarik  ah, got it, thx
