### ISSUE TITLE
Failed to fetch version info for xxx/xxx.

### ISSUE THREAD

**Issue by pexcn** [jsdelivr/jsdelivr#18216]
Hi @jsdelivr developers:

I'm using cdn of jsdelivr recently, but encountered some problems.
When I open this link: https://cdn.jsdelivr.net/gh/pexcn/daily@gh-pages/pac/, the following error will be reported:
```
Failed to fetch version info for pexcn/daily.
```
Its target file is this: https://github.com/pexcn/daily/tree/gh-pages/pac
How should this problem be solved?

Thanks.

**Comment by jimaek** [comment]
Looks like it works now, maybe you changed something on your end

**Comment by pexcn** [comment]
It seems very unstable, just now when I visited another link, it got this error again.

link: https://cdn.jsdelivr.net/gh/pexcn/daily@gh-pages/pac/whitelist.pac

![4D7A848B-034B-4E6E-9B36-1F7B8F6FDC1F](https://user-images.githubusercontent.com/4590439/82245176-0f970400-9975-11ea-97ae-be7df0ba29d8.jpeg)

**Comment by MartinKolarik** [comment]
We're currently having issues fetching some of new files from GitHub. It shouldn' affect existing files.

**Comment by MartinKolarik** [comment]
I think we're getting back to normal now.

**Comment by dbauszus-glx** [comment]
Why is this closed? The issue still persists and seems to get worse. Icons, mostly svg across multiple production projects are missing. This seems to be rather random as different resources are missing on different days.

Ideally we wouldn't use a version to always access a version but this doesn't seem to be working at all these days.

**Comment by Innei** [comment]
I had the same problem, if you visit like `xxx@master`. And only by creating new release, it worked.

**Comment by dbauszus-glx** [comment]
I didn't actually do a release in the first place. But it worked intermittently. I have done now a release but it still doesn't work on most resources. e.g. https://cdn.jsdelivr.net/gh/GEOLYTIX/gla/icon_location.svg

**Comment by MartinKolarik** [comment]
The issue came back this morning as we're again seeing a huge spike in `/gh/` traffic, which causes issues when fetching new files form GitHub in some cases. We've made some improvements to our analytics now that should make it easier to distinguish between regular users and spam/abuse and make this better. A long-term solution to this problem will be in development in the next months.

**Note that this issue mostly affects `@branch` links, as they are only cached for a short time by the CDN and need to be updated from GitHub frequently. If you use `@release` links, after the first successful fetch they are stored on our servers permanently and do not need to be checked again with GitHub.**

**Comment by Rarst** [comment]
I am pulling some JSON data from 3rd party repo, that has no tagged releases, and I had already seen this multiple times for it.

Please consider serving stale data or something in such cases rather than just fail with 404. 🙏

**Comment by MartinKolarik** [comment]
> Please consider serving stale data or something in such cases rather than just fail with 404. 🙏

Indeed that's a good idea, we changed the status code for this specific case to 502 which should trigger stale-on-error behavior at the CDN. We also improved caching for the cases that are causing this, will see in a few hours how that helped.

**Comment by MartinKolarik** [comment]
@Rarst if the files don't need to be updated often there's one more option that I forgot to mention here: use `@commitHash` (needs to be full 40 characters), then the check which is causing this issue is bypassed completely.

**Comment by MartinKolarik** [comment]
We'll keep monitoring this but in the past 24 hours, there wasn't a single error 🎉

**Comment by monokee** [comment]
Trying to use a `@release` link but I'm getting this error:

`Failed to fetch version info for monokee/Cue.`

https://cdn.jsdelivr.net/gh/monokee/Cue@v5.1.1-beta/build/cue.min.js

**Comment by jimmywarting** [comment]
Got this error also...

https://cdn.jsdelivr.net/gh/jimmywarting/native-file-system-adapter/src/adapters/memory.js

**Comment by akhilarjun** [comment]
Hi, this issue still exists. I got this error for my repo
https://cdn.jsdelivr.net/gh/akhilarjun/tinylibs@latest/themejs/theme.js

**Comment by Simvolick** [comment]
The error is still present

**Comment by tctco** [comment]
The error still exists

**Comment by tsq456** [comment]
The error still exists

https://cdn.jsdelivr.net/gh/tsq456/picBed@latest/master/bg.png

https://cdn.jsdelivr.net/gh/tsq456/picBed/master/bg.png

**Comment by jimaek** [comment]
Thats just a wrong URL 
https://cdn.jsdelivr.net/gh/tsq456/picBed@master/bg.png

**Comment by jimaek** [comment]
To everyone else reporting issues please include URLs and HTTP headers. At the moment everything is fine on our end.

**Comment by fnick851** [comment]
Could you help look into this:
https://cdn.jsdelivr.net/gh/PatentsView/pv-header-footer@0.01/header_footer.js
https://cdn.jsdelivr.net/gh/PatentsView/pv-header-footer@master/header_footer.js
https://cdn.jsdelivr.net/gh/PatentsView/pv-header-footer/header_footer.js

I created a release tagged 0.01. But not of these work. The repo is a private repo. But I tried with another private repo and it works. Not sure what is special here?

**Comment by jimaek** [comment]
What other private repo did you try and it worked?
jsDelivr can't possibly have access to any private repo, it's currently built to support only public ones
