### ISSUE TITLE
GitHub tag names prefixed with v

### ISSUE THREAD

**Issue by shane-searles** [jsdelivr/jsdelivr#18211]
Does jsdelivr detect github tags that are prefixed with v? Hypothetically, if there is a v1.0.1 and a 1.0.1, which tag does it consider the @latest?

I pulled this quote from the semver site: "Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

So for GitHub, I thought my tags should start with v. Is that incorrect? If so, does jsdelivr ignore those, or treat them as secondary to tags without a v? I have seen some strange behavior and I wonder if this is the cause.

Also, is there any query to see exactly which tag @latest is detecting?

Thanks.

**Comment by MartinKolarik** [comment]
The leading "v" is ignored for GitHub tags so you can use either and there should be no difference in behavior. You can even use both variants in one repo, just don't use both with the exact same version. E.g., having `1.0.0` and then `v1.0.1` should be ok, having `1.0.0` and `v1.0.0` may cause issues.

**Comment by MartinKolarik** [comment]
> Also, is there any query to see exactly which tag @latest is detecting?

Via the API: https://data.jsdelivr.com/v1/package/gh/jquery/jquery - the versions list is sorted.

**Comment by shane-searles** [comment]
Thanks for the reply Martin!
> > Also, is there any query to see exactly which tag @latest is detecting?
> 
> Via the API: https://data.jsdelivr.com/v1/package/gh/jquery/jquery - the versions list is sorted.

This must be why I am seeing peculiar behavior. When I query one of my projects, as:
https://data.jsdelivr.com/v1/package/gh/S4-NetQuest/biodigital-select-activity
I get:
{
	"status": 404,
	"message": "Couldn't fetch versions for S4-NetQuest/biodigital-select-activity."
}
It only has one release/tag: v1.0.2

When I query my other, which also has only one release/tag:
https://data.jsdelivr.com/v1/package/gh/S4-NetQuest/biodigital-standard-activity
I get: {
	"tags": [],
	"versions": [
		"1.0.1"
	]
}

So the tags array is empty, but it is at least getting a version for that one.

Is there some way to manually clean up releases/tags? It seems like they're corrupted somehow. Or could the API have a bad cached result?

**Comment by MartinKolarik** [comment]
It is possible there was an issue fetching the list of releases on the API side, in that case, our API should retry that shortly on its own. This does not affect the actual availability of the files on the CDN.

**Comment by shane-searles** [comment]
> It is possible there was an issue fetching the list of releases on the API side, in that case, our API should retry that shortly on its own. This does not affect the actual availability of the files on the CDN.
It seems to be affecting the @latest. Yesterday around 3pm it suddenly started returning an old and deleted version of js/main.js. It had been returning the correct version the previous day.
I used the purge API to fix it, but I am concerned that if your API is unable to read my tags, it will go find that old version again somehow. Have any ideas on how to prevent that? I appreciate the help.

**Comment by MartinKolarik** [comment]
What was the tag of the deleted version?

**Comment by shane-searles** [comment]
> What was the tag of the deleted version?
I don't remember, it could have been 1.0.0 (first stable release) or 0.0.1 (when I was testing)

**Comment by shane-searles** [comment]
Did you fix something Martin? Now the 404 error is gone from before:
https://data.jsdelivr.com/v1/package/gh/S4-NetQuest/biodigital-select-activity
{
	"tags": [],
	"versions": [
		"1.0.2"
	]
}

Although the tags array is till empty.

As long as @latest will always return v1.0.2 until I release a newer version, that's all I really care about. I just want to be sure that it isn't going to revert backward to a deleted version again that's cached somewhere.

**Comment by MartinKolarik** [comment]
Tags refer to npm tags and are always empty for GitHub projects. Unlike with npm, where "latest" or anything else can be set explicitly by package author, for GitHub, we simply sort the versions and take the first one.

> As long as @latest will always return v1.0.2 until I release a newer version, that's all I really care about.

This should be the case, provided the deleted version was lower than the existing one.

**Comment by shane-searles** [comment]
> Tags refer to npm tags and are always empty for GitHub projects.
> >
Ah ok, thanks.
> This should be the case, provided the deleted version was lower than the existing one.
>>
Yes, the deleted versions were definitely lower than 1.0.2. I think the odd behavior yesterday had something to do with https://data.jsdelivr.com/v1/package/gh/S4-NetQuest/biodigital-select-activity returning a 404, and it retrieved an old cached version somehow. I'm not sure why an old version would still be cached after @latest was successfully returning a newer one for a day or so. But using the purge API fixed that. 

Now that the 404 error is gone as of half an hour ago, I'm hopeful whatever the problem was is now fixed, although I haven't changed anything on my end since starting this thread.

One more question:
Any idea why https://data.jsdelivr.com/v1/package/resolve/gh/S4-NetQuest/biodigital-standard-activity@1 (retrieve version range) returns a 404? 
While https://data.jsdelivr.com/v1/package/gh/S4-NetQuest/biodigital-select-activity@1.0.2 returns expected json.
And is that a problem?

**Comment by MartinKolarik** [comment]
The "resolve GitHub version" and "list GitHub versions" API endpoints may occasionally fail right now as we're experiencing an increase of abuse traffic and hitting some of GitHub's rate limits.

The CDN and API are completely separate though and the CDN also keeps track of all versions it has previously seen, so once a request is successful, it won't fail in the future even if the GitHub API isn't available. On the other hand, the API always returns live data (with short cache time) so if it can't connect to GitHub, it returns an error.

**Comment by shane-searles** [comment]
Ah, that makes sense. Thanks. 

Speaking of cache, how long is @latest cached if you don't use the purge API? In other words, if I put out a new release 1.0.3, how soon would the CDN find it and distribute the new version without using purge? I looked at some old threads and saw discussions about 1 week and 24 hrs. What was ultimately settled on?

**Comment by MartinKolarik** [comment]
The CDN will find it in 12 - 24 hours but the individual browsers may cache it for up to 7 days.

**Comment by shane-searles** [comment]
Thanks for all the information, Martin.
