### ISSUE TITLE
The default link for npm package is not updated to latest version.

### ISSUE THREAD

**Issue by 3cp** [jsdelivr/jsdelivr#18212]
At least for this one npm package of mine. This is the first time I noticed this issue, not sure what's going on.

`https://cdn.jsdelivr.net/npm/aurelia-dialog-lite/package.json`
**It should return package.json for version 0.3.1, but it still points to 0.2.0.**
```
{
  "name": "aurelia-dialog-lite",
  "description": "A lite dialog plugin for Aurelia.",
  "keywords": [
    "aurelia",
    "plugin",
    "dialog",
    "modal"
  ],
  "main": "./dist/index.js",
  "files": [
    "dist"
  ],
  "version": "0.2.0",
  "license": "MIT",
  ...
```

**Evidences:**
`https://data.jsdelivr.com/v1/package/npm/aurelia-dialog-lite`
```
{
	"tags": {
		"latest": "0.3.1"
	},
	"versions": [
		"0.3.1",
		"0.3.0",
		"0.2.0",
		"0.1.2",
		"0.1.1",
		"0.1.0"
	]
}
```

I can use following links to get the file. So it definitely synced from npm.
```
https://cdn.jsdelivr.net/npm/aurelia-dialog-lite@latest/package.json
https://cdn.jsdelivr.net/npm/aurelia-dialog-lite@0.3.1/package.json
```

**Comment by MartinKolarik** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18063#issuecomment-379584602
