### ISSUE TITLE
Another hiccup with @latest and Purge API

### ISSUE THREAD

**Issue by shane-searles** [jsdelivr/jsdelivr#18217]
Suddenly last night, @latest started serving an old (and deleted from GH a month ago) 1.0.1. Until I started troubleshooting this last night, I had just one release on github, 1.0.2, and for a month up until last night, @latest was loading 1.0.2 as expected. 

This problem happened once before (a month ago) also, and I used the purge API, which fixed it within a few minutes. I used the purge API again this time but it took a couple hours to take effect.

Now, I'm thinking maybe the purge API didn't actually work properly on all the networks, and instead it was just a matter of waiting for one of the "good" networks to come back online and serve the 1.0.2 version.

I'm wondering if 1.0.1 is coming from one of the fallback networks; perhaps one that isn't working properly with the purge API or the automatic propagation of the latest version. There were a lot of storms yesterday, which may increase the likelihood that one of those fallback networks kicked in.

Has anyone seen problems like this, an old version suddenly resurfacing? Is there any way one of the devs can track down which servers/networks have it and force an update?

Thanks!

**Comment by MartinKolarik** [comment]
I was looking into this today and it was most likely a result of two unrelated issues happening at the same time. Both of these issues should be fixed now.

**Comment by shane-searles** [comment]
Thanks Martin. Does that mean the old 1.0.1 no longer exists anywhere and won't be making any more surprise appearances?

**Comment by MartinKolarik** [comment]
Not exactly deleted, but it won't be used unless requested specifically by @1.0.1 in the link. One of the issues was that the fallback system didn't know about the existence of the new versions, which it now does.

**Comment by shane-searles** [comment]
Ok, that makes sense, thanks. And will the fallback system now detect future new releases correctly also?

**Comment by MartinKolarik** [comment]
Of course.

**Comment by shane-searles** [comment]
Great! Thanks again Martin.
