### ISSUE TITLE
Add version of library 

### ISSUE THREAD

**Issue by kostazol** [jsdelivr/jsdelivr#18213]
Hello. I'm interested in amcharts4 library. You have version:
https://www.jsdelivr.com/package/npm/@amcharts/amcharts4
https://www.jsdelivr.com/package/npm/@amcharts/amcharts4-ember 

It's github of library https://github.com/amcharts/amcharts4/tree/master/dist

I use compiled library for javascript. I don't want to spend time for understanding how compilate TypeScript to javascript, i want to use library. 
Can you add amcharts4-script?

**Comment by therealadityashankar** [comment]
it appears that armcharts already has its own CDN and you don't need jsdelivr for this,

see : https://github.com/amcharts/amcharts4/tree/master/dist/script#cdn

i.e. you can use
```html
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
```
to directly access the library

**Comment by MartinKolarik** [comment]
You can get these via the `/gh/` endpoint:

https://cdn.jsdelivr.net/gh/amcharts/amcharts4@4.9.22/dist/script/core.js
https://cdn.jsdelivr.net/gh/amcharts/amcharts4@4.9.22/dist/script/charts.js
https://cdn.jsdelivr.net/gh/amcharts/amcharts4@4.9.22/dist/script/themes/animated.js
