### ISSUE TITLE
CDN won't update old files

### ISSUE THREAD

**Issue by webdevstorage** [jsdelivr/jsdelivr#18219]
Hello JsDelivr team,

I have re-published v1.0.0 of our javascript widget. 
https://github.com/warigroup/hashcharger/releases/tag/1.0.0

However, CDN link is keep sending older version of 1.0.0 JS file:
https://cdn.jsdelivr.net/gh/warigroup/hashcharger@1/hashcharger.js
How can I get this updated immediately? It looks like JsDelivr server is keeping cache of an old file.

Thanks,

**Comment by nadchif** [comment]
Take a look at https://github.com/jsdelivr/www.jsdelivr.com/issues/179. You might find it helpful

**Comment by MartinKolarik** [comment]
You can't modify and existing version. If you already had v1.0.0, then publish v1.0.1 and after that the purge API will make it available immediately instead of with a delay.

**Comment by MaverickDe** [comment]
use this method on this GitHub repo, with this your CDN file will be updated as you update your repo
https://github.com/MaverickDe/GITHUBCDN.git
