### ISSUE TITLE
Error 501 Not Implemented occurred while accessing from mainland China

### ISSUE THREAD

**Issue by Makebignew** [jsdelivr/jsdelivr#18214]
An http error 501 occurred to me while I visit https://cdn.jsdelivr.net via latest Chrome Canary ( 85.0.4148.0) in mainland China.

However, everything works fine if i switch to Firefox or Safari. So I assume those Chinese CDN servers must have compatibility issues with latest Chrome Canary browser.

Hopefully you could get on to investigate and fix the problem. Many thanks to you.

![image](https://user-images.githubusercontent.com/20961097/82115020-d3a44900-9792-11ea-88e0-7f08150c1b44.png)

**Comment by jimaek** [comment]
Can you remove the # from the URL and try again please?

**Comment by Makebignew** [comment]
> Can you remove the # from the URL and try again please?

![image](https://user-images.githubusercontent.com/20961097/82115213-07cc3980-9794-11ea-944f-40858b072799.png)
![image](https://user-images.githubusercontent.com/20961097/82115232-1e729080-9794-11ea-8ff7-8f6c688a3c7e.png)
Already tried. Still,nothing changes.

**Comment by jimaek** [comment]
Do the details provide any additional information?
Also please open the developer tools and send the http response headers including the IP address of the hostname

**Comment by Makebignew** [comment]
> Do the details provide any additional information?
Here is what the detail information shows.
![image](https://user-images.githubusercontent.com/20961097/82115386-fdf70600-9794-11ea-8650-d3e5d009f00b.png)

> Also please open the developer tools and send the http response headers including the IP address of the hostname

![image](https://user-images.githubusercontent.com/20961097/82115418-27179680-9795-11ea-90a3-f5c7d3f372be.png)

**Comment by jimaek** [comment]
Great and also scroll down to check the full request headers

**Comment by Makebignew** [comment]
> Great and also scroll down to check the full request headers

![image](https://user-images.githubusercontent.com/20961097/82115548-0ef44700-9796-11ea-92ae-e88be027d4be.png)
As you wish.

**Comment by jimaek** [comment]
Thank you, I contacted Quantil to help us debug this issue and will let you know
