### ISSUE TITLE
More explicit terms of use are needed

### ISSUE THREAD

**Issue by loveTensor** [jsdelivr/jsdelivr#18229]
Hi everyone, I think jsdelivr is a great free CDN. However, I have not found any explicit terms of use that describe what can be done and what is prohibited. This will make people unclear about the use limitation of the service provided by jsdelivr.

For example, is it considered kind of abuse if a person uses jsdelivr and Github together to work as a CDN for static assets? Is there a difference between personal use and commercial use of jsdelivr?

**Comment by jimaek** [comment]
I agree, we need to make this clearer. I think we already have a task for this.
To answer your question it depends. In most cases if its allowed by Github then it is by jsDelivr as well. 
If you host thousands of images of your dog and use Github+jsDelivr as an alternative to Dropbox then that is against the rules.
But if its javascript, css and images requires for the site to operate then its fine.

We will try to make this clearer

**Comment by loveTensor** [comment]
> I agree, we need to make this clearer. I think we already have a task for this.
> To answer your question it depends. In most cases if its allowed by Github then it is by jsDelivr as well.
> If you host thousands of images of your dog and use Github+jsDelivr as an alternative to Dropbox then that is against the rules.
> But if its javascript, css and images requires for the site to operate then its fine.
> 
> We will try to make this clearer

Thanks for your reply. I'm happy to know that you have already realized this problem.
It depends, and what rule it depends should be clear.

**Comment by SukkaW** [comment]
@jimaek @MartinKolarik 

Since more and more people are using GitHub + jsDelivr as free CDN by utilizing `@gh-pages`, `@master`, `@latest`, and it won't be able to cache at CDN Edge for a long time (7 days for now). I am worrying about it will cause significant load increasing on jsDelivr backend server.

For me, Sometime I do use jsDelivr as a free CDN, but I will publish a NPM package (which will be able to store in jsDelivr's S3), and only use very specific version number to make jsDelivr sending `immutable` cache-control header.

If the terms has to be changed, the default cache-control for `@latest`, `@master`, `@gh-pages` should be reconsidered.

**Comment by MartinKolarik** [comment]
@SukkaW right now I think we'll do fine with the current cache times but we might reevaluate them later.

**Comment by MartinKolarik** [comment]
Please check #18247.

**Comment by loveTensor** [comment]
@MartinKolarik @jimaek  So according to [#18247](https://github.com/jsdelivr/jsdelivr/pull/18247), personal or commercial websites whose main purpose is not to display images or videos, if following the terms of use of jsdelivr and Github, are legal to use jsdelivr and Github to cache static assets, right?

**Comment by MartinKolarik** [comment]
If I had to really simplify it:
 1. If the assets are mostly css, js, images, etc., that are part of the design, it's *likely* ok.
 2. If the files are part of the main content, it *may* be a problem. E.g., a news website that used jsDelivr for all images included in the articles would probably still qualify as media hosting, even though the images are not the "main purpose" of it.

Keep in mind that this is a very simplified interpretation and in the second point, we may decide to make exceptions for projects that we consider valuable to the community.

**Comment by loveTensor** [comment]
> If I had to really simplify it:
> 
> 1. If the assets are mostly css, js, images, etc., that are part of the design, it's _likely_ ok.
> 2. If the files are part of the main content, it _may_ be a problem. E.g., a news website that used jsDelivr for all images included in the articles would probably still qualify as media hosting, even though the images are not the "main purpose" of it.
> 
> Keep in mind that this is a very simplified interpretation and in the second point, we may decide to make exceptions for projects that we consider valuable to the community.

@MartinKolarik 
May you please talk more about the differences between your first example and the news website example? Is the news website likely considered as abusing because it uses excessive pictures or any other reason?
By the way, can you talk about using jsdelivr for image hosting of personal blogs?

**Comment by MartinKolarik** [comment]
If the intention of the news site was to simply offload their media hosting to jsDelivr, it would count as abuse. If their intention was to host some kind of open source based news website on GitHub and foster an open source community, it would be acceptable. If you just create a repo with a bunch of images for the only reason of proxying them through jsDelivr, it's probably against our terms.
