### ISSUE TITLE
Require higher limit of package

### ISSUE THREAD

**Issue by LGTMXD** [jsdelivr/jsdelivr#18228]
> Package size exceeded the configured limit of 50 MB. Try https://github.com/hiboyhiboy/opt-file/tree/master/ instead.

Github repository is 
 **https://github.com/hiboyhiboy/opt-file/**

**Comment by MartinKolarik** [comment]
Please check if your project meets our new [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net) and if yes, resubmit this using the newly created issue template.
