### ISSUE TITLE
404 when file is present?

### ISSUE THREAD

**Issue by LeaVerou** [jsdelivr/jsdelivr#18225]
We recently switched to using jsdelivr to fetch plugins in [Mavo](https://mavo.io) and ran into this issue.

It appears that https://cdn.jsdelivr.net/gh/valterkraemer/mavo-firebase/mavo-firebase.js produces a 404 error, and indeed `mavo-firebase.js` is not in the listing here: https://cdn.jsdelivr.net/gh/valterkraemer/mavo-firebase/

However, the file is in the repo: https://github.com/valterkraemer/mavo-firebase

Does the /gh/ syntax only fetch releases? Is there any way to fetch latest commit without knowing the commit hash? Also in this case, the file was present even in the latest release, so even that wouldn't explain what's going on.

cc @karger

**Comment by MartinKolarik** [comment]
There is no such file in https://github.com/valterkraemer/mavo-firebase/archive/2.0.1.zip. Check https://www.jsdelivr.com/features#gh for docs.

**Comment by LeaVerou** [comment]
Thank you! Indeed, it turns out that file wasn't actually present in the release, which explains why jsdelivr couldn't find it. 

FWIW I had looked at the docs on the homepage, as well as the readme in the repo. I now looked at the docs you linked to as well, which seem to have the same information as the former two sources.
In none of them does it mention that the `@latest` and versionless syntaxes work with releases only, and there is no mention of an `@branch` syntax. Perhaps it would be helpful to others if they were added? I would send a PR, but not sure which of the three docs I should send it for.

**Comment by MartinKolarik** [comment]
@latest/no version work with commits too but releases have higher priority, so if a release exists, you have to be explicit. Otherwise, @latest falls back to @master if there are no releases.

> Perhaps it would be helpful to others if they were added? I would send a PR, but not sure which of the three docs I should send it for.

Ideally both the features page and readme.

**Comment by MartinKolarik** [comment]
Closing, feel free to reopen if you have any other questions.
