### ISSUE TITLE
`src` folder missing for `d3-interpolate`

### ISSUE THREAD

**Issue by CompuIves** [jsdelivr/jsdelivr#18223]
First of all, thanks for creating this great service. It's really fast and helps us a lot!

I recently saw that for one dependency a folder is missing `d3-interpolate`: https://www.jsdelivr.com/package/npm/d3-interpolate. On npm the `src` folder, maybe because they republished? I'm not sure if that's possible.

Is there a way to regenerate the cache?

**Comment by MartinKolarik** [comment]
Not yet sure what happened here, the files were available at the [CDN](https://cdn.jsdelivr.net/npm/d3-interpolate@1.4.0/) but not reported by the API for some reason. I deleted the API cache for this version and all files are listed now: https://data.jsdelivr.com/v1/package/npm/d3-interpolate@1.4.0

@jimaek please purge the API URL to make sure it gets refreshed in all locations.

**Comment by CompuIves** [comment]
Wow, that's insanely fast. Thank you so much for the help!!

**Comment by MartinKolarik** [comment]
No problem. If jsDelivr is useful for your project, a mention in the readme or a similar place is always a good way to say thanks 😄
