### ISSUE TITLE
jsDelivr's GitHub CDN file doesn't match GitHub's actual file

### ISSUE THREAD

**Issue by stangri** [jsdelivr/jsdelivr#18220]
Does anyone have an idea why the https://raw.githubusercontent.com/stangri/openwrt-repo/master/Packages.sig and https://cdn.jsdelivr.net/gh/stangri/openwrt-repo@latest/Packages.sig (also tried https://cdn.jsdelivr.net/gh/stangri/openwrt-repo@master/Packages.sig and https://cdn.jsdelivr.net/gh/stangri/openwrt-repo/Packages.sig) files are different?

Am I not referring to the file correctly?

**Comment by MartinKolarik** [comment]
I see that the file was recently modified

![image](https://user-images.githubusercontent.com/6192491/82744453-1bba0180-9d79-11ea-9f59-bb2a413e6321.png)

So most likely you're seeing one of the previous versions and it'll update within a few hours.

**Comment by stangri** [comment]
The problem is that 'Packages' and 'Packages.sig' don't seem to be updated on jsdelivr in sync which causes warnings with OpenWrt package manager which reports wrong signature.

**Comment by MartinKolarik** [comment]
In that case you need to specify exact release version or commit hash in the url.

**Comment by stangri** [comment]
> In that case you need to specify exact release version or commit hash in the url.

Unfortunately I can't do that. I use GitHub/jsdelivr as an OpenWrt repository and the URL I distribute to users should never change.

Is there a way to cause jsdelivr to update its cache for the specific github repo?

I've been using just the GitHub previously, but would like to make use of jsdelivr CDN now.

**Comment by MartinKolarik** [comment]
There's [purge API](https://github.com/jsdelivr/jsdelivr#purge-cache) that can be used to force update cache at the CDN edge servers but the files may still be cached for a short time at our origin servers.

The closest you can get to realtime updates is with publishing to npm, using a link like `/npm/package/file` that references the latest release, and using the [purge API](https://github.com/jsdelivr/jsdelivr#purge-cache) to force update the cache right after release. npm releases should be available everywhere within seconds.

A similar thing should work with GitHub releases, where the propagation time is within minutes. When using `@branch` references, our origin servers may cache individual files for up to 12 hours, which increases the likelihood of different versions being served shortly after an update.

**Comment by stangri** [comment]
> There's [purge API](https://github.com/jsdelivr/jsdelivr#purge-cache) that can be used to force update cache at the CDN edge servers but the files may still be cached for a short time at our origin servers.

Thanks, requested Purge API access from Dmitriy.

> The closest you can get to realtime updates is with publishing to npm, using a link like `/npm/package/file` that references the latest release, and using the [purge API](https://github.com/jsdelivr/jsdelivr#purge-cache) to force update the cache right after release. npm releases should be available everywhere within seconds.

Repo for a different package manager, not npm.

**Comment by MartinKolarik** [comment]
> Repo for a different package manager, not npm.

That doesn't matter, you can publish to npm and then access it via cdn like now.

**Comment by stangri** [comment]
Thanks @MartinKolarik, I was granted Purge API access and will re-open this if I run into problems.

**Comment by ahelmi365** [comment]
Have you found a solution to this issue?
