### ISSUE TITLE
CDN for url

### ISSUE THREAD

**Issue by gerardo-junior** [jsdelivr/jsdelivr#18231]
I have an idea to bring other git repositories by raw view or other systems.

https://cdn.jsdelivr.net/url/https://domain.ttl/assets/js/script.js

**Comment by MartinKolarik** [comment]
We do support that, but only on request, for projects that really need it (and that we consider appropriate).

**Comment by MartinKolarik** [comment]
I'm going to close this since there's nothing to do. If you have a project where this would make sense, feel free to contact me or @jimaek via email.
