### ISSUE TITLE
Add header access-control-allow-headers:*

### ISSUE THREAD

**Issue by neves** [jsdelivr/jsdelivr#18230]
I'm trying to fetch from the browser using 
```js
fetch("https://cdn.jsdelivr.net/npm/@foo/bar", {
  "headers": {
    "if-none-match": "W/\"f8-Oden5wqhR6bUiNaHDBBRopQ3d80\""
  })
```

But I get this error:

Access to fetch at 'https://cdn.jsdelivr.net/npm/@foo/bar' from origin 'http://localhost:5000' has been blocked by CORS policy: Request header **field if-none-match** is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by MartinKolarik** [comment]
This is taken care of automatically by the browser, you shouldn't send any caching related headers.

**Comment by neves** [comment]
I'm using a 1 minute interval function that checks if the file has change and ask the user to refresh the browser to get the latest version. These days, nobody closes a browser tab anymore or restart the browser (desktop or mobile).
Today it works because I can compare the last etag with the current returned from the fetch, the problem is that without "if-not-match", I have to download the whole script body, instead just the headers.

**Comment by MartinKolarik** [comment]
1. the header is called `if-none-match`, not `if-not-match`
2. as I said, it's added automatically by the browser, you are not supposed to add it yourself

**Comment by neves** [comment]
Sorry for the typo, I edited it.
I create a example comparing jsdelivr with unpkg.
https://codepen.io/neves/pen/jOWvqaZ?editors=1011

Here shows that jsdelivr does not allow this header using cors

https://www.test-cors.org/#?client_method=GET&client_credentials=false&client_headers=if-none-match%3A%20W%2F%22f9-rEzC2pHGKOCkAHaFZpjbB%2BkXETo%22&server_url=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2F%40labz%2Fsemver&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

![www test-cors org_](https://user-images.githubusercontent.com/881/87436264-2ea3c200-c5c3-11ea-9af6-0855aeb4f6bf.png)

Can you point me how to achieve that?

**Comment by MartinKolarik** [comment]
Yes, we don't allow the header because you don't need it. Please read my previous comments.

**Comment by MartinKolarik** [comment]
The header would be added automatically if you didn't use `cache: 'no-store'` - I suppose you're trying to bypass `max-age` but still use etags, which is indeed not possible right now.

The problem with custom headers is that they cause a preflight OPTIONS request, so you end up with always making two requests instead of one, which is often even worse than downloading the file.

For the use case you described it should be ok to omit `cache: no-store` to respect the `max-age` and keep etags. You'll still get an updated version after `max-age` expires.
