### ISSUE TITLE
Messed up CSS file from GitHub

### ISSUE THREAD

**Issue by jcubic** [jsdelivr/jsdelivr#18232]
I have two files:

https://raw.githubusercontent.com/jcubic/jquery.terminal/master/css/jquery.terminal.min.css

and

https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@09d43d2c40055ac4f1e37d580623d7f8d96ec0b3/css/jquery.terminal.min.css

the same is with `@devel` the css file is missing `font-family: monospace`. This is very weird I have no idea why it's happening. JSDelivr don't give me my exact file from github.

**Comment by MartinKolarik** [comment]
The jsDelivr link doesn't point to the latest commit, does it? If I use the latest sha from master the file is correct so it seems you are just comparing two different versions?

**Comment by jcubic** [comment]
It was last commit that changed that file, the same is with @devel branch. I need to use css file and min.css file don't work, they should be the same. Unfortunately I can't change different service because non of the other CDN support files directly from GitHub and raw git is not maintained anymore.

**Comment by jcubic** [comment]
It seems that using latest commit works (there is 100% of my CSS file) but using `@devel` don't show my whole file. Does JSDelivr do some optimization with the files?

**Comment by MartinKolarik** [comment]
The latest commit for that file is different, I don't even see the on you used listed here: https://github.com/jcubic/jquery.terminal/commits/master/css/jquery.terminal.min.css

As for devel, the files seem to match and **neither** has `font-family: monospace`
https://raw.githubusercontent.com/jcubic/jquery.terminal/devel/css/jquery.terminal.min.css
https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/css/jquery.terminal.min.css

**Comment by jcubic** [comment]
Sorry it's seems that something was messed on my repo. My mistake.
