### ISSUE TITLE
Document cache times

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/jsdelivr#18234]

**Comment by jcubic** [comment]
What is cache time for combine URL? I would like to use combine where one part is updating. Maybe there is a way to flush cache after release of new version of my package?

I use this url for my app:

https://cdn.jsdelivr.net/combine/npm/jquery,npm/prismjs,npm/prismjs/components/prism-scheme.min.js,npm/@jcubic/lips@beta/lib/js/prism.js,npm/js-polyfills/keyboard.js,npm/jquery.terminal@2.x.x,npm/@jcubic/lips@beta/dist/lips.min.js,npm/@jcubic/lips@beta/lib/js/terminal.js,npm/jquery.terminal/js/prism.js

Just npm/@jcubic/lips@beta give me beta.7 but combine still serve beta.6.

**Comment by jcubic** [comment]
Ok just found this URL in one of the issues https://purge.jsdelivr.net I've called this two times maybe there is some delay but it works, it now server beta.7

**Comment by jimaek** [comment]
Fixed https://github.com/jsdelivr/jsdelivr#caching
