### ISSUE TITLE
Request to increase package size limit for {{name}}

### ISSUE THREAD

**Issue by chygfm** [jsdelivr/jsdelivr#18249]
see:  https://cdn.jsdelivr.net/gh/appemit/appemit/

The package  larger than 50 MB, which is an extensible lightweight middleware for communication between applications (especially browsers) and local programs.
 
This package is very large, and seems no useless files can be deleted.
Is it possible to give this package a higher limit?
thanks.

**Comment by SukkaW** [comment]
It appears that most files are in `lzma` format. Why you want to download those files through jsDelivr?
