### ISSUE TITLE
Failed to fetch version info for china.

### ISSUE THREAD

**Issue by swannyPeng** [jsdelivr/jsdelivr#18244]
Hi,
I'm from China. When I perform
`<script src="https://cdn.jsdelivr.net/npm/netlify-cms@2/dist/netlify-cms.min.js"></script>`
in
```html
<!doctype html>
<html lang="en-us">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Content Manager \| Academic</title>
<!-- Include Netlify Identity for authentication. -->
<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
</head>
<body>
<!-- Include the latest Netlify CMS v2.x.x script that builds the admin panel. -->
<script src="https://cdn.jsdelivr.net/npm/netlify-cms@2/dist/netlify-cms.min.js"></script>
</body>
</html>
```
It  was automatically relocated [https://cdn.jsdelivr.net/china/npm/netlify-cms@2/dist/netlify-cms.js](https://cdn.jsdelivr.net/china/npm/netlify-cms@2/dist/netlify-cms.js)
and return 
```
Failed to load resource: the server responded with a status of 404 ()
     Failed to fetch version info for china.
```
However, it could return the right result when I delete `/china`.

I have no idea that it is the problem of jsdelivr or netlify-cms...

**Comment by MartinKolarik** [comment]
Thanks for reporting! There was an issue in how redirects are handled in China. A fix will be deployed shortly.
