### ISSUE TITLE
Require package size limit (50M).

### ISSUE THREAD

**Issue by Shmilyqjj** [jsdelivr/jsdelivr#18246]
Package size exceeded the configured limit of 50 MB.

My github repo: https://github.com/Shmilyqjj/Shmily-Web

Thanks! Thanks! Thanks!

**Comment by MartinKolarik** [comment]
Please check if your project meets our new [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net) and if yes, resubmit this using the newly created issue template.
