### ISSUE TITLE
Is it possible to support *.wav files?

### ISSUE THREAD

**Issue by zhouxiaobo1990** [jsdelivr/jsdelivr#18242]
*.wav file is not supported. But *.mp3 file is.
Is it possible to support *.wav file as long as they are small?

**Comment by MartinKolarik** [comment]
What's the use case here? AFAIK it isn't supported on the web.

**Comment by zhouxiaobo1990** [comment]
According to [wikipedia](https://en.wikipedia.org/wiki/HTML5_audio#Supporting_browsers), wav file is supported in most of the major browsers except IE.

The advantage of wav file is lossless. We only want to fallback to mp3 format if it's not supported by current browser.

**Comment by jimaek** [comment]
It should start working soon.
