### ISSUE TITLE
Adding "x-xss-protection" header

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18258]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Adding a `x-xss-protection` security header to `cdn.jsdelivr.net`. Not enable the XSS protection, but disable it:

```
x-xss-protection: 0
```

**Describe alternatives you've considered**

Not applicable.

**Additional context**

Google has enabled `x-xss-protection: 0` for following domain:

- fonts.googleapis.com
- fonts.gstatic.com
- s.ytimg.com
- i.ytimg.com
- www.youtube.com
- www.blogger.com
- 1.bp.blogspot.com
- lh3.googleusercontent.com
- www.facebook.com
- And so on.

I don't know why Google is disabling XSS protection for those static cdn domain (even `www.youtube.com`). And what I found is a question at StackExchange:

https://security.stackexchange.com/questions/104508/what-is-the-benefit-of-the-x-xss-protection-0-header-in-a-production-environmen

I assume by disabling the "useless" browser built-in XSS protection there will be performance benefits.

**Comment by MartinKolarik** [comment]
I don't think this is applicable to us because we don't serve HTML content. The header is for the main HTML document, not the other resources it loads.

**Comment by SukkaW** [comment]
> I don't think this is applicable to us because we don't serve HTML content. The header is for the main HTML document, not the other resources it loads.

So do those Google static CDN domain like gstatic.com or ytimg.com. They do add those headers.

**Comment by MartinKolarik** [comment]
Those domains serve a lot of content, some of it may be HTML, or they just changed the headers globally for everything regardless of the content. I'm not sure about their motivation but considering there are many other services that set the value to `1` (including GitHub), that the header is not standardized and actually deprecated by all browsers that originally supported it, and that it has no effect on content other than HTML, I don't think we should add it.

**Comment by jimaek** [comment]
Since nobody else has requested it and I don't see what exact value this provides I think its safe to close.
