### ISSUE TITLE
Github url return 404

### ISSUE THREAD

**Issue by jcubic** [jsdelivr/jsdelivr#18259]
**Describe the bug**
Github url no longer works

**Affected jsDelivr links**

https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/pipe.js

**Response headers**
```
HTTP/2 502 
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=600, s-maxage=600
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-type: text/plain; charset=utf-8
etag: W/"38-ruhERDD7qGoGdq7UVeAJTs9Eues"
fastly-restarts: 1
accept-ranges: bytes
date: Tue, 15 Sep 2020 13:05:02 GMT
x-served-by: cache-hhn4080-HHN
x-cache: MISS
vary: Accept-Encoding
content-length: 56
```

**Screenshots**

**Please complete the following information:**
 - Device OS: [e.g. iOS] Fedora GNU/Linux, Windows 10
 - Browser: [e.g. chrome, safari] Chrome
 - Broser version: [e.g. 22]
 - VPN provider if you use one: None
 - Your location (country):

**Additional context**
Curl return 502 but dev tools console show error:

```
GET https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/pipe.js net::ERR_ABORTED 404
```

The same is in Incognito mode.

What's weirder is that this url works fine: https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/jquery.terminal.min.js

**Comment by MartinKolarik** [comment]
There is a problem that may cause some `@branch` URLs to fail right now. A hotfix will be deployed shortly.
