### ISSUE TITLE
Failed to fetch user/repo@ver from GitHub.

### ISSUE THREAD

**Issue by gitrats07** [jsdelivr/jsdelivr#18251]
I Got This Problem
![image](https://user-images.githubusercontent.com/63937606/91161291-c7664b00-e6f4-11ea-837f-f343d8cfb5d2.png)
Link: https://cdn.jsdelivr.net/gh/gitrats07/mywebsite@v1.0/master/project/aboutme.html

**Comment by MartinKolarik** [comment]
You had *two* typos in the link: https://cdn.jsdelivr.net/gh/gitrats07/mywebsite@v0.1/project/aboutme.html
