### ISSUE TITLE
jsDelivr Does Not Execute The HTML File

### ISSUE THREAD

**Issue by gitrats07** [jsdelivr/jsdelivr#18252]
I Got This Problem
I Opened The Link You Give Me In My Old Issue (#18251), But It Doesn't Execute The HTML File
![image](https://user-images.githubusercontent.com/63937606/91310954-b2fd7d80-e7dc-11ea-8450-6323c41b6f35.png)
Link you gave me: https://cdn.jsdelivr.net/gh/gitrats07/mywebsite@v0.1/project/aboutme.html

**Comment by SukkaW** [comment]
As far as I know it is the desired behavior, preventing any potential abusement.

**Comment by MartinKolarik** [comment]
This is by design: https://github.com/jsdelivr/jsdelivr#restrictions
