### ISSUE TITLE
Host link doesn’t work

### ISSUE THREAD

**Issue by joshuazhangk** [jsdelivr/jsdelivr#18262]
I host the .js on GitHub repository and CDN it via JSdeliver. but it’s doesn’t work
Here is the GitHub link which works well
https://raw.githubusercontent.com/joshuazhangk/gradient/main/gradient.js

The host link below doesn’t work
https://cdn.jsdelivr.net/gh/joshuazhangk/gradient/main/gradient.js

Does anyone know how to fix it? Thank you

**Comment by MartinKolarik** [comment]
https://cdn.jsdelivr.net/gh/joshuazhangk/gradient@main/gradient/gradient.js
