### ISSUE TITLE
File size exceeded the configured limit of 20 MB, Not 50 MB in Document

### ISSUE THREAD

**Issue by laozhoubuluo** [jsdelivr/jsdelivr#18268]
**Describe the bug**
According the https://github.com/jsdelivr/jsdelivr/blob/master/README.md , The default file limit is 50 MB.
When I configure the 3rd party package link to my project, I found this limit reduce to 20 MB.
**This issue not a request to increase package size limit, Because I didn't have any of them. This issue just need the maintainer confirm this limit is a custom limit for some filetype or a system bug.**
**If it's a system bug, please fix it. If it's a custom limit for some filetype, can the specific restriction strategies for different filetypes (including the black and white lists of filetypes and the size limits of different filetypes) be published at an appropriate time, so that users can apply this project more reasonably.**

**Affected jsDelivr links**
One or more direct links that are affected by this issue.
https://cdn.jsdelivr.net/gh/lxgw/kose-font/TTF%20(Japanese)/Kosefont-JP.ttf
https://cdn.jsdelivr.net/gh/lxgw/kose-font/TTF%20(Japanese)/KosefontP-JP.ttf
https://cdn.jsdelivr.net/gh/lxgw/kose-font/TTF%20(Simplified%20Chinese)/XiaolaiMonoSC-Regular.ttf
https://cdn.jsdelivr.net/gh/lxgw/kose-font/TTF%20(Simplified%20Chinese)/XiaolaiSC-Regular.ttf
https://cdn.jsdelivr.net/gh/laishulu/Sarasa-Mono-SC-Nerd/sarasa-mono-sc-nerd-regular.ttf

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.

From Los Angeles Server: 

```
< HTTP/2 403
< date: Fri, 18 Dec 2020 13:20:46 GMT
< content-type: text/plain; charset=utf-8
< content-length: 49
< access-control-allow-origin: *
< access-control-expose-headers: *
< timing-allow-origin: *
< cache-control: no-cache, no-store, must-revalidate
< cross-origin-resource-policy: cross-origin
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< etag: W/"31-k+6Q3j1xpRkytHAFAlbWO0rgS3g"
< x-served-by: cache-fra19171-FRA, cache-bur17565-BUR
< x-cache: MISS, MISS
< vary: Accept-Encoding
< cf-cache-status: BYPASS
< cf-request-id: 07179b9fb00000ebb534af1000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 60392edf8c91ebb5-LAX
<
* Connection #0 to host cdn.jsdelivr.net left intact
File size exceeded the configured limit of 20 MB.
```

From Beijing Server: 

```
< HTTP/2 403
< date: Fri, 18 Dec 2020 13:27:02 GMT
< content-type: text/plain; charset=utf-8
< content-length: 49
< access-control-allow-origin: *
< access-control-expose-headers: *
< timing-allow-origin: *
< cache-control: no-cache, no-store, must-revalidate
< cross-origin-resource-policy: cross-origin
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< etag: W/"31-k+6Q3j1xpRkytHAFAlbWO0rgS3g"
< accept-ranges: bytes
< x-served-by: cache-fra19149-FRA, cache-hkg17926-HKG
< x-cache-spec: Yes
< x-via: 1.1 PSxgHK5bd29:1 (Cdn Cache Server V2.0), 1.1 dwt198:0 (Cdn Cache Server V2.0), 1.1 wt94:14 (Cdn Cache Server V2.0)
< x-ws-request-id: 5fdcae25_wt94_43160-37246
<
* Connection #0 to host cdn.jsdelivr.net left intact
File size exceeded the configured limit of 20 MB.
```

**Screenshots**

**Please complete the following information:**
 - Device OS: Linux
 - Browser: cURL
 - Broser version: 7.64.0
 - VPN provider if you use one: -
 - Your location (country): Los Angeles, USA and Beijing, China

**Additional context**

**Comment by MartinKolarik** [comment]
Hi @laozhoubuluo, 20 MB is the correct limit for a single file. 50 MB is for a whole repository.

**Comment by laozhoubuluo** [comment]
> 
> 
> Hi @laozhoubuluo, 20 MB is the correct limit for a single file. 50 MB is for a whole repository.

I make a pull request to add this restrictions to document, Please consider merge or add this item by yourself, thank you.
