### ISSUE TITLE
user is blocked

### ISSUE THREAD

**Issue by oophzh** [jsdelivr/jsdelivr#18267]
hi, Some pictures and js resources on my git cannot be accessed through jsdelivr, and the display is blocked, as shown below:

url: https://cdn.jsdelivr.net/gh/oophzh/soccershopping@0.0.188/joyeriachile.online/customize-adv-30.jpg

error message:
User oophzh is blocked. Please refer to https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net for more information.

**Comment by SukkaW** [comment]
The error message is clear that you have violated the term of jsDelivr.

**Comment by oophzh** [comment]
which term ? can you tell me? if i know the detail, i will make corrections.










At 2020-11-25 11:40:53, "Sukka" <notifications@github.com> wrote:

The error message is clear that you have violated the term of jsDelivr.

**Comment by jimaek** [comment]
You are hosting fake e-shops and using jsDelivr to serve content. This is fake Pandora for example https://github.com/oophzh/soccershopping/tree/master/doraide.net

That is illegal in most countries

**Comment by oophzh** [comment]
thank for your replay， i got it, if i delete these images, can i continue using other resources?
