### ISSUE TITLE
webjars assets 404'ing intermittently

### ISSUE THREAD

**Issue by david-wg2** [jsdelivr/jsdelivr#18265]
**Describe the bug**
We're building an application with WebJars, and in production we're using jsDelivr to serve them:

```
<link href="https://cdn.jsdelivr.net/webjars/org.webjars.npm/roboto-fontface/0.10.0/css/roboto/roboto-fontface.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/webjars/org.webjars.npm/mdi__font/5.0.45/css/materialdesignicons.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/webjars/org.webjars.npm/vuetify/2.0.18/dist/vuetify.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/webjars/org.webjars.npm/vue/2.6.10/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/webjars/org.webjars.npm/axios/0.19.0/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/webjars/org.webjars.npm/vuetify/2.0.18/dist/vuetify.js"></script>
```

Sometimes (most recently today at 10:14 CEST), these files will return 404, and our application will be completely dead.

The issue usually resolves itself after a couple of minutes (and refreshes).

**Affected jsDelivr links**
An unknown number of the links above, I can update the issue the next time it happens.

**Response headers**
I can update the issue the next time it happens.

**Please complete the following information:**
 - Device OS: macOS, Ubuntu, Windows (probably also mobile)
 - Browser: Any
 - Your location (country): Norway, England, Canada (but probably all)

**Comment by jimaek** [comment]
These files are proxied from your origin, is there any chance the issue is there? Maybe some deployment script is failing?
We will check everything on our side too in the meantime.

**Comment by david-wg2** [comment]
> These files are proxied from your origin, is there any chance the issue is there?

What do you mean they're proxied from our origin? Our users are accessing these files directly from your servers through their browsers. 

We're not affiliated with the WebJars project in any way, if that's what you thought? We're just a company building an app by using WebJars.

**Comment by jimaek** [comment]
Oh I am sorry, I thought you are a maintainer of webjars. I will get in contact with them then to make sure its not an issue on their side.

Thank you

**Comment by david-wg2** [comment]
> Oh I am sorry, I thought you are a maintainer of webjars. I will get in contact with them then to make sure its not an issue on their side.

No problem, thanks for your swift response :)

**Comment by jamesward** [comment]
I believe this has been fixed.  Let me know if not.
