### ISSUE TITLE
CDN not updating

### ISSUE THREAD

**Issue by TheoFreud** [jsdelivr/jsdelivr#18271]
**Describe the bug**

I have deleted the tags and created a new tag on 0.0.2 and it is not getting the latest css stylesheet. Is there also a way to it to always take the latest version without specifying the tag?

**Affected jsDelivr links**
One or more direct links that are affected by this issue.

https://cdn.jsdelivr.net/gh/TheoFreud/glassesUSA@0.0.2/css/index.css

**Additional context**

https://github.com/TheoFreud/glassesUSA/releases

**Comment by MartinKolarik** [comment]
You can't change existing tags, release a `0.0.3` instead. Then you can also link to `@latest`

**Comment by TheoFreud** [comment]
How long does it take for `@latest` to update?

**Comment by TheoFreud** [comment]
How long does it take for `@latest` to update?

**Comment by TheoFreud** [comment]
So its seems `@latest` updates only when manually purged using https://purge.jsdelivr.net/?

@MartinKolarik

**Comment by MartinKolarik** [comment]
12 - 24 hours

**Comment by glassesUSA** [comment]
Hey,

It's been nearly 24 hours since the last release and `@latest` has still not updated with the latest changes?

**Comment by MartinKolarik** [comment]
Your latest release is not a valid semver number so it's ignored for `@latest` resolution. Use `0.3.0` instead.
