### ISSUE TITLE
Purge never works for me as intended

### ISSUE THREAD

**Issue by xd003** [jsdelivr/jsdelivr#18273]
**Describe the bug**
Even after purging the files , they are not getting updated in jsdelivr cdn . I have purged it so many times already in past 1 hour but still it's displaying the old file. Here's the url i used for purging my file - https://purge.jsdelivr.net/gh/xd003/gindex-v4@frontend-8.3.0/vuejs/dist/app.js 

**Affected jsDelivr links**
Here's the affected jsDelivr link - https://cdn.jsdelivr.net/gh/xd003/gindex-v4@frontend-8.3.0/vuejs/dist/app.js

Here's the Upstream file from my github repo
https://github.com/xd003/gindex-v4/blob/frontend-8.3.0/vuejs/dist/app.js

**Please complete the following information:**
 - Device OS: Android
 - Browser: Kiwi
 - Your location (country): India

**Comment by jimaek** [comment]
You need to follow semver for repo tags. Also you can't modify existing files, we cache them permanently.
So purge works just fine you just are not using the service correctly, it's not a traditional CDN where you can update and purge any file you want.

**Comment by xd003** [comment]
@jimaek thanks for the quick reply , i appreciate it . What actually happened is released v8.3.0 but i forgot a very small commit so i deleted that release and pushed the commit and then rereleased the same v8.3.0 again and jsdelivr was always pointing the older v8.3.0 . Just so i am understanding it correctly , to avoid this situation i would need to draft a new release even if a very small is done right ?

**Comment by MartinKolarik** [comment]
Yes, an existing release can't be modified. Purge works if you have an URL like `@8` and want it to change from 8.3.0 to 8.3.1
