### ISSUE TITLE
Prerelease version handling question

### ISSUE THREAD

**Issue by SokratisVidros** [jsdelivr/jsdelivr#18274]
How does JSDelivr handle semver npm prerelease identifiers when a version range is specified? For example if we have a npm package with the following versions in NPM:

```
1.1.3-pre-release.0
1.1.2
1.1.1
1.1.0
1.0.0
```

Will https://cdn.jsdelivr.net/npm/mylib@1 fetch the latest `1.1.3-pre-release.0` version or will it fallback to `1.1.2`?

Thank you.

**Comment by MartinKolarik** [comment]
It works the same way as npm. In this case, `1.1.2` would be used.

**Comment by SokratisVidros** [comment]
Thanks @MartinKolarik

**Comment by SokratisVidros** [comment]
@MartinKolarik Does the same apply to [dist tags](https://docs.npmjs.com/adding-dist-tags-to-packages)? I noticed that deploying a new version with a dist tag bumped everything. For example

```
Old version 1.0.0
New verison 1.0.1 with dist tag `staging`
```

The outcome was that https://cdn.jsdelivr.net/npm/mylib@1  fetches 1.0.1.

Thanks in advance

**Comment by MartinKolarik** [comment]
@SokratisVidros what's your package name/link?

**Comment by SokratisVidros** [comment]
https://www.jsdelivr.com/package/npm/@clerk/clerk-js.

```
Currently version 1.0.10
Latest staging version 1.0.11 with staging tag

```

**Comment by MartinKolarik** [comment]
Ok, I see. The tags are simply aliases to their versions, so `@latest` -> `1.0.10`, `@staging` -> `1.0.11`. A range `@1` is not a tag - it means "highest matching 1.x.x version that is not a prerelease", which is `1.0.11`.

**Comment by SokratisVidros** [comment]
I see. So to avoid that in the future the package.json for the next prerelease version should be `1.0.12-prerelease.0`. Thanks for the quick reply.
