### ISSUE TITLE
Consider blocking served images from crawling by search engines

### ISSUE THREAD

**Issue by theDavidBarton** [jsdelivr/jsdelivr#18278]
**Is your feature request related to a problem? Please describe.**
When you search for specific content on [Google image Search](https://www.google.hu/imghp?hl=en) you can face that most of the images are the logos appearing on the relevant sites (e.g. in case of portfolio sites and resumes) and mostly coming from [https://www.jsdelivr.com/package/npm/simple-icons](https://www.jsdelivr.com/package/npm/simple-icons). These logos are semantically not related to the search and would be better to exclude them from the results.

Example search query: [`inurl:cdn.jsdelivr.net/npm/simple-icons`](https://www.google.com/search?hl=en&authuser=0&tbm=isch&source=hp&biw=1440&bih=757&ei=csIdYISSBoaOlwSasYSACA&q=inurl%3Acdn.jsdelivr.net%2Fnpm%2Fsimple-icons&oq=inurl%3Acdn.jsdelivr.net%2Fnpm%2Fsimple-icons&gs_lcp=CgNpbWcQA1CdTVidTWDSWWgBcAB4AIABeYgBeZIBAzAuMZgBAKABAqABAaoBC2d3cy13aXotaW1nsAEA&sclient=img&ved=0ahUKEwiEk4bC4dPuAhUGx4UKHZoYAYAQ4dUDCAc&uact=5)

For me it looks unintentional and also it is something cannot be solved by deindexing on the side of the content uploader (as the property owner is jsDelivr.net itself and not the one who uses the svg-s from CDN).

**Describe the solution you'd like**
If you agree that it is a valid problem: I suggest considering blocking the served images from crawling by the search engines.

**Describe alternatives you've considered**
Either it could be done by bulk removal of the svg-s via Google Search Console's [Removal Tools](https://search.google.com/search-console/removals), or additional rules in the `robots.txt` could prevent this behaviour. E.g.:
```
Disallow: /*.svg$
Disallow: /*.png$
...
```
or
```
User-agent: Googlebot-Image
```

**Additional context**
It is visible that many logos land in the image search results from the CDN at the moment:

![image](https://user-images.githubusercontent.com/43063460/107096280-aa3cb900-680a-11eb-97ca-ef74dba5be90.png)

p.s.: I am still not sure if this feature request is relevant here at the [CDN's](https://github.com/jsdelivr/jsdelivr/) repo or rather would be at the [jsDelivr website](https://github.com/jsdelivr/www.jsdelivr.com) repo. Let me know if I should move it there. Thanks!

**Comment by SukkaW** [comment]
As far as I know, the approach is not used by any other "public" service.

For example, you could try the following queries and see what you can find:

```
inurl:raw.githubusercontent.com
```

**Comment by theDavidBarton** [comment]
Thanks for your reply. And you are right, I played with queries of other image CDN-s: they neither bothered by this phenomenon. I close the issue.
