### ISSUE TITLE
Failed to fetch version info

### ISSUE THREAD

**Issue by TheoFreud** [jsdelivr/jsdelivr#18270]
**Describe the bug**

Failed to fetch version info for TheoFreud/glassesUSA.

**Affected jsDelivr links**
One or more direct links that are affected by this issue.

https://cdn.jsdelivr.net/gh/TheoFreud/glassesUSA/styles/index.css

**Additional context**

**Comment by jimaek** [comment]
You are missing tags in your repo https://github.com/TheoFreud/glassesUSA/tags
