### ISSUE TITLE
The new project is confused that the default has been changed to `main`

### ISSUE THREAD

**Issue by fu-sen** [jsdelivr/jsdelivr#18284]
Starting October 2020, the new GitHub project has its branch name changed from `master` to` main`:
https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

As a result, the following examples posted on the top page etc. will not work:
```
// omit the version completely to get the latest one
// you should NOT use this in production
https://cdn.jsdelivr.net/gh/jquery/jquery/dist/jquery.min.js
```
and
```
// add / at the end to get a directory listing
https://cdn.jsdelivr.net/gh/jquery/jquery/
```

If a recent project references this reference, you will receive this message:
```
Failed to fetch user/project@latest from GitHub.
```

The workaround is to explicitly specify the `main` branch:
```
https://cdn.jsdelivr.net/gh/user/repo@main/file
```
Or change the `main` branch to the` master` branch.

This is confusing if you recently created a project.

**Comment by MartinKolarik** [comment]
Technically the docs talk mainly about releases and nothing changed there. Still, we're already tracking this in #18248
