### ISSUE TITLE
Serving from github gives 404 in the first ~15 minutes after a commit

### ISSUE THREAD

**Issue by fonsp** [jsdelivr/jsdelivr#18289]
**Describe the bug**

I am accessing files from our github repository using the commit hash, e.g.

```
https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@7b944bc/frontend/components/RunArea.js
```

I found that _right after making a commit_ (<15 minutes), **some** resources return a 404 (`Failed to fetch fonsp/Pluto.jl@7b944bc from GitHub.`), while others load correctly. The resources that 404 gradually come online. 

The problem has been consistent today. The set of resources that are slow is different for every commit. _I believe that this is a new issue, I did not encounter it in the past 6 months._

**Affected jsDelivr links**
Since this issue is time-bound, I cannot give any links that 404 permanently.

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.

```
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: *
age: 0
cache-control: no-cache, no-store, must-revalidate
content-encoding: gzip
content-length: 71
content-type: text/plain; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Tue, 16 Mar 2021 14:09:08 GMT
etag: W/"33-RND79LZSZC2UN/GjJrGJfV/f0L0"
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: MISS, MISS
x-content-type-options: nosniff
x-served-by: cache-fra19140-FRA, cache-hhn4047-HHN
```

**Screenshots**

In [this screenshot](https://user-images.githubusercontent.com/6933510/111323248-fa106a80-8669-11eb-8a29-7b4b5381b664.png), you see two request on the same commit hash made at the same time. One succeeds, one gives a 404. After about 15 minutes, the second request also succeeds.

**Please complete the following information:**
 - Device OS: MacOS
 - Browser: Chrome
 - Broser version: 89
 - VPN provider if you use one: -
 - Your location (country): Berlin, Germany

**Additional context**
The repository contains static assets, no large files.

**Comment by jimaek** [comment]
Closing for the benefit of https://github.com/jsdelivr/jsdelivr/issues/18288
