### ISSUE TITLE
Remove comment header from dynamically generated files

### ISSUE THREAD

**Issue by jorgebucaran** [jsdelivr/jsdelivr#18281]
I would like to first thank you for this excellent service. I just thought that it would be nicer if dynamically generated, minified files didn't include a comment header by default. We can warn people about not using SRI with dynamically generated files in the documentation instead.

**Comment by MartinKolarik** [comment]
We did consider the impact of adding the comment and it is really negligible - when gzipped, it adds about 160 bytes. The SRI thing is already mentioned in the docs too but it's still valuable that we are easily able to distinguish between original files and the generated ones, that we immediately know the source file and occasionally even the information about the terser version is useful.

**Comment by jorgebucaran** [comment]
I understand. Would you consider a smaller, one-line comment then?

// Optimized by https://jsdelivr.com

**Comment by MartinKolarik** [comment]
That wouldn't cover the "know the source file and information about tool(s) version(s)"
