### ISSUE TITLE
unable to download ttf file

### ISSUE THREAD

**Issue by GopherJ** [jsdelivr/jsdelivr#18280]
**Describe the bug**

```
curl -sSLO https://cdn.jsdelivr.net/gh/tonsky/FiraCode/distr/ttf/FiraCode-Light.ttf
```

returns back:

```
Couldn't find the requested file /distr/ttf/FiraCode-Light.ttf in tonsky/FiraCode.
```

**Affected jsDelivr links**
One or more direct links that are affected by this issue.

https://cdn.jsdelivr.net/gh/tonsky/FiraCode/distr/ttf/FiraCode-Light.ttf

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.
![image](https://user-images.githubusercontent.com/33961674/107459449-2def0080-6b91-11eb-8518-55fc3bc36efb.png)

**Screenshots**

**Please complete the following information:**
 - Device OS: Linux Mint v20 Cinamon
 - Browser: firefox
 - Broser version: 85+
 - VPN provider if you use one: none
 - Your location (country): China

**Additional context**

**Comment by jimaek** [comment]
If you go here https://cdn.jsdelivr.net/gh/tonsky/FiraCode/ you will see that it thinks the latest version is 0.2.1 and that file doesnt exist there. 
That project is not using semver to tag it's releases and thats why jsDelivr is confused.
They could tag a new semver valid release to fix this, or you could use this format of URL:

https://cdn.jsdelivr.net/gh/tonsky/FiraCode@5/distr/ttf/FiraCode-Light.ttf

**Comment by GopherJ** [comment]
@jimaek thanks works like a charm!
