### ISSUE TITLE
Lot of 404 errors from GitHub

### ISSUE THREAD

**Issue by jcubic** [jsdelivr/jsdelivr#18288]
**Describe the bug**
I have all https://jcubic.github.io/lips-test/ and it's broken because of jsDevlr it keep returning 404 and I can't fix that myself becuase of rate limit of purge. I will need to purge every URL from github I use to fix the issue I've fixed one URL now I'm blocked.

**Affected jsDelivr links**
https://cdn.jsdelivr.net/gh/jcubic/lips@devel/lib/js/terminal.js
https://cdn.jsdelivr.net/gh/jcubic/lips@devel/lib/js/prism.js
https://cdn.jsdelivr.net/gh/jcubic/lips@devel/dist/std.scm

**Response headers**
```
access-control-allow-origin: *
access-control-expose-headers: *
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: no-cache, no-store, must-revalidate
cf-cache-status: BYPASS
cf-ray: 630e6d1cca5c23df-ZRH
cf-request-id: 08dce285fb000023df7a848000000001
content-encoding: br
content-type: text/plain; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Tue, 16 Mar 2021 13:46:11 GMT
etag: W/"2e-imGXoMCWfAoZEQ4fl+wKJedceck"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: MISS, MISS
x-content-type-options: nosniff
x-served-by: cache-fra19120-FRA, cache-cdg20770-CDG
```

**Please complete the following information:**
 - Device OS: [e.g. iOS] Windows
 - Browser: [e.g. chrome, safari]
 - Broser version: [e.g. 22]
 - VPN provider if you use one:
 - Your location (country):

**Comment by fonsp** [comment]
We are also getting 404 errors on a subset of our gh assets, the behaviour seems inconsistent.

For example:
```
https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@b29f293/frontend/components/Editor.js
```
gives a 404, even though it is listed in the directory listing:
```
https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@b29f293/frontend/components/
```
and other files inside the same directory, with the same commit hash, work.


Note that unlike #18289, I am also getting reports about 404 errors on git commits that are not recent, the example above is a commit from 6 days ago.

**Comment by jimaek** [comment]
We are looking into this right now. I will have an update soon

**Comment by jimaek** [comment]
The issue is limited to new uncached files hosted on Github. The reason is that we hit their rate-limiting mechanism because of abusive behavior originating in Hong-Kong. 
We are working on fixing this asap

**Comment by jimaek** [comment]
I believe everything should be back to normal, we fixed the issue a while ago. 
Our multi-layered caching prevented this from becoming a big problem and only new requests for new files should have been impacted. 
We blocked the abusive requests and now work on adding checks to avoid this from happening again.

I am sorry for any problems this issue caused and thank you for reporting the issue.

**Comment by jcubic** [comment]
Awesome thanks for fast fix. It seems that for my case it works fine.
