### ISSUE TITLE
Custom domain with jsdelivr

### ISSUE THREAD

**Issue by js-kyle** [jsdelivr/jsdelivr#18285]
Hi there,

I have a requirement to serve front end npm assets from a custom domain, ideally, I would like to just use jsdelivr. 

Does jsdelivr support use through using a proxy? i.e. I proxy a custom domain through to jsdelivr, or, some other type of solution?

Thank you

**Comment by jimaek** [comment]
If the only thing that you need is serving of NPM files and dont need the CDN part then you can use any kind of reverse proxy without a problem. Our service will only accept the cdn.jsdelivr.net domain, so you can just configure the proxy to always send that host.
But unfortunately there is no way to use a custom domain with our CDN.

**Comment by js-kyle** [comment]
Awesome - thanks for the response @jimaek that works well for my needs.
