### ISSUE TITLE
Request to increase package size limit for webots

### ISSUE THREAD

**Issue by omichel** [jsdelivr/jsdelivr#18283]
**Link to the package or GitHub repository**
https://github.com/cyberbotics/webots

**Project license**
Apache 2.0

**Your relation to the project**
maintainer

**Short description of the project**
We use jsdelivr to cache the Webots documentation files from github (a few js files, markdown files and images) and display it on our [web site](https://www.cyberbotics.com/doc/guide/index).

**Please confirm the following:**
 - [x] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
 - [x] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).

**Additional information**
This [url](https://www.cyberbotics.com/doc/reference/supervisor?version=a7c3fef71574dcbbc8576e726e36b510b89d23a0) is currently broken due to 403 answers from jsdelivr.

This [url](https://www.cyberbotics.com/doc/reference/supervisor?version=released) currently works, but we fear it will break soon.

I guess increasing the package size limit to 100mb instead of 50mb should fix the problem.

**Comment by MartinKolarik** [comment]
For GitHub, the package limit only applies if the requested file is itself above 20 MB, or if it doesn't exist. I see the link that was broken was for a recent commit and suspect that the file was first requested shortly before it was actually published and the 404 response got cached for a while. It should work now.
