### ISSUE TITLE
Package size exceeded the configured limit of 50 MB

### ISSUE THREAD

**Issue by ChrisHSandN** [jsdelivr/jsdelivr#18294]
**Describe the bug**
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/build/ol.js

Reports `Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/en/v6.1.1/build/ol.js instead.`

However https://packagephobia.com/result?p=ol@6.1.1 reports it is only 6MB, and this package has been working happily for months now and not returning this error.

**Affected jsDelivr links**
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/build/ol.js

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.
```
General:
Request URL: https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/build/ol.js
Request Method: GET
Status Code: 403 
Remote Address: 151.101.62.109:443
Referrer Policy: strict-origin-when-cross-origin

Response Headers:
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: *
age: 13074
cache-control: public, max-age=604800, s-maxage=43200
content-length: 150
content-type: text/plain; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Tue, 13 Apr 2021 08:17:51 GMT
etag: W/"96-8pNdzjIZK8jpliQWPm5wMpsZV8U"
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: HIT, HIT
x-content-type-options: nosniff
x-served-by: cache-fra19152-FRA, cache-lhr7350-LHR
```

**Please complete the following information:**
 - Device OS: [e.g. iOS] Windows 10
 - Browser: [e.g. chrome, safari] Chrome
 - Broser version: [e.g. 22] 89.0.4389.114
 - VPN provider if you use one: None
 - Your location (country): UK

**Comment by MartinKolarik** [comment]
jsDelivr is normally able to fetch individual files instead of the whole branch, so this limit doesn't usually apply unless you request a directory listing. What most likely happened here is that there was a temporary issue with fetching individual files, which triggered fetching the whole tarball as a fallback, which then failed with this error. The link should now work again.

**Comment by ChrisHSandN** [comment]
Thanks for your quick reply,

Unfortunately it still is returning a 403 and looking at the resources for that package:
https://github.com/openlayers/openlayers/releases/tag/v6.1.1

While I am not sure exactly which one it uses none of them are near 50MB, the `Source code (tar.gz)` is 11MB, and the largest `v6.1.1.zip` is only 26MB

**Comment by 17tgt040-sys** [comment]
unnko
