### ISSUE TITLE
Remove my library from CDN

### ISSUE THREAD

**Issue by Hrishikesh-K** [jsdelivr/jsdelivr#18297]
Hello.

I was developing a JS library and since it's my first time, I was testing out various stuff. Because of this, I ended up publishing a lot of versions, etc. and now that I'm done testing, I wish to remove the library till I'm done fixing it. How can I do it?

I tried emailing for a purge cache API request to the email from Readme, but didn't get a response.

**Comment by jimaek** [comment]
I will reply back to the email, didnt yet have time to check it yet.
