### ISSUE TITLE
Excessive requests from jsdelivr

### ISSUE THREAD

**Issue by burtonquantil** [jsdelivr/jsdelivr#18292]
QUANTIL has provided you with CDN service as a sponsor. 
There are a number of problems with your current use of our service.
1) 
We found you are generating excessive purge requests to our system from IP address, 46.252.181.15. They have been happening at least every second and reached the point where you exceeded the number of file purges permitted in a day.
2) You are requesting purges of the same files over and over even though the previous request is incomplete.
Example:

>  <?xml version="1.0" encoding="UTF-8" standalone="yes"?><purge-urls><version>1.0.0</version><file-url>https://cdn.jsdelivr.net/gh/NobyDa/Script@master/JD-DailyBonus/JD_DailyBonus.js</file-url><dir-action>expire</dir-action></purge-urls>
> <message><![CDATA[Your previous purge request for the following URLs is still in progress: https://cdn.jsdelivr.net/gh/NobyDa/Script@master/JD-DailyBonus/JD_DailyBonus.js. Please submit another purge request for the other URLs. ]]></message></response>

This flood of requests s is affecting the service we provide to our customers.
Please review what you are doing and stop the unnecessary requests. 
We may need to pause your use of our service if it continues to cause problems.

**Comment by jimaek** [comment]
As discussed over email we are working on a solution to this!
