### ISSUE TITLE
Request to increase package size limit for BootsWatch

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [jsdelivr/jsdelivr#18299]
**Link to the npm package or GitHub repository**
https://github.com/thomaspark/bootswatch/issues/1084

**Project license**
MIT

**Your relation to the project**
user

**Short description of the project**
The bootswatch project provides 22, now 25 themes for Bootstrap, the themes keeps increasing by each new release. While the package is available via npm. Most of the users prefer Github as forking and editing is easy. And i use it on gdi.js.org where i need to use GitHub as many users wants to fork bootswatch and edit the themes before using them in fork of my project.

**Please confirm the following:**
 - [ x ] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
 - [ x ] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).

**Additional context**

**Comment by MartinKolarik** [comment]
We recommend using npm where possible in general and since in this case the project even officially supports and recommends the npm package I don't think it's a good idea to use the GH repo.
