### ISSUE TITLE
jsdelivr - update changes from github?

### ISSUE THREAD

**Issue by Frank-Sin99** [jsdelivr/jsdelivr#18295]
I host JS script via jsdelivr and github. Sadly if I change a file, the changes are not update in jsdelivr.

I have to make always a new folder for everything and change the folder name and update the changed links inside the html files...Very cumbersome!

How can I change this?

**Comment by jimaek** [comment]
You need to use tags and tag new releases so jsDelivr could pick up the changes. Otherwise we will continue serving data from our cache for performance reasons.

**Comment by Frank-Sin99** [comment]
@jimaek Thanks. Could you make an example for the link?
