### ISSUE TITLE
Please add support for the Github symlink files

### ISSUE THREAD

**Issue by gbtami** [jsdelivr/jsdelivr#18290]
https://github.com/gbtami/pychess-variants is a chess variants server. It supports several piece set themes and uses symlinked files in several .css files. For example in this .css file https://github.com/gbtami/pychess-variants/blob/master/static/piece/makruk/makrukwb.css
`.makruk .cg-wrap piece.p-piece.white {
    background-image: url('../../images/pieces/makruk/ada/wb/wP.svg');
}
`
ada/wb/wP.svg is a symlink to ada/orig/wP.svg

 On Heroku it is all OK, but if I change static assets to use jsDelivr it doesn't serves symlinked (on github) files.

**Comment by MartinKolarik** [comment]
This is a limitation of how GitHub handles it, it doesn't work when accessed directly either: https://raw.githubusercontent.com/gbtami/pychess-variants/master/static/images/pieces/makruk/ada/wb/bB.svg

**Comment by MartinKolarik** [comment]
Well, the endpoint is just a proxy to GitHub so it has the same limitations. How Heroku works is not relevant here at all.

**Comment by gbtami** [comment]
Maybe to serve symlinked files via GitHub JSON API, idk.
https://api.github.com/repos/gbtami/pychess-variants/contents/static/images/pieces/makruk/ada/wr/bB.svg?ref=master

**Comment by gbtami** [comment]
OK, I think i can solve my issue if i use the not symlinked file URLs in .css files instead of using directories having symlinked files.
Sry for the noise :)
