### ISSUE TITLE
DNS service at maxcdn.bootstrapcdn.com port 443

### ISSUE THREAD

**Issue by vebmaster** [jsdelivr/jsdelivr#18300]
Hello.
Can you please tell me if the host maxcdn.bootstrapcdn.com port 443 has any DNS service?
For example DNS over TLS (DoT) or other DNS service?
Thank you.

**Comment by vebmaster** [comment]
The problem is that I android smartphone through the browser Fennec (firefox) opened a site and Netguard firewall fixed tcp v4 connection to maxcdn.bootstrapcdn.com port 443 from the user root.

The rest of the connections from the root user are DNS over TLS (DoT) requests on port 853.

Screenshot of the NetGuard firewalls - https://disk.yandex.ru/i/5dSjft5sUM3qCw

**Comment by jimaek** [comment]
We do not provide any kind of DNS services. 443 is used for HTTPS
