### ISSUE TITLE
cannot import "lit" via esm.run due to missing lit-html dependency

### ISSUE THREAD

**Issue by rwaldin** [jsdelivr/jsdelivr#18304]
The following esm import fails: `import { LitElement } from 'https://esm.run/lit';`

due to this missing dependency: `https://cdn.jsdelivr.net/npm/lit-html@2.0.0-rc.3/+esm`

The error can be observed in devtools by navigating to the jsfiddle page for "lit" on this page: https://www.jsdelivr.com/esm

**Comment by MartinKolarik** [comment]
It's because we don't currently consider the `main` field for packages, only `module` - this is planned to be changed soon.

**Comment by MartinKolarik** [comment]
This issue should be fixed now 🎉
