### ISSUE TITLE
Update Terser version

### ISSUE THREAD

**Issue by Lakuna** [jsdelivr/jsdelivr#18303]
**Is your feature request related to a problem? Please describe.**
The current version of Terser used by jsDelivr doesn't support some modern language features, such as [private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields).

**Describe the solution you'd like**
Update the version of Terser used by jsDelivr to v5.7.0.

**Describe alternatives you've considered**
The current implementation works, but it can't minify some packages. Making this update will save cache space.

**Additional context**
[Here](https://cdn.jsdelivr.net/npm/ugl@3.0.0) is an example of a package which can't compile due to one private class field. [Removing the private class field makes the package minify correctly](https://cdn.jsdelivr.net/npm/ugl@3.0.1).

As a side note, it appears that the `--module` flag is disabled for minification. Doesn't it make sense for this to be turned on?

**Comment by jimaek** [comment]
We are currently working on updating our ESM implementation and will make sure to cover this issue as well.
If you find any other issues please report them as well.

Thanks

**Comment by MartinKolarik** [comment]
I'm going to close this as we update all dependencies regularly, so this is going to be included in the nearest update (within two weeks).
