### ISSUE TITLE
Intermittent 404s for graphiql-subscriptions-fetcher

### ISSUE THREAD

**Issue by razilevin** [jsdelivr/jsdelivr#18307]
Hello,

We work with a graphql UI which script includes the following urls
`<script src="//cdn.jsdelivr.net/npm/graphiql-subscriptions-fetcher@0.0.2/browser/client.js"></script>
`
Sometimes this include fails with a 404 which causes the UI fail to load. This recently started to happen. 

Any ideas?

**Comment by MartinKolarik** [comment]
Hi @razilevin, a little update here - we've seen this issue occasionally but for some reason only with this one specific package. Still checking what's wrong here.

**Comment by tjaw09a** [comment]
This is occurring now for this url: 
https://cdn.jsdelivr.net/npm/graphiql-subscriptions-fetcher@0.0.2/browser/client.js

**Comment by MartinKolarik** [comment]
@tjaw09a if you still have this issue, can you please paste the full response headers here? Also, what country are you in?

**Comment by MartinKolarik** [comment]
We identified and fixed the root cause here so it shouldn't happen anymore.
