### ISSUE TITLE
Failed to fetch from GitHub for a range of version

### ISSUE THREAD

**Issue by Mitrajit** [jsdelivr/jsdelivr#18301]
This link works as I have specified the exact version
https://cdn.jsdelivr.net/gh/prithwishpramanik/weather-app@1.0/
but this link doesn't work as now I have mentioned a range of version
https://cdn.jsdelivr.net/gh/prithwishpramanik/weather-app@1/

Github repository
https://github.com/prithwishpramanik/Weather-App

Response
`Failed to fetch prithwishpramanik/weather-app@1 from GitHub.`

**System info**
 - Windows 10
 - Chrome ver - 90.0.4430.212
 - Your location (country): India

**Other questions**
- I have googled this and found somewhere that it takes time for caching the files as GitHub API calls are limited. So how much time does it takes to cache?
- It was sometimes showing 505 No healthy backends, what does that mean?

**Comment by MartinKolarik** [comment]
The version number needs to be a valid [semver](https://semver.org/) so `1.0.0` instead of `1.0`

**Comment by Mitrajit** [comment]
Thanks, the issue has been resolved. Really appreciate the quick reply.
