### ISSUE TITLE
jsDelivr doesn't show committed js file

### ISSUE THREAD

**Issue by gitrats07** [jsdelivr/jsdelivr#18308]
I opened a repository and upload a js file to use it on my site using jsDelivr, but when i commit changes, jsDelivr still send the old js file, why?

This is the committed js file, published on github : https://github.com/gitrats07/clickmedata/blob/main/new-script-server.js
And this is the site, still use the old js file although i committed : http://therealbrate.000webhostapp.com/clickme-server.html
(notice the comment and the site's console)
![image](https://user-images.githubusercontent.com/63937606/123569084-decc0400-d7ef-11eb-8463-0d9db31c25bc.png)
![image](https://user-images.githubusercontent.com/63937606/123569132-ef7c7a00-d7ef-11eb-9776-a7c5d6c9a4dc.png)

**Comment by jimaek** [comment]
Because we use tags to track the release of new versions https://github.com/gitrats07/clickmedata/tags
jsDelivr is built for production use and not development testing, for that reason we have multiple levels of caching and other optimizations in place
