### ISSUE TITLE
jsDelivr sometime not working in China

### ISSUE THREAD

**Issue by tdxiong** [jsdelivr/jsdelivr#18316]
First, appreciate your great service.

I suppose you have noticed that these days jsDelivr is not working in China sometimes
![notworking](https://user-images.githubusercontent.com/23134286/128588224-7bef8b87-8399-4b32-9c5e-299264914594.png)

**Comment by SukkaW** [comment]
Please provide detailed information, like:

- What network environment you are under?
- Which ISP do you use?
- Which DNS (and its IP) do you use?
- The output of `nslookup cdn.jsdelivr.net` or `dig cdn.jsdelivr.net`

**Comment by tdxiong** [comment]
by checking my ip, it is AS4134/China Telecom Backbone
I am using cloudflare public DNS, 1.1.1.1, 1.0.0.1, and its ipv6 addresses, browser is firefox which also uses http dns of cloudflare
at this moment, it is working:
![dig](https://user-images.githubusercontent.com/23134286/128617467-0c172542-c88c-459d-a43f-c2f4bd04bb9a.png)

**Comment by SukkaW** [comment]
Because of the DNS you chose to use, you are not able to use jsDelivr's tons of PoP inside Mainland China. Try to change your DNS and try again.
