### ISSUE TITLE
Malicious file

### ISSUE THREAD

**Issue by fastlorenzo** [jsdelivr/jsdelivr#18318]
User account jeanniebalkwill6 is hosting fake shopping websites using your CDN.

Example: https[:]//www[.]catmienfant[.]online/ => Fake Catimini website (official one: https://www.catimini.com/)

Inside it you can find references to jsdeliver.
Example file: https://cdn.jsdelivr.net/gh/jeanniebalkwill6/webapp2.0@0.0.35/js/require.min.js
hash:fbc6a83dcc60714b2516f19c65e98ba978c725fe890e979e1aea289bb759bc5e

Other malicious sites using this one can be found on urlscan: https://urlscan.io/search/#hash%3Afbc6a83dcc60714b2516f19c65e98ba978c725fe890e979e1aea289bb759bc5e

Thank you for taking appropriate actions and avoiding people to get scammed. 😉 

PS: user also has a github account (https://github.com/jeanniebalkwill6/) and is linked to other people talking about scam: https://github.com/jeanniebalkwill6/statistics/issues/1

**Comment by jimaek** [comment]
I banned the user but it could take a while for his URLs to stop working due to caching.

Thank you for reporting this!

**Comment by MartinKolarik** [comment]
Note that we only served some of the static assets. The main website content is not hosted by us, so if you would like to get the site taken down completely, I recommend contacting the hosting provider and domain registrar.

**Comment by fastlorenzo** [comment]
Thanks for the quick action, I'm sure you've avoided a lot of people to get scammed 😊
