### ISSUE TITLE
Can we stub common node APIs for use in a browser?

### ISSUE THREAD

**Issue by NullVoxPopuli** [jsdelivr/jsdelivr#18310]
**Is your feature request related to a problem? Please describe.**

I'm trying to `await import` this package: https://cdn.jsdelivr.net/npm/validated-changeset/+esm
which, I know works in browsers, but I think the build environment I'm using locally automatically stubs out `process.env`.
At the moment, because `process.env` is a node api and not a browser api, I get an error when I try to use the package.

**Describe the solution you'd like**
maybe a comma separated list of node apis to stub?, like: `?node-replace=process,path` would provide empty stubs for process and path (maybe using path-browserify)

**Describe alternatives you've considered**
I have an open issue on the validated-changeset repo about shipping a browser version: https://github.com/validated-changeset/validated-changeset/issues/136

**Comment by jimaek** [comment]
Hey, we're going to support this in the next release!
Thanks for the feedback

**Comment by MartinKolarik** [comment]
We shipped an update that replaces `process.env.NODE_ENV` but it only applies to new files for now. We're currently discussing if/how to apply this change to the previously generated files.

**Comment by MartinKolarik** [comment]
This now works with the latest version of validated-changeset, we'll soon purge our previously generated files to make the older versions work too.
