### ISSUE TITLE
Ability to detect Github API rate limit errors

### ISSUE THREAD

**Issue by wonderfulspam** [jsdelivr/jsdelivr#18311]
**Is your feature request related to a problem? Please describe.**
On 2021-07-27 from 11.30 to approximately 12.00-12.30 CET I was unable to update to a newer version of a JSDeliver-hosted Github repo. The problem is the same as described in eg.  #18216 and as such seems to be caused by JSDeliver hitting GIthub's API rate limit. The issue caused 404s until I reverted to an earlier version. At approximately 12.45 I was able to update to a new version without problems. The service has worked impeccably from early May until now except for the 30 minute outage on Tuesday.

**Describe the solution you'd like**
Ideally, the problem would never occur. Failing that, I would like to be able to know in advance if an update is likely to fail. This could be an endpoint that in turn uses Github's rate limit endpoint to determine whether JSDeliver's Github integration is healthy. If enough users of the service backed off when the rate limit was approaching, the service would theoretically stay healthy at the expense of occasional delays in updating.

**Describe alternatives you've considered**
The obvious alternative would be to increase the rate limit if at all possible and/or to make it automatically scale. Another alternative (or supplementary feature) would be to serve the last cached version of an asset instead of displaying an error. I have also considered manually checking the would-be URLs of the next version's asset to ensure they all return 200 OK before performing the update on my end and I will be implementing something along these lines if no viable solution is possible on your side.

**Additional context**
The problem is possibly compounded by the fact that the users of the repo in question update the version multiple times per day which causes many API lookups. Updating is done by changing the SHA instead of using tags. Example URL of an asset: https://cdn.jsdelivr.net/gh/ku-kom/bootstrap@7cc11c0/docs/dist/css/bootstrap.min.css

**Comment by MartinKolarik** [comment]
I'll check what happened in this particular case in a moment but there are some good news: we're currently working on several GitHub related improvements (after consulting with GitHub's engineers too) and expect those will eliminate the problem.

**Comment by MartinKolarik** [comment]
This case was not related to rate limiting. GitHub uses Fastly as its CDN for serving static files and Fastly had a [temporary issue](https://status.fastly.com/incidents/wkgnl07cyy75) at that time, which resulted in us not being able to fetch new files for a moment.

Note that if you use SHA URLs, we recommend always using the full 40-characters version SHA - that allows us to provide additional fallback logic, although in this case, that would not have helped either.

**Comment by wonderfulspam** [comment]
Thank you for the swift response! I will switch to the 40-character SHA shortly.

Do you have any mitigation plans for future outages outside of your control?

**Comment by MartinKolarik** [comment]
> Do you have any mitigation plans for future outages outside of your control?

We can handle any outage for files that we've previously served. For brand new files, there's no way for us to get them if the source provider is down. Serving an "older" commit is not really an option here, since commits on their own don't have any kind of order.

**Comment by wonderfulspam** [comment]
> Serving an "older" commit is not really an option here, since commits on their own don't have any kind of order.

That is very true. I was hoping you maybe stored a list of SHAs/tags/branches ordered by when they were fetched so you could fall back to the last known good version of an asset, but I understand that's a big ask :-)

Thanks again for the fast and elucidating responses.
