### ISSUE TITLE
Feature: A way to force update to check for @latest

### ISSUE THREAD

**Issue by glassesUSA** [jsdelivr/jsdelivr#18313]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A URL we can go to or a button on the jsdelivr dashboard that will force update the @latest file

**Additional context**
Currently it can take at least 48 hours to update when a new update is pushed. This would force it to update if there was a critical update

**Comment by jimaek** [comment]
We have a purge API. You can email dak@prospectone.io to get access
