### ISSUE TITLE
github releases endpoint

### ISSUE THREAD

**Issue by RodrigoDornelles** [jsdelivr/jsdelivr#18314]
**Is your feature request related to a problem? Please describe.**
I have a library on github that works with webassembly, but I only load the binary compiled in realeses, it would be interesting to be able to receive them through a cdn.

**Describe the solution you'd like**
could be a link as such
`https://cdn.jsdelivr.net/gh-releases/user/repo@1.0/core.wasm`

**Describe alternatives you've considered**
would be an endpoint where you could choose which asset you want to download, this would be very practical for certain projects.

**Comment by MartinKolarik** [comment]
Closing in favor of #18203. In the meantime, I'd recommend pushing the release assets to npm.
