### ISSUE TITLE
Allow MSI and EXE files

### ISSUE THREAD

**Issue by wingers999** [jsdelivr/jsdelivr#18324]
As per discussion here - https://github.com/jsdelivr/jsdelivr/issues/18323

Can't see why MSI and EXE can't be allowed - would work perfectly for using for download links for software packages etc

**Comment by MartinKolarik** [comment]
We can setup a custom endpoint which doesn't have this restriction for reputable projects on request, e.g. https://musescore.org/ uses this option. If you maintain such project, please send a request with details to dak@prospectone.io

We don't allow these file types for the GitHub/npm sources as it would create a large potential for abuse and serving malware.

**Comment by wingers999** [comment]
Okay thanks, just looked at website you mention and can't see where they use jsdelivr.  I would need it for GitHub unfortunately as whole point of my research is to move the EXE/MSI files from my website (www.pcassistsoftware.co.uk) to a new location due to issue with host and false positive detection from ClamAV they use

**Comment by MartinKolarik** [comment]
The custom endpoint could be configured to use GitHub as a source but one of the requirements would be that it's an open source project, which doesn't seem to be the case here.

**Comment by wingers999** [comment]
No it is not open source unfortunately - thanks for trying to help though, much appreciated
