### ISSUE TITLE
Failed to fetch version info

### ISSUE THREAD

**Issue by DKSander21** [jsdelivr/jsdelivr#18327]
**Describe the bug**
Failing to fetch javascript files.

**Affected jsDelivr links**
<script src="https://cdn.jsdelivr.net/gh/DKSander21/DK_CDN/dist/ukpostcode.js"></script>
<script src="https://cdn.jsdelivr.net/gh/DKSander21/DK_CDN/dist/ukpostcodeapply.js"></script>

**Response headers**
Failed to fetch version info for DKSander21/DK_CDN.

**Please complete the following information:**
 - Device OS: MacOS
 - Browser: chrome
 - Broser version: Version 93.0.4577.82
 - Your location (country): United Kingdom

**Comment by jimaek** [comment]
https://cdn.jsdelivr.net/gh/DKSander21/DK-CDN@main/

You need to tag versions to get all jsDelivr features to work properly.
