### ISSUE TITLE
All links I create just take me to a page which says "Forbidden"?

### ISSUE THREAD

**Issue by wingers999** [jsdelivr/jsdelivr#18323]
All links I create from https://www.jsdelivr.com/github just take me to a page saying Forbidden - what am I missing here?

**Comment by jimaek** [comment]
Please provide some example URLs

**Comment by wingers999** [comment]
Gitub url: https://github.com/wingers999/test/releases/download/v2.4/backupwizard.msi

jsdelivr url: https://cdn.jsdelivr.net/gh/wingers999/test@releases/download/v2.4/backupwizard.msi

**Comment by MartinKolarik** [comment]
We don't allow serving exe and msi files.

**Comment by wingers999** [comment]
Ah, that explains it then - might be worth noting this clearly on website - shame though as wanted to use it to provide download links for my product downloads on my website

**Comment by wingers999** [comment]
for info doesn't even work with .txt files

https://github.com/wingers999/test/releases/download/v2.4/updates.txt
https://cdn.jsdelivr.net/gh/wingers999/test@releases/download/v2.4/updates.txt

**Comment by MartinKolarik** [comment]
The file must be in the release, not uploaded as a separate asset.

**Comment by wingers999** [comment]
Don't get that answer as it is part of the release

![image](https://user-images.githubusercontent.com/10872799/132957583-9cc94afa-29b1-41f4-9255-e147dc9f69c0.png)

But anyway main reason I wanted it was for download links for my software releases so if doesn't do MSI or EXE then no use to me - thanks for replying

**Comment by jimaek** [comment]
What Martin means is that the file must be present here https://github.com/wingers999/test/tree/v2.4 as part of the tag, files uploaded to Github's Release feature are not supported

**Comment by wingers999** [comment]
Okay thanks for explaining
