### ISSUE TITLE
 HTTPS certificate problem in Firefox

### ISSUE THREAD

**Issue by jaaortega** [jsdelivr/jsdelivr#18332]
**Describe the bug**
Failure to load CDN files in Firefox. Console logs report:
Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/...”.

**Affected jsDelivr links**
https://cdn.jsdelivr.net/npm/lax.js
https://cdn.jsdelivr.net/npm/universal-parallax@1.3.2/dist/universal-parallax.min.js

**Response headers**
GET /npm/lax.js undefined
Host: cdn.jsdelivr.net
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://support.inductiveautomation.com/
Sec-Fetch-Dest: script
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site

**Screenshots**
![image](https://user-images.githubusercontent.com/92064707/136299139-f90523bd-bcc2-48ea-a970-a12812c47473.png)
![image](https://user-images.githubusercontent.com/92064707/136299144-2fd5d952-989e-4b26-87bc-9f4956c53379.png)

**Please complete the following information:**
 - Device OS: Windows 10
 - Browser: Firefox
 - Browser version: 93.0 64 bit
 - Your location (country): USA

**Comment by jaaortega** [comment]
If there are any other required information please let me know, thank you for your time.

**Comment by MartinKolarik** [comment]
Despite the misleading Firefox message, this is almost certainly NOT an issue with jsDelivr, but something interfering with your network. Most often an AV, firewall or other type of corporate security software.

**Comment by jimaek** [comment]
Also ping cdn.jsdelivr.net and post the IP. To make sure you're hitting our servers.
