### ISSUE TITLE
Add ".min" to MJS file to get a minified version 

### ISSUE THREAD

**Issue by lihanspace** [jsdelivr/jsdelivr#18335]
**Is your feature request related to a problem? Please describe.**
I hope to get a minified version of the MJS file, even if it doesn't exist

**Describe the solution you'd like**
Add ".min" to MJS file to get a minified version.
e.g. 
https://cdn.jsdelivr.net/npm/vite-plugin-inject-externals@1.0.3/dist/index.min.mjs

**Describe alternatives you've considered**
Add "?min=true" to MJS file to get a minified version 

**Additional context**
https://cdn.jsdelivr.net/npm/vite-plugin-inject-externals@1.0.3/dist/index.min.mjs
Couldn't find the requested file /dist/index.min.mjs in vite-plugin-inject-externals.

**Comment by MartinKolarik** [comment]
Thanks for the suggestion, this recently came up in our internal discussion as well and seems like a logical enhancement.

**Comment by MartinKolarik** [comment]
This now works!
