### ISSUE TITLE
All files ending with `.md5` suffix cannot be accessed

### ISSUE THREAD

**Issue by Redbeanw44602** [jsdelivr/jsdelivr#18331]
**Describe the bug**
As Title.

**Affected jsDelivr links**
https://cdn.jsdelivr.net/gh/LiteLDev-LXL/Cloud/6a2db618f27973bf00c2f33b4319db40aac79e25/iLand/languages/zh_CN.json.md5
https://cdn.jsdelivr.net/gh/LiteLDev-LXL/Cloud/6a2db618f27973bf00c2f33b4319db40aac79e25/iLand/languages/vi_VN.json.md5
.......

**Response headers**
```
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: *
cache-control: public, max-age=86400, s-maxage=86400
content-length: 9
content-type: text/plain; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Sat, 02 Oct 2021 15:53:54 GMT
etag: W/"9-PatfYBLj4Um1qTm5zrukoLhNyPU"
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
x-content-type-options: nosniff
x-served-by: cache-fra19120-FRA, cache-hkg17920-HKG
x-via: 1.1 PS-000-01QVC89:3 (Cdn Cache Server V2.0), 1.1 PSjsczsxfr185:9 (Cdn Cache Server V2.0), 1.1 PS-HFE-01xlN116:19 (Cdn Cache Server V2.0)
x-ws-request-id: 61588092_PS-HFE-01bXS120_19357-11209
```

**Screenshots**
![22](https://user-images.githubusercontent.com/29711228/135723772-bbc0fac2-3c93-445c-9a9a-a9ebf53a636b.png)

**Please complete the following information:**
 - Device OS: Windows
 - Browser: Edge
 - Broser version: 94.0.992.31
 - VPN provider if you use one: - 
 - Your location (country): China

**Additional context**
These files exist and are valid on github, such as:
https://github.com/LiteLDev-LXL/Cloud/blob/main/6a2db618f27973bf00c2f33b4319db40aac79e25/iLand/languages/vi_VN.json.md5

**Comment by Redbeanw44602** [comment]
It seems that all files ending in md5 will be rejected, even if they do not exist. Why is there such a setting?
https://cdn.jsdelivr.net/gh/1114514.md5

**Comment by MartinKolarik** [comment]
Historically they were not allowed but I don't actually see a problem with allowing them. @jimaek ?

**Comment by MartinKolarik** [comment]
@Redbeanw44602 note that if you use a branch reference you're likely to run into issues as described in https://github.com/jsdelivr/jsdelivr/issues/18220 because there's no guarantee the files get updated at the exact same time.

**Comment by jimaek** [comment]
Allowing md5 sounds fine by me

**Comment by Redbeanw44602** [comment]
I understand, thanks for the reply.
