### ISSUE TITLE
can i report abuse?

### ISSUE THREAD

**Issue by dora-world** [jsdelivr/jsdelivr#18339]
can i report abuse?

**Comment by dora-world** [comment]
i found that
there are two people who abuse use jsdelivr
they use jsdelivr to upload some video which don't have any copyright, and use m3u8 to play them .
like https://cdn.jsdelivr.net/gh/WN-SY/nhlhy/playlist.m3u8
they don't have any copyright of doraemon

**Comment by dora-world** [comment]
https://github.com/cxsub and https://github.com/WN-SY
two member abuse use jsdelivr

**Comment by dora-world** [comment]
I think they not only violated the jsdelivr user regulations, but also violated the copyright

**Comment by jimaek** [comment]
We banned those users and their URLs will stop working soon after some caches of ours expire.
Thank you for reporting.

**Comment by dora-world** [comment]
sorry to bother you, i found that the url can be visit until now. maybe there are something wrong?

**Comment by dora-world** [comment]
> We banned those users and their URLs will stop working soon after some caches of ours expire. Thank you for reporting.

sorry to bother you, i found that the url can be visit until now. maybe there are something wrong?

**Comment by Big-Cake-jpg** [comment]
> > We banned those users and their URLs will stop working soon after some caches of ours expire. Thank you for reporting.
> 
> 
> 
> sorry to bother you, i found that the url can be visit until now. maybe there are something wrong?
> 
> 
> 
> 

Maybe you can try replace 'cdn' in the url to 'purge' like this 
```

https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Image_For_My_Blog/favicon.ico

TO THIS

https://purge.jsdelivr.net/gh/Big-Cake-jpg/Image_For_My_Blog/favicon.ico

```
It will refresh files
