### ISSUE TITLE
Malicious file

### ISSUE THREAD

**Issue by laurachan** [jsdelivr/jsdelivr#18340]
Hi again. Please take down a malicious script at [https]://cdn[.]jsdelivr[.]net/gh/jqueryest/jquery/jquery[.]js. This obfuscated script is being used in HTML attachments for phishing/malspam emails. Note how this URL is very similar to the one I reported in issue #18338. Thanks.

**Comment by jimaek** [comment]
It will stop working today. And please report abuse via email.

Thanks

**Comment by laurachan** [comment]
Thank you. FYI - https://www.jsdelivr.com/about says to report malicious files via this issue tracker; where can I find the email address to which abuse reports should be sent?
```
<p>We also have protections in place to prevent people from using jsDelivr to serve malicious files, but if you find something that doesn't look right, <a target="_blank" rel="noopener" href="https://github.com/jsdelivr/jsdelivr/issues/new?title=Malicious file">report it at our issue tracker</a>.</p>
```

**Comment by jimaek** [comment]
Same page " Just send us an email " or footer :)
