### ISSUE TITLE
can't load a github repo

### ISSUE THREAD

**Issue by Techno-Disaster** [jsdelivr/jsdelivr#18343]
For some weird reason I can't seem to load https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/ could this be due to the size limit? The repo is visible on github perfectly fine. https://github.com/CTalvio/Ultrachromic/
https://cdn.jsdelivr.net/gh/CTalvio/Monochromic/ works fine

**Comment by jimaek** [comment]
You need to start tagging your releases https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic@main/
