### ISSUE TITLE
Is the CDN offline?

### ISSUE THREAD

**Issue by marciogranzotto** [jsdelivr/jsdelivr#18345]
https://cdn.jsdelivr.net/

looks to be offline. I can't access it or use a script hosted there

**Comment by zarianec** [comment]
Hey @marciogranzotto, we don't see any issues on our side. CDN works fine.

Can you please provide more information:
1. what URL are you trying to hit
2. what error do you see

Often CDN may not work for some users because of their ISPs.

**Comment by marciogranzotto** [comment]
Ohhh sorry for that. Looks like my AdGuard decided to start blocking the CDN. I've added it to the allow list and now it's working again!
