### ISSUE TITLE
Question regarding caching with branches

### ISSUE THREAD

**Issue by altbdoor** [jsdelivr/jsdelivr#18347]
I've read [the Caching section](https://github.com/jsdelivr/jsdelivr#caching) and a couple of issues in here, but I am still unsure about the caching behavior with branches.

The CDN link in question is https://cdn.jsdelivr.net/gh/altbdoor/d2-api-human@data/version.txt .

As mentioned in README, requests with branches are cached for 12 hours. But at the same time, there's:

> We use permanent S3 caching even with dynamic URLs such as version aliasing, meaning once we download your tagged files there is no way for you to update them.

...which I am unsure if it applies to branches. I am currently running a GitHub Action that will refresh the `version.txt` in the `data` branch, every 24 hours.

If I do not perform any purge API call, will the end users get the new `version.txt` after 12 hours?

Sorry for the troubles, and thanks.

**Comment by MartinKolarik** [comment]
Hi, the S3 part doesn't apply to branches.

**Comment by altbdoor** [comment]
Hi, thanks for the response. So after 12 hours of caching, jsDelivr will fetch the file from GitHub again?

**Comment by MartinKolarik** [comment]
Yes.

**Comment by altbdoor** [comment]
Much thanks for the quick response. Hope your day will be well! 🤝
