### ISSUE TITLE
Malicious file

### ISSUE THREAD

**Issue by crctwc** [jsdelivr/jsdelivr#18341]
Received phishing emails containing HTML payload with links to the following:

https://cdn.jsdelivr.net/gh/mooonlybox/cdn/sp_attach_js_k_v1.js
https://cdn.jsdelivr.net/gh/mooonlybox/cdn/sp_css.css

These are being used to render a fake SharePoint page and login prompt to harvest credentials.  Please review and address this malicious content and account.

**Comment by jimaek** [comment]
We banned the user, thanks for reporting.
The URLs will stop working soon
