### ISSUE TITLE
Request to get access to Purge API

### ISSUE THREAD

**Issue by MuhammadMSaleh** [jsdelivr/jsdelivr#18344]
Hello jsDelivr!
I really appreciate your efforts to keep this awesome project always working. 
I just need to know how to get access to the purge API.
I have emailed you on the given email address at project README as described [**here**](https://github.com/jsdelivr/jsdelivr#purge-cache) since a week ago and I didn't receive any hints.
Maybe I have misunderstand or should I just wait for a response ?
Thanks in advance!

**Comment by jimaek** [comment]
I only got the email yesterday, I will reply there
