### ISSUE TITLE
CDN issues happened in China multiple times

### ISSUE THREAD

**Issue by nomagick** [jsdelivr/jsdelivr#18354]
Thanks for providing free CDN services. It's been high quality compared to other providers.

As an NPM package author, I'm currently using `jsdelivr` as the recommended way of importing my code.

However, as I mentioned in the title, CDN issues happen from time to time and seem specific to China.

-  The one we currently experiencing https://github.com/jsdelivr/jsdelivr/issues/18348
-  And in 2019  https://github.com/jsdelivr/jsdelivr/issues/18146

Would you please take measures to prevent common issues like certificate expiration, bad config and etc from happening?

That will boost my confidence In keeping `jsdelivr` as the recommended CDN.

**Comment by x852** [comment]
You can temporarily use cdnjs Com to replace it until jsdelivr is repaired

**Comment by x852** [comment]
You can temporarily use `cdnjs` to replace it until `jsdelivr` is repaired.

**Comment by x852** [comment]
You can temporarily use 'unpkg' to replace it until 'jsdelivr' is repaired.[help](https://www.cnblogs.com/lujiahao/p/15710931.html)

**Comment by x852** [comment]
You can temporarily replace it with `unpkg` until `jsdelivr` is repaired. [help]（ https://www.cnblogs.com/lujiahao/p/15710931.html )

**Comment by x852** [comment]
You can temporarily replace it with `unpkg` until `jsdelivr` is repaired.[help](https://www.cnblogs.com/lujiahao/p/15710931.html )

**Comment by MartinKolarik** [comment]
Hi @nomagick, we're sorry for the issues. As mentioned in https://github.com/jsdelivr/jsdelivr/issues/18348#issuecomment-997703374, we're still checking the cause of this one so will comment here later.

**Comment by jimaek** [comment]
All Chinese traffic was temporarily switched to Fastly while we're working on this issue

**Comment by jimaek** [comment]
The issue itself is solved, we will work today to come up with a permanent solution
