### ISSUE TITLE
CND炸了，麻烦尽快修复

### ISSUE THREAD

**Issue by 597585136** [jsdelivr/jsdelivr#18350]
**Describe the bug**
CND炸了

**Comment by denglouhen** [comment]
坑死了我靠

**Comment by ljcbaby** [comment]
同 #18348，不要另开了

**Comment by wordlesswind** [comment]
与 #18348 重复，请关闭此 issue。
Duplicate of #18348, please close this issue.

**Comment by 597585136** [comment]
> 与 #18348 重复，请关闭此 issue。 Duplicate of #18348, please close this issue.

**Comment by 1447047194** [comment]
炸了呀，啥时候修复了
