### ISSUE TITLE
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by bianbiandashen** [jsdelivr/jsdelivr#18357]
**Describe the bug**

**Affected jsDelivr links**
One or more direct links that are affected by this issue.

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.

**Screenshots**

**Please complete the following information:**
 - Device OS: [e.g. iOS]
 - Browser: [e.g. chrome, safari]
 - Browser version: [e.g. 22]
 - VPN provider if you use one:
 - Your location (country):

**Additional context**

![image](https://user-images.githubusercontent.com/16240681/146733333-a1e3d2eb-0118-4e02-8500-5aa024357fdd.png)

**Comment by seyoon20087** [comment]
It appears like you are in mainland China. jsDelivr is currently experiencing issues with their provider in China, Quantil.
Please see https://uptime.com/s/jsdelivr for the current status

**Comment by x852** [comment]
You can temporarily replace it with `unpkg` until `jsdelivr` is repaired.[help](https://www.cnblogs.com/lujiahao/p/15710931.html )
