### ISSUE TITLE
CDN service of China is broken!

### ISSUE THREAD

**Issue by yzyyz1387** [jsdelivr/jsdelivr#18352]
**Describe the bug**
CDN service of China is broken!

**Affected jsDelivr links**
eg: https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js

**Comment by mouday** [comment]
me too

**Comment by MrOrz** [comment]
Please use #18348 instead.

**Comment by wordlesswind** [comment]
与 #18348 重复，请关闭此 issue。
Duplicate of #18348, please close this issue.
