### ISSUE TITLE
cdn 炸了，麻烦尽快修复下

### ISSUE THREAD

**Issue by 1447047194** [jsdelivr/jsdelivr#18358]
**Describe the bug**

**Affected jsDelivr links**
One or more direct links that are affected by this issue.

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.

**Screenshots**

**Please complete the following information:**
 - Device OS: [e.g. iOS]
 - Browser: [e.g. chrome, safari]
 - Browser version: [e.g. 22]
 - VPN provider if you use one:
 - Your location (country):

**Additional context**

**Comment by TerryZ** [comment]
已经有集中讨论贴了 #18348，不要再另开贴
