### ISSUE TITLE
Request to increase package size limit for {{name}}

### ISSUE THREAD

**Issue by kainy** [jsdelivr/jsdelivr#18362]
**Link to the npm package or GitHub repository**
https://github.com/PATech/ksk_app_dist

**Project license**
MIT

**Your relation to the project**
maintainer

**Short description of the project**
It is a application download page

**Please confirm the following:**
 - [x] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
 - [x] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).

**Additional context**
We need chage the limit to 30MB or highter。

**Comment by MartinKolarik** [comment]
If you need to serve individual files over 20 MiB, please contact @jimaek via email with more details about the project.
