### ISSUE TITLE
Invalid certificate when trying to access subroutes

### ISSUE THREAD

**Issue by johseffer** [jsdelivr/jsdelivr#18364]
**Describe the bug**
Im taking an certificate error when trying to access subroutes of https://www.jsdelivr.com/.

![image](https://user-images.githubusercontent.com/25435217/148216045-0984623a-83f1-4f4a-8332-7714e5a974e3.png)

**Affected jsDelivr links**
https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js

**Response headers**
NET::ERR_CERT_AUTHORITY_INVALID

**Please complete the following information:**
 - Device OS: Win10
 - Browser: Chrome, Brave, Mozilla
 - Browser version: latest
 - Your location (country): Brazil

**Comment by jimaek** [comment]
Please ping cdn.jsdelivr.net and provide the IP address. 
HTTP headers of the broken URLs would also be helpful

**Comment by MartinKolarik** [comment]
Please open one of the links in a separate tab, then open the Security tab of the devtools, view certificate, and post a screenshot here like this:

<details>

![image](https://user-images.githubusercontent.com/6192491/148216760-27578be9-9be1-4a66-a4dd-ad6b583e2be8.png)

</details>

**Comment by johseffer** [comment]
PING:
`Disparando cdn.jsdelivr.net [158.69.16.200] com 32 bytes de dados:
Resposta de 158.69.16.200: bytes=32 tempo=143ms TTL=54
Resposta de 158.69.16.200: bytes=32 tempo=153ms TTL=54
Resposta de 158.69.16.200: bytes=32 tempo=153ms TTL=54
Resposta de 158.69.16.200: bytes=32 tempo=153ms TTL=54

Estatísticas do Ping para 158.69.16.200:
    Pacotes: Enviados = 4, Recebidos = 4, Perdidos = 0 (0% de
             perda),
Aproximar um número redondo de vezes em milissegundos:
    Mínimo = 143ms, Máximo = 153ms, Média = 150ms`

    
![image](https://user-images.githubusercontent.com/25435217/148217047-0a7f6e66-e392-4305-8c18-911e4494b737.png)

**Comment by jimaek** [comment]
Try changing your DNS to something like 8.8.8.8 or 1.1.1.1.
Your ISP or your LAN admin is rerouting the traffic to their own server that has a wrong SSL certificate.
Its not a jsDelivr issue.

**Comment by johseffer** [comment]
It worked after point my dns to google. Thank you guys.
