### ISSUE TITLE
Getting unexpected 404's from esm.run

### ISSUE THREAD

**Issue by bahrus** [jsdelivr/jsdelivr#18361]
**Describe the bug**
Getting 404's from files that jsDelivr finds without the +esm

**Affected jsDelivr links**

These give 404's:

https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/insertAdjacentTemplate.js/+esm
https://cdn.jsdelivr.net/npm/be-observant@0.0.70/hookUp.js/+esm
https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/transform.js/+esm
https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/PEA.js/+esm
https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/SplitText.js/+esm

But without the +esm, jsdelivr finds the files:

https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/insertAdjacentTemplate.js
https://cdn.jsdelivr.net/npm/be-observant@0.0.70/hookUp.js
https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/transform.js
https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/PEA.js
https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/SplitText.js

**Response headers**
access-control-allow-origin: *
access-control-expose-headers: *
age: 15
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
cache-control: public, max-age=31536000, s-maxage=31536000
cf-cache-status: HIT
cf-ray: 6c445471ded90649-IAD
content-encoding: br
content-type: text/plain; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Mon, 27 Dec 2021 17:39:43 GMT
etag: W/"21-M28qQtNh6xlVdIXXeMOLRujDS0c"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: MISS, HIT
x-content-type-options: nosniff
x-served-by: cache-fra19150-FRA, cache-iad-kiad7000040-IAD

**Screenshots**

**Please complete the following information:**
 - Device OS: Windows 11
 - Browser: Edge
 - Browser version: 96.0.1054.62
 - VPN provider if you use one:
 - Your location (country): USA

**Additional context**

**Comment by zarianec** [comment]
Hey @bahrus, the files you mentioned should work now.

This file will still return 404 because it's not exported in your package.json file.
https://cdn.jsdelivr.net/npm/trans-render@0.0.441/lib/SplitText.js/+esm
