### ISSUE TITLE
ping: cannot resolve https://cdn.jsdelivr.net: Unknown host

### ISSUE THREAD

**Issue by gonxas** [jsdelivr/jsdelivr#18363]
**Describe the bug**
I'm being unable to do git pod because I keep getting a timeout ```[!] CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/6/6/9/Mixpanel/4.0.0/Mixpanel.podspec.json Response: Timeout was reached```

When I try to ping both ```https://cdn.jsdelivr.net/cocoa/Specs/6/6/9/Mixpanel/4.0.0/Mixpanel.podspec.json ``` and ```https://www.jsdelivr.net``` I get a ```cannot resolve <url>: Unknown host```

I did this tests from different wifi networks, and also asked people from other countries to do the ping for me, same error on all the tests.

<img width="907" alt="Screenshot 2022-01-03 at 22 35 29" src="https://user-images.githubusercontent.com/1783682/147983159-9fa20031-a5c9-422b-a3d9-31f415be7849.png">

Any ideas why this may be happening? 

Thanks in advance

**Comment by jimaek** [comment]
Please ping `cdn.jsdelivr.net` and provide us the IP address that you get.

**Comment by gonxas** [comment]
@jimaek 
```
PING jsdelivr.map.fastly.net (151.101.65.229): 56 data bytes
64 bytes from 151.101.65.229: icmp_seq=0 ttl=56 time=20.270 ms
```

**Comment by jimaek** [comment]
Does it keep happening? I cant see any issue on our side

**Comment by gonxas** [comment]
hey @jimaek. Don't know what happened, the pings are still returning "Unknown host", but _pod update_ it's working OK today.

**Comment by jimaek** [comment]
Well the unknown host error is not an error, `www.jsdelivr.net` doesnt exist. Its either www.jsdelivr.com or cdn.jsdelivr.net
But if the files work then everything is fine :)
