### ISSUE TITLE
Request to increase package size limit for WinDynamicDesktop

### ISSUE THREAD

**Issue by t1m0thyj** [jsdelivr/jsdelivr#18369]
**Link to the npm package or GitHub repository**
https://github.com/t1m0thyj/WDD-website

**Project license**
MPL 2.0

**Your relation to the project**
Developer

**Short description of the project**
WinDynamicDesktop is a port of the macOS Mojave Dynamic Desktop feature to Windows 10. I host a website for it using GitHub Pages at https://windd.info/themes to showcase dynamic wallpapers that have been created by users of my app.

**Please confirm the following:**
 - [x] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
 - [x] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).

**Additional context**
I am not requesting to host any large files, the raw dynamic wallpapers would be many GB combined and are already hosted on other sites like MediaFire. I only want to host small preview images for thumbnails, and larger preview images (1080p 85% quality JPEGs) so folks can preview a few images from a theme at low-resolution before downloading it.

My repository has outgrown the 50MB limit, since the TGZ from GitHub is now 75MB. As a result, JSDelivr has stopped hosting images for new themes like [this one](https://cdn.jsdelivr.net/gh/t1m0thyj/WDD-website/images/thumbnails/Mountains_%233_night.png). Therefore I am requesting for the 50MB package limit to please be increased. Thank you!

**Comment by MartinKolarik** [comment]
Hi, this actually seems to be an issue with how we handle the `#` character in the name. If you rename the file to `Mountains_3_night.png` it should work. The repository limit applies only to directory listings and individual files should still load regardless of the size.

**Comment by t1m0thyj** [comment]
@MartinKolarik Thanks, removing the `#` character from the filename resolved my problem.

Should I close this issue, or leave it open as a bug/enhancement request to handle URI encoded characters?

**Comment by MartinKolarik** [comment]
I opened an issue in the internal backend tracker so we can close this one.
