### ISSUE TITLE
Is it possible to automaticly purge cache on alias endpoints (such as github default branch)?

### ISSUE THREAD

**Issue by xieyuheng** [jsdelivr/jsdelivr#18365]
i.e. everytime the default branch is pushed, purge cache.

It seems this behavior can cover the majority of the use cases of the upcoming purge tool.

And, for example, vercel.com has this behavior.

**Comment by jimaek** [comment]
We have an API to purge URLs that you could use as a CI step to purge your caches after deploying a new version. But there is not 100% automated mechanism at the moment

**Comment by aditya211935** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/interviewstreet/theia-assets-dev@v174-dev-34/theia.fae805f3c689a9f6e664.js

**Comment by aditya211935** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/interviewstreet/theia-assets-dev@v174-dev-34/theia.fae805f3c689a9f6e664.js
