### ISSUE TITLE
GitHub's resources are inaccessible, or very slow, for more than ten seconds;in China

### ISSUE THREAD

**Issue by A-ANing** [jsdelivr/jsdelivr#18366]
![image](https://user-images.githubusercontent.com/43433064/149746783-b12dd3cf-ae88-4703-8049-8fa46a843263.png)

**Comment by jimaek** [comment]
Can you run the same tests on the following domains too and tell me which performs better for you?

fastly.jsdelivr.net
gcore.jsdelivr.net
testingcf.jsdelivr.net

**Comment by A-ANing** [comment]
Img size : 1.8M 

fastly.jsdelivr.net:
![image](https://user-images.githubusercontent.com/43433064/149749202-c0f1c414-451f-42d3-bae8-8e7205bf5bf4.png)

gcore.jsdelivr.net:
![image](https://user-images.githubusercontent.com/43433064/149749333-3169ad73-4f6f-46be-9b3e-82d3cec2fb4d.png)


testingcf.jsdelivr.net: 
![image](https://user-images.githubusercontent.com/43433064/149749450-a9dfaf68-ade9-43d1-92ca-cfa78acf83d8.png)


cdn.jsdelivr.net: More than one minute
![image](https://user-images.githubusercontent.com/43433064/149750294-1129dffb-8ed5-4779-b9dc-9dbb6aed3846.png)



"testingcf. jsdelivr. net" is the fastest, one or two seconds, the same as "cdn. jsdelivr. net" a month ago; 
Will "cdn. jsdelivr. net" restore the previous speed?

**Comment by A-ANing** [comment]
I did nothing, now `cdn.jsdelivr.net` is ok;
The abnormal situation in the past has lasted for at least half a month

![image](https://user-images.githubusercontent.com/43433064/149867917-ba58582e-572e-45cc-a699-4a1af039fff9.png)

**Comment by MicroCBer** [comment]
From the test results of Chengdu Telecom, the fastly mirror is still faster.
```
Microsoft Windows [版本 10.0.22000.434]
(c) Microsoft Corporation。保留所有权利。

C:\Users\MicroBlock>ping cdn.jsdelivr.net

正在 Ping cdn.jsdelivr.net.cdn.cloudflare.net [104.16.87.20] 具有 32 字节的数据:
来自 104.16.87.20 的回复: 字节=32 时间=199ms TTL=53 
来自 104.16.87.20 的回复: 字节=32 时间=199ms TTL=53
来自 104.16.87.20 的回复: 字节=32 时间=198ms TTL=53

104.16.87.20 的 Ping 统计信息:
    数据包: 已发送 = 3，已接收 = 3，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 198ms，最长 = 199ms，平均 = 198ms
Control-C
^C
C:\Users\MicroBlock>ping fastly.jsdelivr.net

正在 Ping jsdelivr.map.fastly.net [151.101.109.229] 具有 32 字节的数据:
来自 151.101.109.229 的回复: 字节=32 时间=92ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=124ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=123ms TTL=52
来自 151.101.109.229 的回复: 字节=32 时间=124ms TTL=52

151.101.109.229 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 92ms，最长 = 124ms，平均 = 115ms
```

**Comment by A-ANing** [comment]
Now it's broken again. There's no response directly. I'm in Chongqing, China



![image](https://user-images.githubusercontent.com/43433064/150645313-275494bc-8712-4e97-a86e-1aa0c4ef5e86.png)
![image](https://user-images.githubusercontent.com/43433064/150645342-09c6094e-7e26-4f54-a123-74df15f3695c.png)

**Comment by A-ANing** [comment]
Many websites have exploded


[echarts.apache.org](https://echarts.apache.org/zh/index.html)
![image](https://user-images.githubusercontent.com/43433064/150645700-b71fbb22-75c5-4d4b-a1d5-9c0beb4b3dfc.png)

[bootcdn](https://www.bootcdn.cn/)
![image](https://user-images.githubusercontent.com/43433064/150645819-a195d170-3a76-42e1-b339-7cd1cb718e9a.png)

**Comment by jimaek** [comment]
Please run some debugging commands, for example:

```
dig cdn.jsdelivr.net
dig fastly.jsdelivr.net
dig +trace jsdelivr.net
```
