### ISSUE TITLE
Request to increase package size limit for typescript 

### ISSUE THREAD

**Issue by abhishiv** [jsdelivr/jsdelivr#18378]
**Link to the npm package or GitHub repository**
https://github.com/Microsoft/typescript
https://npmjs.com/package/typescript. 

**Project license**
MIT.

**Your relation to the project**
user

**Short description of the project**
Typescript is used by a lots of projects, so would be very helpful to get it on jsdelivr.

**Please confirm the following:**
 - [ x ] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
 - [ x ] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).

**Additional Context**

Unable to import Microsoft/typescript via esm cdn due to package size limit

https://cdn.jsdelivr.net/npm/typescript@3.9.10/+esm

```
Package size exceeded the configured limit of 50 MB.
```

**Comment by MartinKolarik** [comment]
Hi, we increased the limit for `/+esm` requests to match the regular npm files (100 MiB) and this change will be live shortly. Unfortunately, it still doesn't help with typescript, because it imports node's `fs` module, which is not supported.

**Comment by abhishiv** [comment]
Hey @MartinKolarik 

Thanks a lot for your quick response!

Ah yes, I see that it also import a couple of other modules like `os`, `fs`, `path`, `buffer`. Most builtins won't work in the browser, but do you think the one that can be polyfilled should be? Like `buffer` for example? And for the rest just replace them with `{}` the way webpack allows?

If the code for bundler is open source, happy to have a look and send a PR.

**Comment by MartinKolarik** [comment]
We already polyfill most of them. I went to check if adding fs would help but found there's actually a bug because typescript excludes those native modules from bundling in its `package.json` so they shouldn't raise this error - will follow up later.

**Comment by MartinKolarik** [comment]
This now works!

**Comment by abhishiv** [comment]
Works beautifully! 

Thanks a lot! Also since JSDelivr is the only CDN where this works(tried skypack and jspm as well).

**Comment by abhishiv** [comment]
hey @MartinKolarik I just noticed that it works with `https://cdn.jsdelivr.net/npm/typescript@3.9.10/+esm` but not `https://esm.run/typescript`

Is esm.run not the same as jsdelivr or is deprecated?

**Comment by MartinKolarik** [comment]
They are the same but you're comparing two different versions. Seems to be a problem with the latest typescript release, feel free to open a separate issue here.
