### ISSUE TITLE
Fastly - HTTP3

### ISSUE THREAD

**Issue by FireMasterK** [jsdelivr/jsdelivr#18372]
**Describe the bug**
When Fastly is used, HTTP3 isn't enabled.

**Affected jsDelivr links**
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
https://fastly.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js

**Response headers**
```
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: *
age: 1676828
cache-control: public, max-age=31536000, s-maxage=31536000, immutable
content-encoding: gzip
content-length: 30180
content-type: application/javascript; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Sat, 12 Feb 2022 20:08:54 GMT
etag: W/"15283-EFUBjCirQQh++czv5BFgaJPavqI"
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: HIT, HIT
x-content-type-options: nosniff
x-jsd-version: 3.2.1
x-jsd-version-type: version
x-served-by: cache-fra19128-FRA, cache-lcy19267-LCY
```

Note the lack of an `Alt-Svc` header, which is required for HTTP3.

**Please complete the following information:**
 - Device OS: Arch Linux
 - Browser: Brave
 - Browser version: 1.35.101
 - Your location (country): GB

**Comment by FireMasterK** [comment]
To be fair, it is enabled on their homepage at https://www.fastly.com/. It's also worth noting that QUIC is now a stable RFC at https://www.fastly.com/blog/quic-is-now-rfc-9000

HTTP/3 is also an [optional upgrade](https://docs.fastly.com/en/guides/enabling-quic-and-http3-for-fastly-services#configuring-your-fastly-service-to-offer-http3), if HTTP/3 is causing issues, clients will fall back to HTTP/2 automatically in most major browsers. Considering that Google, Cloudflare, Facebook all use HTTP/3 by default, I would say it's likely safe/stable.

**Comment by adityapatadia** [comment]
Fastly launched HTTP/3 in production yesterday: https://docs.fastly.com/en/guides/enabling-http3-for-fastly-services

**Comment by jimaek** [comment]
I enabled HTTP3 on Fastly. Please check

**Comment by adityapatadia** [comment]
It's working like a charm :)
