### ISSUE TITLE
Website Unavailable

### ISSUE THREAD

**Issue by W4J1e** [jsdelivr/jsdelivr#18370]
2022/01/23  03:23 GMT+8 update
I found jsdelivr no longer banned by ChongQing Telecome, ChongQing Mobile still not work.

what happend plz?
![1](https://user-images.githubusercontent.com/74824162/150652282-4fe22343-53f3-4148-ba22-ce78204aaec2.jpg)
![2](https://user-images.githubusercontent.com/74824162/150652284-7bd709c2-ad31-4839-8a9a-80556adc9e5f.jpg)

**Comment by jimaek** [comment]
Wrong domain name, where did you get these links?

**Comment by W4J1e** [comment]
> Wrong domain name, where did you get these links?

domain is cdn.jsdelivr.net, those links in my blog. I run it in localhost that time with vpn, because the domain has banned by ChongQing Telecome in China.
Now it may working right. Thanks.
![92576D0B-F610-4A40-AEC0-EA319F43302D](https://user-images.githubusercontent.com/74824162/150652917-84c489ab-0f61-4d22-bbba-98894606fad4.jpeg)

**Comment by jimaek** [comment]
The original screenshot uses `jsdlivr.net` not `jsdelivr.net` thats where the first error is coming from.


If it's working now then great :)
