### ISSUE TITLE
Removing introduction to QUANTIL CDN on the jsdelivr.com

### ISSUE THREAD

**Issue by laozhoubuluo** [jsdelivr/jsdelivr#18380]
**Is your feature request license to a problem? Please describe.**
Considering that the ICP license of jsdelivr.net in mainland China has been revoked a few months ago, and the QUANTIL CDN service is no longer available at the same time, so should we consider removing the introduction to QUANTIL CDN on the jsdelivr.com website?

**Describe the solution you'd like**
Removing introduction to QUANTIL CDN on the jsdelivr.com.

**Describe alternatives you've considered**
If it is confirmed that the ICP license cannot be restored in predictable time, should the content related to the ICP license on the jsdelivr.com website also be removed?

**Additional context**

**Comment by jimaek** [comment]
We're working on this on the new website, it should go live next month or so.

Thanks
