### ISSUE TITLE
Malicious file

### ISSUE THREAD

**Issue by stephanhughsonsm** [jsdelivr/jsdelivr#18388]
This URL came along in a phishing email.

`https://cdn.jsdelivr.net/gh/madmaxmad1/followsyou/MultipleMumbai@2.js`

The email said that it was a new voicemail notification and that the user should open an attachment to listen to the raw audio.

Then in the attachment, there was a bit of Javascript with the user's email address a unique key and the link above.

**Comment by jimaek** [comment]
The user is blocked and all URLs will start working shortly
