### ISSUE TITLE
Can I request a manual cache purge here please?

### ISSUE THREAD

**Issue by mattkeys** [jsdelivr/jsdelivr#18383]
Sorry if this is no longer the correct way to manually purge the cache on a file. But I have an incorrect version of a file out there negativately impacting users that I need to clear.

This now closed ticket is full of people clearing a cache using the jsdelivrbot:

https://github.com/jsdelivr/jsdelivr/issues/18039

@jsdelivrbot purge https://cdn.jsdelivr.net/gh/mattkeys/FontAwesome-Free-Manifest/5.x/manifest.yml

I've also sent a message to the email here: https://github.com/jsdelivr/jsdelivr#purge-cache but I am not sure if that is really what I need as I don't want API access to do this on an ongoing basis, more of a one time thing.

**Comment by MartinKolarik** [comment]
The bot no longer works. API is the only way currently but soon there'll also be an option to do this via our website. Anyway, I purged that file manually for now.

**Comment by mattkeys** [comment]
Thanks @MartinKolarik 

Should I expect the cache clear to have already taken effect? I am still seeing the wrong data from the CDN.

This is the expected data:

https://raw.githubusercontent.com/mattkeys/FontAwesome-Free-Manifest/master/5.x/manifest.yml

**Comment by MartinKolarik** [comment]
The latest release in that repo is 14 days old actually, so there's nothing new to update to.

**Comment by mattkeys** [comment]
Sorta a complicated story, but releases to that repo are done automatically to track FontAwesome releases. An automatic release happened with FontAwesome 6.x manifest information but this is supposed to be limited to 5.x release information.

I manually removed the bad release, and manually fixed the manifest.yml file I requested the purge on. Everything is correct now on GitHub. However the file on jsdelivr is still showing the information from that bad release.

**Comment by MartinKolarik** [comment]
I see, releases are considered immutable on our end, so changes to an existing release won't be picked up, you'll have to create a new one.

**Comment by odontologista** [comment]
BTW, how does it work with new releases? I've recently released a version and when trying to update my "main" branch file, it's still not loading the latest release? Any way to purge and update to reflect the latest one?

**Comment by rakesh-snippyly** [comment]
Apologies for making a request on this thread. I have requested access to the purge api so that we can do it ourselves. meanwhile is it possible to purge the cache for these:
https://cdn.jsdelivr.net/npm/@snippyly/plugin/snippyly.js
https://cdn.jsdelivr.net/npm/@snippyly/sdk/snippyly.js

How long does it take to get access to the api?

**Comment by MartinKolarik** [comment]
@rakesh-snippyly purged, @jimaek will be in touch shortly about the API.

**Comment by rakesh-snippyly** [comment]
wohoo! thanks @MartinKolarik

**Comment by Kemborrembor** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/Kemborrembor/AMGS-files/server.js

**Comment by Kemborrembor** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/Kemborrembor/AMGS-files/game-server.js
