### ISSUE TITLE
cdn error

### ISSUE THREAD

**Issue by wwh1248** [jsdelivr/jsdelivr#18399]
https://cdn.jsdelivr.net/
https://cdn.jsdelivr.net/npm/hls.js@0.13.1/dist/hls.min.js

**Comment by SUPERDBFMP** [comment]
+1

**Comment by hanmengsjz** [comment]
+1

**Comment by typesbb** [comment]
+1

**Comment by chaigx** [comment]
+1

**Comment by XiaoJ-96** [comment]
++++++++++++++++++1

**Comment by ZHYCarge** [comment]
+1

**Comment by yxlolxy** [comment]
chinese user, too

**Comment by webPpei** [comment]
I had the same problem.
I used LightProxy for forwarding, currently working normally.
^https://cdn.jsdelivr.net/*** https://fastly.jsdelivr.net/$1

**Comment by ITBOYLIN** [comment]
chinese user, too

**Comment by eebssk1** [comment]
#18396

**Comment by kingc2022** [comment]
+1

**Comment by yxlolxy** [comment]
I have move my static resources to netlify, there seems to be no other choice
