### ISSUE TITLE
CDN resources cannot be accessed in China

### ISSUE THREAD

**Issue by Sinclair8023** [jsdelivr/jsdelivr#18396]
**Describe the bug**

**Affected jsDelivr links**
One or more direct links that are affected by this issue.

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.

**Screenshots**

**Please complete the following information:**
 - Device OS: [e.g. iOS]
 - Browser: [e.g. chrome, safari]
 - Browser version: [e.g. 22]
 - VPN provider if you use one:
 - Your location (country):

**Additional context**

**Comment by eebssk1** [comment]
DNS poisoning.

**Comment by eebssk1** [comment]
Url block too.
use hosts file to bind the target ip to fastly or cloudflare does not work.
Use test1.jsdelivr.net does work. Seems the main url is blocked.

**Comment by TerryZ** [comment]
又出问题了，生产项目不敢用了，后面要逐步恢复使用自行构建的版本

**Comment by xqk666** [comment]
Unable to load resource in China

**Comment by seymoe** [comment]
历史总是惊人的相似。

**Comment by weeksun23** [comment]
Because of this, the official website of echarts cannot be opened in some parts of China

**Comment by jimaek** [comment]
Unfortunately there isn't anything we can do about it. We maintained a China specific block list but it still wasn't enough apparently. We don't know the exact reason for the block or how to unblock our service.

Related https://github.com/jsdelivr/jsdelivr/issues/18392

**Comment by eebssk1** [comment]
in the meanwhile, use the mirror link like cloudflare or fastly.Or try write browser extension that redirect the root url to the alternatives.

**Comment by XiaoJ-96** [comment]
中国区就完犊子了？

**Comment by PipecraftNet** [comment]
> in the meanwhile, use the mirror link like cloudflare or fastly.Or try write browser extension that redirect the root url to the alternatives.

Here is a JavaScript code that redirect the root url to the alternatives.
https://github.com/PipecraftNet/jsdelivr-auto-fallback
