### ISSUE TITLE
cdn.jsdelivr.net Partially Censored in China

### ISSUE THREAD

**Issue by hifocus** [jsdelivr/jsdelivr#18392]
**Describe the bug**
The asset domain of `cdn.jsdelivr.net` has been blocked by the GFW in China via DNS hijacking. Currently this affects around 2/5 of users distributed in different part of China, according to a Ping test conducted on the ipip.net platform.

Currently, those affected will see `cdn.jsdelivr.net` being resolved to Facebook/Twitter IPs that are long blocked in China, alternatively users may see an empty response from the DNS resolution.

**Affected jsDelivr links**
`https://cdn.jsdelivr.net/*`

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.

**Screenshots**
![image](https://user-images.githubusercontent.com/30528433/165791630-0c7ac443-9bcd-48e4-bace-db79fa16610c.png)
![image](https://user-images.githubusercontent.com/30528433/165791655-df9f7f15-3536-425b-9c77-daffd7679ab9.png)
![image](https://user-images.githubusercontent.com/30528433/165791667-47f11917-4b35-4cb6-9914-78fae149c05e.png)
![image](https://user-images.githubusercontent.com/30528433/165791681-83e1e61a-4532-4416-bbf1-9c48b1bb4b14.png)
A full-sized screenshot of the test can be seen [here](https://user-images.githubusercontent.com/30528433/165791831-4a974c98-eed3-4414-b6df-46977c7740c9.png).

**Please complete the following information:**
 - Your location (country): China

**Additional context**

According to previous experiences, unless the block triggers a wide-range opposition by internet users, such as the [GitHub block in 2013](https://en.wikipedia.org/wiki/Censorship_of_GitHub#China), it is unlikely that any websites/domains will ever be unblocked.

Thank you for providing this amazing project to Chinese users in the past years.

**Comment by jimaek** [comment]
We're not familiar with the Chinese law, so if anyone knows if there is a way to appeal this and get us unblocked please email me dak@prospectone.io

**Comment by XIU2** [comment]
The main reason for the cancellation of the **ICP license** and this **DNS hijacking** is that ` cdn.jsdelivr.net ` provides a **Github Raw mirror**.

A similar situation, eg: ` cdn.statically.io ` is also **DNS hijacked** because it serves a **Github Raw mirror**.

**Comment by Simple2ich4n** [comment]
My website referenced CDN css js files, it crashed, and the view has been restored

**Comment by jimaek** [comment]
I understand that this sucks and we're very saddened to see the Chinese jsDelivr community suffer but unfortunately there is nothing we can do from our side :(

**Comment by MasterOfStar** [comment]
It is now restored

**Comment by hifocus** [comment]
Amazing to 👂
