### ISSUE TITLE
Intermittent issues with GitHub @branch files in large repos

### ISSUE THREAD

**Issue by fawazahmed0** [jsdelivr/jsdelivr#18393]
**Describe the bug**
I sometimes find jsDelivr link not working, the link doesn't work for 1 day, and from next day it starts working again.
It happened to me couple of times.
I don't remember what error it showed

The files are `.json` files and are on github.

**Affected jsDelivr links**
I currently don't have the url, because it happens rarely and only reproducible for one day.

I had to add fallback mechanism in my code, to fetch from `raw.githubusercontent.com` , incase jsDelivr url fails.
If you would like to debug this bug, I will rewrite my existing code, to save the failed jsDelivr urls, so that you can debug this issue. (but please note that the issue will be reproducible only for 1 day, so this will require your instant attention after I share the failing url)

Thanks for creating jsDelivr

**Comment by fawazahmed0** [comment]
Similar https://github.com/jsdelivr/jsdelivr/issues/18216

**Comment by jimaek** [comment]
Do you have example URLs that have this behaviour?

**Comment by fawazahmed0** [comment]
ok, I will rewrite my code to save the failed urls and will share them as soon as I get one , please wait for few days

**Comment by fawazahmed0** [comment]
@jimaek @MartinKolarik , I made a script to reproduce this bug, I ran the script in github actions (currently it's not reproducible at my end, but was reproducible in github actions)

`curl -v https://cdn.jsdelivr.net/gh/fawazahmed0/debug-jsdelivr-2@1/data/168/936.json`

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.16.85.20:443...
* TCP_NODELAY set
* Connected to cdn.jsdelivr.net (104.16.85.20) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2322 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jul  3 00:00:00 2021 GMT
*  expire date: Jul  2 23:59:59 2022 GMT
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x5584a92c7800)
} [5 bytes data]
> GET /gh/fawazahmed0/debug-jsdelivr-2@1/data/168/936.json HTTP/2
> Host: cdn.jsdelivr.net
> user-agent: curl/7.68.0
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [238 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [238 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
} [5 bytes data]
< HTTP/2 403 
< date: Wed, 04 May 2022 18:32:19 GMT
< content-type: text/plain; charset=utf-8
< content-length: 138
< alt-svc: h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400
< access-control-allow-origin: *
< access-control-expose-headers: *
< timing-allow-origin: *
< cache-control: public, max-age=60, s-maxage=60
< cross-origin-resource-policy: cross-origin
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< etag: W/\"8a-Ce3cJN8OGoB8A/cEP06kPIrDoWI\"
< x-served-by: cache-fra19163-FRA, cache-cdg20735-CDG
< x-cache: MISS, MISS
< vary: Accept-Encoding
< cf-cache-status: HIT
< expect-ct: max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"
< report-to: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=0dxUQhwgACgMnFL6AZLPOCFcg4kEnMD2GwEWeEgmHEZ7tWSBh8sHKsHEKmha5zvXgz8HcCQ6ODax9EeByjOR8zqb8cYk1MBs6JuGkYcXteJGwtbWL3VLQvb5oRKSfoKtlQg%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}
< nel: {\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}
< server: cloudflare
< cf-ray: 7063517eed1a58cc-IAD
< 
{ [138 bytes data]
100   138  100   138    0     0   1179      0 --:--:-- --:--:-- --:--:--  1179
* Connection #0 to host cdn.jsdelivr.net left intact
```

**Comment by fawazahmed0** [comment]
To reproduce this at your end, you can run [this script](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/1/fet.js), just comment out [this line](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/b22007484e49cd6cca863f7f9168a701b0e63d6c/fet.js#L50)

This is what I did to reproduce this bug, I generated random json files in [this repo](https://github.com/fawazahmed0/debug-jsdelivr-2) using [this script](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/1/gen.js)

Then created [this script](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/1/fet.js) to fetch the random json files using [node-fetch](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/b22007484e49cd6cca863f7f9168a701b0e63d6c/fet.js#L35) and on error response it will print the headers using [curl](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/b22007484e49cd6cca863f7f9168a701b0e63d6c/fet.js#L48)

Just for example see log in this [github actions](https://github.com/fawazahmed0/debug-jsdelivr-2/runs/6290421758?check_suite_focus=true#step:3:42)

**Comment by MartinKolarik** [comment]
I checked our analytics for your repos and I see very occasionally something fails, but unfortunately, I'm not sure what we can do here.

What happens is that we use `raw.githubusercontent.com` as the primary way to fetch data from GitHub, but it isn't 100% reliable - on occasion, it may return an error for valid files (not much we can do about that). When then happens, we try to fetch a tarball of the whole repo as a fallback which usually helps, because that's loaded from a different GH service - but that has a limit of 50 MB for the whole repo and yours exceeds that.

Our own S3 fallback doesn't work here either because you use branches instead of proper releases. With the no releases and large repo combination, we're limited by `raw.githubusercontent.com`'s reliability.

**Comment by MartinKolarik** [comment]
I'll try to check what errors GitHub returns and if we can handle them smarter but generally it would help a lot if your project was better structured (e.g., one release per day with just data for that day) - I would be happy to provide suggestions about what would work best but not sure if changing the URL structure is suitable for you at this point.

**Comment by fawazahmed0** [comment]
Thanks Martin for looking into this and yeah changing URL structure for my API's won't be possible now.
I guess I should have used release instead of using a directories.

If you would like, I can run [this same script](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/1/fet.js) with `raw.githubusercontent.com` URL to see what error GitHub returns.

**Comment by fawazahmed0** [comment]
I ran the same script to fetch [raw.githubusercontent.com](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/47092897bd8b384e96aa9efa210bc216f1bd8739/fet.js#L14) links, it seems pretty stable i.e no [error response](https://github.com/fawazahmed0/debug-jsdelivr-2/runs/6301658782?check_suite_focus=true#step:3:13).

Are you sure `raw.githubusercontent.com` is unreliable?

**Comment by MartinKolarik** [comment]
@fawazahmed0 we improved the logging for this case to get further details but so far all errors I see are caused by correct 404 on your prod repo. If you can, please reenable the testing cron for some time and I'll get back to this when some of the failed requests are recorded (we might need more than one so keep it running for some time).

**Comment by fawazahmed0** [comment]
ok, I have restarted the cron for jsdelivr urls, also you will receive an [email of failed url](https://github.com/fawazahmed0/debug-jsdelivr-2/blob/7c81c6d9f23fec76cd3ba22289eb4928fb8e3ede/fet.js#L54)

**Comment by fawazahmed0** [comment]
You can checkout the logs, [here](https://github.com/fawazahmed0/debug-jsdelivr-2/runs/6323751624?check_suite_focus=true) & [here](https://github.com/fawazahmed0/debug-jsdelivr-2/runs/6324827629?check_suite_focus=true), also if you have noticed, there are multiple [ECONNRESET error](https://github.com/fawazahmed0/debug-jsdelivr-2/runs/6323751624?check_suite_focus=true#step:3:76), maybe you might want to look into those urls also, I did not find `ECONNRESET` error with [rawgithub](https://github.com/fawazahmed0/debug-jsdelivr-2/runs/6301658782?check_suite_focus=true#step:3:13) urls

**Comment by MartinKolarik** [comment]
Thanks, @fawazahmed0, you can disable the cron now. I see the errors were caused by GitHub timing out, we have a 2s limit for establishing the initial TCP connection. I will check if we can make any improvements here.

**Comment by fawazahmed0** [comment]
Thanks for looking into it, and yeah I have disabled the cron

**Comment by MartinKolarik** [comment]
We added a retry for this case. In the past 24 hours, I still see one occurrence of a timeout but hopefully, overall it'll be better now.

**Comment by fawazahmed0** [comment]
would you like me to restart the cron?

**Comment by MartinKolarik** [comment]
You can try, though as I said, it appears the issue may still arise occasionally. Hopefully less often.

**Comment by fawazahmed0** [comment]
Nah, I just thought you wanted me to restart the cron, so I was just confirming. 
And yeah, thank you to all you guys for making things more stable
