### ISSUE TITLE
Request to increase package size limit for @withfig/autocomplete

### ISSUE THREAD

**Issue by SeparateRecords** [jsdelivr/jsdelivr#18395]
**Link to the npm package or GitHub repository**
https://github.com/withfig/autocomplete & https://npmjs.com/package/@withfig/autocomplete

**Project license**
ISC

**Your relation to the project**
Maintainer

**Short description of the project**
@withfig/autocomplete is the package that contains autocomplete specs for [fig.io](https://fig.io)'s autocomplete tool. It's also used by Warp, shell.how, https://fig.io/manual - essentially, it is an open source hub for defining the structure of assorted CLI tools, similar to the TLDR pages.

**Please confirm the following:**
 - [x] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests)
 - [x] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).

**Additional context**
The individual completion specs are very small - for example the `ls` spec is only about 6KB. There are just a lot of completion specs.

**Comment by MartinKolarik** [comment]
Hi @SeparateRecords, are you facing any issues with the package right now? I see that https://www.jsdelivr.com/package/npm/@withfig/autocomplete is about 43 MB and our limit is currently 100 MB, so you should be good even without the increase.

**Comment by SeparateRecords** [comment]
Hmm, that's interesting... 2.239.0 was 107MB, 2.240.0 was 42.6MB. Seems like it might have been a bug with esbuild, nothing changed between those two releases other than adding an _additional_ completion spec.

If you could still increase the limit, that would be excellent. We expect the repo to grow a lot in the coming months; the package will eventually hit 100MB. In our experience jsDelivr has been the fastest and most reliable CDN - we'd rather not have to go through this when it's too late!

**Comment by MartinKolarik** [comment]
All right, we'll increase the limit shortly.
