### ISSUE TITLE
Request to increase package size limit for wp-statistics/GeoLite2-City

### ISSUE THREAD

**Issue by mostafasoufi** [jsdelivr/jsdelivr#18394]
**Link to the npm package or GitHub repository**
https://github.com/wp-statistics/GeoLite2-City

**Project license**
CC Attribution-ShareAlike 4.0

**Your relation to the project**
maintainer

**Short description of the project**
We use GeoLite2-City Database created by [MaxMind](https://www.maxmind.com/) on our own plugin ([WP-Statistics](https://wordpress.org/plugins/wp-statistics/)) which needs to be downloaded from the plugin.

**Please confirm the following:**
 - [x] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
 - [x] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).

**Additional context**
At the moment we use raw.githubusercontent.com to download the file but migrating to **jsdelivr**, has a file size restriction and needs to be increased. Thank you so much!

**Comment by MartinKolarik** [comment]
Hi @mostafasoufi, this seems like it may be useful for other people too. Would you consider using a GitHub action to publish this to npm under some common name, so that other people can find and use it easily? The npm packages also work better with large files and have a default limit of 100 MB.

**Comment by jimaek** [comment]
Is this allowed by maxmind's license?

**Comment by MartinKolarik** [comment]
@jimaek yes the license is based on CC BY-SA 4.0

**Comment by mostafasoufi** [comment]
@jimaek Yes, I just updated the license in the issue.

https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en

Btw, thanks for applying & commenting 😉 @MartinKolarik

**Comment by mostafasoufi** [comment]
>Would you consider using a GitHub action to publish this to npm under some common name, so that other people can find and use it easily?

Good point! I'll do that then.

**Comment by MartinKolarik** [comment]
Once you have it on npm the link will be `https://cdn.jsdelivr.net/npm/{name}/{path}` and the higher limit will apply.

**Comment by mostafasoufi** [comment]
This is cool! thanks, guys!

https://cdn.jsdelivr.net/npm/geolite2-city/
