### ISSUE TITLE
China cannot visit cdn. jsdelivr.net 

### ISSUE THREAD

**Issue by cxp1539** [jsdelivr/jsdelivr#18402]
![image](https://user-images.githubusercontent.com/45785238/169003555-87cb3dfa-bd01-4747-8678-4d7d6734265b.png)

**Comment by PipecraftNet** [comment]
@cxp1539 Try this one.
https://github.com/PipecraftNet/jsdelivr-auto-fallback

For Chinese users:
这是一个自动检查 `cdn.jsdelivr.net` 是否可用， 如果不可用时，会自动把所有 **js, css, image** 的地址切换到其他可用的域名的脚本。

**Comment by Xuezenghuigithub** [comment]
@PipecraftNet 用不了

**Comment by cxp1539** [comment]
> Cannot access cdn.jsdelivr.net since this morning.
> 
> https://cdn.jsdelivr.net/npm/shimney-knockout-mapping@2.4.1/main.js?bust=1652320639088

I couldn't visit it yesterday afternoon

**Comment by rysinal** [comment]
Cannot access https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js

**Comment by DelingAlieZ10** [comment]
> 好像恢复了
并没有

**Comment by PasseRR** [comment]
it still not restored, anybody?

**Comment by saowu** [comment]
确实没恢复

**Comment by Guoyuh78** [comment]
我天朝就是怎么屌！！！

**Comment by sonofmagic** [comment]
我的 graphql playground 都打不开了！！
npm/@apollographql/graphql-playground-react@1.7.42/build/static/css/index.css
npm/@apollographql/graphql-playground-react@1.7.42/build/static/js/middleware.js
https://github.com/apollographql/apollo-server/issues/6441

**Comment by my2969500039** [comment]
啥时候能好啊，官方不给力

**Comment by linchengwen** [comment]
error

**Comment by liugezhou** [comment]
Who can tell me what happened？

**Comment by PipecraftNet** [comment]
> @PipecraftNet It doesn't work

@Xuezenghuigithub 能说明一下有什么问题吗？方便截图吗？
刚刚升级了一个版本，性能提高了不少。
https://github.com/PipecraftNet/jsdelivr-auto-fallback 

已用在我的两个网站上，都没问题。
- https://v2hot.pipecraft.net/
- https://discuss-cn.bestxtools.com/d/37

**Comment by PipecraftNet** [comment]
@liugezhou Try this one:
 https://github.com/PipecraftNet/jsdelivr-auto-fallback

**Comment by saowu** [comment]
试过了，无用




吴延博
***@***.***




------------------ Original ------------------
From: Pipecraft ***@***.***&gt;
Date: Fri,May 20,2022 5:23 PM
To: jsdelivr/jsdelivr ***@***.***&gt;
Cc: 吴延博 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [jsdelivr/jsdelivr] China cannot visit cdn. jsdelivr.net  (Issue#18402)





 
@liugezhou Try this one:
 https://github.com/PipecraftNet/jsdelivr-auto-fallback

**Comment by PipecraftNet** [comment]
> 试过了，无用 吴延博 ***@***.***

@saowu 能说明一下有什么问题吗？刚升级了版本，新版本修复了一些问题。

**Comment by abcmiao** [comment]
哎，freedom，freedom

**Comment by jimaek** [comment]
Unfortunately there isn't anything we can do about it. We maintained a China specific block list but it still wasn't enough apparently. If someone knows how to contact the relevant Chinese organs to discuss the unban of the service please let us know.

In the meantime you can try a service like https://github.com/PipecraftNet/jsdelivr-auto-fallback
