### ISSUE TITLE
https://cdn.jsdelivr.net/  can not accessible

### ISSUE THREAD

**Issue by lchlch** [jsdelivr/jsdelivr#18401]
china user

**Comment by yesmore** [comment]
> china user

try `https://fastly.jsdelivr.net/`
I replaced `https://cdn.jsdelivr.net/` in my project with `fastly`, it works.

**Comment by QYF233** [comment]
> 

Thank

**Comment by eebssk1** [comment]
#18396

**Comment by imyangyong** [comment]
any process?

**Comment by shaoshaossm** [comment]
> > 中国用户
> 
> 尝试`https://fastly.jsdelivr.net/` 我`https://cdn.jsdelivr.net/`在我的项目中替换为`fastly`，它可以工作。
谢谢

**Comment by MartinKolarik** [comment]
#18396

**Comment by GC-ZF** [comment]
> > china user
> 
> try `https://fastly.jsdelivr.net/` I replaced `https://cdn.jsdelivr.net/` in my project with `fastly`, it works.

Thank you. Will the original be repaired？

**Comment by Andy17269** [comment]
谢谢您
