### ISSUE TITLE
Why can it be accessed in China Fastly.jsdelivr.net, but Cloudflare.jsdelivr.net and Quantil.jsdelivr.net cannot access JSDELIVR CDN?

### ISSUE THREAD

**Issue by lling1234** [jsdelivr/jsdelivr#18408]
Why can it be accessed in China Fastly.jsdelivr.net, but Cloudflare.jsdelivr.net and Quantil.jsdelivr.net cannot access JSDELIVR CDN?

**Comment by jimaek** [comment]
Because it seems China specifically blocked cdn.jsdelivr.net and not the other subdomains. But the block makes it impossible to do redirects to fix the problem.
