### ISSUE TITLE
Can jsdelivr add an Akamai CDN?

### ISSUE THREAD

**Issue by BNQDZJ** [jsdelivr/jsdelivr#18416]
The speed of Akamai CDN in mainland China is faster than fastly and cloudflare (no ICP filing), and many companies that are not registered in mainland China want to provide services in mainland China and will use Akamai's services, such as Riot Games, Ubisoft , Roblox, Honda, iqiyi, china merchants, Adobe and other companies are using Akamai's services

**Comment by jimaek** [comment]
Unfortunately we've been unable to get in contact with them regarding a sponsorship over the years.
They aren't interested in working with open source it seems
