### ISSUE TITLE
CocoaPods install fail due to cdn.jsdelivr.net cannot be accessed in China

### ISSUE THREAD

**Issue by KidLau** [jsdelivr/jsdelivr#18411]
**Describe the bug**
my app based on react native and it is blocked due to cannot run `pod install` successfully. I tried to access below links with proxy of Clash and worked in Chrome but CLI in terminal. I already set proxy to git. If someone has any solutions, please let me know. Thanks in advance.

**Affected jsDelivr links**
1. https://cdn.jsdelivr.net/cocoa/Specs/6/7/d/boost-for-react-native/1.63.0/boost-for-react-native.podspec.json
2. https://cdn.jsdelivr.net/cocoa/Specs/6/7/d/boost-for-react-native/1.63.0-1/boost-for-react-native.podspec.json

**Screenshots**
![image](https://user-images.githubusercontent.com/12117333/170402142-c184f73c-5892-4cb6-bf62-394dab750808.png)

**Comment by MartinKolarik** [comment]
As per our user reports in #18397 you may be able to use `fastly.jsdelivr.net` instead.

**Comment by KidLau** [comment]
> As per our user reports in #18397 you may be able to use `fastly.jsdelivr.net` instead.

But those links were from a dependency package. How can I change it? I tried setting `199.232.69.229 cdn.jsdelivr.net` in `hosts` but still not working. `199.232.69.229` is an IP of `fastly.jsdelivr.net`.

**Comment by Guleixibian2009** [comment]
@KidLau
