### ISSUE TITLE
Question about JSDelivr - Does it automatically updates the files on the CDN?

### ISSUE THREAD

**Issue by thedoggybrad** [jsdelivr/jsdelivr#18414]
Does it automatically updates the files on the CDN?
I need a Yes or a No only.

**Comment by thedoggybrad** [comment]
I mean when I do a commit does it update or when or every how many minutes, time, or if the file is updated.

**Comment by jimaek** [comment]
Yes, but only from tags.

**Comment by thedoggybrad** [comment]
@jimaek I have just having a small knowledge since I am a beginner. Can you confirm that the tags you are referring to are the individual commits?

**Comment by jimaek** [comment]
No, files won't get auto updated from commits if you don't tag your releases correctly.

**Comment by thedoggybrad** [comment]
Right Now, I do commits from a forked repo using Github Actions (Automatically), does using this commit method updates the content on the CDN. I never touch the Tags or whatever in the repo but the actions-user labels the commit as "Merge ......". Does the changes was sync to the repo. Sorry again for disturbance, I am really a beginner.

@jimaek

**Comment by thedoggybrad** [comment]
@jimaek 
If you need a reference if the tags are correctly labelled by the actions-user here is the repo's commits: https://github.com/thedoggybrad/UBlockFiltersforall/commits/master

**Comment by thedoggybrad** [comment]
@jimaek 
According to my observations, I think the mergers 36 minutes ago was applied for one of the file I visited and compared. I am not still sure, so I will wait for your answer.

**Comment by jimaek** [comment]
@MartinKolarik what do you think?

**Comment by MartinKolarik** [comment]
https://github.com/jsdelivr/jsdelivr#caching

**Comment by thedoggybrad** [comment]
@MartinKolarik Thank You, I now understand.

**Comment by thedoggybrad** [comment]
@jimaek @MartinKolarik 
I would like to thank all of you for answering my questions. I think that the mergers done to my repo is properly labeled so that the updates are properly updated to the CDN.
