### ISSUE TITLE
One possible solution for DNS pollution in China

### ISSUE THREAD

**Issue by Guleixibian2009** [jsdelivr/jsdelivr#18413]
Hey guys, we are now suffering from DNS pollution in China. But I found a solution here:
Install [devSidecar](https://github.com/docmirror/dev-sidecar) on your computer, follow the instructions and install the certificate, then find this:
![图片](https://user-images.githubusercontent.com/79316026/170848846-014d630b-9efe-476b-8639-aedb45750836.png)
Add those selected lines and all `cdn.jsdelivr.net` will be automatically redirected to `fastly.jsdelivr.net` which is not polluted.
```json
"cdn.jsdelivr.net": {
    ".*":  {
      "redirect": "fastly.jsdelivr.net",
      "sni": "baidu.com",
      "test": "https://cdn.jsdelivr.net/npm/clipboard@2.0.8/dist/clipboard.min.js"
    }
  },
```

**Comment by tianyingchun** [comment]
how about this , Is there no official solution?

**Comment by tianyingchun** [comment]
i just local proxy `cdn.jsdelivr.net` 127.0.0.1 rewrite it to https://unpkg.com/*

**Comment by PYUDNG** [comment]
I don't know why but that does not works on my computer…

![截屏2022-06-04 下午6 08 59](https://user-images.githubusercontent.com/63054558/171994767-e93f6809-edb4-413c-b2aa-94a4e6b601b1.jpg)

![截屏2022-06-04 下午6 08 23](https://user-images.githubusercontent.com/63054558/171994753-9bed3189-13dd-4cdb-aed3-d750e0271c6f.jpg)

Is there any solution?

**Comment by Guleixibian2009** [comment]
Hi @PYUDNG Maybe you should:
- Upgrade to the newest version of DevSidecar (1.7.3 instead of 1.7.2)
- Re-install the certificate as `Trusted`
- Uncheck this option:
![图片](https://user-images.githubusercontent.com/79316026/172000327-6c4c9f43-be5f-4c40-9db9-d1b871b8e75b.png) (It used to be `gitee.com` but the project is now banned on `gitee`, so just uncheck is ok)
- Did you turn on your Mac's system proxy option(i dunno, i use Windows)?

**Comment by Guleixibian2009** [comment]
Mine is ok, redirected to `fastly`
![图片](https://user-images.githubusercontent.com/79316026/172000541-96cbe82d-5be0-4562-9fa2-7e153ef55c0c.png)

**Comment by Guleixibian2009** [comment]
P.S. try updating that piece of code with:
```json
  "cdn.jsdelivr.net": {
    ".*": {
      "redirect": "fastly.jsdelivr.net",
      "backup": [
        "cdn.jsdelivr.net",
        "cloudfare.jsdelivr.net",
        "quantil.jsdelivr.net"
      ]
    }
  },
```

**Comment by zhangchuanben** [comment]
worked for me, thanks

**Comment by Guleixibian2009** [comment]
😉

**Comment by Guleixibian2009** [comment]
If the piece of code stopped working for you, just add another line:
```json
"sni": "www.jsdelivr.com",
```

so the full code will be:
```json
  "cdn.jsdelivr.net": {
    ".*": {
      "redirect": "fastly.jsdelivr.net",
      "sni": "www.jsdelivr.com",
      "backup": [
        "cdn.jsdelivr.net",
        "quantil.jsdelivr.net",
        "gcore.jsdelivr.net"
      ]
    }
  },
```

**Comment by Guleixibian2009** [comment]
I heard that some of the `.jsdelivr.net` are in SNI block. So maybe first turn it to `jsdelivr.com`.

**Comment by PYUDNG** [comment]
Thanks for your advice but when I tried:
1. Version 1.7.3 of Dev-Sidecar does not works on my Mac:( So I just uses v1.7.2, and as the changelog says, there is no improvements for mac users between v1.7.3 and v1.7.2
2. I cannot turn on system proxy... When I tried to do so I got this: ![截屏2022-06-10 上午3 18 26](https://user-images.githubusercontent.com/63054558/172926896-7c503fab-b70b-4b1b-9544-8718e9d83e83.jpg)
3. I have already trusted CA ![截屏2022-06-10 上午3 23 02](https://user-images.githubusercontent.com/63054558/172927963-f18aef25-0b12-4b55-9da7-2bc7f6f81dc8.jpg)
4. I have disabled the remote configuration option (and restarted the service)
5. I have tried this already
> ```json
>   "cdn.jsdelivr.net": {
>     ".*": {
>       "redirect": "fastly.jsdelivr.net",
>       "sni": "www.jsdelivr.com",
>       "backup": [
>         "cdn.jsdelivr.net",
>         "quantil.jsdelivr.net",
>         "gcore.jsdelivr.net"
>       ]
>     }
>   },
> ```
But still got this result
![截屏2022-06-10 上午3 25 28](https://user-images.githubusercontent.com/63054558/172928334-8276c49d-5b89-4463-957c-b9c95c32a0b4.jpg)

I really really tried...

**Comment by tianyingchun** [comment]
share my solution here via setup local nginx in `macos`
1. brew info nginx
2. cd /opt/homebrew/etc/nginx/servers/.
3. vim `nginx.conf ` as below
```shell
 server {
       listen       443 ssl;
       server_name  localhost;

       ssl_certificate      sslkey/127.0.0.1+13.pem;
       ssl_certificate_key  sslkey/127.0.0.1+13-key.pem;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;

       location / {
           root   html;
           index  index.html index.htm;
       }
    }
    include servers/*;
```
4. cd `servers/*`, create file named `cdn.jsdelivr.net`
```shell
server {
  listen   443 ssl;
  access_log off;
  server_name cdn.jsdelivr.net;
  ssl_certificate      sslkey/127.0.0.1+13.pem;
  ssl_certificate_key  sslkey/127.0.0.1+13-key.pem;

  ssl_session_cache    shared:SSL:1m;
  ssl_session_timeout  5m;

  ssl_ciphers  HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers  on;

  root /Users/tyc/Documents/flatjs/flatjs-hexo;

  location ~* \.(tpl|inc|cfg|less|scss)$ {
    deny all;
  }

  location ~ /\. {
    deny all;
    log_not_found off;
  }

  location /npm {
    rewrite ^/npm/?(.*)$ /$1 break;
    proxy_pass https://unpkg.com;
  }
}

server {
  listen   80;
  access_log off;
  server_name cdn.jsdelivr.net;
  root /Users/tyc/Documents/flatjs/flatjs-hexo;
  location ~* \.(tpl|inc|cfg|less|scss)$ {
    deny all;
  }

  location ~ /\. {
    deny all;
    log_not_found off;
  }

  location /npm {
    rewrite ^/npm/?(.*)$ /$1 break;
    proxy_pass https://unpkg.com;
  }
}
```
5. Note `    proxy_pass https://unpkg.com;` proxy to `unpkg.com`
6. sslkey/127.0.0.1+13.pem;  you need make an self-sign certification

**Comment by Guleixibian2009** [comment]
☹sorry, I’m afraid I can’t fix this if all of the suggestions above failed…… There is hug difference between Windows and Mac……

**Comment by Guleixibian2009** [comment]
Pollution is now fixed! So I'm gonna close this:) I'll reopen when the problem comes back.
