### ISSUE TITLE
esm.run: error bundling @starbeam/core

### ISSUE THREAD

**Issue by NullVoxPopuli** [jsdelivr/jsdelivr#18419]
**Describe the bug**

Initially reported here: https://github.com/starbeamjs/starbeam/issues/19

When using [this jsfiddle](
https://jsfiddle.net/NullVoxPopuli/dyfgh5tw/) and [esm.run](https://www.jsdelivr.com/esm)

We get an error about rollup not being able to process `@starbeam/core` 

**Affected jsDelivr links**

https://cdn.jsdelivr.net/npm/@starbeam/core/+esm

**Response headers**
n/a

**Screenshots**
n/a

Text tho:
```
/**
 * Failed to bundle using Rollup v2.72.1.
 * If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr
 */

 throw new Error('Failed to bundle using Rollup v2.72.1. If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr');
 ````

**Please complete the following information:**
 - Device OS: n/a
 - Browser: Firefox
 - Browser version: 101.0.1
 - VPN provider if you use one: none
 - Your location (country): US 

**Additional context**

What is happening? shouldn't it only be swapping out absolute import paths with other esm.run urls?

**Comment by NullVoxPopuli** [comment]
I tried the same thing on skypack, and got a meaningful error.

```
/*
 * [Package Error] "@starbeam/core@v0.5.1" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   Failed to load node_modules/@starbeam/core/dist/index.js
 *     Unexpected token (67:10) in @starbeam/core/dist/index.js
 *   Install failed.
 *   Install failed.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */
 ```

It looks like esm.run and skypack are failing on the usage of private fields -- which is goofy, considering private fields are supported natively in browsers now.

**Comment by MartinKolarik** [comment]
> Is there a way to tell esm.run to not bundle / rollup and just swap out the import paths?

No, although we are considering that option. For now, I'll check what's blocking the private field support at this point.

**Comment by MartinKolarik** [comment]
We already support private properties (since #18303) but this is failing at the minification step due to a static initialization block, which isn't [supported by terser yet](https://github.com/terser/terser/issues/1093).

![image](https://user-images.githubusercontent.com/6192491/175783934-7483f332-9616-46d7-91e7-cfe9bd6a7181.png)

We'll update terser to support this as soon as they implement it.

**Comment by NullVoxPopuli** [comment]
can we opt out of terser? :upside_down_face:

**Comment by MartinKolarik** [comment]
Unfortunately no, we minify all files and there's no flag to skip that step.

**Comment by NullVoxPopuli** [comment]
does it make sense for one to be added? otherwise we'll always have this catch up game of browser features and terser updates?

**Comment by MartinKolarik** [comment]
It's a good question for sure. On one side, you might not want to ship unminified js, on the other, it's still better than not working at all.

**Comment by MartinKolarik** [comment]
I believe this works now.

**Comment by NullVoxPopuli** [comment]
it does, thanks!
