### ISSUE TITLE
An resolution to CDN service in China Mainland

### ISSUE THREAD

**Issue by Big-Cake-jpg** [jsdelivr/jsdelivr#18421]
I know jsDelivr's ICP filling has been revoked, but maybe you can try [UPYUN](https://upyun.com).

UPYUN has sponsored many projects like Aplayer etc.

Though UPYUN's CDN services require ICP filling, they may can help jsDelivr regain it's ICP filling.

Just have a try, I hope jsDelivr can become better.

**Comment by Big-Cake-jpg** [comment]
GitHub: https://github.com/upyun

**Comment by xuhuachen** [comment]
I don't understand your point, are you an employee of this company?

**Comment by Big-Cake-jpg** [comment]
> I don't understand your point, are you an employee of this company?

No, I'm not. I just use their CDN services.

**Comment by xuhuachen** [comment]
Maybe UPYUN has a good cdn service, but it doesn't have the ability to help jsdelivr, and doesn't even want to help.

**Comment by Big-Cake-jpg** [comment]
> Maybe UPYUN has a good cdn service, but it doesn't have the ability to help jsdelivr, and doesn't even want to help.

But they sponsored many project. Just like APlayer.

**Comment by xuhuachen** [comment]
It looks like jsdelivr is already accessible in China, and although not the fastest, it's already the best result.
I want to say to jsdelivr: Be yourself and stay away from those bad governments.

**Comment by BNQDZJ** [comment]
This method will not be implemented, because it is clearly stated in the https://github.com/jsdelivr/jsdelivr/issues/18407#issuecomment-1154097518 that it will not
