### ISSUE TITLE
Error from jsdelivr-separator.js

### ISSUE THREAD

**Issue by jcubic** [jsdelivr/jsdelivr#18427]
**Describe the bug**
I've got a weird error from my [bookmarklet](https://lips.js.org/#bookmark). It throws an error in 

https://cdn.jsdelivr.net/sm/jsdelivr-separator.js file

Its content is only a semilcolon.

**Affected jsDelivr links**
I'm trying to use this combined URL:

https://cdn.jsdelivr.net/combine/gh/jcubic/jquery.terminal@3c8166de596b2e4ad539da5f0e1f8a48a937a2bc/js/jquery.terminal.min.js,npm/jquery.terminal/js/prism.js,npm/prismjs/components/prism-scheme.min.js,gh/jcubic/lips@873c9927a1eec478ae0f89ea675ac8c0bcedbabb/lib/js/terminal.js,gh/jcubic/lips@873c9927a1eec478ae0f89ea675ac8c0bcedbabb/lib/js/prism.js,npm/js-polyfills/keyboard.js

**Response headers**
I don't see this file in Network tab

**Screenshots**
![Przechwycenie obrazu ekranu_2022-08-08_20-48-48](https://user-images.githubusercontent.com/280241/183491762-79de2082-f4b5-4a99-9505-ca3c49335f95.png)

**Please complete the following information:**
 - Device OS: [e.g. iOS]: Fedora 36
 - Browser: [e.g. chrome, safari]: Google Chrome
 - Browser version: [e.g. 22] 104
 - VPN provider if you use one:
 - Your location (country): Poland

**Additional context**
I'm not sure if this is an error in my script because all I see is `jsdelivr-separator.js` in the console and I have no idea where it came from. There are no location headers but there is a source map maybe that is the issue:

```javascript
//# sourceMappingURL=/sm/4d68ef7949419fe0839e0ac86bd923c2111d1740fdeaad67baecf981890e716b.map
```

I was searching for jsdelivr-separator.js but only found this old StackOveflow question without an answer:

[How to load editorJs scripts integrated with django after an ajax call?](https://stackoverflow.com/q/69846419/387194)

If the error came from my script, there should be some kind of better error message since this is really confusing.

**NOTE:** the bookmark on the website in the first link is working fine, I have the version I was debugging, but last time when I checked it was working.

**Comment by MartinKolarik** [comment]
It's possible the source map is one line off, but it isn't related to the error - that's an error in the original script. Based on the error message, it's this part:

![image](https://user-images.githubusercontent.com/6192491/183648383-3dfff2fd-de9d-4c19-816c-ee9c564b2c3a.png)

**Comment by jcubic** [comment]
I've found my error. I've added the Prism variable with the default state and later I was checking if Prism is defined. That's why one of my files didn't load.

But it would be nice to do something with the error messages and source map.

**Comment by MartinKolarik** [comment]
I created an issue in our backend repo to check the source map. Going to close this one since the main problem was resolved.

**Comment by jcubic** [comment]
Can you add a link to this issue?

**Comment by MartinKolarik** [comment]
The CDN has a private repo, unfortunately, but we'll crosspost here when it's resolved.

**Comment by jcubic** [comment]
Ok thanks.

**Comment by MartinKolarik** [comment]
@jcubic we're unable to replicate this now, I'm guessing because some of the files got updated and the link you posted doesn't have pinned versions for some of the packages. Any chance you remember what the exact combination of files was that caused this error and can post a combine link that still has this issue?

**Comment by MartinKolarik** [comment]
Actually based on the sourcemap link you posted, I belive this is the combined file: https://cdn.jsdelivr.net/combine/gh/jcubic/jquery.terminal@3c8166de596b2e4ad539da5f0e1f8a48a937a2bc/js/jquery.terminal.min.js,npm/jquery.terminal@2.34.0/js/prism.js,npm/prismjs@1.28.0/components/prism-scheme.min.js,gh/jcubic/lips@873c9927a1eec478ae0f89ea675ac8c0bcedbabb/lib/js/terminal.js,gh/jcubic/lips@873c9927a1eec478ae0f89ea675ac8c0bcedbabb/lib/js/prism.js,npm/js-polyfills@0.1.43/keyboard.js

But it gives me an entirely different error and with correct mapping 🤔 
![image](https://user-images.githubusercontent.com/6192491/186732180-e72af84e-92ec-492e-a2df-8c471082e6b8.png)

**Comment by jcubic** [comment]
Sorry I have no idea what version I was using.
