### ISSUE TITLE
Access to the media resources is redirected to the raw.githubusercontent.com

### ISSUE THREAD

**Issue by plainheart** [jsdelivr/jsdelivr#18420]
**Describe the bug**

Access to the media resources (images, videos...) from China mainland is being redirected to the original server of GitHub: https://raw.githubusercontent.com

**Affected jsDelivr links**

- https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/js/example-bundle.js (Working)
- https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/data/thumb/line-simple.png (Will be redirected to GitHub Raw)
- https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/v4/zh/video/index-4.mp4 (Will be redirected to GitHub Raw)

**Screenshots**
<img src="https://user-images.githubusercontent.com/26999792/176998221-45f9863f-b877-4baf-9e71-caf2694fc099.png" width="400">

**Please complete the following information:**
 - Device OS: Any
 - Browser: Any
 - Browser version: Any
 - Your location (country): China

**Additional context**

As far as I know, the following domains will be redirected when accessing the image/video resources on GitHub,

- cdn.jsdelivr.net
- fastly.jsdelivr.net
- originfastly.jsdelivr.net

**Comment by BNQDZJ** [comment]
To prevent cdn.jsdelivr.net from being contaminated with DNS again in the Chinese mainland, jsdelivr will now redirect media resources to the Github origin server

**Comment by BNQDZJ** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18407#issuecomment-1154097518

**Comment by MartinKolarik** [comment]
This is an intentional change to reduce the chances of getting blocked again. The most essential files are still served from our domain but some riskier and less important files are redirected.

**Comment by plainheart** [comment]
Thanks for your information. Appreciate your work and service. :)

**Comment by itsHenry35** [comment]
> To prevent cdn.jsdelivr.net from being contaminated with DNS again in the Chinese mainland, jsdelivr will now redirect media resources to the Github origin server

but actually raw.githubusercontent.com is also dns polluted so redirect to the Github origin server won't work and affects some websites again

**Comment by BNQDZJ** [comment]
> > To prevent cdn.jsdelivr.net from being contaminated with DNS again in the Chinese mainland, jsdelivr will now redirect media resources to the Github origin server
> 
> but actually raw.githubusercontent.com is also dns polluted so redirect to the Github origin server won't help and affects some websites again ![raw githubusercontent com_多地区多线路HTTP测速](https://user-images.githubusercontent.com/58730749/193985156-909ca171-1943-4bdd-89e7-659022846bf5.png)

But this ensures that jsdelivr is not contaminated with DNS for violating content
