### ISSUE TITLE
Import of latest typescript(4.7.4) fails via esm.run

### ISSUE THREAD

**Issue by abhishiv** [jsdelivr/jsdelivr#18429]
**Describe the bug**
Import of latest typescript seems to broken when imported via esm.run 

AFAIK it was working as of version 3.9.10

**Affected jsDelivr links**
https://cdn.jsdelivr.net/npm/typescript@4.7.4/+esm

**Additional context**
 https://github.com/jsdelivr/jsdelivr/issues/18378#issuecomment-1226118982

**Comment by MartinKolarik** [comment]
Should work now, thanks for reporting.

**Comment by duaneatat** [comment]
Looks like Rollup is failing to load this now, the above link gives the error `Failed to bundle using Rollup v2.74.1: Could not load d96a7b9ea3491d50113b1c41a7b967 (imported by .cache/npm/typescript@4.7.4/lib/typescript.js)`.
