### ISSUE TITLE
File still accessible

### ISSUE THREAD

**Issue by fedeci** [jsdelivr/jsdelivr#18423]
A file that was removed in a version (e.g. in 2.0.123) is still accessible from the hat major version even if the cache has been purged.
URL: https://cdn.jsdelivr.net/npm/@withfig/autocomplete@^2.0.0/build/fig.js (it should no longer exist)

Thanks for the help!

**Comment by MartinKolarik** [comment]
This is by design, the file is in our storage and will continue to work.

**Comment by fedeci** [comment]
What's the best way to prevent it?

**Comment by MartinKolarik** [comment]
What's the goal here? The file won't appear if you use an exact version or a directory listing. This feature simply minimizes the chance of breaking websites that rely on it and use `^2.0.0` range.

**Comment by fedeci** [comment]
I managed to achieve the goal in another way. The "problem" is Fig's autocomplete repo which is not properly semver compliant.

**Comment by fedeci** [comment]
Just a curiosity, how `@2` is different from `@^2.0.0`

**Comment by MartinKolarik** [comment]
It isn't 😄 you can see that here as well: https://semver.npmjs.com/

**Comment by MartinKolarik** [comment]
But with the `^` you could also write something more specific, like `^2.1.0` which would be different then (meaning >= 2.1.0).

**Comment by fedeci** [comment]
🤔 However if I purge the cache for `@^2.0.0` I still get the stale file for a while. If I purge the cache for @2 I immediately get the updated one.

**Comment by MartinKolarik** [comment]
Indeed, that looks like an issue with the API. Will get it fixed.

**Comment by fedeci** [comment]
Thanks!

**Comment by MartinKolarik** [comment]
@fedeci it's fixed now.

**Comment by fedeci** [comment]
🚀
