### ISSUE TITLE
Try jsdelivr to re-icp filing in China possible

### ISSUE THREAD

**Issue by w0oo** [jsdelivr/jsdelivr#18425]
# Telephone consultation through the Ministry of Industry and Information Technology of China

# This is how the customer service responds
(This is translated from audio to text)
![Screenshot_2022-08-01-09-58-07-35_7828fffab8570def7bc0086ba9bb1214.jpg](https://s2.loli.net/2022/08/01/TGtHLg4ca62Xw9W.jpg)

Can not Loading？Visit This:
[https://s1.328888.xyz/2022/08/01/FUFxU.jpg](https://s1.328888.xyz/2022/08/01/FUFxU.jpg) 

OR
[https://aowu-my.sharepoint.cn/:i:/g/personal/b00d_paolu_site/ETU0HeRqDltGrWZhCAChfJIBBP-aNlMCjeHzD08VCe8Bvw?e=naLFeB](https://aowu-my.sharepoint.cn/:i:/g/personal/b00d_paolu_site/ETU0HeRqDltGrWZhCAChfJIBBP-aNlMCjeHzD08VCe8Bvw?e=naLFeB) 

> It probably means to delete the content that is illegal in China, and then contact the Administration Bureau (referring to the Communications Bureau) for rectification, if possible, you can re-ICP filing

The QUANTIL CDN Ever used by Jsdelivr
The company is in Shanghai, in Shanghai, then try to contact the Shanghai Communications Bureau

https://shca.miit.gov.cn （Website）

http://61.129.52.151/（About the ICP Filing system）

This is their contact number  +86 021-63905006

Maybe Working ~~hours~~ Times: （start）8:30 （over）17:00 (including working lunch time)

Maybe They can hely you！

**Comment by jimaek** [comment]
We have discussed this many times in the past. We dont speak Chinese and we dont have the money to hire Chinese lawyers to work on our case. We will also not transfer our domain to China. Check the previous topics for details.
