### ISSUE TITLE
Consider adding License of packages in the comments of every js file being generated?

### ISSUE THREAD

**Issue by renhiyama** [jsdelivr/jsdelivr#18431]
NPM and other Package managers seem to download them (as intended). But esm.run doesn't bundle the license (or even state the name of the license at the start of every js file at the top of code)... Can we consider adding them?

**Comment by MartinKolarik** [comment]
We include a pointer to the original file in the top comment, and of course, the license can be accessed as a standalone file, same as with npm. I believe this is sufficient.
