### ISSUE TITLE
Failed to fetch cdn link created from github repo

### ISSUE THREAD

**Issue by sdcomilla1** [jsdelivr/jsdelivr#18435]
https://cdn.jsdelivr.net/npm/sdcomilla1/keygadstry1/keygadstry.js

https://cdn.jsdelivr.net/gh/sdcomilla1/keygadstry1/keygadstry.js

Both link not working why? 
Any fix? 
Why this is happen? 
Any error i done here? 
Please need help.

**Comment by jimaek** [comment]
Because none of these projects actually exists
https://github.com/sdcomilla1/keygadstry1 404
https://www.npmjs.com/search?q=keygadstry1

**Comment by sdcomilla1** [comment]
> Because none of these projects actually exists https://github.com/sdcomilla1/keygadstry1 404 https://www.npmjs.com/search?q=keygadstry1

My user id is "sdcomilla1" and the repo name is "keygadstry1" and the path i got this "keygadstry.js". 

Anyway, please wolud u kindly cheak the all links from my user access id sdcomilla1? 

Let me kindly know the error where i did.

Thanks.

**Comment by jimaek** [comment]
That user has no repos at all https://github.com/sdcomilla1?tab=repositories 
If you see the repo then it probably means its private and we only support public repos
