### ISSUE TITLE
esm.run: Failed to bundle using rollup 2.75.7  (@starbeam/debug + importmap)

### ISSUE THREAD

**Issue by NullVoxPopuli** [jsdelivr/jsdelivr#18434]
**Describe the bug**
Using chrome + import maps, and this HTML:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Starbeam via CDN - native ESM Demo</title>
  <script type="importmap">
    {
      "imports": {
        "@starbeam/debug": "https://esm.run/@starbeam/debug",
        "@starbeam/core": "https://esm.run/@starbeam/core",
        "@starbeam/js": "https://esm.run/@starbeam/js"
      }
    }
  </script>
</head>
<body>
  <script type="module">
    import * as z from '@starbeam/debug';

    console.log(z.DisplayStruct)
  </script>
</body>
</html>
```

rollup failed to bundle -- providing this error:
```
+esm:6 Uncaught Error: Failed to bundle using Rollup v2.75.7. If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr
    at +esm:6:8
(anonymous) @ +esm:6
```

**Response headers**
The full response is this:
```
/**
 * Failed to bundle using Rollup v2.75.7.
 * If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr
 */

 throw new Error('Failed to bundle using Rollup v2.75.7. If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr');
 ```
 
but --  what's the error?
 Can the rollup error be provided for debugging purposes?
 
**Please complete the following information:**
 - Device OS: Ubuntu
 - VPN provider if you use one: n/a
 - Your location (country): USA

```
❯ google-chrome --version
Google Chrome 104.0.5112.79 
```

**Additional context**

package is pre-bundled

**Comment by MartinKolarik** [comment]
I see you partially debugged this in https://github.com/starbeamjs/starbeam/issues/48, the issue with `/npm/@starbeam/debug` is that our CJS/ESM interop code picks ups some variables that look like exports but aren't exported in the end, causing an `Error: 'zeroWidthCharacters' is not exported by ...` error: 
![image](https://user-images.githubusercontent.com/6192491/191259652-a9659e21-bf15-4c88-857f-57f8b0f59807.png)

At the first glance, it seems like a bug in [cjs-esm-exports](https://www.jsdelivr.com/package/npm/cjs-esm-exports). I'm not sure where that piece of code comes from, but not having what looks like a CJS syntax inside the ESM file should help.

**Comment by NullVoxPopuli** [comment]
sounds good to me! I'll take a look at the build config for starbeam, and see if I can eliminate this issue

**Comment by MartinKolarik** [comment]
@NullVoxPopuli I found we might be able to fix this case on our side too. Please check if it works as expected now.

**Comment by NullVoxPopuli** [comment]
ooo thanks!
I tested with this HTML on firefox, and things appear to be working
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Starbeam via CDN - native ESM Demo</title>
</head>
<body>
  <script type="module">
    import * as z from 'https://esm.run/@starbeam/debug';

    console.log(z)
  </script>
</body>
</html>
```

Now, to figure out why `Uncaught SyntaxError: ambiguous import: isDebug` is happening for `@starbeam/timeline` -- which seems handled by ya'll just fine: https://cdn.jsdelivr.net/npm/@starbeam/timeline@0.7.2/+esm -- unambiguating isDebug.

I've never seen this error.
On Chrome, I get a different error _runtime_! Exciting!!
```
+esm:7 Uncaught ReferenceError: _brand_check_timestamp is not defined
    at <instance_members_initializer> (+esm:7:1879)
    at new T (+esm:7:1928)
    at T.now (+esm:7:1647)
    at <instance_members_initializer> (+esm:7:2362)
    at new <anonymous> (+esm:7:2351)
    at +esm:7:2347
```
Tho, the problem file is still `@starbeam/timeline` -- but this looks like a real issue on our side. 

If I run in to anything after digging in to this a bit more, I think I'll open a new issue as it looks like the original issue is resolved. Thank you!! :tada:
