### ISSUE TITLE
jsDelivr cannot download the EXE files in a repo

### ISSUE THREAD

**Issue by PumpkinJui** [jsdelivr/jsdelivr#18441]
**Is your feature request related to a problem? Please describe.**

I found that jsDelivr can't seem to download EXE files stored in the repository. If I try to download such a file, the web page will say "Forbidden", just like the screenshot shown. Here's [the test link](https://cdn.jsdelivr.net/gh/PumpkinJui/Selector@1.2/Tools&EXPs/SL1.2-EXPModule.exe). 
(The link directs to my repo. I tested all the EXE files in it and they all did like this.)

**Describe the solution you'd like**

I hope you will be able to provide a feature to download EXE files, although it doesn't seem like many people will store EXE files in a repository instead of publishing a release.

**Describe alternatives you've considered**

The alternative I considered might be to change an agent to access GitHub download files directly. But given the complexity of China's online environment, I think the chances of finding a suitable agent are slim.

**Additional context**

Here's the screenshot:
![Screenshot](https://user-images.githubusercontent.com/76104432/197347448-e76ef4fe-3666-43da-a5a8-f1e7c07c19c5.png)

Thank you for this!

**Comment by jimaek** [comment]
We block most executable extensions including .exe for security and anti-abuse reasons. So unfortunately we cant help in this case

**Comment by PumpkinJui** [comment]
All right. Anyway, thank you for providing this service in China!
