### ISSUE TITLE
Request file, return content error

### ISSUE THREAD

**Issue by GOOD-AN** [jsdelivr/jsdelivr#18445]
**Describe the bug**
When I access it directly, the returned content is the latest, but when I use python's requests library and request it using get, the returned content becomes the last old version, and this is the only file in this case, other files are requested using the same method and the returned content is the latest.

**Affected jsDelivr links**
https://fastly.jsdelivr.net/gh/GOOD-AN/mys_exch_goods@latest/update_log.json

**Response headers**
```
{
	'Connection': 'keep-alive',
	'Content-Length': '220',
	'Access-Control-Allow-Origin': '*',
	'Access-Control-Expose-Headers': '*',
	'Timing-Allow-Origin': '*',
	'Cache-Control': 'public, max-age=604800, s-maxage=43200',
	'Cross-Origin-Resource-Policy': 'cross-origin',
	'X-Content-Type-Options': 'nosniff',
	'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
	'Content-Type': 'application/json; charset=utf-8',
	'X-JSD-Version': '1.1.0',
	'X-JSD-Version-Type': 'version',
	'ETag': 'W/"1a2-nKLwxfaa+cDtOPh3PxjJzZAUlZw"',
	'Content-Encoding': 'gzip',
	'Accept-Ranges': 'bytes',
	'Date': 'Mon, 31 Oct 2022 16:07:47 GMT',
	'Age': '8361',
	'X-Served-By': 'cache-fra19169-FRA, cache-nrt-rjtf7700068-NRT',
	'X-Cache': 'HIT, HIT',
	'Vary': 'Accept-Encoding',
	'alt-svc': 'h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400'
}
```

**Screenshots**
Right
![image](https://user-images.githubusercontent.com/53306377/199056229-3bd71cc7-649f-42c7-87d5-c95cfc64ba01.png)
Wrong
![image](https://user-images.githubusercontent.com/53306377/199056489-8ba8cd7d-e4d2-4a63-8f7d-a706ec93ec97.png)

**Please complete the following information:**
 - Device OS: Windows
 - Browser: Edge
 - Browser version: 107.0.1418.26
 - VPN provider if you use one:
 - Your location (country): China

**Comment by jimaek** [comment]
I purged the cache and it should be accurate now. In general it takes a few days for the file to get updated after a new release is deployed, especially when a CLI is used cause it doesn't have revalidation logic
