### ISSUE TITLE
I can't update the file via https://purge.jsdelivr.net

### ISSUE THREAD

**Issue by fscarmen** [jsdelivr/jsdelivr#18447]
**Describe the bug**
Six months ago, I used `https://purge.jsdelivr.net/gh/fscarmen/warp/menu.sh` to update the files, but it doesn't work anymore. The resulting file at `https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh` is very old.

Please
**Affected jsDelivr links**
https://cdn.jsdelivr.net/gh/fscarmen/warp/menu.sh

**Response headers**
```
{
  "id": "pZIH2RvurKCO5MYR",
  "status": "finished",
  "timestamp": "2022-11-10T07:51:11.549Z",
  "paths": {
    "/gh/fscarmen/warp/menu.sh": {
      "throttled": false,
      "providers": {
        "fastly": true,
        "bunny": true,
        "cloudflare": true,
        "gcore": true,
        "quantil": true
      }
    }
  }
}
```

**Screenshots**

**Please complete the following information:**
 - Device OS: [e.g. iOS]
 - Browser: [e.g. chrome, safari]
 - Browser version: [e.g. 22]
 - VPN provider if you use one:
 - Your location (country):

**Additional context**

**Comment by jimaek** [comment]
The system follows semver to understand what version is the latest. https://github.com/fscarmen/warp/releases unfortunately "latest" logic will not work correctly with that kind of format
