### ISSUE TITLE
plotly.js error

### ISSUE THREAD

**Issue by seefor** [jsdelivr/jsdelivr#18440]
**Describe the bug**
Using this path generates an error - https://cdn.jsdelivr.net/npm/plotly.js/+esm

/**
 * Failed to bundle using Rollup v2.79.0.
 * If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr
 */

 throw new Error('Failed to bundle using Rollup v2.79.0. If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr');
**Affected jsDelivr links**
One or more direct links that are affected by this issue.
https://cdn.jsdelivr.net/npm/plotly.js/+esm

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.
access-control-allow-origin: *
access-control-expose-headers: *
age: 1462
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: public, max-age=604800, s-maxage=43200
cf-cache-status: HIT
cf-ray: 7588d048bfcb8eb6-DEN
cross-origin-resource-policy: cross-origin
date: Tue, 11 Oct 2022 16:01:18 GMT
etag: W/"191-7c3atC76Ur7M/EN5EOx1IXFpkZo"
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=JGFhEJ8VDXsEBd%2BReeL6GSKflnxC%2B4NMCT5bQrCTXP32H%2F8UIvH1MuaLs%2BH4nwUTMBJjYco2eMBk2GdAcv8J8fc%2BGaqQKfcnzkPSsdKyZUsztHXlCfqBccQDhXKT21WgniY%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: HIT, MISS
x-content-type-options: nosniff
x-jsd-version: 2.15.1
x-jsd-version-type: version
x-served-by: cache-fra19173-FRA, cache-yyz4555-YYZ
**Screenshots**

**Please complete the following information:**
 - Device OS: MacOS 12.6
 - Browser: [e.g. chrome, safari] Chrome
 - Browser version: [e.g. 22] 105.0.5195.125 
 - VPN provider if you use one:
 - Your location (country): US

**Additional context**

**Comment by MartinKolarik** [comment]
Should work now.

**Comment by seefor** [comment]
It does, thank you for the quick fix
