### ISSUE TITLE
MUX is not getting initialized and LIVE playback is not working

### ISSUE THREAD

**Issue by RushikeshLogituit** [jsdelivr/jsdelivr#18454]
Hi Team,

I am using videojs version - 7.14.1 &
hls-4k-fix library version - 5.14.1

We are getting issues integrating MUX for the live playback for HTML5 TVs.
For live playback, hls library is used, and in order to handle high quality and high bitrate we are using this hls-4k-fix library.
I have attached the screenshot of the error as well.

https://drive.google.com/file/d/1HS1Kvip040gxAzuSsMEImNB-thxgrsZt/view?usp=sharing

Please help me out what is going wrong here. If any information needed please let me know

Thanks,
Rushikesh Kalhapure

**Comment by jimaek** [comment]
Hey, we're just a CDN, we serve the files provided by authors as is and cant help with the code itself. You will have to ask the Mux team about this.
Thanks
