### ISSUE TITLE
jsDelivr is using the "main" instead of the "jsdelivr" in npm/package url

### ISSUE THREAD

**Issue by matteobruni** [jsdelivr/jsdelivr#18458]
**Describe the bug**
I changed the "jsdelivr" field on my `package.json` to use a bundled version of my library. I've released it today but jsDelivr in the npm/library url, without version or file, is using the "main" field instead.

I think that this link https://cdn.jsdelivr.net/npm/tsparticles should be the same as this https://cdn.jsdelivr.net/npm/tsparticles@2.7.0/tsparticles.bundle.min.js since that is the default file, visible also here: https://www.jsdelivr.com/package/npm/tsparticles.

Package.json for reference: https://github.com/matteobruni/tsparticles/blob/21707e32297d01f650149714ee47e13a8b3d7d67/bundles/full/package.dist.json#L75 (the package.dist.json is used during the release, copied and renamed in the `dist` folder during the publish process)

**Affected jsDelivr links**
https://cdn.jsdelivr.net/npm/tsparticles

**Response headers**
1
1
2,57 KB
1,35 KB
0
89,6 ms
Anteprima
Header
Cookie
Dimensioni
Tempo
Sicurezza
Riepilogo
URL: https://cdn.jsdelivr.net/npm/tsparticles
Stato: 200
Sorgente: Rete
Indirizzo: 172.224.55.24:443 (proxy)

Richiesta
:method: GET
:scheme: https
:authority: cdn.jsdelivr.net
:path: /npm/tsparticles
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: it-IT,it;q=0.9
Connection: keep-alive
Accept-Encoding: gzip, deflate, br
Host: cdn.jsdelivr.net

Risposta
:status: 200
Content-Encoding: gzip
Timing-Allow-Origin: *
Cache-Control: public, max-age=604800, s-maxage=43200
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
Content-Length: 890
Vary: Accept-Encoding
Date: Fri, 23 Dec 2022 12:18:31 GMT
Access-Control-Expose-Headers: *
Age: 34466
Content-Type: application/javascript; charset=utf-8
ETag: W/"a0e-eVs9eatBlPbbkVmtZYpwX0nj7Qw"
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
x-served-by: cache-fra-eddf8230059-FRA, cache-mxp6980-MXP
Alt-Svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
x-jsd-version-type: version
x-jsd-version: 2.5.3
x-cache: HIT, HIT

**Screenshots**
Not necessary

**Please complete the following information:**
 - Device OS: macOS
 - Browser: Safari
 - Browser version: 16.2
 - VPN provider if you use one:
 - Your location (country): Italy

**Additional context**

**Comment by MartinKolarik** [comment]
Resolved by purging the affected link, which wasn't updated to the latest version yet.

**Comment by matteobruni** [comment]
Thank you!
