### ISSUE TITLE
Wrong MIME Type is returned 

### ISSUE THREAD

**Issue by ennisa-ire** [jsdelivr/jsdelivr#18455]
Hi  Folks,
 I am getting the wrong mime type returned from request below. I expect "application/javascript" for js and min.js file types.

**Request**
curl -is "https://cdn.jsdelivr.net/gh/mybusinesspal/iot-tech-homepage-mvn-libs/services/ux/menuclientSubscriptionSignupMenuWidget.js?v=872"

**Response**
HTTP/2 403 
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=60, s-maxage=60
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
**content-type: text/plain; charset=utf-8**
etag: W/"c0-Hq9pfpREdyMg32+UM3kJkOPs7pQ"
accept-ranges: bytes
date: Thu, 01 Dec 2022 14:17:20 GMT
age: 0
x-served-by: cache-fra-eddf8230075-FRA, cache-ams21041-AMS
x-cache: MISS, MISS
vary: Accept-Encoding
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 192

Thanks Anthony

**Comment by MartinKolarik** [comment]
That file/branch doesn't exist.

**Comment by anwarulislam** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/Ace-Tinker/screen-recorder@gh-pages/assets/index.js
