### ISSUE TITLE
Importing two file modules cause override error

### ISSUE THREAD

**Issue by momrak** [jsdelivr/jsdelivr#18463]
**Describe the bug**
Importing these two
```   
<script type="module">
        import 'https://cdn.jsdelivr.net/npm/@material/web@1.0.0-pre.1/button/filled-button.js/+esm';   
        import 'https://cdn.jsdelivr.net/npm/@material/web@1.0.0-pre.1/button/outlined-button.js/+esm';   
</script>
```
Cause the following error message in the console
`Uncaught DOMException: CustomElementRegistry.define: 'md-focus-ring' has already been defined as a custom element`

This does not happen when using unpkg or snowpack. Not sure what causes this, and which behavior is the correct. Does anyone have a clue on have to get this working like with the two others?

**Please complete the following information:**
 - Device OS: MacOS
 - Browser: chrome, firefox
 - Your location (country): Norway

** edit
added jsfiddle example https://jsfiddle.net/btj69srn/

extra info: @material/web uses [Lit](https://lit.dev/)

**Comment by momrak** [comment]
Tested with esm.sh now, and it works there as well. So it is consistent amongst the other CDNs.

unpkg*        ✅ 
esm.sh      ✅ 
skypack    ✅ 
jsdelivry    ❌ 

* works, but lots of errors on fetching, but these are probably not related. Need to refresh multiple times

**Comment by MartinKolarik** [comment]
Hey, this is, unfortunately, a limitation of our current bundling approach. Accessing files within the package (other than the default file) may not work correctly with some packages. We'll likely improve this but no ETA right now.

**Comment by momrak** [comment]
I see. Thanks for the response. Is there an existing open issue for this that I can follow, or should I keep this open?

**Comment by MartinKolarik** [comment]
I believe the problem behind this is the same as #18337.

**Comment by momrak** [comment]
Looks like the same, indeed. I'll close this and subscribe to that one instead. Thanks

Duplicate of https://github.com/jsdelivr/jsdelivr/issues/18337
