### ISSUE TITLE
Bulma css file not found

### ISSUE THREAD

**Issue by akicho8** [jsdelivr/jsdelivr#18468]
https://www.jsdelivr.com/package/npm/bulma
https://cdn.jsdelivr.net/npm/bulma@0.9.4/bulma/css/bulma.min.css

I saw the link written in the document, but it became 404.

**Comment by akicho8** [comment]
Where did the extra path come from?
Is it a problem on JSDelivr's side?

**Comment by jimaek** [comment]
Maybe a typo in the docs? jsDelivr serves the files as they are in npm

**Comment by jimaek** [comment]
Sorry I just re-checked everything and it does seem to a problem with our auto-detection of main files

**Comment by MartinKolarik** [comment]
Hey, this is an issue with bulma's package.json, I've sent them a PR to fix it: https://github.com/jgthms/bulma/pull/3625.

**Comment by akicho8** [comment]
Thanks.

**Comment by akicho8** [comment]
Oh, wait, I just realized that I meant to post this issue on the Bulma side. Nevertheless, I appreciate that you also submitted a pull request.
