### ISSUE TITLE
fs promises unrecognisable

### ISSUE THREAD

**Issue by prhasn** [jsdelivr/jsdelivr#18466]
**Describe the bug**
When `require("fs/promises")` is used in an npm module it gives error `the file imports a not supported node.js built-in module "fs"` for esm. An example is when [this file](https://github.com/trustwallet/wallet-core/blob/master/wasm/src/keystore/fs-storage.ts) is compiled to JS it carries on the `"fs/promises"` import into its `require` statement.

**Affected jsDelivr links**
https://cdn.jsdelivr.net/npm/@trustwallet/wallet-core/+esm

**Response**
`/** * Failed to bundle using Rollup v2.74.1: the file imports a not supported node.js built-in module "fs". * If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr */ throw new Error('Failed to bundle using Rollup v2.74.1: the file imports a not supported node.js built-in module "fs". If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr');`

**Screenshots**
![Screenshot 2023-02-10 143517](https://user-images.githubusercontent.com/55940669/218030711-4d23a96a-1347-476c-97c7-6c8df3a11072.jpg)

**Please complete the following information:**
 - Device OS: [Windows 10]
 - Browser: [Brave]
 - Browser version: [1.48.157]
 - VPN provider if you use one:
 - Your location (country): Indonesia

**Comment by MartinKolarik** [comment]
The `fs` module is not supported since it cannot be reasonably polyfilled in browsers. If the package can actually work in a browser without it, it needs to add `browser: { "fs/promises": false }` to `package.json` to mark it as ignored.
