### ISSUE TITLE
Some CDN links redirected from RawGit returns empty files

### ISSUE THREAD

**Issue by Gnbrkm41** [jsdelivr/jsdelivr#18462]
**Describe the bug**
Certain links redirected from rawgit returns an empty file without any errors, resulting in pages relying on the hosted libraries failing to load. 

**Affected jsDelivr links**

https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css
https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js

What appears to be the jsdelivr equivalent loads just fine: https://cdn.jsdelivr.net/gh/michalsnik/aos@2.1.1/dist/aos.js

**Response headers**
A complete list of response headers for one affected link, copied from browser developer tools or curl.

cache-control: public, max-age=2592000
cdn-cache: HIT
cdn-cachedat: 01/29/2023 10:00:06
cdn-edgestorageid: 948
cdn-proxyver: 1.03
cdn-pullzone: 201235
cdn-requestcountrycode: KR
cdn-requestid: 81ceac5e497b484f4c9d24eff17f761d
cdn-requestpullcode: 200
cdn-requestpullsuccess: True
cdn-status: 200
cdn-uid: b1941f61-b576-4f40-80de-5677acb38f74
content-length: 0
date: Mon, 30 Jan 2023 03:28:41 GMT
server: BunnyCDN-JP1-1066
vary: Accept-Encoding

**Screenshots**

**Please complete the following information:**
 - Device OS: Windows
 - Browser: Microsoft Edge
 - Browser version:  111.0.1633.0 (Official build) dev (64-bit) 
 - VPN provider if you use one: None
 - Your location (country): KR

**Additional context**
I am aware that technically RawGit is no longer supported & should be migrated away from but this is just a website I visited and it seemed odd that the source file is just empty.

**Comment by Gnbrkm41** [comment]
FWIW apparently it stopped working since yesterday and it seems to line up with the `cdn-cachedat` which is 01/29/2023 10:00:06?

**Comment by jimaek** [comment]
Looks like the CDN provider had caching issues, I purged all rawgit files from the CDN to make sure no other files are broken.
Thank you for reporting this!

**Comment by Gnbrkm41** [comment]
Lovely, Thanks for the quick fix! ❤️
