### ISSUE TITLE
[Question] Can't reach the path of the image linked to the package

### ISSUE THREAD

**Issue by akicho8** [jsdelivr/jsdelivr#18465]
The following directory is published to NPM as a package.
https://github.com/akicho8/shogi-player/tree/master/dist

I wrote the following in package.json's main

> "main": "./dist/shogi-player-wc.min.js",

https://github.com/akicho8/shogi-player/blob/master/package.json#L8

The image can be read correctly in the this HTML.

```html
<script src="https://cdn.jsdelivr.net/npm/shogi-player@0.0.368/dist/shogi-player-wc.min.js"></script>
<shogi-player-wc />
```

https://codepen.io/akicho8/pen/YzjoXZE

However, if omit the file path as follows, the image cannot be read.

```html
<script src="https://cdn.jsdelivr.net/npm/shogi-player@0.0.368"></script>
<shogi-player-wc />
```
https://codepen.io/akicho8/pen/VwBJLPM

Is there nothing that can be done about this?

**Comment by MartinKolarik** [comment]
Unfortunately, this is how relative links work, and we can't do anything on our side. If you're the package author and really want to use the short links, you could add some extra js logic for building the correct URLs.

**Comment by akicho8** [comment]
Thank you for your quick reply. I understand. I initially thought I might have made a setting mistake, but it turns out that it's originally designed that way. For now, I will proceed using the method of writing the full path.
