### ISSUE TITLE
hot to get development (or non-minified version) of a package in ESM format. 

### ISSUE THREAD

**Issue by mediabuff** [jsdelivr/jsdelivr#18479]
### Description

For non-ESM, it's simple to change the url to .index.js from .index.min.js. What is the URL format for ESM ?

I am looking for react-dom

### Affected jsDelivr links

https://www.jsdelivr.com/package/npm/react-dom

### Response headers

```

```

### Information

Windows

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
You can add `/+esm` to any file: https://cdn.jsdelivr.net/npm/react-dom@18.2.0/cjs/react-dom.production.min.js/+esm

**Comment by mediabuff** [comment]
thank you. How do you it for entire package ?

like how esm.sh does
import React from "https://esm.sh/react?dev"

**Comment by MartinKolarik** [comment]
The file I linked *is* the entire package. You just need to find which file is the main one.
