### ISSUE TITLE
Only first purge from consecutive purge requests works

### ISSUE THREAD

**Issue by jcubic** [jsdelivr/jsdelivr#18471]
**Describe the bug**
If you make a change to the GitHub repo make a purge to update the file then make another change then the second purge doesn't work.

**Affected jsDelivr links**
https://cdn.jsdelivr.net/gh/jcubic/chat-gpt/bookmark.js

**Response headers**
```
access-control-allow-origin: *
access-control-expose-headers: *
age: 1
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: public, max-age=604800, s-maxage=43200
cf-cache-status: HIT
cf-ray: 7a42382318aa349d-WAW
content-encoding: br
content-type: application/javascript; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Tue, 07 Mar 2023 10:40:15 GMT
etag: W/"765-R8thYTzjpXQhGcWUhW4Z/pgXbGY"
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=%2FlKNZvC133HFZRGf%2Fvoo%2BX142QUqdE92fSxOxa6pE%2B%2BfkbFD61KaNkSwYQx55K7gXpFskbfTqCdDeTkJ8TA7xgV4uT%2FdZt7OKwFLlFU0l9iqy%2FgEMLZQRt%2BTAmnP%2BwA2iqU%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: MISS, MISS
x-content-type-options: nosniff
x-jsd-version: master
x-jsd-version-type: branch
x-served-by: cache-fra-eddf8230117-FRA, cache-jnb7026-JNB
```

**Please complete the following information:**
 - Device OS: [e.g. iOS]: Fedora GNU/Linux
 - Browser: [e.g. chrome, safari]: Google Chrome
 - Browser version: [e.g. 22]: 110.0.5481.177
 - VPN provider if you use one: None
 - Your location (country): Poland

**Additional context**
I've added a semicolon because it was giving syntax errors. And I'm not able to purge and update the file.

**Comment by jimaek** [comment]
You should tag a new version of your project to allow jsDelivr to pick up the change instantly

**Comment by jcubic** [comment]
I will need to modify the GitHub page's HTML file for each commit.

**Comment by jcubic** [comment]
I've assumed that I will need to use `@tag`, but I don't like the idea to tag every commit, so so the JSDelivr can work. Purge should update the file anyway. I've tried 3 times and nothing happened.

**Comment by MartinKolarik** [comment]
If you use tags and `@latest` the purge will always work immediately. If you refer only to a branch, the purge isn't entirely reliable as there's currently some minimum cache time for branch files (up to 12 hours).

**Comment by jcubic** [comment]
`@latest` is a nice trick thanks.
