### ISSUE TITLE
mime question

### ISSUE THREAD

**Issue by 54ayao** [jsdelivr/jsdelivr#18475]
Refused to execute script from 'https://cdn.jsdelivr.net/npm/typed.js' because its MIME type ('application/node') is not executable, and strict MIME type checking is enabled.

mime There's a problem.

**Comment by 54ayao** [comment]
> Refused to execute script from 'https://cdn.jsdelivr.net/npm/typed.js' because its MIME type ('application/node') is not executable, and strict MIME type checking is enabled.
> 
> mime There's a problem.

**Comment by 54ayao** [comment]
I do not know why this is the case, I think it should not be my problem, direct access to the JS file, the browser directly downloaded, I feel that part of the NPM may not be normal, hope to solve it as soon as possible, thank you

**Comment by MartinKolarik** [comment]
You're loading a node.js file. The correct file for browsers is https://cdn.jsdelivr.net/npm/typed.js@2.0.15/dist/typed.umd.js
