### ISSUE TITLE
https certificate on https://www.jsdelivr.com/ has expired 5 days ago

### ISSUE THREAD

**Issue by limonte** [jsdelivr/jsdelivr#18477]
### Description

https://www.sslshopper.com/SSL-CHECKER.HTML#hostname=https://www.jsdelivr.com/

<img width="855" alt="CleanShot 2023-04-23 at 14 14 43@2x" src="https://user-images.githubusercontent.com/6059356/233836592-b043ccd3-ffc1-4ddb-a1ce-fd85b5361de2.png">

### Affected jsDelivr links

not relevant

### Response headers

not relevant

### Information

not relevant

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by limonte** [comment]
you guys might want to set up some monitoring and reminder about https, this is really bad for your reputation

<img width="432" alt="CleanShot 2023-04-23 at 14 16 00@2x" src="https://user-images.githubusercontent.com/6059356/233836740-54e7df67-713a-4f70-a974-1f0068515841.png">

**Comment by jimaek** [comment]
We're aware of the issue. The SSL didn't expire, its an effect of the current DDOS attack

**Comment by limonte** [comment]
> We're aware of the issue. The SSL didn't expire, its an effect of the current DDOS attack

oh, got you, thanks for the prompt reply. I wasn't aware that DDOS may cause this type of issue.

**Comment by jimaek** [comment]
I was switching traffic between different providers to handle the load and one of the providers did not issue the updated SSL in time. But I believe now everything should be back to normal. The attack is still ongoing but it seems to be handled by the firewall. And cdn.jsdelivr.net is unaffected.

Can you confirm the site works for you?

**Comment by limonte** [comment]
yup, all is well on my side, thank you for the great service!
