### ISSUE TITLE
mime types for wasm files

### ISSUE THREAD

**Issue by shyamsfo** [jsdelivr/jsdelivr#18470]
**Is your feature request related to a problem? Please describe.**

We are trying to use wasm files hosted in jsdelivr. Specifically from here: https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.21.0/dist/ 
We'd like for jsdeliver to send the mime type application/wasm for these files. so that the browser will process them as such.

**Describe the solution you'd like**

 send the mime type application/wasm when the browser tries to bring in wasm files 
eg https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.21.0/dist/duckdb-eh.wasm

**Describe alternatives you've considered**

No good solution other than self hosting it in my own nginx servers.

**Comment by jimaek** [comment]
Sounds like a good idea. Let's do it @MartinKolarik

**Comment by shyamsfo** [comment]
Works good. Thanks.
