### ISSUE TITLE
how to download sub-directory or sub-path from a package. 

### ISSUE THREAD

**Issue by mediabuff** [jsdelivr/jsdelivr#18483]
### Is your feature request related to a problem? Please describe.

I would like get types for Typescript in a module. Typescript will only take types in local drive or node_modules (?). 
I want types for @mui/material/Box  - which is a sub-folder in the package. I can download  @mui/material  - but it is humongous! 

If I do, https://cdn.jsdelivr.net/npm/@mui/material/Box/+esm, it gives me a single file. But I need the directory structure download ?

Are there better ways of downloading types from sub-folders ?

### Describe the solution you would like.

Download subfolders of ESM packages.

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Check https://cdn.jsdelivr.net/npm/@mui/material/Box/ and download whatever files you need. If you need to list the files programmatically, you can use our API to get the list and the download them from the CDN: https://www.jsdelivr.com/docs/data.jsdelivr.com#get-/v1/packages/npm/@-scope-/-package-@-version-
