### ISSUE TITLE
Please consider optimizing the DNS routing rules assigning CDN nodes in China.

### ISSUE THREAD

**Issue by PowerfulRichard** [jsdelivr/jsdelivr#18487]
### Description

> jsDelivr has multiple locations close Chinese urban centers to ensure low latency and high performance for all Chinese users.

I would like to first thank you for this excellent service. But I think it currently does not work. According to the <u>Chinese website speed measurement service</u><sup>[1]</sup>,It appears that most Chinese traffic to cdn.jsdelivr.com is redirected to CDN nodes in Germany and the United States. This is obviously not low latency and high performance.

You may notice that compared to other regions, fastly has far more network routing in China than the other two CDN providers, and all traffic drops sharply after May 2022.
![image](https://user-images.githubusercontent.com/36656969/235763870-98c21c13-24cd-487d-acbb-34c25bbd4379.png)

Therefore maybe it's time to fix this.The primary choice of Chinese network traffic is redirected them to CDN nodes in HKSAR. And consider other nearby areas as backup options.To be noticed that different ISP and different locations have relatively different response speeds to different nodes.

Thanks!🙂

`[1]:www.itdog.cn,www.ipip.net`

**Comment by Loukky** [comment]
I recommend default routing to GCore CDN node.Fastly CDN only applies to China Mobile

**Comment by jimaek** [comment]
I believe GCore had availability issues in China so we switched the traffic

**Comment by PowerfulRichard** [comment]
> I believe GCore had availability issues in China so we switched the traffic

I think so too, gcore may be intermittently blocked. I tried to ping this domain 20 times and it timed out 7 times.  

> It appears that most Chinese traffic to cdn.jsdelivr.com is redirected to CDN nodes in Germany and the United States. This is obviously not low latency and high performance.

The main problem is that only a few coastal areas have traffic flowing to CDN nodes around China, but most areas have network traffic flowing to the US or EU.
The network traffic even crosses half of the world, so I think there might be something wrong?

**Comment by Loukky** [comment]
> > I believe GCore had availability issues in China so we switched the traffic
> 
> I think so too, gcore may be intermittently blocked. I tried to ping this domain 20 times and it timed out 7 times.
> 
So how about CloudFlare?
> > It appears that most Chinese traffic to cdn.jsdelivr.com is redirected to CDN nodes in Germany and the United States. This is obviously not low latency and high performance.
> 
> The main problem is that only a few coastal areas have traffic flowing to CDN nodes around China, but most areas have network traffic flowing to the US or EU. The network traffic even crosses half of the world, so I think there might be something wrong?

Both China Unicom and China Telecom tend to route to the US and Europe due to the higher cost of internet traffic in China and the Asia-Pacific region.The consequence of forcibly routing to the Asia-Pacific region is that it is not available at all during the evening peak hours.


> I believe GCore had availability issues in China so we switched the traffic

All in all, I recommend switching traffic to CloudFlare

**Comment by jimaek** [comment]
Switching to Cloudflare is not a problem, the reason we didnt was previous user feedback that CF performed even worse.
You can run your own tests using these domains:

fastly.jsdelivr.net
gcore.jsdelivr.net
testingcf.jsdelivr.net
