### ISSUE TITLE
@mui/icons-material ESM version - getting non-EMS version

### ISSUE THREAD

**Issue by mediabuff** [jsdelivr/jsdelivr#18480]
### Description

** Bug ***** , does not bring ESM version of createSvgIcon.js, so we use in browser import map

"@mui/icons-material/Close": "https://cdn.jsdelivr.net/npm/@mui/icons-material/Close/+esm",
           
I ended up creating a local copy with npm.
            "@mui/icons-material/Close": "./node_modules/@mui/icons-material/esm/Close.js",
            "./node_modules/@mui/icons-material/esm/utils/createSvgIcon": "./node_modules/@mui/icons-material/esm/utils/createSvgIcon.js",

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@mui/icons-material/Close/+esm

### Response headers

```

```

### Information

- Device OS: [e.g. iOS, Windows, MacOS]
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108]
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Sorry but I don't see what the issue is here.

**Comment by mediabuff** [comment]
https://cdn.jsdelivr.net/npm/@mui/icons-material/Close/+esm bundles @mui/icons-material/utils/createSvgIcon.js rather than @mui/icons-material/esm/utils/createSvgIcon.js

**Comment by MartinKolarik** [comment]
Shouldn't you be using this file then? https://cdn.jsdelivr.net/npm/@mui/icons-material@5.11.16/esm/Close.js/+esm

**Comment by mediabuff** [comment]
Hmm, Ok, I will try that. Was not familiar with that syntax. Yes, your new syntax works, great!, you saved my day and download of 30m of materail ui code in my disk.

But could you please explain the difference between the two approaches ? Is your approach a work around ? Is the first approach not valid ? or is it a bug ?

**Comment by MartinKolarik** [comment]
You were simply linking to a file outside of the `esm` dir. Check the package structure to see the difference: https://cdn.jsdelivr.net/npm/@mui/icons-material@5.11.16/
