### ISSUE TITLE
[ESM] `assert@2.0.0` TypeError: tr is undefined

### ISSUE THREAD

**Issue by loynoir** [jsdelivr/jsdelivr#18481]
### Description

**BUG**
TypeError: tr is undefined

**Reproduce**
```js
await import('https://esm.run/assert@2.0.0')
```

**Got** 
```
TypeError: tr is undefined
```

**Debug**

```js
  er = tr.isAnyArrayBuffer,
  rr = tr.isArrayBufferView,
  nr = tr.isDate,
  or = tr.isMap,
  ir = tr.isRegExp,
  ar = tr.isSet,
  cr = tr.isNativeError,
  ur = tr.isBoxedPrimitive,
  fr = tr.isNumberObject,
  sr = tr.isStringObject,
  lr = tr.isBooleanObject,
  hr = tr.isBigIntObject,
  pr = tr.isSymbolObject,
  gr = tr.isFloat32Array,
  yr = tr.isFloat64Array;
```

https://github.com/browserify/commonjs-assert/blob/8969d8eaa74357b5285d99cdd4ade4d993a1c183/package.json#L43

https://github.com/browserify/commonjs-assert/blob/8969d8eaa74357b5285d99cdd4ade4d993a1c183/internal/util/comparisons.js#L34-L50

### Affected jsDelivr links

https://esm.run/assert@2.0.0

https://cdn.jsdelivr.net/npm/assert@2.0.0/+esm

### Response headers

```
HTTP/2 200 OK
```

### Information

- Device OS: [e.g. iOS, Windows, MacOS] ArchLinux
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108] Firefox
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

By the way, why **always** return status 200?

Isn't it better return status 304?

**Comment by MartinKolarik** [comment]
Thanks for the report. This should be fixed soon with the next deployment.

**Comment by MartinKolarik** [comment]
Should work now.
