### ISSUE TITLE
file size validation

### ISSUE THREAD

**Issue by arjunpswork40** [jsdelivr/jsdelivr#18492]
### Is your feature request related to a problem? Please describe.

tried so many ways to incorporate file size validation on jquery validator.
 $.validator.addMethod('filesize', function (value, element, param) {
                    // Check if element is a file input and that a file is selected
                    if (element.type === "file" && element.files.length) {
                        var fileSize = element.files[0].size; // Get file size in bytes
                        // Convert to kilobytes
                        fileSize = Math.round(fileSize / 1024);
                        // Check if file size is smaller than the maximum allowed size
                        return fileSize <= param;
                    }
                    return true;
                }, 'File size must be less than {0} KB.');
                
                but not worked
                
                https://cdn.jsdelivr.net/npm/jquery-validation-filesize/jquery.validate.filesize.min.js => URL gives a response of Failed to fetch version info for jquery-validation-filesize. also tried URL https://cdn.jsdelivr.net/npm/jquery-validation-filesize/1.19.3/jquery.validate.filesize.min.js 

### Describe the solution you would like.

please add filesize validation in your codebase

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
This is not the place to request features in the hosted projects. Refer to the project's GitHub, e.g. https://github.com/jquery-validation/jquery-validation/
