### ISSUE TITLE
False positives issue in jsDelivr purge API

### ISSUE THREAD

**Issue by piquark6046** [jsdelivr/jsdelivr#18491]
### Description

There is a false positives issue in jsDelivr purge API.
I discussed with Dmitriy A. via email.

### Affected jsDelivr links

```
https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-AdGuard.txt
https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-uBlockOrigin.txt
```

### Response headers

```
{
  "success": false,
  "error": {
    "code": "NotFound",
    "message": "Purge status not found"
  }
}
```

### Information

- Device OS: Ubuntu 23.04
- Browser & Version: Mozilla Firefox 113.0.1
- VPN provider (if you use one): Mullvad VPN (M247)
- Your location (country/region): South Korea (physical), Japan (VPN)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

 - https://github.com/List-KR/List-KR/actions/runs/4937160618/jobs/8825605255
 - https://github.com/List-KR/List-KR/actions/runs/4967348830/jobs/8889296659

**Comment by MartinKolarik** [comment]
Sorry, but I don't understand what is the issue here, exactly. Please describe what exactly you call and how it fails.

**Comment by piquark6046** [comment]
When I send a purge request to the server, it returns with `finished` or `failed` as value of `status` property.
However, The purge API does not make cache in the server up to date.

**Comment by MartinKolarik** [comment]
The API is meant to work with semver tags, such as `v1.2.3` which can then be referenced as `@1` or `@latest` in the CDN links. We don't currently support purging for branches (it may work sometimes but not reliably).

**Comment by piquark6046** [comment]
Then, can you develop it to support?

**Comment by MartinKolarik** [comment]
It is planned but no ETA, probably not very soon. The branches expire within 12 hours, and tags can be used if immediate updates are necessary.

**Comment by piquark6046** [comment]
Can you process the issue because an anti-adblock issue on YouTube is ongoing. YouTube developers update their anti-adblock logic every weekday.

The issue affects uBlock Origin filters lists.

**Comment by piquark6046** [comment]
It seems that purging latest tag does not work correctly.
Can you take a look?

https://github.com/List-KR/microShield/actions/runs/7013759258/job/19080447594#step:2:514
https://github.com/List-KR/microShield/actions/runs/7025978340/job/19117895783#step:2:514

When I connect to ProtonVPN KR#16, I see that the latest version is not purged.

**Comment by piquark6046** [comment]
Also, https://github.com/List-KR/NamuLink/actions/runs/7070486367/job/19247232056#step:2:501

**Comment by piquark6046** [comment]
@MartinKolarik Please take a look.

**Comment by MartinKolarik** [comment]
@piquark6046 the log includes several `@main` links, which are not expected to work reliably, as explained in my previous comment. Can you confirm which links you're seeing the issue with and if it's targeting a tagged release?

**Comment by piquark6046** [comment]
The address are:
 - https://cdn.jsdelivr.net/gh/List-KR/NamuLink@latest/NamuLink.user.js
 - https://cdn.jsdelivr.net/gh/List-KR/microShield@latest/microShield.user.js

No. Both repo do not have any tagged release.

**Comment by MartinKolarik** [comment]
> Both repo do not have any tagged release.

In that case this is expected, as per my previous comment: https://github.com/jsdelivr/jsdelivr/issues/18491#issuecomment-1546728124

**Comment by MartinKolarik** [comment]
No, if there are any tagged links, those will be purged fine. But any branch files may not get purged.

**Comment by piquark6046** [comment]
https://github.com/List-KR/microShield/actions/runs/7177267482/job/19543587237
Same even if the logic has been changed.

**Comment by piquark6046** [comment]
https://github.com/List-KR/microShield/actions/runs/7211237959/job/19646208580
When I connect to a ProtonVPN server located in Japan, I can see that the file is not purged.

**Comment by MartinKolarik** [comment]
@piquark6046 if you are still seeing the issue, please again post here:
 - the exact purge request HTTP call,
 - the exact link you're accessing that returns an outdated version.

**Comment by piquark6046** [comment]
@MartinKolarik 
https://github.com/List-KR/microShield/actions/runs/7567205800/job/20606059815
https://cdn.jsdelivr.net/gh/List-KR/microShield@latest/microShield.user.js

**Comment by MartinKolarik** [comment]
As I explained several times, purging is not supported for repositories that don't use tagged releases. Branch links will update on their own in a couple of hours. If you run into purging issues with releases, please open a new issue with details.
