### ISSUE TITLE
[ESM] `saxon-js@2.5.0` error: Uncaught ReferenceError: abstractNode is not defined

### ISSUE THREAD

**Issue by adamatat** [jsdelivr/jsdelivr#18497]
### Description

```
error: Uncaught ReferenceError: abstractNode is not defined
    at https://esm.sh/v121/saxon-js@2.5.0/deno/saxon-js.mjs:64:54270
    at https://esm.sh/v121/saxon-js@2.5.0/deno/saxon-js.mjs:2:1093
    at https://esm.sh/v121/saxon-js@2.5.0/deno/saxon-js.mjs:78:51118
```

### Affected jsDelivr links

https://esm.sh/saxon-js@2.5.0

### Response headers

```
:status: 200
Content-Type: application/javascript; charset=utf-8
Access-Control-Allow-Origin: *
Age: 475
Access-Control-Allow-Methods: *
Content-Encoding: gzip
Cache-Control: public, max-age=86400
Date: Thu, 18 May 2023 19:49:16 GMT
Vary: Origin,User-Agent, Accept-Encoding
Last-Modified: Thu, 18 May 2023 19:41:21 GMT
Alt-Svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
x-content-source: https://esmbuild.com
```

### Information

- Device OS: MacOS 12.0.1
- Browser & Version: Safari 15.1

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
esm.sh is not our service, we only use esm.run domain

**Comment by adamatat** [comment]
> esm.sh is not our service, we only use esm.run domain

My mistake, the same error happens with the jsdeliver domain though, so I've updated the issue.

**Comment by adamatat** [comment]
Ping @MartinKolarik
