### ISSUE TITLE
JsDelivr 504 !!!!

### ISSUE THREAD

**Issue by google-new-updates-schools** [jsdelivr/jsdelivr#18493]
### Description

We use more than 100 links through Github. It gives the error at the bottom. Please, we demand that it be corrected immediately.

Unable to retrieve spec for https://cdn.jsdelivr.net/gh/324525dfg56/5499@main/645784354.xml. HTTP error 504

### Affected jsDelivr links

https://cdn.jsdelivr.net/gh/324525dfg56/5499@main/645784354.xml

### Response headers

```

```

### Information

- Device OS: [e.g. iOS, Windows, MacOS]
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108]
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Please provide additional information. 
- The exact error.
- HTTP headers of the failing URL
- ping cdn.jsdelivr.net and provide the output

Thanks

**Comment by google-new-updates-schools** [comment]
> Please provide additional information.
> 
> * The exact error.
> * HTTP headers of the failing URL
> * ping cdn.jsdelivr.net and provide the output
> 
> Thanks

The problem is solved. It was a temporary error caused by github.
thanks!
