### ISSUE TITLE
GitHub version ranges

### ISSUE THREAD

**Issue by samuelstroschein** [jsdelivr/jsdelivr#18494]
### Description

Taking our email conversation public in case other people face the same issue: 

_From @niklasbuchfink_

> we are still having problems with purging old versions. I have tried to purge this:
https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js
> 
> To update it to the latest version of:
https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2.3/dist/index.js
> 
> What exactly do I need to enter [here](https://www.jsdelivr.com/tools/purge) to get the latest version cached?

_Reply from the maintainer_

> Its not a purging issue, you need to start using semver valid versions.
> 
> https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js
> Is using 2.2.0 because it considers it higher than 2.3 which is not valid. It fails to compare it correctly.
> If the tag was 2.3.0 then the purge would work correctly.
>
> To fix this you simply need to release 
2.3.1.

## Problem

The reply seems contradictory. [The documentation](https://www.jsdelivr.com/documentation#id-github) explicitly showcases versioning without a patch version. What a "valid semver" version is referring to is ambiguous. The documentation gives the impression that versions will be resolved like `@1` < ` @2.3` and `@3.1` < `@3.1.1` etc : 

<img width="816" alt="CleanShot 2023-05-15 at 18 04 45@2x" src="https://github.com/jsdelivr/jsdelivr/assets/35429197/dfd9dd6f-be67-426e-aed6-c9befc98d03a">

From a reasoning standpoint, version 2.2.0 shouldn't be higher than 2.3. I assume that the whole inlang team ran into this issue multiple times now, wondering why the purging doesn't work (for example https://github.com/inlang/inlang/issues/678#issuecomment-1548389094). 

## Proposal 

1. Either throw an error when an "incorrect" semver version like `2.3`
2. Resolve versions "as expected" e.g. major is compared with major, then minor with minor and then (if available) patch with patch.  
3. Update the docs. BUT, not resolving `@2` to be a higher version than `@1` doesn't seem to make sense and breaks the reason why we choose JSDelivr for inlang. We want auto-updating plugins fixed to a major version, or (if desired) a more specific version.

**Comment by MartinKolarik** [comment]
First, this has nothing to do with purging. Second, the documentation, even in the screenshot you posted here, says "works only with valid semver versions". What that means is the tag on your repo must be valid semver. You **can** use `@2.3` in the URL, and it'll match any version in the form of `2.3.x` (valid semver). But a tag `2.3` has an undefined meaning and won't be considered when matching versions. See also https://semver.npmjs.com/ for examples of how the matching works.

**Comment by samuelstroschein** [comment]
> "works only with valid semver versions"

Now I understand what you are referring to. We [had a tag](https://github.com/samuelstroschein/inlang-plugin-json/tags) with `2.3` that is indeed incorrect. I thought you are referring to `2.3` being resolved lower than `2.2.0`. 

I am wondering what @ivanhofer ran into with https://github.com/inlang/inlang/issues/678#issuecomment-1548389094. 

## Proposal(s) 

- [ ] update the documentation to say "only works on valid semver version release tags" to clarify that the semver versions are referring to the release tags, not the

**Comment by samuelstroschein** [comment]
Closing because misunderstanding and no bug.
