### ISSUE TITLE
Repository abusing of JSDelivr's service

### ISSUE THREAD

**Issue by PencilNavigator** [jsdelivr/jsdelivr#18490]
### Description

I recently found out that github repository "https://github.com/Misaka-blog/imgs", website "https://blog.misaka.rest/“ is violating jsdelivr's [Acceptable Use Policy](https://github.com/jsdelivr/jsdelivr/blob/master/Acceptable%20Use%20Policy%20-%20jsdelivr.net.md), especially `4. Prohibited Use - 2. Abusing the service and its resources, or using jsDelivr as a general-purpose file or media hosting service.`

This website is using JSDelivr for it's image, media hosting, and has lots of request through JSDelivr. 

e.g. 
https://blog.misaka.rest/2023/05/09/porkbun-dns/
![pic](https://github.com/jsdelivr/jsdelivr/assets/85282140/2ed467dd-081e-4807-9cf9-595ec8c8d71f)
All images and media content are provided via jsdelivr. As a general media hosting service.

According to [JSDelivr Stats](https://www.jsdelivr.com/package/gh/Misaka-blog/imgs?tab=stats), this repo has produced over 3.7Mil requests and 748GB of data, it is also the "2735th most popular repository" on JSDelivr.

This repository's JSDelivr Hits stats card-[![](https://data.jsdelivr.com/v1/package/gh/Misaka-blog/imgs/badge)](https://www.jsdelivr.com/package/gh/Misaka-blog/imgs)

Actions should be taken of this kind of abuse.

**Comment by jimaek** [comment]
Thank you for reporting, we will look into this internally

**Comment by PencilNavigator** [comment]
Hi, it's been like 2 months, and this site is still up using jsdelivr as a image hosting service.
