### ISSUE TITLE
Stats shows 0 downloads

### ISSUE THREAD

**Issue by jcubic** [jsdelivr/jsdelivr#18498]
### Description

Not sure if this is the right repo, but my project shows zero downloads:

https://www.jsdelivr.com/package/npm/jquery.terminal?tab=stats

![](https://data.jsdelivr.com/v1/package/npm/jquery.terminal/badge?style=rounded)

But I just released a new version. Does the stats per the last version? How to get total download stats?

### Affected jsDelivr links

https://data.jsdelivr.com/v1/package/npm/jquery.terminal/badge?style=rounded

### Response headers

```
Access-Control-Allow-Origin:
*
Access-Control-Expose-Headers:
*
Alt-Svc:
h3-29=":443"
Alt-Svc:
h3=":443"
Cache-Control:
public, stale-while-revalidate=3600, stale-if-error=86400
Cdn-Cache:
MISS
Cdn-Cachedat:
05/19/2023 12:37:30
Cdn-Edgestorageid:
668
Cdn-Proxyver:
1.03
Cdn-Pullzone:
499850
Cdn-Requestcountrycode:
PL
Cdn-Requestid:
69df64db84a9b60f2b738913ab8ad270
Cdn-Requestpullcode:
200
Cdn-Requestpullsuccess:
True
Cdn-Status:
200
Cdn-Uid:
b1941f61-b576-4f40-80de-5677acb38f74
Cf-Cache-Status:
DYNAMIC
Cf-Ray:
7c9c64416a362de9-KBP
Content-Encoding:
br
Content-Type:
image/svg+xml; charset=utf-8
Cross-Origin-Resource-Policy:
cross-origin
Date:
Fri, 19 May 2023 12:37:30 GMT
Deprecation:
Sun, 01 Jan 2023 00:00:00 GMT
Etag:
W/"28b-kTepSYbbq2Ytnucypkxgz1Ae1Ls"
Expires:
Sat, 20 May 2023 02:00:00 GMT
Link:
<https://www.jsdelivr.com/docs/data.jsdelivr.com#get-/v1/stats/packages/npm/-package-/badge>; rel="deprecation", <https://data.jsdelivr.com/v1/stats/packages/npm/jquery.terminal/badge>; rel="successor-version"
Server:
BunnyCDN-PL1-668
Timing-Allow-Origin:
*
Vary:
Accept-Encoding
X-Render-Origin-Server:
Render
X-Response-Time:
18ms

```

### Information

- Device OS: [e.g. iOS, Windows, MacOS]
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108]
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
There is an issue with the stats database, @MartinKolarik is working on it and the data should be back soon

**Comment by MartinKolarik** [comment]
Sorry, we ran into a number of issues today. Nevertheless, it's back to normal now.
