### ISSUE TITLE
URL with `+esm` responds a 404

### ISSUE THREAD

**Issue by regseb** [jsdelivr/jsdelivr#18496]
### Description

The URL [`https://cdn.jsdelivr.net/npm/cronnor@2.1.2/+esm`](https://cdn.jsdelivr.net/npm/cronnor@2.1.2/+esm) responds a `404`: _Couldn't find the requested file._

These URLs work:

- [`https://cdn.jsdelivr.net/npm/cronnor@2.1.2`](https://cdn.jsdelivr.net/npm/cronnor@2.1.2)
- [`https://cdn.jsdelivr.net/npm/cronnor@2.1.1/+esm`](https://cdn.jsdelivr.net/npm/cronnor@2.1.1/+esm)

Significant changes between https://github.com/regseb/cronnor/compare/v2.1.1...v2.1.2:

```diff
{
  "name": "cronnor",
- "version": "2.1.1",
+ "version": "2.1.2",
  "files": [
-   "src/",
-   "types/"
+   "./src/",
+   "./types/"
  ],
- "main": "src/index.js",
  "exports": {
-   ".": "./src/index.js",
-   "./cron": "./src/cron.js",
-   "./cronexp": "./src/cronexp.js",
-   "./at": "./src/at.js",
+   ".": {
+     "default": "./src/index.js",
+     "types": "./types/index.d.ts"
+   },
+   "./cron": {
+     "default": "./src/cron.js",
+     "types": "./types/cron.d.ts"
+   },
+   "./cronexp": {
+     "default": "./src/cronexp.js",
+     "types": "./types/cronexp.d.ts"
+   },
+   "./at": {
+     "default": "./src/at.js",
+     "types": "./types/at.d.ts"
+   },
    "./package.json": "./package.json"
  },
+ "main": "./src/index.js",
- "types": "types/index.d.ts",
+ "types": "./types/index.d.ts",
}
```

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/cronnor@2.1.2/+esm

### Response headers

```
HTTP/3 404 Not Found
content-length: 38
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=31536000, s-maxage=31536000
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-type: text/plain; charset=utf-8
etag: W/"21-M28qQtNh6xlVdIXXeMOLRujDS0c"
content-encoding: br
accept-ranges: bytes
date: Thu, 18 May 2023 13:35:55 GMT
age: 351
x-served-by: cache-fra-eddf8230139-FRA, cache-mrs10526-MRS
x-cache: MISS, HIT
vary: Accept-Encoding
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
```

### Information

- Device OS: Ubuntu 22.04.2 LTS
- Browser & Version: Firefox 113.0.1
- VPN provider (if you use one): none
- Your location (country/region): France

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
As per https://nodejs.org/dist/latest-v20.x/docs/api/packages.html#conditional-exports:

> "default" - the generic fallback that always matches. Can be a CommonJS or ES module file. This condition should always come last

The text says *should*, not *must* but the [enhanced-resolve](https://www.jsdelivr.com/package/npm/enhanced-resolve) package that we use requires this to be the case (since really, anything after default would be just ignored). That's why the module isn't being resolved now.

**Comment by regseb** [comment]
@MartinKolarik Thanks for the feedback. By swaping `types` and `default`, the package is available: [`https://cdn.jsdelivr.net/npm/cronnor@2.1.3/+esm`](https://cdn.jsdelivr.net/npm/cronnor@2.1.3/+esm) 🎉

[Conditional exports](https://nodejs.org/dist/latest-v20.x/docs/api/packages.html#conditional-exports): I understand that `default` should always be the last property among `node-addons`, `node`, `import`, `require` and `default`. But the property `types` can be positioned wherever you want.
