### ISSUE TITLE
CDN not working in Egypt

### ISSUE THREAD

**Issue by peter-tharwat** [jsdelivr/jsdelivr#18503]
### Description

The cdn not working on my country **EGYPT**
works only when we are using VPN
**ALL CDN LINKS NOT WORKING**
and woking **ONLY** when using VPN

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
https://cdn.jsdelivr.net/npm/pace-js@latest/pace.min.js

### Response headers

```

```

### Information

My Location is : EGYPT

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by selgamal** [comment]
Yea, confirm that, tried 3 different ISP still not working

**Comment by jimaek** [comment]
Egyptian ISP providers are blocking the hostname cdn.jsdelivr.net
It's not an issue on our side. Please try to contact your ISP provider and ask them why they're blocking us.
We're trying to contact them as well.
