### ISSUE TITLE
jsdelivr service down in Egypt Region

### ISSUE THREAD

**Issue by pvrameshkf** [jsdelivr/jsdelivr#18505]
### Description

I'm using the Monaco Editor package in my web app, which retrieves the necessary resources from jsdelivr. However, my client encountered an issue when trying to access the site from Egypt. One of the resource API calls failed for him, preventing him from using the site. This issue appears to be specific to that region, as there are no issues reported in other regions.

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/loader.js

### Response headers

```
  Failed to load response data: No data found for resource with given identifier
```

### Information

- Device OS: [ Windows]
- Browser & Version: [Chrome 113]
- VPN provider (if you use one) - No
- Your location: Egypt

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Egyptian ISP providers are blocking the hostname cdn.jsdelivr.net
It's not an issue on our side. Please try to contact your ISP provider and ask them why they're blocking us.
We're trying to contact them as well.

**Comment by pvrameshkf** [comment]
@jimaek , Any alternate solution or approach or workaround to tackle this problem?
