### ISSUE TITLE
cdn error in egypt

### ISSUE THREAD

**Issue by mrjk990** [jsdelivr/jsdelivr#18508]
### Description

the site "cdn.jsdelivr.net" not reachable in egypt
is this problem from your side ??
ERR_CONNECTION_RESET

### Affected jsDelivr links

http://cdn.jsdelivr.net/npm/chart.js

### Response headers

```

```

### Information

- Device OS:Window
- Browser & Version: Chrome 103
- VPN provider : no
- Your location: Egypt

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Egyptian ISP providers are blocking the hostname cdn.jsdelivr.net
It's not an issue on our side. Please try to contact your ISP provider and ask them why they're blocking us.
We're trying to contact them as well.
