### ISSUE TITLE
renamed npm package does not exist in the CDN

### ISSUE THREAD

**Issue by 4www** [jsdelivr/jsdelivr#18519]
### Description

The npm package `@sctlib/mwc` [does not exist in the CDN](https://cdn.jsdelivr.net/npm/@sctlib/mwc), while it exists in the public [NPM registry](https://www.npmjs.com/package/@sctlib/mwc).

This package used to be named `@sctlib/matrix-room-element`, but was re-named recently https://www.npmjs.com/package/@sctlib/matrix-room-element and it seems that jsdelivr does not reflect this change (this old package still works on jsdelivr).

It seems unpkg has a different behavior, and both package names resolve to the right package code served by the CDN.

I wonder if this behavior is intended, and I should deprecate the previous package name, in order for jsdelivr to serve the new one? Or if this might be a user-experience bug, and both packages could "co-exists" both in NPM and CDN, without deprecation of the old one.

Ref: [package code on gitlab](https://gitlab.com/sctlib/mwc) for both the "old and new names".

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@sctlib/mwc

### Response headers

```
GET https://cdn.jsdelivr.net/npm/@sctlib/mwc
No headers for this request
```

### Information

- Device OS: any
- Browser & Version: any
- VPN provider: any
- Your location (country/region): any (through VPN)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Tried to purge both URLs:
```
https://cdn.jsdelivr.net/npm/@sctlib/mwc
https://cdn.jsdelivr.net/npm/@sctlib/matrix-room-element
```

Thanks for the nice tool/service!

**Comment by MartinKolarik** [comment]
The `exports` field is currently considered only when using ESM bundling. The URL is https://cdn.jsdelivr.net/npm/@sctlib/mwc/+esm in that case. If you have a single file that can be used as a default at https://cdn.jsdelivr.net/npm/@sctlib/mwc, you can set it via `main`, `browser`, or `jsdelivr` field in `package.json`, or use the full URL, of course.

**Comment by 4www** [comment]
Oh thank you! I will fix this, sorry for the wrong issue.

**Comment by MartinKolarik** [comment]
> I guess I got confused because it does not appear in search results on the home page.

That's indeed a different issue that we're working on.
