### ISSUE TITLE
Couldn't find the requested file

### ISSUE THREAD

**Issue by kumardeo080** [jsdelivr/jsdelivr#18517]
### Description

I am trying to use jsdelivr for the github file:
https://github.com/fineshop/plus-ui/blob/2.6/js/GoogleTranslate.min.js

The jsdelivr link I am using:
https://cdn.jsdelivr.net/gh/fineshop/plus-ui@2.6/js/GoogleTranslate.min.js

But it says:
Couldn't find the requested file /js/GoogleTranslate.min.js in fineshop/plus-ui.

I am facing this issue from few weeks, new files and updated files can't be accessed through jsdelivr.

**Comment by jimaek** [comment]
I think you added that file after you tagged the version. So it doesn't exist from jsDelivr's point of view.
https://cdn.jsdelivr.net/gh/fineshop/plus-ui@2.6/js/

To make that file available you will need to tag a new version, e.g. 2.6.1

**Comment by kumardeo080** [comment]
> I think you added that file after you tagged the version. So it doesn't exist from jsDelivr's point of view. https://cdn.jsdelivr.net/gh/fineshop/plus-ui@2.6/js/
> 
> To make that file available you will need to tag a new version, e.g. 2.6.1

What if I remove/delete the tags?

**Comment by jimaek** [comment]
We cache them permanently to protect our users. Once we download a tag you can't make any changes to it, only tag a new release.
But as long as you use aliased versions your users don't have to do anything to get the updates
