### ISSUE TITLE
Unable to download packages from Egypt

### ISSUE THREAD

**Issue by bibhas2** [jsdelivr/jsdelivr#18518]
### Description

Unable to download vueJS 2 library from Egypt. The URL works from everywhere else.

Chrome shows ERR_CONNECTION_RESET error.

This has been going on for a while and there are plenty of posts on the Internet. Examples:

https://stackoverflow.com/questions/76455527/is-jsdelivr-cdn-down
https://stackoverflow.com/questions/76822178/cdn-jsdelivr-net-is-blocked-and-not-working-from-egypt

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/vue@2

### Response headers

```

```

### Information

Windows 11. Chrome and Edge browsers were tested.

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

DNS seems to resolve fine.

**Comment by bibhas2** [comment]
Thank you so much for the fast response.

Switching to fastly.jsdelivr.net will require massive changes to the web app.

We tried mapping cdn.jsdelivr.net to the IP of fastly.jsdelivr.net.

```
199.232.81.229 cdn.jsdelivr.net
```

That didn't solve the problem. HTTP(s) connections are refused.

**Comment by jimaek** [comment]
Unfortunately it's not an IP block but a hostname block. So we can't bypass it by changing our IPs
