### ISSUE TITLE
Package Landing Page is Broken - 404 Not Found 

### ISSUE THREAD

**Issue by vishwas-r** [jsdelivr/jsdelivr#18515]
### Description

Landing page of a package gives 404 in https://www.jsdelivr.com, whereas the package is getting listed in https://cdn.jsdelivr.net.

Below is an example of such scenario:
CDN Link: [https://cdn.jsdelivr.net/npm/@canvasjs/charts@3.7.13/](https://cdn.jsdelivr.net/npm/@canvasjs/charts@3.7.13/)
Landing Page: [https://www.jsdelivr.com/package/npm/@canvasjs/charts](https://www.jsdelivr.com/package/npm/@canvasjs/charts)

### Affected jsDelivr links

https://www.jsdelivr.com/package/npm/@canvasjs/charts

### Response headers

```
https://www.jsdelivr.com/readme/npm/@canvasjs/charts
[HTTP/2 404 Not Found 546ms]
Not Found
```

### Information

- Device OS: Windows 10 & Windows 11
- Browser & Version: Chrome v114.0.5735.248, Firefox v115.0.2
- VPN provide: NA
- Your location (country/region): India

### Requisites

- [x] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
This is an issue with our search provider, please follow here for more updates: algolia/npm-search#1112. The package is available at the CDN regardless of what the website currently shows.

**Comment by vishwas-r** [comment]
The package is not being shown in the search result could be the issue with algolia (search provider). But, landing page of the package is also giving 404 error. Isn't that different from search results?
