### ISSUE TITLE
Search for npm package "p5play" doesn't show correct results

### ISSUE THREAD

**Issue by quinton-ashley** [jsdelivr/jsdelivr#18516]
### Description

Hi I'm the author of an npm package called "p5play", which used to be named "p5.play".

I noticed when searching for "p5play" that it only returns results with the old "p5.play" package name. Clicking on the link causes a 404 response. 

A few months ago I contacted npm and had them remove "p5.play" so I could do the slight rename to "p5play" without the period, which they were able to do.

Please remove the "p5.play" package from your database and have jsdelivr serve "p5play" instead.

### Affected jsDelivr links

https://www.jsdelivr.com/package/npm/p5.play

### Response headers

```
{
	"status": 404,
	"message": "Couldn't fetch versions for p5.play."
}
```

### Information

- macOS
- any web browser
- no VPN
- Bogotá, Colombia

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
This is an issue with our search provider, please follow here for more updates: https://github.com/algolia/npm-search/issues/1112. The package is available at the CDN regardless of what the website currently shows.

**Comment by quinton-ashley** [comment]
@MartinKolarik  Okay hopefully that will be sorted soon.

But also I can't access it with a direct link either:
https://www.jsdelivr.com/package/npm/p5play

**Comment by quinton-ashley** [comment]
The direct link still doesn't work.
