### ISSUE TITLE
Verdaccio fixed token

### ISSUE THREAD

**Issue by pedrow-coelho** [jsdelivr/jsdelivr#18526]
### Description

I'm trying to use the verdaccio fixed-token
when I try to publish the package I get the following error

```
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://verdaccio.kind.local/meu-pacote-de-teste - request size did not match content length
```

### Affected jsDelivr links

https://www.jsdelivr.com/package/npm/verdaccio-fixed-token

### Information

- Device OS: [linux]

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
The error you have attached is unrelated to jsDelivr. It's something on your side
