### ISSUE TITLE
A deprecated package is not shown as deprecated

### ISSUE THREAD

**Issue by fulldecent** [jsdelivr/jsdelivr#18525]
### Description

The package web3modal is available on jsDelivr without a warning at:

https://www.jsdelivr.com/package/npm/web3modal

However, this package is deprecated, as evidenced at:

https://www.npmjs.com/package/web3modal

---

Please correct the jsDelivr web page to show that this is deprecated.

### Affected jsDelivr links

https://www.jsdelivr.com/package/npm/web3modal

### Response headers

HTTP status 200. Not relevant.

### Information

Web browser. Not relevant.

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Original discussion from downstream: https://github.com/WalletConnect/web3modal/issues/1307#event-10265820495

**Comment by MartinKolarik** [comment]
This should get resolved after https://github.com/algolia/npm-search/issues/1112. Please subscribe there for updates.

**Comment by riderx** [comment]
Hey @MartinKolarik do we have a way to see/hide deprecated when we do this: https://data.jsdelivr.com/v1/package/npm/@capgo/capacitor-updater ?
I'm using https://marketplace.visualstudio.com/items?itemName=idered.npm
and i would like to make it stop showing deprecated versions in the list, or display them differently

**Comment by riderx** [comment]
It would be beautiful! If you need any help, i can try to work on it
