### ISSUE TITLE
404 Error for Each Request to My 'Capitalised' GitHub Repo

### ISSUE THREAD

**Issue by AnthonyRKing** [jsdelivr/jsdelivr#18535]
### Description

It is my understanding that to access a resource from a public GitHub repo, we simply construct a jsdeliver url like that I've attached, with no versioning specification necessary.

Although I can access resources on other users' GitHubs like this, this doesn't work with mine.

I'm wondering whether this could be anything to do with the capitalisation I seem to have landed myself, with my user and repo names.

### Affected jsDelivr links

https://cdn.jsdelivr.net/gh/AnthonyRKing/TKonan/thumbnail.jpeg

### Response headers

```
Request URL: https://cdn.jsdelivr.net/gh/AnthonyRKing/TKonan/thumbnail.jpeg
Request Method: GET
Status Code: 404 
Remote Address: 146.75.73.229:443
Referrer Policy: strict-origin-when-cross-origin
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: *
age: 51
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
cache-control: public, max-age=60, s-maxage=60
content-encoding: br
content-length: 69
content-type: text/plain; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Fri, 13 Oct 2023 18:34:56 GMT
etag: W/"48-iSiezrz4n8CHjkb1t+r+rEXn3NI"
strict-transport-security: max-age=31536000; includeSubDomains; preload
timing-allow-origin: *
vary: Accept-Encoding
x-cache: MISS, HIT
x-content-type-options: nosniff
x-served-by: cache-fra-etou8220086-FRA, cache-lcy-eglc8600059-LCY
:authority: cdn.jsdelivr.net
:method: GET
:path: /gh/AnthonyRKing/TKonan/thumbnail.jpeg
:scheme: https
accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: en,en-US;q=0.9,en-GB;q=0.8
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: image
sec-fetch-mode: no-cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
```

### Information

- Device OS: Raspberry Pi OS Buster
- Browser & Version: Chroimium 90
- Location: UK

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
The file you requested is on `main`, not `master`. The correct link is https://cdn.jsdelivr.net/gh/AnthonyRKing/TKonan@main/thumbnail.jpeg

**Comment by AnthonyRKing** [comment]
Thanks for clarifying that, Martin. I did check the documentation, which said:

'Omit the version completely or use "latest" to load the latest one (only works with valid semver versions): (Dev environment only)'

I couldn't find any mention of needing to be on the Master branch for that to work. I'm afraid I couldn't say whether I'm compliant with the 'semver' and 'Dev environment' stipulations.

**Comment by MartinKolarik** [comment]
That part applies to using valid semver tags, as it says, which you don't use. Branches generally need to be referenced via `@branch`, with default being the `@master`. I'll look into improving the docs to explain this better.

**Comment by AnthonyRKing** [comment]
Great. I think a little improvement there would be beneficial to any newcomer to the JSDelivr/GitHub method looking for the simplest way to get started; particularly those new to GitHub, who may have only simple mono-version repositories.

It does strike me though, that since GitHub has changed its default root branch name from 'master' to 'main', perhaps jsdelivr would better treat 'main' as a 2nd default; better still, have it as 1st default before 'master'.
