### ISSUE TITLE
document how to not guess at related links

### ISSUE THREAD

**Issue by tacman** [jsdelivr/jsdelivr#18539]
### Is your feature request related to a problem? Please describe.

In the package at https://www.jsdelivr.com/package/npm/simple-datatables?tab=files, I don't want the column_filter.css as my default css, but rather style.css

![image](https://github.com/jsdelivr/jsdelivr/assets/619585/3e035994-ff6c-4ea1-bc99-19096cba0dc2)

The default link URL appears to simply be the first one alphabetically.

https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/dist/

### Describe the solution you would like.

Is there a way for the package author to "hint" to jsdelivr which link should be included?

    The URL is guessed and might not be correct. You can always browse all package files to find the correct one.
 
Is there a way to not guess? In composer, a PHP package manager, there's a "suggests" key, which hints at what other dependencies to include.  Is there anything like that in package.json?

If indeed it's simply the first css file that jsdelivr finds, can you document that somewhere so package creators can know how to structure their directories?  Symfony's new AssetMapper component allows developers to download packages from jsdelivr, and the default css is now very important.

```bash
bin/console importmap:require simple-datatables

                                                                                                                        
 [OK] 2 new items (simple-datatables, simple-datatables/dist/column_filter.min.css) added to the importmap.php!         
                                                                                                                        

tac@tac-desktop1:~/g/trash/command-7$ bin/console importmap:require simple-datatables -vv
10:19:13 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/simple-datatables/resolved"
10:19:13 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/simple-datatables/resolved"
10:19:13 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/+esm"
10:19:13 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/simple-datatables@8.0.0/entrypoints"
10:19:14 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/+esm"
10:19:14 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/simple-datatables@8.0.0/entrypoints"
10:19:14 INFO      [http_client] Request: "GET https://data.jsdelivr.com/v1/packages/npm/simple-datatables/resolved?specifier=8.0.0"
10:19:14 INFO      [http_client] Response: "200 https://data.jsdelivr.com/v1/packages/npm/simple-datatables/resolved?specifier=8.0.0"
10:19:14 INFO      [http_client] Request: "GET https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/dist/column_filter.min.css"
10:19:14 INFO      [http_client] Response: "200 https://cdn.jsdelivr.net/npm/simple-datatables@8.0.0/dist/column_filter.min.css"

                                                                                                                        
 [OK] 2 new items (simple-datatables, simple-datatables/dist/column_filter.min.css) added to the importmap.php!        
```

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
You can use `style` field in `package.json`, e.g. : https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/package.json

**Comment by MartinKolarik** [comment]
I'll check what went wrong here because, without that field, you should get the file with the most monthly downloads, which would be `/dist/style.css`

**Comment by tacman** [comment]
Thanks!  What do you think of changing the error message (The URL is guessed and might not be correct. You can always browse all package files to find the correct one.) to something like

    No style key in package.json, so the URL is guessed.   Browse the packages (link to packages) to manually install more.

**Comment by MartinKolarik** [comment]
I added this case to the readme and changed the message to link to that section, thanks.

**Comment by MartinKolarik** [comment]
We also fixed the issue with guessing that affected this particular package. The correct file is now shown, even without the `styles` field: https://www.jsdelivr.com/package/npm/simple-datatables
