### ISSUE TITLE
Failed to bundle: npm module @aws-sdk/util-endpoints for ESM type

### ISSUE THREAD

**Issue by mjgurney** [jsdelivr/jsdelivr#18534]
### Description

The npm module @aws-sdk/util-endpoints which is essential for use of related @aws-sdk modules returns body contents indicating that it has "failed to bundle" when requested as ESM type.

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@aws-sdk/util-endpoints@3.428.0/+esm

### Response headers

```

```

### Information

- Device OS: iOS, Windows, MacOS
- Browser & Version: Safari, Chrome, Firefox
- My location: Canada

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Hey, thanks for reporting. We should be able to fix this one shortly.

**Comment by MartinKolarik** [comment]
Hey, thanks for reporting. We should be able to fix this one shortly.

**Comment by MartinKolarik** [comment]
Should work now.
