### ISSUE TITLE
@latest link tag not updating

### ISSUE THREAD

**Issue by bhaktatejas922** [jsdelivr/jsdelivr#18530]
### Description

latest commit - correct: https://cdn.jsdelivr.net/gh/autoinfra-ai/lingtual-embedded-chat@6b63d2d/dist/build/static/js/bundle.min.js

Tried purge link https://purge.jsdelivr.net/npm/lingtual-embedded-chat@latest

Still going off of cache : https://cdn.jsdelivr.net/gh/autoinfra-ai/lingtual-embedded-chat@latest/dist/build/static/js/bundle.min.js

### Affected jsDelivr links

https://cdn.jsdelivr.net/gh/autoinfra-ai/lingtual-embedded-chat@latest/dist/build/static/js/bundle.min.js

### Response headers

```
Age:
2588
Alt-Svc:
h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
Cache-Control:
public, max-age=604800, s-maxage=43200
Date:
Sat, 30 Sep 2023 18:54:50 GMT
Etag:
W/"33cdd-aaCGqaVZ/uGHopqzDNtUW3UaJas"
Vary:
Accept-Encoding
X-Cache:
HIT
X-Served-By:
cache-bur-kbur8200176-BUR

```

### Information

macos, chrome

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by bhaktatejas922** [comment]
does the purge link no longer do anything?

**Comment by jimaek** [comment]
I think you have mixed many different things.

You're purging NPM (npm/lingtual-embedded-chat@latest) while trying to use the Github URL (gh/autoinfra-ai/lingtual-embedded-chat@latest/dist/build/static/js/bundle.min.js)? It will never work of coure.

Additionally you're not using tags https://github.com/autoinfra-ai/lingtual-embedded-chat/tags which are quired for purge to work. Please read the docs, the purge API works correctly
