### ISSUE TITLE
@social-mail/social-mail-client package not found

### ISSUE THREAD

**Issue by ackava** [jsdelivr/jsdelivr#18533]
### Description

It has been almost couple of months, the package `@social-mail/social-mail-client` isn't available and we are using unpkg but I just want to know is it a bug or something is not configured?

**Comment by MartinKolarik** [comment]
This was likely just a website issue described in https://github.com/jsdelivr/jsdelivr/issues/18516#issuecomment-1652423103

It has just got fixed so please check again.

**Comment by ackava** [comment]
@MartinKolarik Thanks I can see it now.
