### ISSUE TITLE
Github repo size is limited to 50mb, but the docs say 150mb

### ISSUE THREAD

**Issue by LorisSigrist** [jsdelivr/jsdelivr#18544]
### Description

The [Documentation](https://www.jsdelivr.com/documentation#id-restrictions) says that Github repositories/packages are restricted to 150mb in size. In practice it seems that the limit is actually 50mb. (The intended limit used to be 50mb)

If the 150mb declared in the documentation isn't intended, and the limit really should be 50mb, then the documentation should be updated to reflect that.

### Affected jsDelivr links

https://cdn.jsdelivr.net/gh/inlang/monorepo/inlang/documentation/assets/plugin.jpg (current repo size 110mb)

### Response headers

```
Access-Control-Allow-Origin:
*
Access-Control-Expose-Headers:
*
Age:
20
Alt-Svc:
h3=":443"; ma=86400
Cache-Control:
public, max-age=60, s-maxage=60
Cf-Cache-Status:
HIT
Cf-Ray:
831381ec1f975264-MXP
Content-Encoding:
br
Content-Type:
text/plain; charset=utf-8
Cross-Origin-Resource-Policy:
cross-origin
Date:
Wed, 06 Dec 2023 09:29:58 GMT
Etag:
W/"97-mCh0GZUwxx4OmVM/4W99445X+Yc"
Nel:
{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Report-To:
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=aTo6Hw%2B4uCvyG1Z4mrxYOJj7joB0YoO1YmiuSwwmNMeNwGAX7DxlvwPEgRbzwWSVg53n%2Fgi0kv4w2cMBAca60%2BQMn0v3ZnjVCeryfXIR9i1tcDCcoiHsHV%2B5PAV1UqeuzHz5BTGVOLRfocsTQxg%3D"}],"group":"cf-nel","max_age":604800}
Server:
cloudflare
Strict-Transport-Security:
max-age=31536000; includeSubDomains; preload

Timing-Allow-Origin:
*
Vary:
Accept-Encoding
X-Cache:
MISS, MISS
X-Content-Type-Options:
nosniff
X-Served-By:
cache-fra-etou8220039-FRA, cache-mxp6923-MXP
```

### Information

- Device OS: MacOS Ventura
- Browser & Version: Arc Browser running Chromium 119
- VPN provider None
- Your location  Switzerland

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Also please make sure the file you request actually exists. 404 on individual file fetch may trigger a fallback behavior, in which case the limit applies. But for existing files, the repo size doesn't matter.

**Comment by LorisSigrist** [comment]
I'm very sorry about that, I saw a wall of 403s and got spooked. 
I'll pay better attention next time!
