### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by ackava** [jsdelivr/jsdelivr#18548]
### Description

Newly pushed package not found, it is available on npmjs.com https://www.npmjs.com/package/@entity-access/tracer-client?activeTab=code

**Comment by MartinKolarik** [comment]
Looks like there's a delay on npm's end, and the package has not yet propagated to their replicate endpoint: https://replicate.npmjs.com/registry/@entity-access%2Ftracer-client

It'll be indexed once it's available there.
