### ISSUE TITLE
False positives issue in jsDelivr purge API

### ISSUE THREAD

**Issue by piquark6046** [jsdelivr/jsdelivr#18549]
### Description

The file is not changed even if I create a tagged release.

<details><summary>Screenshot</summary>
<p>

![Screenshot from 2024-01-19 02-42-09](https://github.com/jsdelivr/jsdelivr/assets/98787049/5dc80d8f-f796-40dd-9ccc-05ba3e2c7ad3)

</p>
</details> 

Purge Request API Result:
```
{
  "id": "6VR8pidJZiHFHsUR",
  "status": "finished",
  "timestamp": "2024-01-18T18:47:28.370Z",
  "paths": {
    "/gh/List-KR/microShield@latest/microShield.user.js": {
      "throttled": false,
      "providers": {
        "CF": true,
        "FY": true
      }
    }
  }
}
```

### Affected jsDelivr links

https://cdn.jsdelivr.net/gh/List-KR/microShield@latest/microShield.user.js

### Response headers

```
GET /gh/List-KR/microShield@latest/microShield.user.js HTTP/2
Host: cdn.jsdelivr.net
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Sec-GPC: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache
```

### Information

- Device OS: Linux
- Browser & Version: Firefox 121.0.1
- VPN provider: ProtonVPN
- Your location (country/region): South Korea

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

https://github.com/jsdelivr/jsdelivr/issues/18491#issuecomment-1898769622

**Comment by MartinKolarik** [comment]
Your release numbers are not valid semver.

> Valid semver releases must be used for purge to work

https://github.com/jsdelivr/jsdelivr
