### ISSUE TITLE
Latest files not available anymore. Did something change?

### ISSUE THREAD

**Issue by chromoxdor** [jsdelivr/jsdelivr#18541]
### Description

ESPeasy  (https://github.com/letscontrolit/ESPEasy) used as a kind of fall back option a specific jsdelivr URL to point to the latest version:
https://cdn.jsdelivr.net/gh/letscontrolit/ESPEasy/

This worked fine until recently. Now it points to a very old version.
Did something changed? Is there anything one can do about it?

**Comment by MartinKolarik** [comment]
We recently improved our version resolving to follow the semver rules closer. The resolved version `2.0.0-dev9` is the most recent valid semver tag. Previously, pre-release tags were (incorrectly) ignored, and the project was served from the `@mega` branch as a fallback. You can revert to that behavior by specifying the branch explicitly https://cdn.jsdelivr.net/gh/letscontrolit/ESPEasy@mega/file.

**Comment by chromoxdor** [comment]
Thank you for your answer!

>  You can revert to that behavior by specifying the branch explicitly

This is what we going to do.
