### ISSUE TITLE
https://esm.run/hyop/single_hyop - Failed to bundle using Rollup v2.79.1.

### ISSUE THREAD

**Issue by btakita** [jsdelivr/jsdelivr#18551]
### Description

The hyop package defines [various exports](https://github.com/hyopjs/hyop/blob/main/package.json#L36-L43).

The export js files themselves import no files.

https://github.com/hyopjs/hyop/blob/main/single_hyop/index.js

The ./single_hyop/index.d.ts file imports types from ./index.d.ts

https://github.com/hyopjs/hyop/blob/main/single_hyop/index.d.ts

### Affected jsDelivr links

https://esm.run/hyop/single_hyop

### Response headers

```
HTTP/2 200 
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=604800, s-maxage=43200
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-type: application/javascript; charset=utf-8
x-jsd-version: 0.2.2
x-jsd-version-type: version
etag: W/"191-bxIMGg15ZOChCP6DHTNrUGWVWRA"
content-encoding: br
accept-ranges: bytes
date: Sun, 11 Feb 2024 03:12:47 GMT
age: 2048
x-served-by: cache-fra-eddf8230118-FRA, cache-bos4688-BOS
x-cache: MISS, HIT
vary: Accept-Encoding
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 173
X-Firefox-Spdy: h2
```

### Information

- Device OS: Arch Linux
- Browser & Version: Firefox 122.0
- NA
- CT/USA

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Hey, I'm currently getting a successfully bundled file. Have you managed to fix this on your end?

**Comment by btakita** [comment]
Thank you, I refreshed my cache & it works! I had an older version where I forgot to include the export directories in the `package.json` `files`, which probably caused the build to fail.

**Comment by btakita** [comment]
Closing
