### ISSUE TITLE
Many esm.run URLs are broken since yesterday

### ISSUE THREAD

**Issue by mootari** [jsdelivr/jsdelivr#18557]
### Description

Since yesterday many paths of the form `https://esm.run/{name}` and `https://esm.run/{name}@{version}` have started breaking, instead serving a 421 response with the body:
~~~
Requested host does not match any Subject Alternative Names (SANs) on TLS certificate [4e88d7db0fa92f185d522e0448683816c7a71e4568d87f65ec4a42f984f5c991] in use with this connection.

Visit https://docs.fastly.com/en/guides/common-400-errors#error-421-misdirected-request for more information.
~~~

### Affected jsDelivr links

Two of many examples:
- https://esm.run/d3@7
- https://esm.run/acorn

Caching may play a role, as e.g. `https://esm.run/d3` still redirects.

### Response headers

`curl -I 'https://esm.run/d3@6'`
```
HTTP/2 421 
date: Wed, 28 Feb 2024 11:38:19 GMT
content-type: text/plain; charset=utf-8
content-length: 297
x-served-by: cache-ams21023
cf-cache-status: BYPASS
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=%2Ff%2BTJucN68ihRRCb5T2e0rMmqi2JTkZdVP2sg7aUEa3izExyDHIqxqftjmufSorkAEJ0nLAeXGBGHfVHr4E3JsRZyfzaqCRoFmjZeV5tiy%2Bg24Jzobc1xhmI7%2FzQKZ%2FlQww0jYfk"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 85c8616d994d6fcf-CDG
alt-svc: h3=":443"; ma=86400
```

### Information

- Device OS: n/a
- Browser & Version: n/a
- Location: Germany, but confirmed via VPN for other countries (US, Japan)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Fastly deprecated a TLS setting we were using which resulted in this unfortunately outage. The issue is now permanently fixed.
