### ISSUE TITLE
Support SourceForge / GitLab

### ISSUE THREAD

**Issue by fawazahmed0** [jsdelivr/jsdelivr#18556]
### Is your feature request related to a problem? Please describe.

GitHub can sometimes block repositories if there is excess usage.
For example, see [this](https://github.com/fawazahmed0/currency-api).

Excess usage can happen when the project is useful and alot many people are using it. ( eg: see [this](https://github.com/LSPosed/MagiskOnWSA) & [this](https://github.com/LSPosed/MagiskOnWSALocal#:~:text=Please%20don%27t%20build%20using%20GitHub%20Actions%2C%20as%20GitHub%20will%20count%20your%20forked%20GitHub%20Actions%20usage%20against%20this%20upstream%20repository%2C%20which%20may%20cause%20this%20upstream%20repository%20gets%20disabled%20by%20GitHub%20staff%20like%20MagiskOnWSA)

### Describe the solution you would like.

It will be helpful, if there is support for other source code hosting services, preferably sourceforge (see [this](https://opengapps.org/blog/post/2019/08/23/sourceforge-migration/?back=true) ) 

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Our source code repos dont really have a lot of traffic or files. So I don't think its a realistic problem to prepare against. For now we prefer to stay here. But our binaries like CLI and Docker containers do work outside of GitHub

**Comment by jimaek** [comment]
Oh I understand now. Unfortunately the development time to properly support a new source would be quite long and we cant afford it for now. It's something we would like to add in the future, but I cant promise a timeline for now.
