### ISSUE TITLE
Increase package size limit for dns-blocklists

### ISSUE THREAD

**Issue by hagezi** [jsdelivr/jsdelivr#18550]
### Project

https://github.com/hagezi/dns-blocklists

### Project License

GPL-3.0 license 

### Relationship

Maintainer

### Short description of the project

All in one DNS blocklists in various versions.

### Requisites

- [X] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
- [X] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

https://github.com/hagezi/dns-blocklists/issues/2097

**Comment by MartinKolarik** [comment]
Hey @hagezi 👋 I see you linked a GH repo here. We actually allow files up to 20 MB for GitHub regardless of the overall repo size, so you should be good even now. One caveat is that directory listings won't work for repos of your size, but any direct file link will.

**Comment by hagezi** [comment]
Thanks @MartinKolarik, but try: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@main/hosts/ultimate.txt

`File size exceeded the configured limit of 20 MB.`

**Comment by hagezi** [comment]
Everything works now, thank you @MartinKolarik

**Comment by MartinKolarik** [comment]
Great! I forgot to post the update here, so thanks for checking and confirming.

**Comment by hagezi** [comment]
@MartinKolarik 

Can you increase the package size for the following repositories in the same way (150 MB)?

- https://github.com/hagezi/dns-blocklists-legacy
- https://github.com/hagezi/nrd

Thank you very much,
Gerd

**Comment by MartinKolarik** [comment]
Done.

**Comment by hagezi** [comment]
Thanks @MartinKolarik, and have a great rest of the week.
