### ISSUE TITLE
Increase package size limit for Articulate360ForKhaoNiewClassroom

### ISSUE THREAD

**Issue by paung23** [jsdelivr/jsdelivr#18564]
### Project

https://github.com/paung23/Articulate360ForKhaoNiewClassroom

### Project License

N/A

### Relationship

Maintainer

### Short description of the project

This is the codebase for an Articulate 360 course that an NGO is going to be using on their website for educational purposes.

### Requisites

- [X] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
- [X] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

Hello! I would like to request for an increase for single file limit for this little educational video: https://github.com/paung23/Articulate360ForKhaoNiewClassroom/blob/main/Articulate360_Content/assets/LoW_Campaign%20to%20Ban%20Landmines%20and%20Cluster%20%20Munitions%20Coalition_NoSubs_v01.mp4. The project is an Articulate 360 course that an NGO is going to be putting up on their website and we would really appreciate it if we can get a file limit increase. It is only around 37 MB so a slight increase would be enough. Thank you for your consideration!

**Comment by MartinKolarik** [comment]
Hi, since this doesn't seem to be an OSS project where other people would use the files, we won't be increasing the limits in this case.

**Comment by paung23** [comment]
Hi Martin,

Thank you for your response. We actually want to make the repo an open source project which everyone can refer to or just utilize our course straight on Wix or another website builder. There have actually been multiple forum discussions where people could not figure out how to use an Articulate 360 course on a website builder like Wix as shown below:
1. https://community.articulate.com/discussions/articulate-storyline/articulate-360-interactive-course-on-wix-website
2. https://community.articulate.com/discussions/articulate-storyline/upload-my-storyline-2-file-on-my-wix-website
3. https://community.articulate.com/discussions/articulate-storyline/uploading-corm-compliant-storyline-2-project-in-wix
4. https://community.articulate.com/discussions/articulate-storyline/upload-to-wix-or-google-site
We would like to show that they can utilize our course directly or reference it so that they can integrate a course on a website builder. We also really want our course to be used in other websites by other people.

Please reconsider for us. We greatly appreciate your help.

Thanks,
Phyo.
--
Phyo Thuta Aung
Lead Software Engineer
Raphael Center for Neurorestoration <http://neurorestoration.jefferson.edu/> at Jefferson Health, Philadelphia, PA, USA
Mobile: (+1) 717-203-9582
Email: ***@***.*** ***@***.***>
