### ISSUE TITLE
Purging API reverts the resources to its past version

### ISSUE THREAD

**Issue by piquark6046** [jsdelivr/jsdelivr#18568]
### Description

The server returns 2.1.9 version as NamuLink userscript latest version.
And, it returns 3.12.16 as microShield userscript latest version.
All above repos have valid semver.

### Affected jsDelivr links

https://cdn.jsdelivr.net/gh/List-KR/microShield@latest/microShield.user.js
https://cdn.jsdelivr.net/gh/List-KR/NamuLink@latest/NamuLink.user.js

### Response headers

```
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: *
Age: 366
Alt-Svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
Cache-Control: public, max-age=604800, s-maxage=43200
Content-Encoding: br
Content-Length: 2536
Content-Type: application/javascript; charset=utf-8
Cross-Origin-Resource-Policy: cross-origin
Date: Fri, 03 May 2024 13:25:48 GMT
Etag: W/"21ed-IuKyXkJy56hwrJl5AqVFqV6Lw2c"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

Timing-Allow-Origin: *
Vary: Accept-Encoding
X-Cache: HIT, MISS
X-Content-Type-Options: nosniff
X-Jsd-Version: 2024.123.0
X-Jsd-Version-Type: version
X-Served-By: cache-fra-eddf8230124-FRA, cache-tyo11937-TYO
```

### Information

- Device OS: Ubuntu 24.04 LTS
- Browser & Version: Brave web browser 1.65.126 and Firefox 126.0b8
- VPN provider: Proton VPN KR#22
- Your location: South Korea

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

 - https://github.com/List-KR/NamuLink/actions/runs/8938674558/job/24556061807
 - https://github.com/List-KR/microShield/actions/runs/8939148655/job/24556051956

**Comment by MartinKolarik** [comment]
Hey, I can see the response content doesn't match your GH release, but the headers say `X-Jsd-Version: 2024.123.0`. Have you, by any chance, modified the release `2024.123.0` after publishing it?

**Comment by piquark6046** [comment]
OK. I close the issue.
