### ISSUE TITLE
421 Misdirected Request - errors

### ISSUE THREAD

**Issue by artsiom10** [jsdelivr/jsdelivr#18566]
### Description

Doesn't work files for some scripts. For example Swiper JS

When I try to use js script I get this error – 421 Misdirected Request

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js
https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css

### Response headers

Request URL:
https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css
Request Method:
GET
Status Code:
421 Misdirected Request
Remote Address:
104.16.89.20:443
Referrer Policy:
strict-origin-when-cross-origin
Cf-Ray:
87d61706988d7905-MSQ
Content-Length:
573

Content-Type:
text/html
Date:
Thu, 02 May 2024 06:52:41 GMT
Server:
cloudflare
:authority:
cdn.jsdelivr.net
:method:
GET
:path:
/npm/swiper@9/swiper-bundle.min.css
:scheme:
https
Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding:
gzip, deflate, br, zstd
Accept-Language:
ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control:
max-age=0
Dnt:
1
Sec-Ch-Ua:
"Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"macOS"
Sec-Fetch-Dest:
document
Sec-Fetch-Mode:
navigate
Sec-Fetch-Site:
none
Sec-Fetch-User:
?1
Upgrade-Insecure-Requests:
1
User-Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

### Information

- Device OS: [e.g. iOS, Windows, MacOS]
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108]
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by rizkytegar** [comment]
hello @artsiom10,

Please try the following URL:

```
https://fastly.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css
https://fastly.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js
```

Please read the following issue: [cdn.jsdelivr.net has SSL issue. #18565](https://github.com/jsdelivr/jsdelivr/issues/18565)

**Comment by artsiom10** [comment]
Thanks! It helps. It's temporary solution? Or use this subdomain now?
