### ISSUE TITLE
cdn.jsdelivr.net switching CDN provider

### ISSUE THREAD

**Issue by ihsangan** [jsdelivr/jsdelivr#18577]
### Description

in Indonesia before May 2 (#18565 ), all traffic to cdn.jsdelivr.net is routed through Cloudflare. After Cloudflare back online and ClouDNS added back to the provider's DNS, sometimes traffic is moved to Fastly. I hope Cloudflare can become the main CDN like before.

p.s: Fastly does not have a PoP and Cloudflare has two PoPs in Indonesia.

**Comment by ihsangan** [comment]
Connection from Central Borneo with AS18004
![IP address from Fastly](https://github.com/jsdelivr/jsdelivr/assets/63774886/8bcae812-8417-4be2-b93f-34a94a200f1c)
![](https://github.com/jsdelivr/jsdelivr/assets/63774886/b05caacc-207f-46c1-a8e1-9e0fa6e8b0d8)

**Comment by jimaek** [comment]
For now unfortunately there will be no active geo steering. But the effective performance should not be negatively impacted overall. Even in cases where Fastly doesn't have a POP in a region that CF has, Fastly most often than not has better peering making their performance roughly equal or sometimes even better. Its something I have seen multiple times and confirmed with data.
