### ISSUE TITLE
Cannot visit JsDelivr in China

### ISSUE THREAD

**Issue by Googologyer** [jsdelivr/jsdelivr#18579]
### Description

It may be had GFW blocked in China. Why?
Why no ICP makes GFW Blocked? Because too many people to abuse?

### Affected jsDelivr links

https://cdn.jsdelivr.net/*/*

### Response headers

```
ERR::CONNECTION_TIMED_OUT
```

### Information

- Device OS: Windows
- Browser & Version: Edge ~~(Latest)~~
- VPN provider isn't use
- Your location China.

### Requisites

- [ ] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [x] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Hello, our ICP license was pulled a while ago and unfortunately there is nothing we can do to reinstate it as we have no connections to China and it's regulators. We did our best to avoid it but at the moment all we can offer trying a different endpoint like fastly.jsdelivr.net

Thank you

**Comment by Googologyer** [comment]
You can contacting via phone, a method to search China's regulators is Baidu Search or Bing/Google.

**Comment by PumpkinXD** [comment]
check #18397 and stop duplicating/spamming, gongxiang01

**Comment by Googologyer** [comment]
I'm not Gongxiang01, I'm Googol.
Please note that "Gongxiang01 never equal Googol".
And I not to duplicating/spamming, again i'll report to GitHub.
________________________________
发件人: PumpkinXD ***@***.***>
发送时间: 2024年5月31日 23:04
收件人: jsdelivr/jsdelivr ***@***.***>
抄送: Googology ***@***.***>; Author ***@***.***>
主题: Re: [jsdelivr/jsdelivr] Cannot visit JsDelivr in China (Issue #18579)


check #18397<https://github.com/jsdelivr/jsdelivr/issues/18397> and stop duplicating/spamming, gongxiang01

―
