### ISSUE TITLE
Request a ban xiaohaiya 

### ISSUE THREAD

**Issue by 54ayao** [jsdelivr/jsdelivr#18586]
### Description

https://cdn.jsdelivr.net/china/gh/xiaohaiya/video/4k/sx/suxun001.ts
https://cdn.jsdelivr.net/gh/xiaohaiya/video/4k/sx/suxun001.ts
https://fastly.jsdelivr.net/china/gh/xiaohaiya/video/4k/sx/suxun001.ts
https://fastly.jsdelivr.net/china/gh/xiaohaiya/video/4k/sx/suxun001.ts

This repository is requesting to load slice videos and some m3u8 type files, which severely maliciously consumes jsDelivr traffic, violates jsDelivr's Terms of Service, requesting to be banned, thank you.

**Comment by 54ayao** [comment]
https://www.jsdelivr.com/package/gh/xiaohaiya/video?tab=stats



This type of video is a global anime video. The video contains gambling advertisements, which may violate the DMCA. Please review and make timely adjustments. Thank you.

**Comment by 54ayao** [comment]
- [ ] ![Screenshot_2024-06-19-03-40-07-930_com.android.browser.jpg](https://github.com/jsdelivr/jsdelivr/assets/86733666/78fbb9fc-8058-447d-8f70-26b765c395dd)
 
ts  or m3u8 

We kindly request that you consider enhancing your detection measures, as it would facilitate the timely identification and resolution of any potential issues. This is especially crucial in light of the concerns surrounding certain types of files, Including those that have been previously linked to inappropriate content on platforms like npm, such as The Joy of Life 2.Although we acknowledge the valuable role of npm or GitHub's detection mechanisms, we believe that heightened vigilance is necessary. Our goal is to collaborate in order to foster a safer and more secure online environment, thereby avoiding any unnecessary losses or complications that may arise. Thank you for your attention to this matter.

**Comment by 54ayao** [comment]
Machine translations may have some discrepancies; please refer to the general meaning.

**Comment by jimaek** [comment]
The user was banned and the URLs will stop working shortly as caches expire. In the future please email us directly to report such abuse. Thank you!
