### ISSUE TITLE
RU ISP Filtering? Eyeball network performance issues

### ISSUE THREAD

**Issue by Wizzerinus** [jsdelivr/jsdelivr#18581]
### Description

When loading pretty much any large JS file from cdn.jsdelivr.net, I am experiencing huge load times (20-45 seconds, sometimes even longer), sometimes with NS_ERROR_NET_PARTIAL_TRANSFER, sometimes they load just before the timeout happens. This started a couple months ago and affects ONLY cdn.jsdelivr, other CDNs seem to work fine. I think loading CSS files works perfectly fine. I have not found any pattern in this slowdown or any known slowdown problem. It does not seem to matter whether this is a repeat load or a new load, either (spamming ctrl+f5 a lot does usually fix the issue for repeat loads, but ctrl+f5 after a delay of a few minutes is similar to first-time load), but small files seem to not be affected, i.e. I tested with Alpine (which is 18kb download compressed) and it worked just fine. Stylesheets also work (tested with Bulma which is a 150kb download).

This issue might stem from my ISP (see last chart), I cannot easily tell what's happening so asking in both places. Edit: but this is very unlikely because this happened with multiple different ISPs in different places.

![image](https://github.com/jsdelivr/jsdelivr/assets/52964431/0d377e28-0159-4094-9795-30c98e56ad9b)

![image](https://github.com/jsdelivr/jsdelivr/assets/52964431/407852b6-39f8-473d-a5ba-51c5417410ed)

For comparison, unpkg for Vue:
![image](https://github.com/jsdelivr/jsdelivr/assets/52964431/09cc4051-8697-4ec1-9167-74b473a3df6f)

cdnjs for Swagger:
![image](https://github.com/jsdelivr/jsdelivr/assets/52964431/e9fc04dd-d20d-429e-922f-838ebb656a2d)

The strange thing is this chart (different request here, but all other requests also had the same chart profile):
![image](https://github.com/jsdelivr/jsdelivr/assets/52964431/724544cb-a3e6-4c5a-99b7-45fb0ad5a0a9)

### Affected jsDelivr links

```
https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js
https://cdn.jsdelivr.net/npm/vue@3.4.27/dist/vue.global.min.js
```

### Response headers

Swagger - 24 seconds:
```
HTTP/2 200 
date: Tue, 04 Jun 2024 08:34:03 GMT
content-type: application/javascript; charset=utf-8
content-length: 394209
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=31536000, s-maxage=31536000, immutable
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-jsd-version: 5.9.0
x-jsd-version-type: version
etag: W/"15230a-6FSerVoxtKZalTFZEMAda1RLTwY"
content-encoding: br
x-served-by: cache-fra-etou8220022-FRA, cache-lga21969-LGA
x-cache: HIT, HIT
vary: Accept-Encoding
alt-svc: h3=":443"; ma=86400
cf-cache-status: HIT
age: 1607615
accept-ranges: bytes
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=lLwkkmMp3EopjzNCO8tVds%2Fv73j4jFeCgFFrpi2Egxh45dIJdGy%2BwxF6UZsTfaAynpjuFYAn8S0Ny8rTMyYGfvwksUe%2B%2FGpmm2EqeN5qNY%2FsT6oVSOn4whdZ8RJZRzx2FXk%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 88e694e37bb39db3-DME
X-Firefox-Spdy: h2
```
Vue - 13 seconds:
```
HTTP/2 200 
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=31536000, s-maxage=31536000, immutable
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-type: application/javascript; charset=utf-8
x-jsd-version: 3.4.27
x-jsd-version-type: version
etag: W/"2f9b3-2wYb03142Ewy7ynSNBMglH4QwHU"
content-encoding: br
accept-ranges: bytes
age: 1735610
date: Tue, 04 Jun 2024 08:41:06 GMT
x-served-by: cache-fra-etou8220142-FRA, cache-ams21079-AMS
x-cache: HIT, HIT
vary: Accept-Encoding
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 74835
X-Firefox-Spdy: h2
```

Note: these headers might not be the exact same with the screenshot requests since I did each request multiple times, I did make sure to get a slow request with each

### Information

- Device OS: Fedora Linux
- Browser & Version: Firefox 124.0.2
- VPN provider: none
- Your location: Russia, Moscow

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Based on the headers and the fact this affects only specific file types, this seems specific to your device. Please try to disable all browser extensions or use a different browser in a default configuration, and also disable any security/AW software you might have and let us know the results.

**Comment by jimaek** [comment]
Please also ping cdn.jsdelivr.net and tell us the IP

**Comment by netsuileo** [comment]
Same issue with https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.30.0/swagger-ui.css and https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.30.0/swagger-ui-bundle.js
Very long loading times, sometimes this files are not loaded at all, even after several minutes of waiting.

Device OS: Windows 10
Browser & Version: 125.0.6422.114
VPN provider: none
Your location: Russia, Yekaterinburg

But files are loading fast with VPN in Netherlands. Maybe it is location related issue?

**Comment by jimaek** [comment]
Please ping and traceroute cdn.jsdelivr.net and provide the results. A screenshot of the certificate would also be useful.

**Comment by netsuileo** [comment]
> Please ping and traceroute cdn.jsdelivr.net and provide the results. A screenshot of the certificate would also be useful.

Ping:
```
➜  ~ ping cdn.jsdelivr.net
PING jsdelivr.map.fastly.net (151.101.65.229) 56(84) bytes of data.
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=1 ttl=54 time=66.7 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=2 ttl=54 time=68.0 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=3 ttl=54 time=65.5 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=4 ttl=54 time=67.4 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=5 ttl=54 time=65.8 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=6 ttl=54 time=66.5 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=7 ttl=54 time=65.2 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=8 ttl=54 time=65.6 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=9 ttl=54 time=65.3 ms
64 bytes from 151.101.65.229 (151.101.65.229): icmp_seq=10 ttl=54 time=65.8 ms
64 bytes from 151.101.65.229: icmp_seq=11 ttl=54 time=65.4 ms

--- jsdelivr.map.fastly.net ping statistics ---
11 packets transmitted, 11 received, 0% packet loss, time 10829ms
rtt min/avg/max/mdev = 65.216/66.102/67.977/0.878 ms
```

Traceroute:
```
➜  ~ tracepath cdn.jsdelivr.net
 1?: [LOCALHOST]                      pmtu 1500
 1:  OR-Prog12.c3d.local                                   0.383ms
 1:  OR-Prog12.c3d.local                                   0.278ms
 2:  router.c3d                                            0.694ms
 3:  vl1458.ar03-25.ekb.ru.mirasystem.net                  1.503ms
 4:  be3-4040.sr32-27.ekb.ru.mirasystem.net                2.019ms asymm  6
 5:  92.242.30.117                                         4.910ms
 6:  zoo-cr01-be35.ekt.mts-internet.net                    2.263ms
 7:  zoo-cr03-be3.66.ekt.mts-internet.net                  2.605ms
 8:  vish-cr01-be7.66.kaz.mts-internet.net                18.178ms
 9:  mag9-cr02-be6.16.msk.mts-internet.net                29.729ms
10:  a197-cr06-be14.77.msk.mts-internet.net               30.234ms
11:  anc-cr03-ae3.77.ff.mts-internet.net                  64.312ms asymm  8
12:  no reply
13:  no reply
14:  no reply
15:  no reply
16:  no reply
17:  no reply
18:  no reply
19:  no reply
20:  no reply
21:  no reply
22:  no reply
23:  no reply
24:  no reply
25:  no reply
26:  no reply
27:  no reply
28:  no reply
29:  no reply
30:  no reply
     Too many hops: pmtu 1500
     Resume: pmtu 1500
```

A screenshot of cdn.jsdelivr.net (redirects to jsdelivr.com)
![Screenshot_2](https://github.com/jsdelivr/jsdelivr/assets/4002358/dd5d5736-2d73-48cc-8213-ef929c5fb30b)

**Comment by MartinKolarik** [comment]
@netsuileo, in this case, I see your AV is intercepting the communication, so please try see if turning it off resolves the issue.

**Comment by Wizzerinus** [comment]
This does seem related to some kind of extensions as it works perfectly fine right now after disabling them and reenabling, but also can be a temporary resolution change - will send the IP and SSL at that time if the issue happens again.

**Comment by isage** [comment]
Having same issue. No AV, no extensions, event curl can't download file.
Ping:
```
$ ping cdn.jsdelivr.net
PING jsdelivr.map.fastly.net (151.101.1.229) 56(84) bytes of data.
64 bytes from 151.101.1.229 (151.101.1.229): icmp_seq=1 ttl=53 time=77.9 ms
64 bytes from 151.101.1.229 (151.101.1.229): icmp_seq=2 ttl=53 time=68.5 ms
64 bytes from 151.101.1.229 (151.101.1.229): icmp_seq=3 ttl=53 time=66.5 ms
64 bytes from 151.101.1.229: icmp_seq=4 ttl=53 time=75.7 ms
64 bytes from 151.101.1.229: icmp_seq=5 ttl=53 time=59.5 ms
64 bytes from 151.101.1.229: icmp_seq=6 ttl=53 time=71.6 ms
64 bytes from 151.101.1.229 (151.101.1.229): icmp_seq=7 ttl=53 time=71.6 ms
64 bytes from 151.101.1.229: icmp_seq=8 ttl=53 time=67.6 ms
^C64 bytes from 151.101.1.229: icmp_seq=9 ttl=53 time=75.5 ms

--- jsdelivr.map.fastly.net ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 9620ms
rtt min/avg/max/mdev = 59.538/70.487/77.937/5.357 ms
```
traceroute:
```
traceroute to cdn.jsdelivr.net (151.101.1.229), 30 hops max, 60 byte packets
 1  _gateway (192.168.2.1)  0.473 ms  0.595 ms  0.720 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  188.170.161.59 (188.170.161.59)  56.413 ms  56.436 ms 188.170.161.57 (188.170.161.57)  47.368 ms
 9  188.170.161.58 (188.170.161.58)  46.511 ms  47.353 ms 188.170.161.56 (188.170.161.56)  46.438 ms
10  83.169.204.104 (83.169.204.104)  77.330 ms  77.277 ms  77.446 ms
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

curl (has certificate info)
```
curl -v 'https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js' > /dev/null
* processing: https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.101.1.229:443...
* Connected to cdn.jsdelivr.net (151.101.1.229) port 443
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2837 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=jsdelivr.net
*  start date: Sep 27 18:13:13 2023 GMT
*  expire date: Oct 28 18:13:12 2024 GMT
*  subjectAltName: host "cdn.jsdelivr.net" matched cert's "*.jsdelivr.net"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA 2023 Q3
*  SSL certificate verify ok.
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [193 bytes data]
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: cdn.jsdelivr.net]
* h2 [:path: /npm/redoc@next/bundles/redoc.standalone.js]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
} [5 bytes data]
> GET /npm/redoc@next/bundles/redoc.standalone.js HTTP/2
> Host: cdn.jsdelivr.net
> User-Agent: curl/8.2.1
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0{ [5 bytes data]
< HTTP/2 200 
< access-control-allow-origin: *
< access-control-expose-headers: *
< timing-allow-origin: *
< cache-control: public, max-age=604800, s-maxage=43200
< cross-origin-resource-policy: cross-origin
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< content-type: application/javascript; charset=utf-8
< x-jsd-version: 2.0.0-rc.75
< x-jsd-version-type: version
< etag: W/"fe658-D1m2sTQlsv1NLOsB3fvbEH5eGYU"
< accept-ranges: bytes
< age: 27438
< date: Wed, 05 Jun 2024 11:55:00 GMT
< x-served-by: cache-fra-eddf8230126-FRA
< x-cache: HIT
< vary: Accept-Encoding
< alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
< content-length: 1042008
< 
{ [5 bytes data]
  4 1017k    4 50474    0     0   1989      0  0:08:43  0:00:25  0:08:18     0^C
```

loads just a few KB, then crawls to a complete stop.

**Comment by jimaek** [comment]
Do you a difference in behavior when using 
https://testingcf.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

Or

https://fastly.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js

**Comment by isage** [comment]
Almost no difference. CF endpoint also stops after 30-50Kb, but also has very slow initial reply

**Comment by isage** [comment]
Works when using another network provider, though
(tbh, given that, i'm pretty sure it's broken on our country side, but who knows)

**Comment by Wizzerinus** [comment]
Happened again now. Certificate: ![image](https://github.com/jsdelivr/jsdelivr/assets/52964431/143bfaac-1072-4bd2-aa49-66b4da592e15)

Ping response:
```
% ping cdn.jsdelivr.net
PING cdn.jsdelivr.net.cdn.cloudflare.net (104.18.186.31) 56(84) bytes of data.
```

**Comment by jimaek** [comment]
Hmm, if the same issue persists when hitting 2 completely different CDNs and networks it sounds like the issue is not related to us. Any chance something in your network, or ISP, target the *.jsdelivr.net specifically? Or even the CDNs in general?

For example here is a file with Fastly https://www.fastly.com/cimages/ocb1q9kflo7k/6bqwybV2kc70SHeH8NfdkW/0076a80922dc08b77c3401c755745ccb/image-gartner-voc_3.png

and Cloudflare
https://cf-assets.www.cloudflare.com/slt3lc6tev37/76x52jIsr93tqZq0h3HCFW/33a7575a9dc880e0a45c0f69fcbcfc8f/cc-diagram-orange-2024.png

Is it the same problem?

**Comment by isage** [comment]
No, those load fine

**Comment by jimaek** [comment]
I tried downloading the files from datacenter hosting servers in Russia and it works fine. Any chance its some kind of ISP filtering?

**Comment by isage** [comment]
Id does look like either ISP issue, or some ip-based filtering somewhere else.
Tried yet another network provider (well, server in datacenter) - loaded instantly from both cf and fastly.

**Comment by jimaek** [comment]
I checked some online databases and they all say that jsDelivr is not blacklisted in Russia.

Let me know how I can help debug this issue and maybe we can contact the ISPs to ask to remove the filtering. But without evidence they will probably ignore us.
