### ISSUE TITLE
Stats display 0 for every pkg

### ISSUE THREAD

**Issue by adamlui** [jsdelivr/jsdelivr#18588]
### Description

When visiting the stats page of any pkg e.g. https://www.jsdelivr.com/package/npm/jsdelivr-cdn-data?tab=stats , requests/bandwidth wrongly display as 0

![image](https://github.com/jsdelivr/jsdelivr/assets/10906554/d660ded0-8c9a-4115-b8cd-0bbaa64b346f)

### Affected jsDelivr links

https://www.jsdelivr.com/package/npm/jsdelivr-cdn-data?tab=stats
https://www.jsdelivr.com/package/gh/KudoAI/googlegpt?tab=stats

### Response headers

```
HTTP/1.1 200 OK
Date: Wed, 03 Jul 2024 02:50:03 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Cache-Control: public, max-age=300, must-revalidate, stale-while-revalidate=600, stale-if-error=86400
Link: <https://www.jsdelivr.com/package/npm/jsdelivr-cdn-data>; rel="canonical"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
rndr-id: 9dc0b77d-dbd4-4e3b
x-render-origin-server: Render
x-response-time: 15ms
CF-Cache-Status: MISS
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=Ptl1JVZDosjAqqDierQiTmzNlWEOevwwzbsGjnn8FRknhaYzldeDaDAhJJg6wkWMUFQaqMHB522HNyi%2BZcaDYCa7UIrWr7r32q%2FKEGNkoSBQpkQwqZZNU8fNATHPqIseBDDn"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 89d390d8ecaf96c5-SJC
alt-svc: h3=":443"; ma=86400
```

### Information

- Device OS: Windows
- Browser & Version: Firefox 127.0.2
- VPN provider: none
- Your location: California, USA

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by adamlui** [comment]
It's happening again for every pkg

![image](https://github.com/jsdelivr/jsdelivr/assets/10906554/c10122c1-ed4b-411f-a921-9345594dafc1)

**Comment by MartinKolarik** [comment]
Thanks, we'll take a look.

**Comment by MartinKolarik** [comment]
Should be fixed.
