### ISSUE TITLE
Any service degradation between 02:00-09:00 UTC on 06-Jun?

### ISSUE THREAD

**Issue by fshuman-a** [jsdelivr/jsdelivr#18582]
### Description

Hello,

I was wondering if you noticed any service degradation between 02:00 and 09:00 UTC today (06-Jun-2024)? We experienced some slowness trying to fetch packages from fastly but we cannot be 100% sure the issue is from jsDelivr (it's a bit complicated). 
Just thought I'd check if there was any general slowness experienced?

Thanks!

**Comment by jimaek** [comment]
There were no outages. But are you based in Russia? Because its possible some ISPs are doing something with the traffic https://github.com/jsdelivr/jsdelivr/issues/18581

**Comment by fshuman-a** [comment]
No, our servers are based in Dublin. Thank you!
