### ISSUE TITLE
Browsers refuse scripts with `application/node` mime type

### ISSUE THREAD

**Issue by Juice10** [jsdelivr/jsdelivr#18584]
### Description

I'm getting the following error in both safari and chrome:
```
Refused to execute script from 'https://cdn.jsdelivr.net/npm/rrweb-player@2.0.0-alpha.15/dist/rrweb-player.umd.cjs' because its MIME type ('application/node') is not executable, and strict MIME type checking is enabled.
```
When I try to add any of the following script tags:
```html
<script src="https://cdn.jsdelivr.net/npm/rrweb-player@2.0.0-alpha.15/dist/rrweb-player.umd.cjs" type="text/javascript"></script>

<script src="https://cdn.jsdelivr.net/npm/rrweb-player@2.0.0-alpha.15/dist/rrweb-player.umd.cjs" type="application/javascript"></script>

<script src="https://cdn.jsdelivr.net/npm/rrweb-player@2.0.0-alpha.15/dist/rrweb-player.umd.cjs"></script>
```

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/rrweb-player@2.0.0-alpha.15/dist/rrweb-player.umd.cjs
https://cdn.jsdelivr.net/npm/rrweb-player@2.0.0-alpha.15/dist/rrweb-player.umd.min.cjs

### Response headers

```
Accept-Ranges:
bytes
Access-Control-Allow-Origin:
*
Access-Control-Expose-Headers:
*
Age:
3973
Alt-Svc:
h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
Cache-Control:
public, max-age=31536000, s-maxage=31536000, immutable
Content-Length:
255405
Content-Type:
application/node
Cross-Origin-Resource-Policy:
cross-origin
Date:
Thu, 13 Jun 2024 19:53:56 GMT
Etag:
W/"3e5ad-yNPmH7/k50zECcU9X6Pt3dk39zc"
Timing-Allow-Origin:
*
Vary:
Accept-Encoding
X-Cache:
MISS, HIT
X-Content-Type-Options:
nosniff
X-Jsd-Version:
2.0.0-alpha.15
X-Jsd-Version-Type:
version
X-Served-By:
cache-fra-eddf8230022-FRA, cache-ams21054-AMS
```

### Information

- Device OS: MacOS 14.5
- Browser & Version: Chrome 125.0.6422.112 & Safari 17.5
- Location: Amsterdam, the Netherlands

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

I've checked a number of other issues on this repo with similar issues but all with a slight nuance difference (for example .cjs but not .umd.cjs), so I decided to open up an issue just to be sure.

**Comment by MartinKolarik** [comment]
Hi, this is correct behavior, `cjs` files are not meant to be directly executable. `.umd.cjs` doesn't really make sense as it's one or the other. If the file really is UMD, it should be just `.js` at the end.

**Comment by Juice10** [comment]
@MartinKolarik apologies for the slow response on my end, I needed to ship the new version of rrweb asap so I ended up moving away from Jsdelivr to another service but I'd like to move back as soon as possible.

> If the file really is UMD, it should be just `.js` at the end.

This is correct if the project is set to `"type": "commonjs"` but if it is set to `"type": "module"` all .js files need to use esm style modules. As far as I've been able to research UMD is compatible with commonjs so this would mean that a file extension of .umd.cjs would be valid.

> Hi, this is correct behavior, `cjs` files are not meant to be directly executable. `.umd.cjs` doesn't really make sense as it's one or the other. 

I'm not sure about this but the validation tools I've put these through seem to accept them.

**Comment by MartinKolarik** [comment]
@Juice10 if you're interested in a bit of context, please see here: https://github.com/jshttp/mime-db/pull/186#issuecomment-591008280

Now, about your problem: I'm assuming you have a package authored in ESM and want to include UMD files for browsers inside that package?

If that's the case, you may very well use a `.js` extension regardless of the `type`, as that field is applicable only for node.js and similar runtimes.

If you need that `.js` file to work in both browsers and node.js, while also having `type: "module"`, I'm afraid the only way is to have a `.js` for browsers (which ignore the `type`) and then `.cjs` for node.

**Comment by eoghanmurray** [comment]
Probably it would have been good if you could make an exception for `.umd.cjs` (as opposed to just `.cjs`)
The UMD is a chimera that can function as either commonjs or regular js so having .cjs as the extension isn't quite wrong.
