### ISSUE TITLE
player.style/sutro/+esm failed to bundle (exports field)

### ISSUE THREAD

**Issue by luwes** [jsdelivr/jsdelivr#18596]
### Description

We're running into an issue where the exports field might be causing a build error.
https://cdn.jsdelivr.net/npm/player.style/sutro/+esm

Does anyone know what might be causing this? Is the exports field completely supported, wildcards and alias?

The error that is shown:

```
/**
 * Failed to bundle using Rollup v2.79.1.
 * If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr
 */

 throw new Error('Failed to bundle using Rollup v2.79.1. If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr');
```

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/player.style/sutro/+esm
https://cdn.jsdelivr.net/npm/player.style/themes/sutro/+esm
https://cdn.jsdelivr.net/npm/player.style/themes/sutro/dist/media-theme.js/+esm

### Response headers

```
accept-ranges:
bytes
access-control-allow-origin:
*
access-control-expose-headers:
*
alt-svc:
h3=":443"; ma=86400
cache-control:
public, max-age=604800, s-maxage=43200
cf-cache-status:
REVALIDATED
cf-ray:
8c4a580f9ab153f7-ATL
content-encoding:
br
content-length:
163
content-type:
application/javascript; charset=utf-8
cross-origin-resource-policy:
cross-origin
date:
Tue, 17 Sep 2024 16:06:31 GMT
etag:
W/"191-bxIMGg15ZOChCP6DHTNrUGWVWRA"
nel:
{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
report-to:
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=9cxqzFwWyDTsUhloDSTQ29ArLlp3PyubptMnXL2BrxRbgw%2FW5KAClpjgYvR%2F4pEcQHyfwidNeeZXo5sW%2F8fWsRfUwhMy2wkyS1HnbMruU9SOq4OIV9APs3vcrVjTXzjqJGYqBdtMFXpfai0fu2E%3D"}],"group":"cf-nel","max_age":604800}
server:
cloudflare
strict-transport-security:
max-age=31536000; includeSubDomains; preload
timing-allow-origin:
*

vary:
Accept-Encoding
x-cache:
MISS, MISS
x-content-type-options:
nosniff
x-jsd-version:
0.0.8
x-jsd-version-type:
version
x-served-by:
cache-fra-eddf8230062-FRA, cache-lga21983-LGA

```

### Information

- Device OS: MacOS
- Browser & Version: Chrome 128
- VPN provider (if you use one)
- Your location (country/region) US/TX

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Hey, we do support the export field, but the file you're trying to bundle has a syntax error on line 170 - unescaped backtick inside a template string.

**Comment by luwes** [comment]
thank you for checking! oh my, I should add some tests 🤦
