### ISSUE TITLE
the jsDeliver's @unocss/reset link doesn't work

### ISSUE THREAD

**Issue by Tzyito** [jsdelivr/jsdelivr#18591]
### Description

When I use esm link it doesn't work： https://esm.run/@unocss/reset@0.61.0 (all versions)
It redirect to https://cdn.jsdelivr.net/npm/@unocss/reset@0.61.0/+esm, and response this message: "Couldn't find the requested file."

But, this link is work: https://esm.run/@unocss/core@0.61.0, they all in the same monorepo: https://github.com/unocss/unocss/tree/main/packages

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@unocss/reset@0.61.0/+esm

### Response headers

```
Couldn't find the requested file.
```

### Information

- Device OS: [e.g. iOS, Windows, MacOS]
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108]
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
https://cdn.jsdelivr.net/npm/@unocss/reset@0.65.0/package.json doesn't have a default export or `index.js`, so it is not clear which file exactly you want. You can use the individual files like this: https://cdn.jsdelivr.net/npm/@unocss/reset@0.65.0/eric-meyer.css
