### ISSUE TITLE
jsDelivr service has been suspended

### ISSUE THREAD

**Issue by adamlui** [jsdelivr/jsdelivr#18599]
### Description

When visiting jsdelivr.com or cdn.jsdelivr.net it shows service is suspended

### Affected jsDelivr links

https://www.jsdelivr.com
https://cdn.jsdelivr.net

### Response headers

N/A

### Information

- Device OS: Win10
- Browser & Version: Firefox 130.0.1
- VPN provider (if you use one) N/A
- Your location (country/region) Oakland, California, USA

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

![image](https://github.com/user-attachments/assets/7175445b-f4c9-4380-9312-693cf083ac04)

Also when displaying stats via shields.io

```
<a href="https://www.jsdelivr.com/package/npm/generate-ip?tab=stats"><img height=31 src="https://img.shields.io/jsdelivr/npm/hm/generate-ip?style=for-the-badge&logo=jsdelivr&logoColor=white&label=jsDelivr%20Hits&labelColor=464646&color=49c5d8"></a>
```

... it now shows 'inaccessible'

![image](https://github.com/user-attachments/assets/d77f495b-52da-4780-b254-6cf30c7d4212)

**Comment by raileo98** [comment]
https://archive.is/zdBR8

**Comment by raileo98** [comment]
Poland Current Time
As of 7:19 AM on Monday, September 30, 2024, the current local time in Poland is 09:19 CEST.
