### ISSUE TITLE
Server is sometimes not setting access-control header to *

### ISSUE THREAD

**Issue by fulldecent** [jsdelivr/jsdelivr#18595]
### Description

![Screenshot 2024-09-12 at 11 28 33](https://github.com/user-attachments/assets/7b21fae6-f676-45ed-91d0-4b6e650d2ea3)

### Affected jsDelivr links

.

### Response headers

^^

### Information

- Device OS: [e.g. iOS, Windows, MacOS]
- Browser & Version: [e.g. Chrome 103, Safari 8, Firefox 108]
- VPN provider (if you use one)
- Your location (country/region)

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

details coming from ahmed

**Comment by jimaek** [comment]
Please send more information like the URL you're testing and web page where we can see the issue

**Comment by fulldecent** [comment]
@Raza403 can you please add details here

**Comment by Raza403** [comment]
You can see this on https://acls.net.
This happens when the URL gets redirected form https://acls.net to https://www.acls.net.

**Comment by fulldecent** [comment]
Hi @Raza403 we need the reproducible curl line, please. 

Please use that Network > Copy as cUTL to share that

**Comment by Raza403** [comment]
Here it is
```
curl 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' \
  -H 'accept: text/css,*/*;q=0.1' \
  -H 'accept-language: en-US,en;q=0.9,ur-PK;q=0.8,ur;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'origin: https://www.acls.net' \
  -H 'pragma: no-cache' \
  -H 'priority: u=0' \
  -H 'referer: https://www.acls.net/' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: style' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' -I
```

**Comment by MartinKolarik** [comment]
Hey, are you still seeing this? I can't reproduce it myself, and the headers from the screenshot don't entirely match our typical responses (some seem missing and some are there which we don't send) so I'm not 100% sure it was a request to our domain.

**Comment by fulldecent** [comment]
Thank you @Raza403 cannot reproduce, let's close this
