### ISSUE TITLE
Why curl and browser get different version for a same js link?

### ISSUE THREAD

**Issue by maggch97** [jsdelivr/jsdelivr#18590]
### Description

![image](https://github.com/user-attachments/assets/d338d999-dd0c-4676-b1ca-eb431221b3b3)

### Affected jsDelivr links

https://fastly.jsdelivr.net/gh/VideoTogether/VideoTogether@latest/release/extension.website.user.js

### Response headers

![image](https://github.com/user-attachments/assets/26bd9ae0-4671-468d-80be-85a59b9e5221)
![image](https://github.com/user-attachments/assets/5702d5e0-5c9c-4064-8f5c-5edc4b5bc3db)

### Information

Location: China
VPN: shadowsocks, Azure Singapore

I observed this problem in all browsers include Safari in the same network.
1. Are requests from curl and browser processed by different cdn server?
2. Only the situation VPN enabled + browser has this problem. I confirmed browser cache is disabled. The problem has not been solved after ten hours when I first time observed it.
I saw the x-cache field is different, "MISS, HIT" and "HIT, HIT", but I do not know what's that means

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
In this case the difference was likely because of `Vary: Accept-Encoding`. curl doesn't send that header but browsers do, so it results in different cache entries being used (each with its own expiration).
