### ISSUE TITLE
The MediaPipe Tasks Vision 0.10.16 package doesn´t have the wasm folder

### ISSUE THREAD

**Issue by olalinv** [jsdelivr/jsdelivr#18598]
### Description

When loading the link https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/ you can see that there is no ‘wasm’ folder. All previous versions of this package include it, even the RC version (0.10.16-rc.20240925).

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.16/wasm/vision_wasm_internal.js

### Response headers

Couldn't find the requested file /wasm/vision_wasm_internal.js in @mediapipe/tasks-vision.

```
accept-ranges: bytes
access-control-allow-origin:*
access-control-expose-headers:*
age:3330
alt-svc:h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
cache-control:public, max-age=86400, s-maxage=86400
content-encoding:br
content-length:82
content-type:text/plain; charset=utf-8
cross-origin-resource-policy:cross-origin
date:Thu, 26 Sep 2024 12:27:20 GMT
etag:W/"5a-fWoCIwEeaoIyLeMNOk44XCfoDOQ"
strict-transport-security:max-age=31536000; includeSubDomains; preload
timing-allow-origin:*
vary:Accept-Encoding
x-cache:MISS, HIT
x-content-type-options:nosniff
x-served-by:cache-fra-eddf8230076-FRA, cache-mad2200112-MAD
```

### Information

- Device OS: MacOS Sequoia 15.0
- Browser & Version: Chrome 129
- Location: Spain

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Hey @olalinv, we have no control over the package files, and simply serve what is published on npm. Please report this to the package author.

**Comment by olalinv** [comment]
OK, thank you @MartinKolarik
