### ISSUE TITLE
Inform location (city) of the sensor

### ISSUE THREAD

**Issue by arraisfilho** [jsdelivr/jsdelivr#18592]
### Is your feature request related to a problem? Please describe.

I'm using some Globalping sensors via docker, the geolocation measured does not match reality.

### Describe the solution you would like.

Would it be possible to have parameters where we can inform the location? 
Are they by coordinates or the name of the city?

### Requisites

- [x] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Can you please report this issue here with some extra data? https://github.com/jsdelivr/globalping/issues/268

Additionally we will soon launch the user dashboard that will allow you to edit the location
