### ISSUE TITLE
Cannot purge files in a npm package

### ISSUE THREAD

**Issue by piquark6046** [jsdelivr/jsdelivr#18605]
### Description

Cannot purge files in a npm package via the purge API

### Affected jsDelivr links

https://cdn.jsdelivr.net/npm/@list-kr/tinyshield@latest/dist/tinyShield.user.js

### Response headers

```
HTTP/2 200 
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=604800, s-maxage=43200
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
content-type: application/javascript; charset=utf-8
x-jsd-version: 1.3.11
x-jsd-version-type: version
etag: W/"36ef-yGJE0TnIjwZKxYTYmxpSDQg4Qq0"
content-encoding: br
accept-ranges: bytes
date: Fri, 06 Dec 2024 02:18:03 GMT
age: 425
x-served-by: cache-fra-eddf8230024-FRA, cache-nrt-rjtf7700085-NRT
x-cache: HIT, HIT
vary: Accept-Encoding
alt-svc: h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400
content-length: 2408
X-Firefox-Spdy: h2
```

### Information

- Device OS: Ubuntu 24.10
- Browser & Version: Firefox 132.0b5
- VPN provider (if you use one): Proton VPN Korea server
- Your location (country/region): South Korea

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

https://github.com/List-KR/tinyShield/actions/runs/12191606187/job/34010794815
https://github.com/List-KR/tinyShield/actions/runs/12191673910/job/34010985139

**Comment by MartinKolarik** [comment]
Based on your CI logs, you're calling the API with wrong URL:
![image](https://github.com/user-attachments/assets/9ddc975d-1b19-44fa-9e2e-9b7eb2915449)

**Comment by piquark6046** [comment]
Oh.. My bad. Thanks.

**Comment by piquark6046** [comment]
https://github.com/List-KR/tinyShield/actions/runs/12226571386/job/34102046564
Hmm... It looks same.
