### ISSUE TITLE
Support github.io website

### ISSUE THREAD

**Issue by chenxizhang** [jsdelivr/jsdelivr#18600]
### Is your feature request related to a problem? Please describe.

We are using Github pages to generate the docs for our open-source projects, and the default output is a website which is hosted under "github.io", but in China, this domain has been blocked. So people in China can't access the website, unfortunately 

### Describe the solution you would like.

I want to have a solution to leverage jsdelivr service for a specific github.io website, thanks

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by MartinKolarik** [comment]
Supporting GitHub pages isn't something we can do in the foreseeable future, and we wouldn't want to encourage using jsDelivr to bypass Chinese blocking either - doing so just increases the risk of jsDelivr getting blocked as well.
