### ISSUE TITLE
https://jsdelivr.net won't load + stats wrongly show 0

### ISSUE THREAD

**Issue by adamlui** [jsdelivr/jsdelivr#18602]
### Description

https://jsdelivr.net/ won't load

![image](https://github.com/user-attachments/assets/a35aedb0-8597-4074-91da-5c12c36e515e)

Oddly https://www.jsdelivr.com/ loads

Also https://www.jsdelivr.com/statistics + any project stats page wrongly show 0 for all stats

![image](https://github.com/user-attachments/assets/1fa742af-21cd-4c6a-b6f1-b1a955c7c15f)
![image](https://github.com/user-attachments/assets/aa480d11-62d5-42dc-b8a5-19d6a9637bb4)

Also shields.io JSD shields wrongly show 0 now

```
https://img.shields.io/jsdelivr/gh/hm/adamlui/chatgpt-infinity?style=for-the-badge&logo=jsdelivr&logoColor=white&label=jsDelivr%20Requests&labelColor=464646&color=2bbbd8
```

![image](https://github.com/user-attachments/assets/0f7936a7-f9b7-434c-9bcf-bc310e259830)

### Affected jsDelivr links

- https://jsdelivr.net/
- https://www.jsdelivr.com/statistics
- https://www.jsdelivr.com/package/gh/adamlui/chatgpt-infinity?tab=stats
- https://img.shields.io/jsdelivr/gh/hm/adamlui/chatgpt-infinity?style=for-the-badge&logo=jsdelivr&logoColor=white&label=jsDelivr%20Requests&labelColor=464646&color=2bbbd8

### Response headers

n/a

### Information

- Device OS: Windows
- Browser & Version: Firefox 131
- VPN provider N/A
- Your location Oakland, California, USA

### Requisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/jsdelivr/jsdelivr) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by jimaek** [comment]
Hello, jsDelivr.net is not a functioning hostname and it's not expected to load. But we're looking into the missing stats.

Thank you
