### ISSUE TITLE
Help packaging my project

### ISSUE THREAD

**Issue by paddymul** [jsdelivr/jsdelivr#18601]
### Description

I don't think this is a bug with jsdelivr, but, I don't know how to use your project given the documentation.  The core bug is probably in my webpack or package.json configuration.  I'm here asking for help.

## Core problem

I have a project that I can't load into codepen from jsdelivr, and it's not obvious what is failing.

Here is a codepen pointing to an NPM built off my branch ([chore/fix-codepen](https://github.com/paddymul/buckaroo/pull/294))
https://codepen.io/paddymul/pen/VwoPOzW

This gets js console errors of 
```
GET
https://unpkg.com/react-day-picker@9.1.3/dist/style.css
NS_ERROR_CORRUPTED_CONTENT

The resource from “https://unpkg.com/react-day-picker@9.1.3/dist/style.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
[VwoPOzW](https://cdpn.io/paddymul/fullpage/VwoPOzW?nocache=true&view=)
Uncaught TypeError: d is null
    <anonymous> Transition.js:607
[Transition.js:607:19](https://cdn.jsdelivr.net/npm/react-transition-group@2.9.0/Transition.js)
```
That codepen makes a call to https://cdn.jsdelivr.net/npm/buckaroo@0.7.5-test4/+esm
That page is integrated into docs (from main) here. https://buckaroo-data.readthedocs.io/en/latest/examples/#/DFViewerEx_large

## What could be clearer
* I don't know when to use `+esm` in jsdelivr urls. 
* I don't know what the preferred output target is for jsdelivr `amd`, `esm`, `umd`...
* It is unclear how to deal with packaged css for projects
* It is unclear how federated modules are interacting with the built package.

### About my project
Buckaroo is a jupyter lab extension that bundles js and python to extend the jupyter lab environment so that it has a better table experience.  The webpack config is fairly complex using federated modules.  My understanding is that the entire js bundle needs to be packaged into a single file that is put into the python wheel.  This works.

### What I'm trying to do

I want to have a live edittable code gallery of the JS components of my project.  This makes it easier for new develoeprs to see and play with the JS part of the project without setting up an entire repo.  I have based this part of Buckaroo on https://mmomtchev.github.io/react-edit-list/#/simple with live codepen links that work. react-edit-list is calling to skypack at https://cdn.skypack.dev/react-edit-list
.  My code is based on react edit list and my widget js build.

react-edit-list used skypack and works.

My package.json is put together from react-edit-list, and [ipydatagrid](https://github.com/jupyter-widgets/ipydatagrid)

**Comment by MartinKolarik** [comment]
Hi, the error you posted mentions unpkg, which is an unrelated service. It seems you're trying to load a file from there which doesn't exist. 

Still, to answer your questions:
 - loading files without `/esm+` gives you exactly what the package author published,
 - adding `/+esm` performs additional bundling of ES modules, which may be needed if the published files are not bundled,
 - for non-esm mode, the output target really depends only on how you want to load the files; for esm mode, it should be esm or cjs
 - css files are supported automatically in esm mode; in non-esm mode you add them manually via `link`
