### ISSUE TITLE
angular.gantt doesn't update

### ISSUE THREAD

**Issue by Toilal** [jsdelivr/jsdelivr#2569]
Since i use [release-it](https://github.com/webpro/release-it) to automate release process, [angular.gantt](https://github.com/jsdelivr/jsdelivr/blob/master/files/angular.gantt/update.json) doesn't get updated in jsDelivr.

Before, releases were created manually on github in releases page, and it was automatically added in jsDelivr. Now, releases are created through [release-it](https://github.com/webpro/release-it) and won't appear in jsDelivr. 

Those release are standard git tags created locally and then pushed to github. Is it the cause of the problem ?

**Comment by Toilal** [comment]
I've just release a new version of angular-gantt library, but when using latest, it doesn't not pick the latest version.

http://cdn.jsdelivr.net/angular.gantt/latest/angular-gantt.min.js => This point to 1.2.1.
http://cdn.jsdelivr.net/angular.gantt/1.2.3/angular-gantt.min.js => But 1.2.3 is released and available.

**Comment by jimaek** [comment]
That is correct, we cache /latest/ for 7 days to ensure there is a performance benefit.
I purged the file and it should be showing the latest version now.

But we also allow project owners to purge their own cache if they want to. This feature is not public to avoid abuse. If you email me I can give you the instructions if you want.
