### ISSUE TITLE
WordPress proxy

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr#2632]
A new feature that I always wanted to have is finally here.
We can now automatically proxy any file from the WordPress repository. All you have to do is specify the name and version.

For example:
`http://cdn.jsdelivr.net/wp/1000eb/tags/3.3.1/javascripts/admin.js`
`http://cdn.jsdelivr.net/wp/wp-slimstat/tags/3.8.5/wp-slimstat.js`

This feature can simplify the integration of jsDelivr for all developers. Now its ridiculously easy to add a CDN option to any plugin.

It works by proxying http://plugins.svn.wordpress.org/ and adding the correct content-type headers. So WordPress takes care of the security audit and adding new versions.

The proxy for now allows only css,js and font files to be proxied.
Please test it out and let me know what you think. Are there any bugs? Any features missing?

@getusedtoit As a WP dev what do you think?

**Comment by getusedtoit** [comment]
I just released version 3.9.2 to fix a bug discovered by one of our users, and everything worked out perfectly right away. This is really a killer app!

**Comment by jimaek** [comment]
@getusedtoit Awesome! Unfortunately very few devs will know about this because we suck at promoting new features :p

**Comment by as-com** [comment]
I know! Let's just put a huge pop up on jsdelivr.com! There's a 100% chance if people noticing! There's also a 100% chance of annoying users! :-P

**Comment by guix77** [comment]
wow I just had that idea looking at my sites PageSpeed audits. Glad you did it ! Keep it up :)

**Comment by getusedtoit** [comment]
Hi guys, I have a quick question about this functionality. I see that the following URL is working as expected:

http://cdn.jsdelivr.net/wp/wp-slimstat/trunk/wp-slimstat.js

Is it safe to assume that it will be available in the foreseeable future just like the "tags" version? I usually push the latest stable both as a tag and in trunk (since I use github for development), and by using this trick, I wouldn't have to worry about including the version number in the URL anymore.

**Comment by pnommensen** [comment]
Yeah, should work great :) 

--
Patrick Nommensen
http://nginx.com

**Comment by getusedtoit** [comment]
:+1:

**Comment by as-com** [comment]
There is an issue with caching, though. I believe the CDNs, origin, and browsers cache a copy of it for an indefinite amount of time. I think it is necessary to include the version number in the tag version for cache-busting.

**Comment by getusedtoit** [comment]
Good point!

**Comment by jimaek** [comment]
Yes, dont use trunk because it will always show older versions. You can use some wordpress variable with the plugin's version to automate the process.

**Comment by hubdotcom** [comment]
Amazing feature, well done!

**Comment by getusedtoit** [comment]
Hi guys,

we pushed an update to our plugin, however the CDN is serving the old file for some reason:

https://plugins.trac.wordpress.org/browser/wp-slimstat/trunk/wp-slimstat.min.js

versus

http://cdn.jsdelivr.net/wp/wp-slimstat/trunk/wp-slimstat.min.js

Could you please look into this?

**Comment by jimaek** [comment]
Dont use the trunk, use the tags. Trunk gets cached and needs purging and its not recommended to use it. This is much better:
http://cdn.jsdelivr.net/wp/wp-slimstat/tags/4.0.2/wp-slimstat.min.js

You can use a wp function to automatically get the plugin's version and insert it into URLs, fully automated.

P.S. I purged the trunk as well.

**Comment by getusedtoit** [comment]
Hi jimaek, 

thank you for your prompt response. The reason why I'm using trunk is that many of our users use caching plugins for WordPress. Which means that the source code of the page is "frozen" for days. When we release a new update, the URL in the cached version of the page will still point to the previous one, thus breaking the functionality for all those users. We've tried to warn our users by displaying messages that invite them to clear their WP cache, but many times people end up submitting a support request anyway, lamenting that the tracker is not working. Our goal was to minimize those requests to our support team, by finding a way to keep the URL always the same. 

What solution could be implemented to address this issue? (other than telling our users to clear their cache every time they upgrade).

Thank you again!

**Comment by jimaek** [comment]
Have you tried something like this http://wordpress.stackexchange.com/questions/7112/w3-total-cache-cache-refresh-programmatically ?

When you update plugins W3 Total Cache will notify the user as well that he needs to clear his cache.

Anyway if none of this solutions work then shoot me an email and I will give you access to our purging API. You will be able to use trunk and purge when you release a new version

**Comment by getusedtoit** [comment]
Interesting link, thank you for sharing. Unfortunately not everybody uses W3. Some of our users use SuperCache, others use HyperCache, etc. I wish it was that easy :( How much work would it be to have trunk purged let's say once every 2 hours. If that doesn't work, I'm okay with purging it through the API. Let me know what works best for you :)

**Comment by jimaek** [comment]
You can set a cronjob on your server and ping our API to purge the cache whenever you want. But if you purge every 2 hours then the CDN will get much slower because every 2 hours all 70 nodes will need to re-cache the file.

**Comment by getusedtoit** [comment]
You're right, and I don't want that :) I'll just do it manually whenever I release an update. That works for me. I'll send you a private message. Again, thank you so much for this service and for being on top of things!

**Comment by jimaek** [comment]
np :)

**Comment by as-com** [comment]
I think most caching plugins automatically clear the page cache when a
plugin is installed or updated. It's possible that people disabled that
functionality or they are simply using stupid caching plugins.

Also, there is the possibility that some lazy/ignorant people don't update
your plugin and there are bugs caused by incompatible JS.

**Comment by hubdotcom** [comment]
Setting as trunk would cause some issues with non updated installs. Let's say you introduce new code in wp-slimstat.min.js that is not backwards compatible - it will break any installs running on previous versions of the plugin (since the plugin always requests the latest js file).

**Comment by getusedtoit** [comment]
@hubdotcom Good point. Major changes to the tracker are quite rare, I must say. Most of the time, we tweak the code to fix bugs in the JS code, which means that even people who don't update Slimstat, will get the new tracking script automatically. And of course, those who have their own rationale for not wanting to upgrade the plugin, can always turn the CDN setting off, and serve the script from their website ;)

**Comment by hubdotcom** [comment]
Fair enough - just using this for the tracking script makes perfect sense!

**Comment by jimaek** [comment]
Documented https://github.com/jsdelivr/jsdelivr/blob/master/README.md#wordpress
