### ISSUE TITLE
Letter case problem in links from integration button

### ISSUE THREAD

**Issue by elixom** [jsdelivr/jsdelivr#2885]
I have only had this problem with one link so I do not know if it affects any others.
With the jquery.minicolors item, sometimes the filename in contains capital when you click the integration button. If you copy this code and use it it does not work. however if you change the name to lowercase it works.

e.g. this was copied from the integration display

    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.minicolors/2.1.2/jquery.miniColors.css">
    <script src="//cdn.jsdelivr.net/jquery.minicolors/2.1.2/jquery.miniColors.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.minicolors/2.1.2/jquery.miniColors.min.js"></script>

note the capital "C" in miniColors, change it to 

    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.minicolors/2.1.2/jquery.minicolors.css">
    <script src="//cdn.jsdelivr.net/jquery.minicolors/2.1.2/jquery.minicolors.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.minicolors/2.1.2/jquery.minicolors.min.js"></script>

and it works fine.

**Comment by jimaek** [comment]
We are working on a new website already, this bug should be fixed over there.
https://github.com/jsdelivr/beta.jsdelivr.com
