### ISSUE TITLE
What files from jVectorMap would be appropriate?

### ISSUE THREAD

**Issue by lewisgoddard** [jsdelivr/jsdelivr#2964]
I am looking to add [bjornd/jvectormap](https://github.com/bjornd/jvectormap) to jsDelivr.

We will need `jquery-jvectormap.css` and `jquery-jvectormap.js`.

There are also several files in `tests/assets/jquery-jvectormap-***.js`.
Should they be included as well?

There isn't a minified version, is that a major issue?

**Comment by jimaek** [comment]
jquery-jvectormap.css and jquery-jvectormap.js. seem to be enough. But yes that fact that they are not minified is bad. Maybe ask the author to create a `dist/` folder with production files?
