### ISSUE TITLE
Rupyainr - Indian currency symbol for website

### ISSUE THREAD

**Issue by VinuRaj** [jsdelivr/jsdelivr#3217]
Indian currency symbol (Rupee) in web font along with easy Javascript implementation for websites.
Please view the latest comment on the previous issue #900
Please validate the same.

**Comment by jimaek** [comment]
I dont see any changes in the commit, the issue that megawac pointed out is still there

**Comment by VinuRaj** [comment]
I have added a website detailing about the project out here - http://rupyainr.com/
This website is now included with the codes.

**Comment by jimaek** [comment]
Can you send a new PR with all the corrections then?

**Comment by VinuRaj** [comment]
Done,  have created a new pull request with the above details.
