### ISSUE TITLE
lodash 3.0.1

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#3282]
Can someone please upload [v3.0.1](https://lodash.com/) please?
I would, but I use website only for jsDelivr, so I'd end up with 4 commits....

**Comment by tomByrer** [comment]
Now 3.1.0...

**Comment by jimaek** [comment]
I believe this was fixed?

**Comment by tomByrer** [comment]
Seems 3.0.1 was never uploaded.  But newer versions are, & no one else complained, so I guess forget it 😄
