### ISSUE TITLE
Easier way to add projects

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr#347]
I hate the idea of hosting all files in Github but I don't see any other alternative. 

Does anyone have any ideas on how improve this system? Ideally we want to host in Github only configs/meta data required for everything to function and not the actual files.

**Comment by passcod** [comment]
A note that if people want to clone the repo locally without downloading all the history, `git clone --depth=1 ...` works quite well.

**Comment by hubdotcom** [comment]
Hi guys, I completely agree with @jimaek that the process must be at least as easy as currently for users to contribute. I've made 10 commits without cloning the repo locally and I would assume most people, especially those with other priorities, would prefer to do the same. I've been racking my brains too on how this could be done.

Currently there are 2 methods of committing:
1. Use the github web interface, this is fairly easy although is limited by the number of files
2. Use git CLI - higher resource use but more powerful

I think the optimal solution would be if github allowed multiple files per commit. It doesn't look like that's going to happen anytime soon so let's try to get close to that seamless experience.

Below are some suggestions. 

A) Custom web interface:
1. User goes to contribute.jsdelivr.com + authenticates with github
2. User browses using a file browser (e.g. http://demo.tutorialzine.com/2014/09/cute-file-browser-jquery-ajax-php/ OR a github styled browser)
3. User creates folder, uploads files and clicks a COMMIT button to save all their changes (with a preview window to confirm)
4. This gets pushed to a staging repo and a PR is automatically opened

B) Enhanced jsDelivr interface:
1. User clicks the update button on jsdelivr + authenticates with github
2. User fills in a form with the version number and attaches the updated files
3. This gets pushed to a staging repo and a PR is automatically opened

C) The crazy solution:
Utilise the github API to allow multiple file uploads from the user themselves. (More info: http://www.levibotelho.com/development/commit-a-file-with-the-github-api/)

Essentially, once the user is authenticated, we actually:
- fork the repo
- commit the files they added
- create a pull request

Mirroring the current process but allowing the user to submit multiple files in an easy way in a single commit.

**Comment by passcod** [comment]
I'd note that the git CLI way can be made less resource-intensive/faster by
recommending shallow cloning... But that of course does nothing towards
people's reluctance or lack of experience (or convenience) with the CLI.

B) is probably the best UX option. Accompanied with some kind of API so
people can a) build their own tools and/or b) integrate with their release
process, would be ace.

**Comment by coderaiser** [comment]
As a temporary solution [clone a git repositorys sub directory](http://stackoverflow.com/questions/600079/is-there-any-way-to-clone-a-git-repositorys-sub-directory-only) with help of `sparseCheckout`  could be used this way:
```sh
git config core.sparseCheckout true #once
git init <repo>
cd <repo>
git remote add origin <url>
echo "files/ace/" >> .git/info/sparse-checkout
git pull origin master
```

**Comment by tomByrer** [comment]
I've never tried that @coderaiser; perhaps some day.

Now I just use the [web interface](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md#web-interface-recommended) for auto-updates. Made a Node-CLI tool to help automatically half-fill the `package.json` & `info.ini` for me; might release what I have soonish.

**Comment by finom** [comment]
Agreed with custom web interface.
1. Fork
2. Change needed files via web-based filemanager and Github API
3. Pull request

**Comment by jimaek** [comment]
We already modified our instructions to encourage the usage of GIthub's Web interface.
No plans for custom web interface yet, not an easy task.

**Comment by finom** [comment]
@jimaek another idea: you can split up files by the first letter and add them to corresponding folders.
```
a/
  alib1/
  alib2/
```
... etc

**Comment by tomByrer** [comment]
It would be some work; I don't want to create another host service, & JS-Git will need testing.   I have an alpha of a CLI-node helper, which will start as output that requires some manual editing.
Changing IDE, so might be a few days.

**Comment by megawac** [comment]
@tombryer whats the motivation of supplanting the one I made? ^^
https://github.com/megawac/cdn-it

**Comment by tomByrer** [comment]
I started mine before you released yours.  Yours is more mature, but since I'm using node, it will be easier to translate into web interface.

Plus since I already started it, might as well finish it; I need portfolio fillers.

**Comment by altanai** [comment]
hello , as i dont have write permissions on this github created a fork for me  which is practically not the point of adding a folder and info.ini . Any thing I am missing ?

**Comment by megawac** [comment]
Hi @altanai, that is the proper workflow. You want to 1) create a fork 2) create a branch 3) create your files 4) submit a pull request to this project

**Comment by jimaek** [comment]
It took us 3 years but we finally did it https://github.com/jsdelivr/jsdelivr#usage
