### ISSUE TITLE
[Slimstat] Vary: Accept-Encoding header

### ISSUE THREAD

**Issue by B-iggy** [jsdelivr/jsdelivr#3537]
camu send me here.
Can you add this type of header to your cdn? 
When I'm testing my page on tools.pingdom.com I get:
The following publicly cacheable, compressible resources should have a "Vary: Accept-Encoding" header:

http://cdn.jsdelivr.net/wp/wp-slimstat/trunk/wp-slimstat.min.js
Or do you have a reason for not to do this?

**Comment by jimaek** [comment]
Its already there:
```
curl -I http://cdn.jsdelivr.net/wp/wp-slimstat/trunk/wp-slimstat.min.js
HTTP/1.1 200 OK
Server: keycdn-engine
Date: Fri, 20 Feb 2015 14:14:27 GMT
Content-Type: application/javascript; charset=utf-8
Content-Length: 11217
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Thu, 19 Feb 2015 00:40:03 GMT
Expires: Fri, 19 Feb 2016 01:25:41 GMT
Cache-Control: public, max-age=31536000
Access-Control-Allow-Origin: *
Timing-Allow-Origin: *
X-Cache: HIT
X-Edge-Location: defr
Accept-Ranges: bytes
```

**Comment by B-iggy** [comment]
Wow, you are quick :)
Any idea why this message shows up?
Wrong apache config, php config, .htaccess config?

**Comment by jimaek** [comment]
I found the problem. We were sending 2 vary headers, while browsers will ignore the second and will simply accept it, tools.pingdom couldn't parse them and thought there were none.

I fixed the issue and once the cache invalidates tools.pingdom will start showing the correct value. In the meantime real users always had the vary header and will continue to have it

**Comment by B-iggy** [comment]
from 91/100 to 96/100 Points now! You are smart! Thank you! :)

**Comment by jimaek** [comment]
np :) Thanks for reporting the problem
