### ISSUE TITLE
Foundation JS not providing minified version

### ISSUE THREAD

**Issue by chauncey-garrett** [jsdelivr/jsdelivr#3590]
`//cdn.jsdelivr.net/foundation/5.5/js/foundation.min.js` does not give the minified version of the JS file.

**Comment by chauncey-garrett** [comment]
Looks like there's already an issue open on the topic:

https://github.com/zurb/foundation/issues/6073

**Comment by jimaek** [comment]
I believe that we can close this issue then. Once they fix it we will use the correct files automatically. Basically its up to Zurb right now

**Comment by chauncey-garrett** [comment]
Agreed. Thanks!
