### ISSUE TITLE
error in api

### ISSUE THREAD

**Issue by HedCET** [jsdelivr/jsdelivr#3687]
i can't get latest version 1.10.3, 1.10.4 of semantic-ui in http://api.jsdelivr.com/v1/jsdelivr/libraries

```  {
    "name": "semantic-ui",
    "_id": "-J4lJlM8vx2",
    "created": "2015-03-01T19:00:12.580Z",
    "versions": [
      "1.10.2",
      "1.10.0",
      "1.9.3",
      "1.9.2",
      "1.9.1",``

**Comment by jimaek** [comment]
@UnbounDev Can you please check it out? I restarted the sync process and cleared the CDN cache but I cant see the latest versions. Looks like a bug

@HedCET Thanks for reporting

**Comment by HedCET** [comment]
@jimaek i found from this tool - https://github.com/HedCET/cdnify it's working based on ur API

**Comment by jimaek** [comment]
It looks awesome! Thanks for using our API to build something useful :)

**Comment by jimaek** [comment]
hey, looks like the API updated http://api.jsdelivr.com/v1/jsdelivr/libraries/semantic-ui
We will work on it to make sure it updates a lot faster next time

**Comment by UnbounDev** [comment]
@HedCET Thanks for the report! I've created an [issue](https://github.com/jsdelivr/api-sync/issues/20) on the [api-sync](https://github.com/jsdelivr/api-sync) repo and will look into it shortly.
