### ISSUE TITLE
Clappr 'latest' directory not pointing to the correct resource

### ISSUE THREAD

**Issue by lucasmundim** [jsdelivr/jsdelivr#3809]
Even though clappr already have the version 0.0.117 (https://github.com/jsdelivr/jsdelivr/tree/master/files/clappr), the "latest" directory still links to the version 0.0.91 on http://cdn.jsdelivr.net/clappr/latest/clappr.min.js (search for "version:")

The same happens to http://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js that return the version 0.0.3 and already have 0.0.5 on https://github.com/jsdelivr/jsdelivr/tree/master/files/clappr.level-selector

**Comment by jimaek** [comment]
This is expected behavior. For performance reasons we cache the `/latest/` files for 1 week. I believe its a good balance between speed and having the latest version.

**Comment by lucasmundim** [comment]
Is there a way to force the purge of this cache? Because this can be problematic for users linking to the "latest" if a broken version is cached.

**Comment by jimaek** [comment]
The file should be purged now.
As I understand this is a rare occurrence, correct? (a broken version that needs to be purged asap)

**Comment by lucasmundim** [comment]
Exactly, it's not the case this time, but it can be someday, we all make mistakes. I believe that having a way to purge those files can be useful to help people that likes to live on-the-edge. Or Maybe just adding a warning in readme file should be enough.

**Comment by jimaek** [comment]
We do have a way to purge the files, but to avoid abuse we dont make it public.
For now only 2 big companies know how to do it. 
If you need this functionality then send me an email, otherwise in the future you can create a new ticket asking to purge a URL and I will do it asap.

**Comment by lucasmundim** [comment]
Ok, thanks.
