### ISSUE TITLE
clappr/latest not pointing to the latest version

### ISSUE THREAD

**Issue by lucasmundim** [jsdelivr/jsdelivr#4001]
When I hit http://cdn.jsdelivr.net/clappr/latest/clappr.min.js it returns the 0.0.107 version, although the latest version currently is 0.0.114.

I know that it caches the latest entrypoint for about a week, but version 0.0.108 was released 11 days ago.

**Comment by jimaek** [comment]
Can you paste the HTTP headers here? I hit CloudFlare and I see 0.0.114

**Comment by lucasmundim** [comment]
![screen shot 2015-03-25 at 19 04 31](https://cloud.githubusercontent.com/assets/32864/6836556/d922a880-d321-11e4-804b-c9c4bdb47f13.png)

**Comment by pnommensen** [comment]
I am seeing the correct version, ref: https://www.dropbox.com/s/m5swsphso6pv7cs/Screenshot%202015-03-25%2015.03.39.png <https://www.dropbox.com/s/m5swsphso6pv7cs/Screenshot%202015-03-25%2015.03.39.png>

Could you share output of curl -I http://cdn.jsdelivr.net/clappr/latest/clappr.min.js <http://cdn.jsdelivr.net/clappr/latest/clappr.min.js> 

--
Patrick Nommensen
http://nginx.com

**Comment by lucasmundim** [comment]
$ curl -I http://cdn.jsdelivr.net/clappr/latest/clappr.min.js
HTTP/1.1 200 OK
Date: Wed, 25 Mar 2015 22:06:41 GMT
Content-Type: application/x-javascript; charset=utf-8
Content-Length: 203793
Connection: keep-alive
X-Version: 0.0.107
Cache-Control: public, max-age=604800
Last-Modified: Mon, 13 Jan 2014 18:17:35 GMT
Access-Control-Allow-Origin: *
Vary: Accept-Encoding
CF-Cache-Status: HIT
Server: cloudflare-nginx
CF-RAY: 1ccdeca5a5d207c1-MIA

**Comment by jimaek** [comment]
Can you please try again? It should be fixed. Also please let me know if this problem happens again (cache not expiring after 7 days for latest)

**Comment by lucasmundim** [comment]
Thank you, worked now. I let you know if it happens again.

curl -I http://cdn.jsdelivr.net/clappr/latest/clappr.min.js
HTTP/1.1 200 OK
Date: Wed, 25 Mar 2015 22:15:18 GMT
Content-Type: application/x-javascript; charset=utf-8
Content-Length: 192629
Connection: keep-alive
X-Version: 0.0.114
Cache-Control: public, max-age=604800
Last-Modified: Mon, 13 Jan 2014 18:17:35 GMT
Access-Control-Allow-Origin: *
Vary: Accept-Encoding
CF-Cache-Status: HIT
Server: cloudflare-nginx
CF-RAY: 1ccdf9458a6218ad-GRU

**Comment by lucasmundim** [comment]
The same problem is affecting clappr.level-selector too.

curl -I http://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js
HTTP/1.1 200 OK
Date: Wed, 25 Mar 2015 22:20:48 GMT
Content-Type: application/x-javascript; charset=utf-8
Content-Length: 14598
Connection: keep-alive
X-Version: 0.0.5
Cache-Control: public, max-age=604800
Last-Modified: Mon, 13 Jan 2014 18:17:35 GMT
Access-Control-Allow-Origin: *
Vary: Accept-Encoding
CF-Cache-Status: HIT
Server: cloudflare-nginx
CF-RAY: 1cce01517efe1018-GRU

**Comment by jimaek** [comment]
It should be ok now.
The permament fix will affect only newly cached files.

**Comment by lucasmundim** [comment]
Ok, thanks!
