### ISSUE TITLE
Change Github reference for Ramda 

### ISSUE THREAD

**Issue by CrossEye** [jsdelivr/jsdelivr#4033]
I'm not sure if this is the correct way to go about this, but I could find nothing in the actual repo that would let me set this.

On the Ramda page of JSDelivr (http://www.jsdelivr.com/#!ramda) the GitHub link points to the original development site for the project, when it was part of my personal account.  It's moved to a group account now, and I was hoping that it would be easy to change that link to https://github.com/ramda/ramda.  Is that something I can control myself, or is an issue like this the right way to do so?

Thanks.

**Comment by jimaek** [comment]
Here is the file that contains the data, you can send a PR yourself if you want (use the web interface to do it faster)
https://github.com/jsdelivr/jsdelivr/blob/master/files/ramda/info.ini

**Comment by CrossEye** [comment]
Thank you.  I don't know why I don't have that in my local branch...  I'll update right now.
