### ISSUE TITLE
jsDelivr is Not serving woff2 (font) files properly

### ISSUE THREAD

**Issue by TheTannerRyan** [jsdelivr/jsdelivr#4082]
When a woff2 font file is loaded for the first time, it takes upwards of 14 seconds. Once cached by the browser, it loads instantly. Clear the local cache, it takes forever again. You can see for yourself at http://www.hamiltonweather.ca 

I think the problem may be the memeType that is loading as "application/octet-stream" instead of the proper "application/font-woff2".

**Comment by jimaek** [comment]
can you send me the HTTP headers?

**Comment by TheTannerRyan** [comment]
Request:
Host: cdn.jsdelivr.net
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: identity
Referer: https://cdn.jsdelivr.net/cyber-font/3.0.0/cyber-font.min.css
Origin: https://www.hamiltonweather.ca
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

Response:
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=31536000
Content-Encoding: gzip
Content-Type: application/octet-stream
Date: Mon, 30 Mar 2015 19:43:42 GMT
Etag: W/"55193bd9-677c"
Last-Modified: Mon, 30 Mar 2015 12:04:41 GMT
Server: NetDNA-cache/2.2
Timing-Allow-Origin: *
X-Cache: HIT
X-Firefox-Spdy: 3.1

I tried with chrome and I also get the same issue.

**Comment by jimaek** [comment]
Can you refresh a few times and tell me if you still see the problem?

**Comment by TheTannerRyan** [comment]
It looks like the problem is gone but it is still serving as octet-stream

**Comment by jimaek** [comment]
I added the correct content-type for woff2 to Nginx. Should be good now.

**Comment by TheTannerRyan** [comment]
It is still having issues. Is there a such thing as purging the file cache on the CDNs for the two files as it caches the file and file type?

```//cdn.jsdelivr.net/cyber-font/3.0.0/woff2/cyber-font-bold.woff2
//cdn.jsdelivr.net/cyber-font/3.0.0/woff2/cyber-font.woff2```

**Comment by jimaek** [comment]
I already purged the cache for these 2 files and I can see the correct mime
```
 curl -I http://cdn.jsdelivr.net/cyber-font/3.0.0/woff2/cyber-font-bold.woff2
HTTP/1.1 200 OK
Server: keycdn-engine
Date: Mon, 30 Mar 2015 20:12:15 GMT
Content-Type: application/font-woff2
Content-Length: 29228
Connection: keep-alive
```

**Comment by TheTannerRyan** [comment]
It's now serving with the correct mimeType but is still very slow at loading, even after clearing my cache.

**Comment by jimaek** [comment]
Hey, was this issue fixed?

**Comment by TheTannerRyan** [comment]
I was still experiencing the issue. 

I had to remove the woff2 in the CSS files as it was causing my website not to load. For now, woff2 isn't a big deal, but in the future, it will be (it is the newest and fastest font format). 

If you would like to debug the issue you can call the v3.0.0 CSS file in an HTML file using the CSS ```font-name: cyber-font``` attribute.

The woff2 files will take over 12 seconds to load but all the other formats will load correctly. 

I won't be able to do anything right now as I am at school and have no access to my computer.

**Comment by jimaek** [comment]
I dont have this problem on my PC. It looked like a known issue with CloudFlare, but I created a special rule for woff2 which should had fixed the problem.
Can you run some tests again when you are home?
Take a screenshot showing the 12s loading time along with the HTTP headers of that request

**Comment by jimaek** [comment]
Ping

**Comment by ajkj** [comment]
![image](https://cloud.githubusercontent.com/assets/7894760/7082036/d43d3f0c-df87-11e4-8996-3f4dc82c12a4.png)

**Comment by jimaek** [comment]
@ajkj MaxCDN requires 3 hits to cache a file.

**Comment by ajkj** [comment]
![image](https://cloud.githubusercontent.com/assets/7894760/7086128/5f5b7682-dfb8-11e4-918b-361ae1896867.png)

**Comment by jimaek** [comment]
52ms I dont see any problems here, so can we close this issue or the problem remains for someone?

**Comment by TheTannerRyan** [comment]
Sorry. I haven't been on lately (have had a lot of school work and assignments). When I get a chance, I will check to see if this issue is present and update this (within 24 hours).
