### ISSUE TITLE
Request to add the Baidu maps API

### ISSUE THREAD

**Issue by dandv** [jsdelivr/jsdelivr#4151]
Let's see who adds this first... https://github.com/cdnjs/cdnjs/issues/4533

Not sure if the Great Firewall of China is to blame, but from my Californian ISP, downloading the Baidu Maps API js file stalls or takes MINUTES:

![image](https://cloud.githubusercontent.com/assets/33569/6999388/097d8c3a-dbbe-11e4-966d-506f0466775e.png)

Their demo site most of the time fails to launch the map - http://developer.baidu.com/map/jsdemo.htm (but it may succeed if you let it load for several minutes)

It remains to be seen if the API would be able to download tiles from Baidu's servers if it's hosted somewhere else.

**Comment by pnommensen** [comment]
@dandv Can you submit a pull request following the guidelines in the readme? https://github.com/jsdelivr/jsdelivr/

**Comment by dandv** [comment]
The Baidu API isn't hosted on GitHub as far as I can tell, so per https://github.com/jsdelivr/jsdelivr/#custom-cdn-hosting, ping @jimaek.

**Comment by jimaek** [comment]
I dont think that we can proxy a full API. They are very dynamic and frequently accept POST parameters. jsDelivr was built to work with files that can be cached for a long time and blocks all POST requests. I dont think its possible unfortunately.
