### ISSUE TITLE
Interested hosting a cool resource? It's vanilla/native javascript for Bootstrap :)

### ISSUE THREAD

**Issue by thednp** [jsdelivr/jsdelivr#4233]
I recently finished a tiny Javascript library developed with pure native Javascript.

Demo here
http://thednp.github.io/Native-Javascript-for-Bootstrap/

Well?

**Comment by jimaek** [comment]
Sure, once its stable you can submit it if you want. Use `bootstrap.native` as the name. Also please tag your releases.

**Comment by thednp** [comment]
I added the first release tag, but I don't know where the <code>bootstrap.native</code> should go.

**Comment by jimaek** [comment]
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by thednp** [comment]
Please tell me, the distribution files should also be renamed to bootstrap.native.min.js or keep them as they are bootstrap-native.min.js?

**Comment by jimaek** [comment]
Yes, my comment was referring to the directory name not your files.

**Comment by thednp** [comment]
ok I created a PR, please check whenever you like.
