### ISSUE TITLE
font-awesome web fonts 404

### ISSUE THREAD

**Issue by gottaloveit** [jsdelivr/jsdelivr#4353]
here is script we load:

[//cdn.jsdelivr.net/g/fontawesome@4.1.0(css/font-awesome.min.css),select2@3.5.2(select2.css),chosen@1.1.0(chosen.min.css)](//cdn.jsdelivr.net/g/fontawesome@4.1.0(css/font-awesome.min.css),select2@3.5.2(select2.css),chosen@1.1.0(chosen.min.css))

we get these requests as 404 not found:
http://cdn.jsdelivr.net/g/fonts/fontawesome-webfont.woff?v=4.1.0
http://cdn.jsdelivr.net/g/fonts/fontawesome-webfont.ttf?v=4.1.0

Can the /fonts folder of fontawesome be included?

**Comment by jimaek** [comment]
You can't use /g/ with css files that include other files, it breaks the paths and it results in 404 errors.
Load them normally and it will work just fine
