### ISSUE TITLE
invalid lodash v3.7.0.

### ISSUE THREAD

**Issue by jdalton** [jsdelivr/jsdelivr#4358]
I noticed the copy on jsdelivr does not have a fix that the official 3.7.0 has could you all refresh.

**Comment by jimaek** [comment]
I believe this is correct now? https://github.com/jsdelivr/jsdelivr/commit/801c85f9ed904a2b4d46fc5eb46f8040fd0d5441

**Comment by jdalton** [comment]
Yes! Thank you!

**Comment by jimaek** [comment]
Great, thank you for letting me know. I purged the cache for these files
