### ISSUE TITLE
Only loading last file in multiple request

### ISSUE THREAD

**Issue by cortopy** [jsdelivr/jsdelivr#4564]
I'm trying to create a combo of foundation files from http://www.jsdelivr.com/#!foundation but with no success

The following request returns one 404 error: 
```<script src="https://cdn.jsdelivr.net/g/foundation@5.5.1(foundation.accordion.js+foundation.alert.js)"></script>```

The following request returns two 404 errors (both for the last file in the list)
```<script src="https://cdn.jsdelivr.net/g/foundation@5.5.1(foundation/foundation.accordion.js+foundation/foundation.alert.js)"></script>```

And the following request is successful but just delivers the last file in the list (no matter the number of requested files
```<script src="https://cdn.jsdelivr.net/g/foundation@5.5.1(js/foundation/foundation.accordion.js+js/foundation/foundation.alert.js)"></script>```

What should the request be like? Are folders important when making multiple requests?

**Comment by jimaek** [comment]
The correct link is:
`https://cdn.jsdelivr.net/g/foundation@5.5.1(js/foundation/foundation.accordion.js+js/foundation/foundation.alert.js)`

It combines both files and works just fine for me. Can you give me more information if you see errors with that link?

**Comment by cortopy** [comment]
I get same behaviour as before as only the last file in the list gets downloaded

With the script

```<script src="https://cdn.jsdelivr.net/g/foundation@5.5.1(js/foundation/foundation.accordion.js+js/foundation/foundation.alert.js)"></script>```

only the last file is downloaded. 

I've tried with Firefox and Chrome, and in the latter I get something which may be helpful.

In the sources tab, a folder appear under cdn.jsdelivr.net which is called `/g/foundation@5.5.1(js/foundation/foundation.accordion.js+js/foundation`. There's only one asset in it (the alert.js file).

To me it looks as if only the last file is "visible" in the request

**Comment by jimaek** [comment]
1. Can you paste here the contents of the file that you get?
2. Can you paste here the HTTP headers?

**Comment by cortopy** [comment]
As I was pasting contents of file I realised that the browser was showing the name of the last file only, but the actual contents were the concatenation of the two files. Thank you!! It works great

**Comment by jimaek** [comment]
Awesome :)
