### ISSUE TITLE
[question] get latest from CDN ?

### ISSUE THREAD

**Issue by thednp** [jsdelivr/jsdelivr#4672]
Instead of having 

<pre>
&lt;script type="text/javascript" src="https://cdn.jsdelivr.net/project/0.9.6/project.js">&lt;/script>
</pre>

can we actually have

<pre>
&lt;script type="text/javascript" src="https://cdn.jsdelivr.net/project/latest/project.js">&lt;/script>
</pre>

??

**Comment by jimaek** [comment]
Yes, http://cdn.jsdelivr.net/jquery/latest/jquery.min.js

But I dont recommend it because sooner or later the author will release a version that will break your website.

**Comment by thednp** [comment]
Thanks

**Comment by dandv** [comment]
Is `latest` documented anywhere? It's a neat feature, that [CDNJS doesn't have](https://github.com/cdnjs/cdnjs/issues/360).

**Comment by jimaek** [comment]
@dandv Yes here you go https://github.com/jsdelivr/jsdelivr#version-aliasing

**Comment by dandv** [comment]
@jimaek Oh cool. I was looking for that on the website, didn't find it there.

**Comment by megawac** [comment]
Though restricting to a major or minor version is almost always a better idea btw

Major
https://cdn.jsdelivr.net/project/0/project.js
Minor
https://cdn.jsdelivr.net/project/0.9/project.js
