### ISSUE TITLE
jquery.prettyphoto.js Security Update

### ISSUE THREAD

**Issue by anantshri** [jsdelivr/jsdelivr#4878]
In continuation to what i already reported at https://hackerone.com/reports/62385 let me try to see if you do this via GITHUB issues.

1) There is a new version in repository, when are you going to make that available. 
https://github.com/scaron/prettyphoto
https://github.com/scaron/prettyphoto/releases/tag/3.1.6

2) Do you at any point would like to put a notice on your website around vulnerable versions of the repositories / code

**Comment by pnommensen** [comment]
@anantshri You're welcome to submit a pull request. Information on how to do so can be found here: https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by anantshri** [comment]
That answers part of one the question what about the other question.

Do you at any point would like to put a notice on your website around vulnerable versions of the repositories / code.

This would be to ensure people do not use vulnerable version. coz clearly if the version is vulnerable or not you will not be removing it from CDN, the second best way is to ensure people are aware of the risk.

**Comment by jimaek** [comment]
@anantshri I added the new version http://www.jsdelivr.com/#!prettyphoto

**Comment by anantshri** [comment]
I am still waiting for the answer to the second part. Can jsDelivr as a CDN service provider put up a notice that this version (3.1.5 and 3.1.4) should not used as it contains security issues.

**Comment by jimaek** [comment]
Where? On the website? There is no point, existing users wont see it. And new users will use the latest one by default.

**Comment by anantshri** [comment]
So It boils down to what we can do to inform people that there is a security issue. We still provide users with an option to use older version's. At this point we do not even suggest that the user should use latest version. we have a list of options and a user can pick what they want.

I would suggest following
1) We either remove listing for specific vulnerable version's from the website but keep them on the CDN so that old users still keep getting the file but no new user is able to pick it even in the drop down list. (I am personally not in favour of keeping them in CDN also but as per previous discussion this is one of your core values so we need to stick to it.)
2) we add a notice on vulnerable versions that these are not to be used. 

-Anant

**Comment by jimaek** [comment]
1. At this moment this is not technically possible
2. You mean to modify their code to add messages on their website? If so this is not possible either

**Comment by anantshri** [comment]
No Not on client side that's a serious no no.

What i am saying is when a person reaches the portal say http://www.jsdelivr.com/#!prettyphoto and select 3.1.5 or 3.1.4 in dropdown they get a message stating security issues are present in this release. and in general we should have a notice for all versions older then the current version that there is a newer version and it is encouraged to use the newer version.

And as for option 1 i suppose that might be something you could add as a feature request.

Another question that will come up is how we can keep a track on the security issues : https://github.com/RetireJS/retire.js could be one source for getting that information.
