### ISSUE TITLE
Rename 99Lime to HTML Kickstart

### ISSUE THREAD

**Issue by ethanpil** [jsdelivr/jsdelivr#4889]
http://www.jsdelivr.com/#!99lime

Please see: https://github.com/jsdelivr/jsdelivr/pull/4654

99Lime is the name of the developer not the name of the library, which is why i couldnt find it when i searched... the library is called HTML Kickstart. Perhaps a rename would be in order?

**Comment by jimaek** [comment]
I see the problem but we cant rename the project, that would break all existing URLs.
Also given that the project is not very popular and hasnt been updated in a long time I think we can leave it like it is.
