### ISSUE TITLE
"latest" in the URL doesn't actually point to the latest release

### ISSUE THREAD

**Issue by ToX82** [jsdelivr/jsdelivr#5056]
I'm having a problem using the "latest" version of a plugin through the URL.

The latest release of my plugin, as today, is version 1.4.0. So if I use this

    http://cdn.jsdelivr.net/cookie-bar/latest/cookiebar-latest.js

It should point to the latest version, but it actually points to an older version, 1.2.0. If I use this it correctly points to version 1.4.0.

    http://cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.js

**Comment by jimaek** [comment]
For performance reasons we cache /latest/ URLs for 7 days. Its not supposed to be instant.

**Comment by ToX82** [comment]
Ok, sounds fair... but today I'm noticing the opposite behaviour:

this points to an older release (1.3.0)

    http://cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.js

and this is the actual latest release (1.4.0)

    http://cdn.jsdelivr.net/cookie-bar/latest/cookiebar-latest.js

**Comment by jimaek** [comment]
Get you post here the full HTTP headers you are getting?

**Comment by ToX82** [comment]
Sure! This is the full HTTP headers that Chrome reports:

General

	Remote Address: 95.141.32.94:80
	Request URL: http://cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.js
	Request Method: GET
	Status Code: 200 OK

Request Headers

	GET /cookie-bar/1/cookiebar-latest.js HTTP/1.1
	Host: cdn.jsdelivr.net
	Connection: keep-alive
	Pragma: no-cache
	Cache-Control: no-cache
	Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
	User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
	DNT: 1
	Accept-Encoding: gzip, deflate, sdch
	Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4

Response Headers

	HTTP/1.1 200 OK
	Server: keycdn-engine
	Date: Thu, 04 Jun 2015 13:08:46 GMT
	Content-Type: application/x-javascript; charset=utf-8
	Transfer-Encoding: chunked
	Connection: keep-alive
	Vary: Accept-Encoding
	X-Version: 1.3.0
	Cache-Control: public, max-age=604800
	Last-Modified: Wed, 27 May 2015 11:36:47 GMT
	Access-Control-Allow-Origin: *
	X-Cache: HIT
	X-Edge-Location: itmi
	Content-Encoding: gzip

**Comment by jimaek** [comment]
The same 7 days rule applies in this case as well.
So technically there is nothing wrong yet. https://db.tt/1nxmpzcF

But I can purge the cache manually if you want.

**Comment by ToX82** [comment]
The strange thing is that the behaviour of the two links has switched: I had "latest" pointing to an older release and "1" to the latest, while now it is exactly the opposite.

**Comment by jimaek** [comment]
Its possible that you are hitting different CDN or POP locations each time. Some never had a hit so they cached the new file and some had a hit before and have cached the old file.
Its a small problem with low traffic files. But in any case the expiration of files was meant to be gradual and not instant. For instant upgrades I recommend using static links and simply changing the code.

**Comment by ToX82** [comment]
So it's a caching issue that sometimes could be different between the CDNs. It's ok then, I'll just wait for now.

You can close the issue if you like, thank you for the support!

**Comment by jimaek** [comment]
Ok, ping me here again if you want me to re-open this issue.
