### ISSUE TITLE
@2x.png contains illegal characters

### ISSUE THREAD

**Issue by hubdotcom** [jsdelivr/jsdelivr#5112]
Bot is reporting @2x as illegal characters
```
There are some fundamental issues with your PR :no_good:
files/jquery.mb.ytplayer/2.9.3/css/images/raster@2x.png contains illegal characters
files/jquery.mb.ytplayer/2.9.3/css/images/raster_dot@2x.png contains illegal characters
```

e.g. https://github.com/jsdelivr/jsdelivr/pull/5108

**Comment by jimaek** [comment]
In this case these illegal characters are allowed.

**Comment by hubdotcom** [comment]
Maybe so but the bot shouldn't report this?

**Comment by jimaek** [comment]
The bot cant know what illegal characters are allowed and what not. It reports everything and the moderator decides.

**Comment by hubdotcom** [comment]
fair enough - I was just thinking an exception for @2x. since these will become increasingly common
