### ISSUE TITLE
Add Asteroid (Meteor DDP client)

### ISSUE THREAD

**Issue by dandv** [jsdelivr/jsdelivr#5264]
CC @pscanf, @mondora - https://github.com/mondora/asteroid/issues/65

Asteroid is a [DDP](https://en.wikipedia.org/wiki/Distributed_Data_Protocol) client for [Meteor.js](https://github.com/meteor/meteor).

**Comment by jimaek** [comment]
The files here are unminified https://github.com/mondora/asteroid/tree/v0.6.1/dist
If you start uploading the min files somewhere then we can enable auto-updates by our bot
