### ISSUE TITLE
Proxy of GA js?

### ISSUE THREAD

**Issue by hubdotcom** [jsdelivr/jsdelivr#5308]
Leverage browser caching
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:
https://www.google-analytics.com/analytics.js (2 hours)

Is it possible to have this in jsdelivr?

**Comment by jimaek** [comment]
Google analytics will work much better if its loaded from Google. Its not an open source project so we cant host it
