### ISSUE TITLE
Version ordering incorrect for esri.leaflet

### ISSUE THREAD

**Issue by patrickarlt** [jsdelivr/jsdelivr#5796]
Currently http://www.jsdelivr.com/#!leaflet.esri is showing 1.0.0-rc.8 as the latest release but the latest release version wise is 1.0.0.

```js
require('semver').gt('1.0.0', '1.0.0-rc.8'); // true
```

This is probably sorting alphabetically, sorting using `semver.gt` would solve this.

**Comment by jimaek** [comment]
Its something that is going to be fixed in the new website

**Comment by patrickarlt** [comment]
:+1:
