### ISSUE TITLE
Missing version for leaflet.esri.geocoder

### ISSUE THREAD

**Issue by patrickarlt** [jsdelivr/jsdelivr#5797]
The 1.0.0 release is not showing up http://www.jsdelivr.com/#!leaflet.esri.geocoder the 1.0.0-rc.4 release is still the only release available. However the files for the 1.0.0 release are in this repo leading me to think there is a bug somewhere. https://github.com/jsdelivr/jsdelivr/tree/master/files/leaflet.esri.geocoder/1.0.0

**Comment by megawac** [comment]
Hi @patrickarlt, its available on the CDN however it takes a while for that version of the site to refresh with the hosted libraries

http://cdn.jsdelivr.net/leaflet.esri.geocoder/1.0.0/esri-leaflet-geocoder-src.css

**Comment by jimaek** [comment]
Its live now http://www.jsdelivr.com/#!leaflet.esri.geocoder
