### ISSUE TITLE
why jsdelivr blocked  for 5 days

### ISSUE THREAD

**Issue by a-moses** [jsdelivr/jsdelivr#5822]
https://cdn.jsdelivr.net/riot/2.2.2-beta/compiler.js

 Server not found  :(

Please fix that

**Comment by jimaek** [comment]
I dont understand, everything is working for me. Send me:
1. Screenshot of what you see
2. IP of cdn.jsdelivr.net
3. HTTP headers of the response

**Comment by a-moses** [comment]
hi @jimaek 
now is working!!  maybe the talking I'm doing with my ISP fix the problem.
next time if i will see it agian i send  it to you as you want. 

thank you .

**Comment by crazyjums** [comment]
why I get a problem like this "User crazyjums is blocked."
