### ISSUE TITLE
angularjs 1.x bundles broken

### ISSUE THREAD

**Issue by delamitry** [jsdelivr/jsdelivr#5824]
url https://cdn.jsdelivr.net/g/angularjs(angular.min.js+angular-resource.min.js) fails with 404 and 'Could not find file angular.min.js for project: angularjs.'

Looks like a bad commit made it into the angularjs project adding 2.0.0-alpha.30

**Comment by jimaek** [comment]
This should fix the issue https://cdn.jsdelivr.net/g/angularjs@1(angular.min.js+angular-resource.min.js)
Using latest is not recommended but I will look into it further. Thanks

**Comment by jimaek** [comment]
I reverted the change that broke latest completely. But I still recommend to use versioning instead of latest.

**Comment by delamitry** [comment]
I concur, versioning ftw.  Thanks for the tip.
