### ISSUE TITLE
corrupted CDN cache for esri-leaflet 1.0.0

### ISSUE THREAD

**Issue by jgravois** [jsdelivr/jsdelivr#5869]
prior to the successful publication of leaflet.esri version 1.0.0 on the cdn, i made a request for the version which wasn't available yet and the CDN responded by returning an earlier release.

http://cdn.jsdelivr.net/leaflet.esri/1.0.0/esri-leaflet.js
> returned

http://cdn.jsdelivr.net/leaflet.esri/1.0.0-rc.8/esri-leaflet.js?foo

im noticing now that the inappropriately cached content on the particular server im talking to makes it impossible to fetch the actual latest release.  is it possible to selectively clear the cache for the IP address 190.93.247.228? if not, can you do something more nuclear?

![screenshot 2015-07-14 14 54 47](https://cloud.githubusercontent.com/assets/3011734/8686139/76c6b17c-2a38-11e5-8f4f-757c6e288838.png)

ive received confirmation that the CDN is already returning the appropriate results for folks in PDX and NYC.

cc @patrickarlt

**Comment by jgravois** [comment]
i'm seeing the correct response from my smartphone, so im starting to think my firewall at work is the problem here.

will report back with more info shortly.

**Comment by jimaek** [comment]
Before the release of `1.0.0` if you entered `1.0.0` it would be aliased to `1.0.0-rc8`. This function is cached for 7 days for performance reasons. 
So what you see now is probably the still old cache of that version. These changes are not supposed to be instant and get purged gradually across all CDNs. 

Regardless I purged the cache manually for your file. check it out

**Comment by jgravois** [comment]
confirmed all is well.  thanks all.
