### ISSUE TITLE
Issue with jsface

### ISSUE THREAD

**Issue by tnhu** [jsdelivr/jsdelivr#5899]
I tagged jsface (https://github.com/tnhu/jsface) wrong to 2.6.7 then deleted it. Unfortunately, jsdelivr bot grabbed 2.6.7 and refuses to grab the newest version of 2.4.7.

Can somebody delete the wrong version of 2.6.7 and update jsface to latest build of 2.4.7?

Thanks,
Tan

**Comment by jimaek** [comment]
Should be fixed now
