### ISSUE TITLE
Emojione assets not updated for 1.5.0 release

### ISSUE THREAD

**Issue by ping** [jsdelivr/jsdelivr#5953]
The latest emojione 1.5.0 release has been updated (#5949), but the assets don't seem to be. Existing images that were updated have not been refreshed, and new ones are not available.

Example: https://github.com/Ranks/emojione/blob/v1.5.0/assets/png/1F5FA.png

$ curl -I "https://cdn.jsdelivr.net/emojione/assets/png/1F5FA.png"
HTTP/1.1 404 Not Found
Date: Fri, 17 Jul 2015 15:18:46 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 168
Connection: keep-alive
Server: NetDNA-cache/2.2

$ curl -I "https://cdn.jsdelivr.net/emojione/assets/png/1F5FA.png"
HTTP/1.1 404 Not Found
Server: cloudflare-nginx
Date: Fri, 17 Jul 2015 15:19:08 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
CF-Cache-Status: HIT
CF-RAY: 2076ec63d2c21792-SIN

**Comment by jimaek** [comment]
Assets are proxied and not deployed with the script.
This is the origin of the owners of emojione http://git.emojione.com/assets/png/1F5FA.png
Its their issue

**Comment by emitstop** [comment]
@jimaek Sorry about that! We've updated the assets on our side of things. Can we have the proxy script pull those again?

Thanks

**Comment by jimaek** [comment]
@emitstop No need to do anything, its all automated. The URLs https://cdn.jsdelivr.net/emojione/assets/png/1F5FA.png now work just fine. Thank you

**Comment by emitstop** [comment]
Thanks @jimaek ! This issue can probably be closed now.

**Comment by emitstop** [comment]
@jimaek We're noticing some appear to be out of date. Is there a regular interval that the update process runs at?

http://git.emojione.com/assets/png/1F645.png
vs.
http://cdn.jsdelivr.net/emojione/assets/png/1F645.png

**Comment by jimaek** [comment]
there is no update process, its a proxy. The file just got cached. They will expire eventually but if you want I can force a cache purge. I will need a list of the URLs to purge for that

**Comment by emitstop** [comment]
Hmm, so each individual file needs to be purged? There's far too many that would need to be updated for that to be a reasonable task. 

Is there a way to purge all of them or perhaps an entire directory?

**Comment by mikebe11** [comment]
@jimaek Is it possible to purge the cache just based on extension?
http://cdn.jsdelivr.net/emojione/assets/png/*.png 
and 
http://cdn.jsdelivr.net/emojione/assets/svg/*.svg

**Comment by jimaek** [comment]
Our CDN providers dont support that. 
If you want just send me the output of the `ll` command on your server in that directory and I will purge all the URLs.

**Comment by mikebe11** [comment]
I put them into the URLs, hopefully the correct one. There were so many I just emailed them to you.
