### ISSUE TITLE
Request to add the Microsoft.jQuery.Unobtrusive.Ajax

### ISSUE THREAD

**Issue by evorios** [jsdelivr/jsdelivr#6095]
See how many downloads [here](https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Ajax/). I think it is an occasion for the library connected via CDN.

[Googling](https://www.google.com/search?q=inurl:cdn+jquery.unobtrusive-ajax) showed that the network does not have the latest version of the library, and there is only [an old version for MVC3](http://www.asp.net/ajax/cdn#ASPNET_MVC_Releases_on_the_CDN_16), which is not suitable for MVC4 and MVC5.

Thanks!

**Comment by jimaek** [comment]
Does the project have some kind of repo or official website except from nuget?

**Comment by evorios** [comment]
No, only [unofficial fork on github for bower](https://github.com/whyleee/Microsoft.jQuery.Unobtrusive.Ajax) with version 3.2.2. The latest version is 3.2.3.

**Comment by evorios** [comment]
Fixed in #6137
