### ISSUE TITLE
Failed to load resource: the server responded with a status of 500

### ISSUE THREAD

**Issue by katrotz** [jsdelivr/jsdelivr#6473]
The polyfill as a service CDN returns status code 500.

Tried in Chrome and Safari - reproduces in both.
Steps: 
1. Add `<script src="https://cdn.jsdelivr.net/polyfills/polyfill.js"></script>` to the source of a static HTML file
2. Open the browser console and see the error: `Failed to load resource: the server responded with a status of 500`

**Comment by jimaek** [comment]
Its a problem with the origin server of the polyfill project. jsDelivr proxies and caches their files, but it cant work indefinitely if their server is down. You need to ping the owners of polyfill.
There is nothing we can do

**Comment by katrotz** [comment]
Thanks. Will do so!
