### ISSUE TITLE
Web interface search not matching plugins

### ISSUE THREAD

**Issue by yyx990803** [jsdelivr/jsdelivr#6536]
Currently, when you search "jquery", you only get one result that is jquery itself. It doesn't show plugins that have names like "jquery.xxx". Not sure if this is working as intended. I think it'd be useful to see plugins with partial match.

**Comment by jimaek** [comment]
This is fixed in the new website http://lb.jimaek.svc.tutum.io/

**Comment by yyx990803** [comment]
Wow, nice, didn't know there's a new version in development :)
When is it going to launch?

**Comment by jimaek** [comment]
I hope next month. We are actively working in the new version of our API as well https://github.com/jsdelivr/api which will integrate into the website

**Comment by yyx990803** [comment]
:+1:
