### ISSUE TITLE
Auto-Updating didn't work for free-jqgrid 4.9.2

### ISSUE THREAD

**Issue by OlegKi** [jsdelivr/jsdelivr#6550]
Hi,

I published (tagged) the version 4.9.2 of [**free-jqgrid**](https://github.com/free-jqgrid/jqGrid/tree/v4.9.2) on GitHub and published it on [npmjs](https://www.npmjs.com/package/free-jqgrid) 12 days ago. I did the publishing in absolutely the same way like with 4.9.1 version, but 4.9.2 is still not updated on jsdelivr.

Please could you verify the reason why auto-updating don't work. What shell I do for refreshing free-jqgrid on jsdelivr CDN?

**Comment by jimaek** [comment]
When the PR came our bot was having issues and I had to close the PR. Unfortunately I didnt delete the branch so the bot didnt send any new PRs for the same version. I am sorry for that.
Its fixed now https://github.com/jsdelivr/jsdelivr/pull/6555

**Comment by OlegKi** [comment]
Thank you very much for publishing of the version 4.9.2!
