### ISSUE TITLE
[Request] Add library: lodash-fp

### ISSUE THREAD

**Issue by Nieralyte** [jsdelivr/jsdelivr#6637]
**Library name:** lodash-fp
**Git repository url:** http://github.com/lodash/lodash-fp
**npm package url:** http://npmjs.com/package/lodash-fp
**License(s):** MIT
**Official homepage:** http://lodash.com/#formats

**Comment by megawac** [comment]
Feel free to submit a pull request as documented in https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md for the library

**Comment by jdalton** [comment]
@Nieralyte for jsdelivr the bundled files your looking for can be found in [lodash-fp/dist](https://github.com/lodash/lodash-fp/tree/master/dist)
