### ISSUE TITLE
Files order on website

### ISSUE THREAD

**Issue by mistic100** [jsdelivr/jsdelivr#6699]
Hello,

It would be cool if we could define in which order files are displayed on jsdelivr.com, it order to show the main files on top.

Example for http://www.jsdelivr.com/#!jquery.query-builder, main JS files are at the bottom of the list, which is not very friendly.

A good start would be to respect the order or `include` declaration https://github.com/jsdelivr/jsdelivr/blob/master/files/jquery.query-builder/update.json#L7

**Comment by jimaek** [comment]
We show the mainfile on top on the new site http://www-jsdelivr-com.dak.netdna-cdn.com/projects/jquery.query-builder

But there is no way to prioritize the files after that

**Comment by mistic100** [comment]
Nice WIP (is it ?)

Any reason why js/query-builder.standalone.min.js is not at the bottom ?

**Comment by jimaek** [comment]
The site is almost ready to launch, let me know if you have feedback.
Like I said we only know the mainfile and nothing else.  Creating file priorities that match all projects is impossible.

**Comment by mistic100** [comment]
i understand that but my question is why the rest of the files are not sorted alphabetically like in current version ("js" is after "i18n")

**Comment by jimaek** [comment]
@MartinKolarik How the files are sorted?

**Comment by MartinKolarik** [comment]
1. main file
2. `.min` files
3. other files
4. map files

**Comment by mistic100** [comment]
got it, waiting for new website

I have a feedback though, (let me know if there is a better place) :
the "second header" (red) should not be always displayed, because it duplicates buttons on the screen.

It would be better to display it, on top, after we scrolled about 200px (enough to hide the top header)

**Comment by jimaek** [comment]
Not sure what you mean, can you send a screenshot?

**Comment by mistic100** [comment]
http://imagizer.imageshack.com/img540/3944/8f3sGi.jpg
red bar is duplicate of the header

**Comment by jimaek** [comment]
Oh I see. That was intentional, its the most optimal way to do what we wanted.
If you have any other feedback let me know

**Comment by mistic100** [comment]
well it's very confusing
