### ISSUE TITLE
Project doesn't get pulled

### ISSUE THREAD

**Issue by moay** [jsdelivr/jsdelivr#6708]
Hey guys,

I applied yesterday (and obviously got accepted, thank you!) with the project "afterglow". As far as I can see, I did everything exactly as described in the guides, but the project didn't get updated until now. 

Is there anything I'm not doing the correct way? Or maybe, jsDelivr doesn't pull github prereleases?

Thank you very much!

**Comment by jimaek** [comment]
https://github.com/jsdelivr/jsdelivr/blob/master/files/afterglow/update.json
`http://github.com/afterglow/moay` doesnt exist

**Comment by moay** [comment]
Whoo god.. so sorry. Forgive me, oh Lord.

Didn't see that, I promise. Will correct it.
