### ISSUE TITLE
Manually add Vue v0.12.13

### ISSUE THREAD

**Issue by abishekrsrikaanth** [jsdelivr/jsdelivr#6811]
Could you please add the release version 0.12.13 for the project Vue. 

Repo: https://github.com/yyx990803/vue
Releases: https://github.com/yyx990803/vue/releases

Release to be manually added: https://github.com/yyx990803/vue/releases/tag/0.12.13

There was a Prod release (0.12.13) performed after a Pre Release (1.0.0-alpha.2). If I understand correctly, the bot thought that 0.12.13 was a release lesser that 1.0.0-alpha.2 and did not pull that release.

**The Bot should stop pulling pre-releases, RC and alpha releases**

**Comment by jimaek** [comment]
Done https://github.com/jsdelivr/jsdelivr/commit/a73e7a926c54be33475e8d72195c8f9c66a8725d

**Comment by abishekrsrikaanth** [comment]
@jimaek, @megawac There is now a 0.12.14 version. Could you force update the same?
