### ISSUE TITLE
No files found for tsumegumi.js ( 404 )

### ISSUE THREAD

**Issue by getphuture** [jsdelivr/jsdelivr#6820]
I submited tsumegumi.js last week and checking now at the site no files were found.

* http://www.jsdelivr.com/?query=tsumegumi
* https://cdn.jsdelivr.net/tsumegumi//tsumegumi.min.js

Is there something wrong ? Should I fix something on my side ?
Thank you for your help

**Comment by jimaek** [comment]
The files specified here https://github.com/jsdelivr/jsdelivr/blob/master/files/tsumegumi/update.json dont exist here https://github.com/allianceport/tsumegumi.js/tree/0.0.1
Thats why the bot fails

**Comment by getphuture** [comment]
Thank you very much for the feedback.
I forgot to re-package the 0.0.1 after updating the project name.
It should be good now. よろしく〜

**Comment by jimaek** [comment]
awesome
