### ISSUE TITLE
Latest not updating

### ISSUE THREAD

**Issue by moay** [jsdelivr/jsdelivr#6913]
Hi everyone. I don't know if this is a known issue or if I'm just doing something wrong, but for my project afterglow, there is a slight problem. The updates are correctly taken from the repo, but the `https://cdn.jsdelivr.net/projectname/latest/filename` doesn't update correctly. 

So: https://cdn.jsdelivr.net/afterglow/latest/afterglow.min.js still delivers v0.1.1, which is outdates since a few days. 

Any idea?

**Comment by moay** [comment]
Okay, just saw https://github.com/jsdelivr/jsdelivr/issues/5056 which seems to clarify things. With a new release being out, this is a bummer because I'd have to wait until the CDN catches up until updating the website.

Is there some way for project authors to purge their "latest" version? That would be great.

**Comment by jimaek** [comment]
Send me an email and I will give you access to the purge functionality.
