### ISSUE TITLE
jsdelivr bot seems to skip versions when they are released in quick succession

### ISSUE THREAD

**Issue by yyx990803** [jsdelivr/jsdelivr#6982]
Hi there, for [Vue.js](http://www.jsdelivr.com/projects/vue) I'm currently in the 1.0 alpha phase, so I'm doing 1 stable release and 1 preview release together each week. Last week I released 0.12.14 and 1.0.0-alpha.4 together, but it seems only 1.0.0-alpha.4 got picked up, while 0.12.14 was skipped. Is this intended or should this be fixed in some way?

**Comment by megawac** [comment]
Yeah, the issue is the bot considers prereleases a proper version and ignores the "older"  0.12.4

Moving this to https://github.com/jsdelivr/libgrabber/issues/50
