### ISSUE TITLE
[Request] AdminLTE

### ISSUE THREAD

**Issue by kethomassen** [jsdelivr/jsdelivr#7021]
Making a request to add the latest version of AdminLTE (css +js )

https://github.com/almasaeed2010/AdminLTE

**Comment by jimaek** [comment]
Well we already host bootstrap. I dont think it makes sense to host the custom theme related files as well since its meant to be modified anyway

**Comment by kethomassen** [comment]
Except it is basically an entire rewrite of Bootstrap, only utilising its grid system, basic css elements and javascript plugins.

It would be really nice to add this due to its exhaustive amount of files (css + js), and have it on the same CDN as everything else everybody uses. 

@jimaek
