### ISSUE TITLE
Use load multiple files with single HTTP request for ONE library

### ISSUE THREAD

**Issue by enjoyiacm** [jsdelivr/jsdelivr#7076]
Hello. Thank you for CDN!
I'm very happy to found it :+1: 

Question: right to use [load multiple files with single HTTP request](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request) for only ONE library? I.e.:

```html
<script src="https://cdn.jsdelivr.net/g/jquery"></script>
```

It's request **always** get a ``latest`` library version. 'Cause browser save in cache last of load version and this URL don't work fine:

```html
<script src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
```

In my browser I'll get jQuery version ``1.11.3``, but must be a ``3.0.0-alpha``.

The same thing happens with [my project](http://www.jsdelivr.com/projects/jquery.goodshare.js).

When I send HTTP request ``https://cdn.jsdelivr.net/jquery.goodshare.js/latest/goodshare.min.js``&nbsp;— I have version ``3.0``. But last version on CDN is ``3.1.3``...

If I try load only my project as multiple files — ``https://cdn.jsdelivr.net/g/jquery.goodshare.js``&nbsp;— I always have **last** version ``3.1.3`` (**not even clear browser's cache**).

**Comment by jimaek** [comment]
`/latest/` URLs are cached for much longer than `/g/` URLs. Thats why the upgrade between versions takes longer. I purged the cache for those files and they should be showing the correct latest version now.

**Comment by enjoyiacm** [comment]
I.e. that's okay if I (and other users) use ``/g/`` address for call only one project from CDN?

In the sense of this URL ``//cdn.jsdelivr.net/{projectName}/latest/{file}`` and this ``//cdn.jsdelivr.net/g/{projectName}`` — the same thing? Only difference in cache time?

**Comment by jimaek** [comment]
What I recommend:
1. Use static files with full versions or use version aliasing for only minor versions (1.x)
2. Don't use /latest/ unless you know what you are doing.
3. Use /g/ only for combining files and not for a single file.

Technically you can do everything that works, but I recommend doing the above.

>In the sense of this URL //cdn.jsdelivr.net/{projectName}/latest/{file} and this //cdn.jsdelivr.net/g/{projectName} — the same thing? Only difference in cache time?

Yes. They load the same thing using different functions

**Comment by enjoyiacm** [comment]
Now all became clear.

Thank you Dmitry for the answer :+1:
