### ISSUE TITLE
Unable to search my library on the website

### ISSUE THREAD

**Issue by ArunMichaelDsouza** [jsdelivr/jsdelivr#7172]
My library, CSS-Mint (https://cdn.jsdelivr.net/css-mint/1.2.4/css-mint.min.css) has been added to jsdelivr, but I am not able to search it on the website - https://www.jsdelivr.com/

**Comment by jimaek** [comment]
Unfortunately we have a small problem with our API. New projects are delayed.
The files are uploaded and served normally. It should be fixed soon.

@UnbounDev @megawac Related to local api-sync. We need it

**Comment by ArunMichaelDsouza** [comment]
Ok. Thanks for the reply @jimaek

**Comment by UnbounDev** [comment]
@ArunMichaelDsouza progress: `http://www.jsdelivr.com/?query=css-mint` :)

**Comment by ArunMichaelDsouza** [comment]
Awesome @UnbounDev :)
