### ISSUE TITLE
algolia/instantsearch.js v0.4.1 never got picked 

### ISSUE THREAD

**Issue by vvo** [jsdelivr/jsdelivr#7257]
http://www.jsdelivr.com/projects/instantsearch.js
https://www.npmjs.com/package/instantsearch.js

Do you know why the v0.4.1 was not picked by jsdelivr? Cannot find why. Thanks

**Comment by jimaek** [comment]
The file is there https://cdn.jsdelivr.net/instantsearch.js/0.4.1/instantsearch.min.js but the API has a small problem and is delayed. It will be fixed soon. Sorry about that

**Comment by jimaek** [comment]
Fixed

**Comment by vvo** [comment]
Weeeeee thx
