### ISSUE TITLE
React lastversion shows 0.14.0-rc1 instead of 0.14.0

### ISSUE THREAD

**Issue by spicyj** [jsdelivr/jsdelivr#7281]
Can we make this show 0.14.0? Not sure if this is a stupid question.

http://www.jsdelivr.com/projects/react

**Comment by jimaek** [comment]
Technically 0.14.0-rc1>0.14.0 but I will create a task to fix it.
Thanks for reporting

**Comment by MartinKolarik** [comment]
@jimaek `0.14.0` is greater than `0.14.0-rc1`.

**Comment by jimaek** [comment]
This is now fixed.

**Comment by spicyj** [comment]
Thank you!
