### ISSUE TITLE
POP in China

### ISSUE THREAD

**Issue by watermelonjuice** [jsdelivr/jsdelivr#729]
Most CDNs would have trouble getting a node inside China due to censorship laws. It would be a great benefit if a provider could donate a server in China.

Also a POP in china using jsdelivr's technology would avoid issues like cdnjs/cdnjs#1922.

**Comment by jimaek** [comment]
Btw I wanted to let everyone know that we got an ICP license to operate in China.

**Comment by Yexiaoxing** [comment]
That's  amazing . How can you manage to do that?

On Sunday, May 10, 2015, Dmitriy Akulov <notifications@github.com> wrote:

> Btw I wanted to let everyone know that we got an ICP license to operate in
> China.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsdelivr/jsdelivr/issues/729#issuecomment-100626598>.
>


-- 
Regards,
Xiaoxing Ye

**Comment by jimaek** [comment]
With the help of our contributors :)
![image](https://cloud.githubusercontent.com/assets/1834071/7656402/89acba44-fb2a-11e4-84bd-a5f8cc30bcf0.png)

**Comment by jimaek** [comment]
Who wants to test the following Chinese CDNs?
http://e4a460fff0.a.uxengine.net/r20.gif
http://90f29d9537a6c39a.tan14.net/r20.gif

Not sure if it makes sense to use them both. Which one is the fastest?

**Comment by watermelonjuice** [comment]
What do you want us to test? Ping?

If you want us to test speed then a 1 pixel image may not be the best
gauge...

**Comment by jimaek** [comment]
You can change the URL to any project on jsDelivr. They use the same origin.
Ping, HTTP, whatever else you want to test.

**Comment by as-com** [comment]
@watermelonjuice How about the largest file in the CDN? :stuck_out_tongue_winking_eye:  http://cdn.jsdelivr.net/ace/1.1.5/noconflict/worker-xquery.js
http://e4a460fff0.a.uxengine.net/ace/1.1.5/noconflict/worker-xquery.js
http://90f29d9537a6c39a.tan14.net/ace/1.1.5/noconflict/worker-xquery.js

How about a more practical example?
http://cdn.jsdelivr.net/jquery/1.11.3/jquery.min.js
http://e4a460fff0.a.uxengine.net/jquery/1.11.3/jquery.min.js
http://90f29d9537a6c39a.tan14.net/jquery/1.11.3/jquery.min.js

**Comment by as-com** [comment]
Oh wait, the first example gzips to a tiny size. How about this 2.7 MB (gzipped) font file?
http://cdn.jsdelivr.net/files/font-kopub/1.0/KoPubBatang-Regular.ttf
http://e4a460fff0.a.uxengine.net/files/font-kopub/1.0/KoPubBatang-Regular.ttf
http://90f29d9537a6c39a.tan14.net/files/font-kopub/1.0/KoPubBatang-Regular.ttf

**Comment by watermelonjuice** [comment]
wget http://cdn.jsdelivr.net/font-kopub/1.0/KoPubBatang-Regular.ttf
--2015-07-02 21:52:26--  http://cdn.jsdelivr.net/font-kopub/1.0/KoPubBatang-Regular.ttf
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 146.88.128.44
Connecting to cdn.jsdelivr.net (cdn.jsdelivr.net)|146.88.128.44|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6536312 (6.2M) [application/x-font-ttf]
Saving to: ‘KoPubBatang-Regular.ttf’

KoPubBatang-Regular 100%[=====================>]   6.23M   297KB/s   in 28s    

2015-07-02 21:52:54 (232 KB/s) - ‘KoPubBatang-Regular.ttf’ saved [6536312/6536312]

wget http://e4a460fff0.a.uxengine.net/font-kopub/1.0/KoPubBatang-Regular.ttf
--2015-07-02 21:56:19--  http://e4a460fff0.a.uxengine.net/font-kopub/1.0/KoPubBatang-Regular.ttf
Resolving e4a460fff0.a.uxengine.net (e4a460fff0.a.uxengine.net)... 222.187.0.70, 183.60.90.89, 183.60.90.86, ...
Connecting to e4a460fff0.a.uxengine.net (e4a460fff0.a.uxengine.net)|222.187.0.70|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6536312 (6.2M) [application/x-font-ttf]
Saving to: ‘KoPubBatang-Regular.ttf’

KoPubBatang-Regular 100%[=====================>]   6.23M  16.5KB/s   in 8m 20s s

2015-07-02 22:04:41 (12.8 KB/s) - ‘KoPubBatang-Regular.ttf’ saved [6536312/6536312]

wget http://90f29d9537a6c39a.tan14.net/font-kopub/1.0/KoPubBatang-Regular.ttf
--2015-07-02 22:20:07--  http://90f29d9537a6c39a.tan14.net/font-kopub/1.0/KoPubBatang-Regular.ttf
Resolving 90f29d9537a6c39a.tan14.net (90f29d9537a6c39a.tan14.net)... 124.226.64.249, 14.17.123.71, 113.105.248.109, ...
Connecting to 90f29d9537a6c39a.tan14.net (90f29d9537a6c39a.tan14.net)|124.226.64.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6536312 (6.2M) [application/x-font-ttf]
Saving to: ‘KoPubBatang-Regular.ttf’

KoPubBatang-Regular 100%[=====================>]   6.23M  1.24MB/s   in 7.6s   

2015-07-02 22:20:16 (839 KB/s) - ‘KoPubBatang-Regular.ttf’ saved [6536312/6536312]

**Comment by as-com** [comment]
Ouch, uxengine is almost as slow as dial up! Perhaps the performance of
each cdn differs between ISPs?

**Comment by watermelonjuice** [comment]
Depends on peering, the position of the moon, and is currently viral on the
chinesenet.

**Comment by as-com** [comment]
Looks like we've got a situation where Cedexis would really shine! :smile:

**Comment by jimaek** [comment]
We dont have enough RUM tests in China to support more than 1 CDN I think. Thats why I try to choose one that is going to be blended with MaxCDN, CF and others.

**Comment by jimaek** [comment]
I finally pushed live a Chinese CDN provider.
Can everyone do some tests against cdn.jsdelivr.net and see if they get good performance?
This is important, if you have any issues I will report them to the provider.

**Comment by as-com** [comment]
Are you going to update the open mix repository?

**Comment by jimaek** [comment]
Yes, once its confirmed to be working correctly. Otherwise I will restore the code from the repo

**Comment by ajkj** [comment]
does chinese cdn support https without SNI? seems like they don't support it.

http://gs.statcounter.com/#browser_version_partially_combined-CN-monthly-201406-201506
http://gs.statcounter.com/#desktop-browser_version_partially_combined-KR-monthly-201406-201506

**Comment by ajkj** [comment]
![image](https://cloud.githubusercontent.com/assets/7894760/8877010/1d38aa4c-325e-11e5-9d99-b85a419d0dbf.png)
![image](https://cloud.githubusercontent.com/assets/7894760/8877027/3649e276-325e-11e5-8ce6-bb951ef2884d.png)

there might be performance issue due the the mismatch in addresses.
ex) korea

quantil.jsdelivr.net
ping 49.1.245.104(105)  ~ 4ms (to Korea, Seoul)

cdn.jsdelivr.net(currnet quantil?)
ping 61.120.154.173 ~ 31ms (to japan, tokyo)
ping 202.122.145.73 ~ 100ms (to Malaysia?)
ping 58.229.157.173 ~ 4ms(to Korea, Seoul)

cdn.jsdelivr.net.cdn.cloudflare.cnet
ping 190.93.247/246.228 ~ 4ms(Korea, Seoul)

**Comment by jimaek** [comment]
Thank you, thats very useful information. If you find anything else let me  know.

**Comment by Yexiaoxing** [comment]
According to test  (
http://www.17ce.com/site/http/201507_d9011606e49f9a7e8d92a277b30f5ed8.html),
the speed is acceptable.

Regards,
Xiaoxing Ye

**Comment by jimaek** [comment]
Can you run the tests 2-3 times? The first one is a uncached and the performance will be bad.

**Comment by Yexiaoxing** [comment]
Second run:
http://cdn.jsdelivr.net/darfonts/0.1/asifa-cap-curv-flow/ge_asifa_bold-webfont.eot
Almost every pop can get more than 1MB/s
But I noticed that some encounter low speed due to DNS query.

Result can be found here:
http://www.17ce.com/site/http/201507_d9011606e49f9a7e8d92a277b30f5ed8.html

Regards,
Xiaoxing Ye

**Comment by jimaek** [comment]
The performance looks good to me. I believe we finally found our Chinese provider.

**Comment by tomByrer** [comment]
:tada: :balloon:

**Comment by jimaek** [comment]
I updated the network map http://lb.jimaek.svc.tutum.io/features/network-map

**Comment by Yexiaoxing** [comment]
I want to know that what service we are using in China...
P.S. is http://lb.jimaek.svc.tutum.io/features/network-map a new website of
jsDelivr?

Regards,
Xiaoxing Ye

**Comment by jimaek** [comment]
You mean our Chinese provider? Its https://www.quantil.com/
And yes thats the new website
