### ISSUE TITLE
babel browser-polyfill.js minified version

### ISSUE THREAD

**Issue by jhiswin** [jsdelivr/jsdelivr#7375]
The browser-polyfill for babel does not contain a minified version of the library.

**Comment by tomByrer** [comment]
Thanks for your report.

@megawac I'm trying to understand the configurations' highlighted lines:
https://github.com/jsdelivr/jsdelivr/blob/master/files/babel/update.json#L6
https://github.com/jsdelivr/jsdelivr/blob/master/files/babylonjs/info.ini#L5

**Comment by megawac** [comment]
the babel package is for running es6 code processed by babel in a script tag. It should mostly be used for debugging and may be good for things like jsbin/fiddles. See documentation. A minified file does not exist for babel-browser as its mostly just a quick hack for demos

http://babeljs.io/docs/usage/browser/

**Comment by jhiswin** [comment]
@megawac that only applies to browser.js, not browser-polyfill.js
browser-polyfill.js is essentially just regenerator and es6 polyfill, while browser.js is a full blown transpiler.

https://babeljs.io/docs/usage/polyfill/
Just want to note that cdnjs includes a minified browser-polyfill.js

**Comment by tomByrer** [comment]
Bable changed file structure again:
http://jamesknelson.com/the-six-things-you-need-to-know-about-babel-6/

**Comment by jhiswin** [comment]
Seems like @megawac is right on its true intention

Shouldn't jsdelivr only host babel-polyfill?

Or maybe it would make more sense to just not include it, and have people include corejs and regenerator themselves?
