### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by finom** [jsdelivr/jsdelivr#7400]
Hi guys. I'd like to get usage statistics of libraries I pushed to jsdelivr. I guess it could be helpful for tracking popularity of libraries. What kinds of statistics theoretically can be retrieved?
-  Number of downloads of latest version. "Downloads" mean how many times a webpage with given script is opened. Script must be returned with code 200.
- Number of usages of latest version. "Usage" means script is attached on pages on single domain (example.com/index.html and example.com/blah.html is a single "usage").
- Number of downloads of all versions.
- Number of usages of all versions.

Is it possible? 

Thanks

**Comment by jimaek** [comment]
https://github.com/jsdelivr/api/issues/62 will be live soon and can provide some information that you need.
For now it can only show the amount of downloads per project per day. Nothing else.
In the future we plan to add a lot more information.

**Comment by finom** [comment]
OK, great. Thank you.

**Comment by jimaek** [comment]
should be part of new website https://github.com/jsdelivr/www.jsdelivr.com/issues/86
