### ISSUE TITLE
jsDelivr Big Data - Analytics

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr#7426]
The current analytics system that I run is very basic and not very good.
- A bunch of scripts pull the raw logs from all the CDNs
- They parse the data and then compile an array. The array contains $projectName,$hits,$date
- This data then gets merged into the DB

This way we can create basic charts with the number of hits each project had over the course of days/weeks/months.

It also eats very little space.

But except from the number of hits we have lots of interesting data like user-agents, HTTP version, HTTPS vs HTTP, exact project version, referral url, user's location....
All this data could be used to create amazing charts and graphs mapping the usage of HTTP2, HTTPS, popular countries and much more.

One way to do it is to use Elasticsearch:
- A bunch of scripts pull the raw logs from all the CDNs
- They parse the data and format it into JSON. The JSON contains ALL the information
- We then batch insert the json document into Elasticsearch
- Once we have the data in Elasticsearch we can do pretty much anything we want

Awesome right? The problem here is the amount of data we have.
More than 6 billion HTTP requests per month. Each HTTP request contains data ranging from 200bytes to 500bytes.
Thats more than 1TB of information per month that needs to be processed and stored. Which is not going to expire as we need this historical data.
And then of course Elasticsearch would need to process our analytics queries in a timely fashion to build all the cool stuff we want.
While its possible, its too expensive for me to build such a powerful server cluster.

Any ideas or suggestion what to do? Any alternative methods to achieve that? Or a company that would be interested to sponsor the project?
We can do nothing and just live with number of hits per project. Thats already more than any other public CDN offers.

**Comment by as-com** [comment]
I don't think it would be exactly 1 TB of data. Much of the data would be highly redundant and compressible.

**Comment by jimaek** [comment]
Thats the raw values. Compression and the rest depends on the technology and solution. (not sure how easy it is to search billions of compressed documents)
But in any case it shows the scale that we would need.
