### ISSUE TITLE
Keep the order of scripts as described in update.json

### ISSUE THREAD

**Issue by finom** [jsdelivr/jsdelivr#7580]
I expectеd to get the same order of files which are sorted by priority:
https://github.com/jsdelivr/jsdelivr/blob/master/files/matreshka/update.json

But I've got very unclear list which is not usable:
http://www.jsdelivr.com/?query=matreshka

In my case I expected to get 3 files from root and then get 3 files from /magic/. Does it make sense? If not I have to remove /magic/ files from update.json.

**Comment by jimaek** [comment]
The site gives priority to min files as they are most needed in production.
For example the map files are not needed at all, thats why they are in the bottom

**Comment by finom** [comment]
@jimaek OK, got it. Then I need to remove all /magic/ stuff.

I have an idea how to make my issue solved. Can I add another library to jsdelivr with new name but using the same repo? The difference is only in list of files.

matreshka/update.json
```js
{
  "packageManager": "github",
  "name": "matreshka",
  "repo": "matreshkajs/matreshka",
  "files": {
    "include": [
		"matreshka.min.js",
		"matreshka.js",
		"matreshka.min.map"
	]
  }
}
```

matreshka-magic/update.json
```js
{
  "packageManager": "github",
  "name": "matreshka-magic",
  "repo": "matreshkajs/matreshka",
  "files": {
    "include": [
		"./magic/matreshka-magic.min.js",
		"./magic/matreshka-magic.js",
		"./magic/matreshka-magic.min.map"
	]
  }
}
```

Thank you for great job!

**Comment by jimaek** [comment]
I actually dont see the problem here. The file order doesn't matter much, the user will definitely find what he looking for.
Plus you can use any order you want in your documentation when linking to jsDelivr.

And yes, you can create 2 projects that use the same repo if you want.

**Comment by finom** [comment]
> I actually dont see the problem here.
But I do. Matreshka has average popularity, so things like this are important.

Thanks for your answers. I'll make another folder on this repo.
