### ISSUE TITLE
No autoupdate at leaflet library

### ISSUE THREAD

**Issue by admiralsmaster** [jsdelivr/jsdelivr#7589]
Hello,

The auto update mechanism of the leaflet library is faulty.
See https://github.com/jsdelivr/jsdelivr/tree/master/files/leaflet
Current version is 0.7.7

Thank you.

**Comment by jimaek** [comment]
I will look into this, thanks for reporting

**Comment by ali-bugdayci** [comment]
Seems like it is a general issue.

The autoupdater did not update the Angular.js to 1.4.7

The latest release tag for Angular 1.4.7 is:
```
Latest commit 2f61145  on Sep 29 @matsko matsko chore(CHANGELOG): update with changes for 1.4.7
```

**Comment by jimaek** [comment]
@ali-bugdayci angular.js is not configured to be auto-updated https://github.com/jsdelivr/jsdelivr/tree/master/files/angularjs

This is not a general issue but specific to leaflet and 2 other projects. We are looking into it

**Comment by ali-bugdayci** [comment]
So should I fork and update Angularjs, or can we add Angular.js to auto-update ?

**Comment by jimaek** [comment]
angular.js doesnt deploy the production files to any source where our bot could pull from. So it has to be added manually. I will do it myself

**Comment by ali-bugdayci** [comment]
@jimaek  

OK. 

I am not sure how the auto updater works, but if there is background process for checking, I believe we can check https://code.angularjs.org/. Similar to:

https://code.angularjs.org/1.4.7/

I believe cdnjs uses there. Check out the combo box for the angular project:

https://cdnjs.com/libraries/angular.js

Or if we need a discrete place for the project version to be written, then angular.js tags might be used:


May I create a request for the angular project to create a dist or

**Comment by jimaek** [comment]
The bot can take as source github/npm/bower. It uses their API to check for new versions and download the needed files. It cant use a website like https://code.angularjs.org/1.4.7/
Unfortunately I havent seen the files that we use at any of those sources.

**Comment by ali-bugdayci** [comment]
@jimaek 

Ok. How can we create an issue at the angular.js repo to fix this? Would adding a field to their bower.json be sufficient ?

**Comment by jimaek** [comment]
Not a just field, all I want is these exact files https://code.angularjs.org/1.4.7/ but deployed at github or npm or bower. Then the bot could copy what it needs and push to jsDelivr

**Comment by ali-bugdayci** [comment]
Well angular is deployed to bower.  e.g.:
```
    "angular": "1.4.6",
    "angular-resource": "1.4.6",
    "angular-animate": "1.4.6",
    "angular-i18n": "1.4.6",
```

The files under angular.js are:
```
angular-csp.css
angular.js
angular.min.js
angular.min.js.gzip
angular.min.js.map
bower.json
index.js
package.json
README.md
```

bower.json details for angular:
```
public/lib/angular[master*](3h25m|% more bower.json 
{
  "name": "angular",
  "version": "1.4.6",
  "main": "./angular.js",
  "ignore": [],
  "dependencies": {
  }
}
```

**Comment by jimaek** [comment]
These files dont match those in here https://code.angularjs.org/1.4.7/
The bot needs all of them in one place

**Comment by ali-bugdayci** [comment]
himm, well its a hard job, since angular comes with different projects and they should be updated at the same time.

I believe changing the updater code to work with web resources might be added in the future.

**Comment by admiralsmaster** [comment]
Nice discussion about angularjs, but leaflet?

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
