### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by jonataswalker** [jsdelivr/jsdelivr#7661]
Hi,

If I try an address for a project, say, http://www.jsdelivr.com/projects/openlayers.contextmenu or http://www.jsdelivr.com/projects/leaflet.esri, I get `503 Service Unavailable`.

**Comment by jimaek** [comment]
The site should be online. I am very sorry, there was a strange issue that crashed the Docker image.
Only the site was affected, the CDN is completely separate.

We will look into this to make sure it doesnt happen again. @MartinKolarik

**Comment by jonataswalker** [comment]
:clap: Fixed!
