### ISSUE TITLE
Your connection is not private + no Gzip

### ISSUE THREAD

**Issue by mjau-mjau** [jsdelivr/jsdelivr#7681]
Today, I am getting "Your connection is not private", which has basically broken our app, at least from this location.

![connection](http://d.pr/i/158vi+)

Also, we are intermittently getting uncompressed outputs. Perhaps only from combined files, but that would be quite counter-productive nevertheless:

![no-compression](http://d.pr/i/1eXRh+)
![response](http://d.pr/i/uyum+)

The other day, traceroute to jsdeliver was all over the place, hopping from Thailand-HK-SG-HK-Australia. Today, it seems really good, and it seems you have POP servers in Bangkok now? Thus, speeds are excellent, although the issues with gzip and ssl are kinda critical. Here is my traceroute:

```
traceroute cdn.jsdelivr.net
traceroute: Warning: cdn.jsdelivr.net has multiple addresses; using 61.90.241.25
traceroute to 1stapacsniwebmw.dtwscache.speedcdns.com (61.90.241.25), 64 hops max, 52 byte packets
 1  10.0.1.1 (10.0.1.1)  1.336 ms  1.275 ms  1.241 ms
 2  192.168.1.1 (192.168.1.1)  2.186 ms  1.661 ms  1.611 ms
 3  119.42.80.1 (119.42.80.1)  25.878 ms  26.513 ms  25.837 ms
 4  110.78.190.110 (110.78.190.110)  40.808 ms  42.427 ms  39.870 ms
 5  110.78.188.2 (110.78.188.2)  41.815 ms  41.885 ms  42.524 ms
 6  122.155.254.73 (122.155.254.73)  40.093 ms  39.727 ms  40.539 ms
 7  122.155.254.50 (122.155.254.50)  39.720 ms
    122.155.254.38 (122.155.254.38)  42.614 ms  46.516 ms
 8  61-91-213-198.static.asianet.co.th (61.91.213.198)  41.370 ms  40.468 ms  40.139 ms
 9  61-90-241-25.static.asianet.co.th (61.90.241.25)  42.263 ms  41.545 ms  40.118 ms
```

Here are results from debug-tool:
http://goo.gl/cAJLbc

Really like the idea of jsdelivr, especially the the widespread locations/pops and combining files. However, it seems a bit counter-productive with some of the issues above. I could solve the SSL issue by adding protocol-relative paths of course, but would prefer to avoid that.

**Comment by mjau-mjau** [comment]
#7683

**Comment by jimaek** [comment]
Our certificate expires on "02-Oct-16"

Can you give me more information? Like HTTP headers and the SSL that you get.
Also is it possible that your ISP has a proxy?

**Comment by mjau-mjau** [comment]
not sure what more information I can provide. If I override the chrome warning and "proceed anyway", I get this:
![ssl](http://d.pr/i/14qEN+)

Im not on proxy.
![noproxy](http://d.pr/i/1dHCY+)

To me, it seems like the pop server doesn't do SSL, or isn't doing it properly.

**Comment by jimaek** [comment]
Show me the SSL certificate that you get.

**Comment by mjau-mjau** [comment]
![expired](http://d.pr/i/oPFQ+)

**Comment by jimaek** [comment]
I switched all traffic away from the affected CDN provider until they fix this issue. I am sorry about that
