### ISSUE TITLE
expired ssl certificate

### ISSUE THREAD

**Issue by jhiswin** [jsdelivr/jsdelivr#7683]
The GlobalSign SSL cert expired today, so the https server is not working.

**Comment by jimaek** [comment]
Our certificate expires on "02-Oct-16"

Can you give me more information? Like HTTP headers and the SSL that you get.
Also is it possible that your ISP has a proxy?

**Comment by jhiswin** [comment]
@jimaek It's very possible.  I highly suspect there is some kind of MITM going on.  I'll send you a copy of the certificate I received and a har file for analysis.  I noticed this before when I was first trying to test your servers, which is why I mentioned ssl possibly being an issue.
I want to note that I've noticed this kind of thing on a lot of foreign sites using ssl.

**Comment by jhiswin** [comment]
Ah, looks like the problem was found in #7681 
Maybe it's something with Chinese cdns in general.  The consensus I get from IT guys over here is that cdn services in China are wrought with 504 errors and the like, and my own techs are pretty insistent on dissuading me from using any kind of cdn or cloud-like service.

**Comment by jimaek** [comment]
Yeah its a strange problem. I removed them from jsDelivr and waiting for a response from support.
Everything should be working fine.

**Comment by jhiswin** [comment]
Just want to note that performance is much better now.  It's not only
usable, but fast.

**Comment by jimaek** [comment]
This is very strange, MaxCDN has no servers inside China, while Quantil has a big network close to all big cities.

**Comment by jhiswin** [comment]
It is indeed.  Right now: TTFB is always around 50-80ms (seems to be
improving), but download is near instantaneous.
Quantil has ~20ms ping, but it always stalls to around 30s.  I think
there's something very wrong with Quantil.

**Comment by jhiswin** [comment]
Okay actually Quantil just doesn't connect anymore.

**Comment by jimaek** [comment]
Btw they fixed the issue shortly and I added them back. The performance is getting looked at.

**Comment by jhiswin** [comment]
Ah yes, they contacted me.  I've sent some more info to them.
