### ISSUE TITLE
preparing brotli compression.

### ISSUE THREAD

**Issue by ajkj** [jsdelivr/jsdelivr#7702]
Mozilla's issue tracker shows that Firefox 45 with brotli support is planed to release on 2016-03-03.

Google Chrome also have a plan for Chrome48 with brotli support.

maybe we could prepare for brotli compression, at least on some cdn?

https://www.chromestatus.com/features/5420797577396224
https://code.google.com/p/chromium/issues/detail?id=452335
https://bugzilla.mozilla.org/show_bug.cgi?id=366559
https://quixdb.github.io/squash-benchmark/
https://github.com/google/ngx_brotli

**Comment by jimaek** [comment]
Its completely not up to us. If our CDN providers begin to support it we will enable it, otherwise there is nothing we can do.

**Comment by ajkj** [comment]
by changing origin behavior, is it not possible?

i thought that it's possbile by detecting https and js 'accept-encoding: brotli ' at origin and sending brotli response because cdn just work as http proxy which doesn't care response body.

**Comment by jimaek** [comment]
Most CDNs re-compress the files regardless of what the origin sends them. Even if I set gzip to level 9 they re-compress the file to their own level which varies between all of them
