### ISSUE TITLE
jquery-cookie was superseded by js-cookie

### ISSUE THREAD

**Issue by tylerlong** [jsdelivr/jsdelivr#7719]
https://github.com/carhartl/jquery-cookie was moved to https://github.com/js-cookie/js-cookie

The former is superseded by the latter.

What should we do? Create a new project or change the old one?

**Comment by jimaek** [comment]
Create a new project please

**Comment by FagnerMartinsBrack** [comment]
x-ref: https://github.com/jsdelivr/jsdelivr/pull/5507
