### ISSUE TITLE
is it possible to benchmark throughput?

### ISSUE THREAD

**Issue by ajkj** [jsdelivr/jsdelivr#7744]
is it possible to benchmark throughput with cedexis ?

if possible, i think we need to measure not only response time but also throughput.

ex)
https://github.com/jsdelivr/jsdelivr/issues/7683#issuecomment-152855998
https://github.com/jsdelivr/dns-openmix/issues/8

**Comment by jimaek** [comment]
Their throughput benchmarks wont work well for us. Throughput tests are for users serving huge files and doing video streaming. Most of our files are under 100kb, the current HTTP response time benchmark makes more sense and works better for us.

**Comment by ajkj** [comment]
then, how about benchmarking real-size(ex, 30kb~60kb after gzip) file?
i think current 43 byte gif file doesn't represent real world performance.

**Comment by jimaek** [comment]
We would never be able to match their community data by ourselves. Thats a huge benefit of Cedexis, they offer the data from billions of tests that they do for any client to use.

**Comment by ajkj** [comment]
ok. thanks for answering.
