### ISSUE TITLE
leaflet.esri 1.0.1 didn't make it to the cdn

### ISSUE THREAD

**Issue by jgravois** [jsdelivr/jsdelivr#7747]
hi there,
i backported a fix and tagged [`1.0.1`](https://github.com/Esri/esri-leaflet/releases/tag/v1.0.1) of 'leaflet.esri' yesterday.  when a new release is not the *latest* (ie: we're up to 2.0.0-beta.x) is something additional required to ensure that your bot opens a PR and the release makes it to your CDN?

**Comment by jimaek** [comment]
Unfortunately now the 2.x is the latest version, so the bot wont update anymore the 1.x branch. It will need to be updated manually from now.

**Comment by jgravois** [comment]
awesome.  i don't expect we'll have many patches, so i'm happy to PR the raw files manually.

thanks @jimaek!
