### ISSUE TITLE
CloudFlare network.geojson needs updating

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#7778]
[network-map.png](https://www.cloudflare.com/media/network-map.png)
[text list](https://support.cloudflare.com/hc/en-us/articles/200169986-Which-CloudFlare-data-centre-do-I-reach-)
* Africa
  - MBA: Mombasa, KE
* Asia
  - [KUL: Kuala Lumpur, MY](https://blog.cloudflare.com/kuala-lumpur-malaysia-cloudflares-45th-data-center/)
* Europe
  - [DUB: Dublin, IE](https://blog.cloudflare.com/dublin-ireland-cloudflares-38th-data-center/)
  - [Manchester, UK](https://blog.cloudflare.com/manchester-uk-cloudflares-63rd-data-center/)
  - [OTP: Bucharest, RO](https://blog.cloudflare.com/bucharest-datacenter/)
* Middle East
  - DOH: Doha, QA
  - DXB: Dubai, AE
  - KWI: Kuwait City, KW
  - MCT, Muscat, OM
* USA
  - PHX: Phoenix, AZ ("Phoenix has not been announced officially yet, but it is online for some traffic~John Roberts of CF & on map)
- [Beadu's CDN in China](https://blog.cloudflare.com/how-we-extended-cloudflares-performance-and-security-into-mainland-china/)

Might want to update PoP count.

I was going to edit the geojson by hand, but unsure of the IDs.  I'm assuming you use a tool?

**Comment by tomByrer** [comment]
Better to scrape/compare text list: https://www.cloudflarestatus.com

**Comment by jimaek** [comment]
I am exporting the json from mapbox.com
I also didnt add the China POPs because its not available to all clients, its invite only and has some temp limitations that wont work with jsDelivr.
Thanks for finding this, the new json should be live soon

**Comment by tomByrer** [comment]
Welcome!  Is PHX not peering for you?

**Comment by jimaek** [comment]
I want them to announce it officially before adding it to the map.

**Comment by tomByrer** [comment]
https://blog.cloudflare.com/pho/
:P

**Comment by jimaek** [comment]
lol ok then :)

**Comment by tomByrer** [comment]
I think they posted just hours after you said you wanted to wait; maybe they read your mind?   Or my tech support ticket got to the right people...
