### ISSUE TITLE
add Cloudflare Copenhagen Denmark PoP

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#7981]
CloudFlare
* [ ] [Denmark: Copenhagen](https://blog.cloudflare.com/copenhagen-denmark-cloudflares-65th-data-center/)
* [ ] [India: Mumbai, Chennai and New Delhi](https://blog.cloudflare.com/cloudflare-launches-in-india-with-data-centers-in-mumbai-chennai-and-new-delhi/)
* [ ] [Switzerland: Zürich,](https://blog.cloudflare.com/zurich-switzerland-cloudflares-69th-data-center/)

[MaxCDN](https://www.maxcdn.com/features/)
* [ ] South America: São Paulo

[QUANTIL](https://www.quantil.com/network-map/) seems to have have many more POP than we list...

**Comment by jimaek** [comment]
They said that will release more locations soon, lets wait and add them all together instead of 1 per day

**Comment by tomByrer** [comment]
`ping`

**Comment by jimaek** [comment]
I added the CloudFlare locations. MaxCDN Sao Paulo is not enabled for most clients including jsDelivr.
And for Quantil we only had a deal for Chinese locations and Thailand.
Thanks for reminding me :)

**Comment by tomByrer** [comment]
Welcome.
Map is getting more full!
