### ISSUE TITLE
more POPs

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/jsdelivr#8554]
If you want to make the map's updates monthly, that's cool:
 * [x] [vancouver-montreal-canada](https://blog.cloudflare.com/vancouver-montreal-canada-cloudflares-70th-71st-data-center/)
 * [x] [Hamburg, GE](https://blog.cloudflare.com/unser-neues-72-rechenzentrum-hamu/)
 * [x] [Sofia, Bulgaria](https://blog.cloudflare.com/sofia/)
 * [x] [Cairo, Egypt](https://blog.cloudflare.com/cairo/)

**Comment by jimaek** [comment]
https://www.keycdn.com/blog/pop-in-switzerland/

**Comment by jimaek** [comment]
https://www.keycdn.com/blog/pop-in-brazil/
