### ISSUE TITLE
Purge CDN cache

### ISSUE THREAD

**Issue by getusedtoit** [jsdelivr/jsdelivr#8592]
Hi guys,

would it be possible to issue a purge command through the CDN, to refresh these two files?

https://cdn.jsdelivr.net/wp/wp-slimstat/trunk/wp-slimstat.js
https://cdn.jsdelivr.net/wp/wp-slimstat/trunk/wp-slimstat.min.js

The new files have been pushed to the repo a few hours ago:

http://plugins.svn.wordpress.org/wp-slimstat/trunk/wp-slimstat.js
http://plugins.svn.wordpress.org/wp-slimstat/trunk/wp-slimstat.min.js

When I try to issue a purge, I get a 504 Gateway error message. Is that normal?

Thank you,
Luigi

**Comment by jimaek** [comment]
Purged. Also im not getting any errors when purging. Did you do it correctly?
