### ISSUE TITLE
jsdelivrbot pull request for ng-file-upload

### ISSUE THREAD

**Issue by danialfarid** [jsdelivr/jsdelivr#8631]
I see these pull request whenever I release a new version of [ng-file-upload](http://github.com/danialfarid/ng-file-upload):

https://github.com/jsdelivr/jsdelivr/pull/8628

What are all the warnings and is it trying to update the CDN?  It doesn't seem to be available: https://cdn.jsdelivr.net/danialfarid/10.1.14/ng-file-upload.min.js

**Comment by jimaek** [comment]
It says that it cant find `ng-file-upload.min.js` in the older versions. This is a warning useful for mods.
We plan to update the bot to be smarter and ignore it when its safe
