### ISSUE TITLE
Question about leaflet.markercluster

### ISSUE THREAD

**Issue by Kcchouette** [jsdelivr/jsdelivr#8697]
Hello,
Thanks for jsdelivr

For leaflet.markercluster, is there a way to host branch like https://github.com/Leaflet/Leaflet.markercluster/tree/leaflet-0.7 (to use it with leaflet 0.7)?

Thanks

**Comment by jimaek** [comment]
You can only add it manually. The bot cant use branches, only tags.

**Comment by Kcchouette** [comment]
Ok thanks
