### ISSUE TITLE
jsdelivr doesn't pull the later versions of the library (chrono)

### ISSUE THREAD

**Issue by wanasit** [jsdelivr/jsdelivr#8750]
I have followed the contributing guild and submitted my library to jsdelivr. 
- https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md
- https://github.com/jsdelivr/jsdelivr/pull/8319

However, only Chrono version 0.1.11 is available in jsdelivr. I have released a few updated after that and the latest version is 1.1.2.

Why doesn't jsdelivr detect the new version? Did I forget to do something?

**Comment by jimaek** [comment]
Hey, sorry about that. The issue was fixed, the bot is now auto-updating the project once again https://github.com/jsdelivr/jsdelivr/pull/8756

**Comment by wanasit** [comment]
thanks!

**Comment by bradvogel** [comment]
Thanks!
