### ISSUE TITLE
jsdelivr almost always outdated compared to cdnjs

### ISSUE THREAD

**Issue by eskhool** [jsdelivr/jsdelivr#8793]
Aren't libraries being picked up automatically by both the CDNs? I have checked multiple libraries (jquery.flexslider) and invariably jsdelivr is a few versions behind. Its my only reason for not using jsdelivr since it is otherwise so advanced in the feature set. Could someone help elaborate?

**Comment by jimaek** [comment]
We are trying to switch all of our hosted projects to auto-updating. Some unfortunately dont support it and I dont have the time to manually update those. Thats why flexslider and some other older projects might be out of date. But people that need them can send a PR to add the newer versions.

**Comment by eskhool** [comment]
I understand of course that you can't manually enter each one but submitting a PR on every single release may be a surefire way of turning people away, an auto updating mechanism is the right way?

Any idea how cdnjs.cloudflare is doing it? flexslider is just one example (and its hosted on github so should be updatable from there?)

**Comment by jimaek** [comment]
Like I said we have auto-updates and they already work for a lot of projects.
If flexslider can be autoupdated(simply being on github is not enough, some dont publish production files, others dont have tags...) you can add the update.json file yourself and our bot will take care of the rest.

No idea what cdnjs does and how.

**Comment by perosb** [comment]
I'm hijacking this issue, but jquery and others are also falling behind? Is the jsdelivrbot running on its knees?

**Comment by jimaek** [comment]
jQuery beta is now live. What other projects are out of date? If there is no update.json feel free to add it.

**Comment by perosb** [comment]
thanks. but jquery still missing 1.12 and 2.2.0
jquery-migrate is missing 1.3.0

**Comment by jimaek** [comment]
jquery-migrate is not auto-updated. If you find a suitable source for the files then we can enable it.
And jquery doesnt have those versions because the bot can only send the latest version, which is 3.x.
A user sent a manual PR which should now live https://github.com/jsdelivr/jsdelivr/pull/8973

**Comment by tomByrer** [comment]
Please help out where you can @perosb; @swcheon is just a regular user like you who helped us keep jQuery updated by hand.

@eskhool You're right, I get frustrated also.  I personally have over 100 jsDelivr PRs & issue posts.  But there is only so much a 1 lead a 1-5 dedicated volunteers can do.  We need occasional volunteers to fill in the gaps.  We tried to make it easy with the bot & [short instructions](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md).  If you find a project missing missing minified files, you can PR a Gulp/Grunt update to help them help you help everyone.

**Comment by jimaek** [comment]
Instant updates https://github.com/jsdelivr/jsdelivr#usage
