### ISSUE TITLE
instantsearch.js 1.1.1 and 1.1.2 are not available

### ISSUE THREAD

**Issue by vvo** [jsdelivr/jsdelivr#8841]
They were published to npmjs: https://www.npmjs.com/package/instantsearch.js

**Comment by jimaek** [comment]
Here is the reason https://github.com/jsdelivr/jsdelivr/pull/8813
I didnt delete the branch to prevent the bot sending it again every 30 minutes. But it also blocked everything lower than `1.2.0-beta.1`

**Comment by jimaek** [comment]
If the beta is no longer online you can delete the branch and the bot will pick up the 1.1.2 version.
Otherwise you will have to add them manually

**Comment by vvo** [comment]
> If the beta is no longer online

The beta is "online" only on npmjs

Are you talking about the jsdelivr branch?

**Comment by vvo** [comment]
Here: https://github.com/jsdelivrbot/jsdelivr/branches ?

**Comment by jimaek** [comment]
The bot will always pick the largest version possible. If npmjs has the 1.2.0-beta then if you delete the jsdelivr branch it will create the same PR again.
You need to get rid of  1.2.0-beta at npm for the bot to pick up 1.1.2.

**Comment by jimaek** [comment]
Or add these versions with a manual PR

**Comment by vvo** [comment]
Oh ok this basically means I guess we cannot really publish different npmjs tags AND use jsdelivr npmjs thing. allright

**Comment by jimaek** [comment]
Yes. The bot will use the largest version available at npm/github/bower no matter what.

**Comment by vvo** [comment]
@jimaek I unpublished the betas, can you remove the branch? I do not have the rights

**Comment by jimaek** [comment]
Done
