### ISSUE TITLE
Huge navbar

### ISSUE THREAD

**Issue by franciscop** [jsdelivr/jsdelivr#8851]
The navbar for 1920x1080px screens is huge in height. Right now it occupies a 29% of my screen, almost one third. A screenshot:

![huge bar](https://cloud.githubusercontent.com/assets/2801252/12211588/949753e4-b662-11e5-803f-c188a3b0fe5e.png)

That screenshot is without any zoom active, in *level 0* (ctrl+0). However, if I zoom out (ctrl -) then it shows properly. I propose to fix it so it doesn't overflow into two bars so soon, as there's no real state for the content of the page itself.

**Comment by jimaek** [comment]
@MartinKolarik Hey, can you look why the "Add, API, Link" buttons go down and break design?

**Comment by MartinKolarik** [comment]
@franciscop can you give us details about your device, browser, and OS? Your screenshot shows a version for devices with screen width lower than 1366px.

@jimaek that's also answer to your question; they go down because on the smallest devices, project name and description get 100% width as there's not enough space to have everything next to each other.

**Comment by MartinKolarik** [comment]
This is how the website should look at various resolutions: https://www.dropbox.com/sh/fs7nr0ft81l42le/AABqG7edgu1pEHmj32C7FkGRa?lst

**Comment by franciscop** [comment]
That is completely true, I have `layout.css.devPixelsPerPx` set to 1.5, so my Ctrl+0 is not really "no zoom", sorry for stating "no zoom" before.

- Device: Asus Zenbook UX31A (1920x1080px laptop)
- Browser: Firefox 43.0, with AdBlockPlus Plugin (has caused issues in other pages)
- OS: Ubuntu 15.04

1920 / 1.5 = 1280px, which is consistent with the screenshots shown above. It still covers a big part of the screen, but I guess it's a design decision.

**Comment by MartinKolarik** [comment]
Thanks for the info. Indeed, if you have 1.5 zoom (probably set on OS level) then the website works as expected.

I'd suggest trying to change the ratio to 1.2, that would get you 1600x900px, which should be about right for a 13" laptop.
