### ISSUE TITLE
Question about leaflet.search

### ISSUE THREAD

**Issue by Kcchouette** [jsdelivr/jsdelivr#8897]
Why leaflet.search is not yet available on jsdelivr website?

I add it on jsdelivr 9 days ago (#8757).
Is there a problem with my update.json?

Thanks.

**Comment by jimaek** [comment]
This is why
```
bower install leaflet.search
bower                        ENOTFOUND Package leaflet.search not found

```

Your update.json is incorrect

**Comment by Kcchouette** [comment]
```leaflet-search``` is better?

**Comment by jimaek** [comment]
Yes, that seems to be working

**Comment by Kcchouette** [comment]
Ok so I understand my errors. I'll fix them :)

Thanks
