### ISSUE TITLE
 /latest/ different from /{latestVersion}/ file

### ISSUE THREAD

**Issue by ellisonleao** [jsdelivr/jsdelivr#9230]
Not sure if this a cache issue, but right now:
 
https://cdn.jsdelivr.net/sharer.js/latest/sharer.min.js

!=

https://cdn.jsdelivr.net/sharer.js/0.2.7/sharer.min.js  (latest version)

Any thoughts?

**Comment by jimaek** [comment]
/latest/ caches for 7 days for performance reasons. Its not instant.
I manually purged the cache now for that file.

**Comment by ellisonleao** [comment]
Nice, thanks for heads up!
