### ISSUE TITLE
Support rawgit-like cdn ability

### ISSUE THREAD

**Issue by ping** [jsdelivr/jsdelivr#9325]
I don't know if it's possible, but will you consider adding [rawgit](https://rawgit.com/)-like cdn capabilities to jsDelivr?

It's a very useful and powerful feature in my opinion, where you can support repos without the hassle of PRs, updates, etc.

rawgit right now uses only MaxCDN so jsDelivr will be a better proposition with multiple providers.

**Comment by jimaek** [comment]
Technically its easy to do. But it creates a lot of possible issues like abuse and malware.
Our sponsors agreed to sponsor us as long as we serve only open source projects and dont have any issues like getting hacked and serving malware. If we support rawgit functionality then anyone can create a repo with anything he wants and serve that content over our network including phishing sites, viruses, infected javascript, non-open source files.... We lose all control.

**Comment by ping** [comment]
I understand. It's too bad then. Thanks.
