### ISSUE TITLE
About Page Not Working

### ISSUE THREAD

**Issue by SamuelEnglard** [jsdelivr/jsdelivr#9468]
In IE11 on Windows 10 the About page just redirects to the home page.

**Comment by jimaek** [comment]
Can you tell me the URL of the about page you are trying to open?

**Comment by SamuelEnglard** [comment]
http://www.jsdelivr.com/about

**Comment by jimaek** [comment]
Strange, just tried that and it works great. Can you send me the HTTP headers if that continues to happen?

**Comment by SamuelEnglard** [comment]
Looking through the headers nothing looks wrong to me but... http://1drv.ms/1Sy42eF

**Comment by jimaek** [comment]
Sorry I dont understand how to read that XML. Do you have a linux output or a screenshot?
I am trying to see the moment it does the redirect.

**Comment by SamuelEnglard** [comment]
Did some debugging and the issue is that search event on the header is fired incorrectly. With no actual query it just redirects to the home page.

**Comment by jimaek** [comment]
@MartinKolarik Can you please take a look? 
@SamuelEnglard Thanks for reporting.

**Comment by MartinKolarik** [comment]
@SamuelEnglard Thanks for reporting. The problem here is that IE fires "input" event for no reason. I discovered this issue before the site went live and there has already been a workaround, but it must have stopped working after some IE update. Fixed now.

**Comment by SamuelEnglard** [comment]
Works for me. Thanks!
