### ISSUE TITLE
Menu-io v1.0.0 file not found

### ISSUE THREAD

**Issue by coderaiser** [jsdelivr/jsdelivr#9606]
[menu-io](http://github.com/coderaiser/menu-io) [was added](https://github.com/jsdelivr/jsdelivr/pull/9600) to [jsdelivr repo](https://github.com/jsdelivr/jsdelivr/tree/master/files/menu-io/1.0.0) today but when I try to open links from https://www.jsdelivr.com/projects/menu-io:
```
https://cdn.jsdelivr.net/menu-io/1.0.0/menu-io.min.js
https://cdn.jsdelivr.net/menu-io/1.0.0/menu-io.min.css
```
It returns `404 file not found`.

**Comment by jimaek** [comment]
Its fixed now.
The deployment failed for some reason. Probably a temp problem with either Github's or Deployhq's API. If it happens again I will investigate further.

Sorry about that

**Comment by coderaiser** [comment]
Thank you, now it works.
