### ISSUE TITLE
Re-enable SRI for all files

### ISSUE THREAD

**Issue by lenovouser** [jsdelivr/jsdelivr#9631]
In your [blog post](http://blog.jsdelivr.com/2015/10/new-website-and-sri-support.html) you stated:

> If you noticed one file doesn't have an SRI. Thats because Chrome has a buggy implementation that breaks files containing UTF-8 characters. This bug is not present in Firefox Developer Edition which also supports SRI, but to ensure a smooth experience for all users we decided to temporary stop generating hashes for those files.

maybe SRI can be re-enabled for all files since you stated it is going to be temporary and as the the issue seems to have been resolved in **Chrome 46** according to [chromium/issues/#527286](https://code.google.com/p/chromium/issues/detail?id=527286) in December 2015.

**Comment by jimaek** [comment]
@MartinKolarik Can you confirm? Should we remove that warning?

**Comment by MartinKolarik** [comment]
Yes, it seems to be fixed.

**Comment by jimaek** [comment]
Great, lets update the site.
@lenovouser Thanks for the info
