### ISSUE TITLE
Order of CDN files

### ISSUE THREAD

**Issue by thasmo** [jsdelivr/jsdelivr#9649]
The order of files in the project-details view seems odd, kinda random - e.g.:
https://www.jsdelivr.com/projects/gridable

Is there any logic in sorting the files?
In the case of gridable, alphabetical order would help a lot to select files.

**Comment by jimaek** [comment]
mainfile and min files on top I believe, the rest below. I can find out 100% if you want.

**Comment by thasmo** [comment]
Ah, I see - makes sense. Thanks!
