### ISSUE TITLE
RiotJS latest version not deployed to CDN

### ISSUE THREAD

**Issue by gregorypratt** [jsdelivr/jsdelivr#9667]
https://github.com/riot/riot/issues/1583

Seems like it's fallen through the gaps some how?

**Comment by jimaek** [comment]
Looking into it

**Comment by gregorypratt** [comment]
Thank you!

**Comment by jimaek** [comment]
There was a small issue with our local repo that is used by the bot scan for projects. Its fixed now and we are working on a patch to avoid this in the future.
Sorry about that. Your latest 2.x is now live https://cdn.jsdelivr.net/riot/2.3.15/riot.min.js
